### PR TITLE
fix: Minor UI fixes

### LINKED ISSUE #4385: If no facility is selected, show `FacilitySelectDialog` when Import/Export asset is clicked
**Is your feature request related to a problem? Please describe.**
Currently, when we go to the asset list page, we are unable to directly import / export.
We either have to select a facility from advanced filters or view assets from the facility home page.

image

**Describe the solution you'd like**
When either Import/Export is selected and not filtered by a facility, then a `FacilitySelectDialog` should be shown similar to how Create Asset works.

However, Create Asset's facility select does not apply the filter, rather it directly takes to the facility's asset create page.

image

### LINKED ISSUE #4488: asset scanning- "Page not found"
**Describe the bug**
CARE has the option to scan a registered QR code sticker and user is taken to the particular asset page. (https://care.coronasafe.in/assets)

This is not working. The user is instead taken to a "Page not found" page

**To Reproduce**

1. Go to ['...'](https://care.coronasafe.in/assets)
2. Click on 'Scan Asset QR'
3. Scan the below QR code (the QR is already linked to "Test camera: (https://care.coronasafe.in/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/assets/926a0371-a772-47e8-925f-aa853e24ee58)
WhatsApp Image 2022-12-27 at 11 35 56 AM

5. user will be taken to "Page not Found" page- BUG

**Expected behavior**
Te user must be taken to the asset page upon scanning qr code

### LINKED ISSUE #4544: BUG: error in error message
https://care.coronasafe.in/facility/e6dc0b39-0d8b-42d4-abd5-5f887058527b/patient

When you submit the patient registration form with COVID Section with Date of sample given to be a later date than date of test result and click on submit, the error message comes up as "Date should not be before minimal date"

Instead the error should read as "Date should not be before the date of sample collection"

### LINKED ISSUE #4600: Asset confirm delete button should be of `type="danger"`
**Describe the bug**
Asset confirm delete button should be of `type="danger"`

**To Reproduce**

1. Delete an asset

**Expected behavior**
Danger actions should be using button `type="danger"`.

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by cp-Coder**
# Bug Fix

## Proposed Changes

- Updated error message for date of test result
- Added `variant=danger` to confirm button for `Delete Asset` operation
- Updated redirected url from `/asset/:assetID` to `/facility/:facilityID/asset/:assetID` after scanning QR code
- Added `FacilitySelectDialog` on clicking Import/Export button when no facility is selected

## Associated Issue

- Fixes #4544
- Fixes #4600
- Fixes #4488
- Fixes #4385

## Screenshot

- For #4544
image

- For #4600
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update product [documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [ ] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder 
image

- even though the validation is there, I am able to create a patient. 
https://deploy-preview-4603--care-net.netlify.app/facility/a31e6a24-0146-4043-b295-3a6c2fe7e095/patient/a709c84e-28e8-41ee-bf5e-f7beb7e859f3/update

image

- in the responsive view of the delete asset pop-up, make the button in uniform size

**Comment by nihal467** [comment]
@cp-Coder 
image

the QR code scanner is not working

**Comment by aeswibon** [comment]
@nihal the QR scanner code is working fine. 
I have tested the QR code having the URL type `https://status.10bedicu.org/karnataka?asset=1242142412424124124` and it is working. Please post the QR code and type of URL on which the scanner is not working.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
