### PR TITLE
Collect postpartum data

### LINKED ISSUE #6943: Patient registration form: Collect "Post partum"
https://care.coronasafe.in/facility/eeb23cb7-1524-479a-825e-660311386b47/patient/51ff0682-065d-4e25-bcc6-fb1b682642fb/update

After Gender is collected, there is a question of whether the patient, if female is anenatal. 

- [ ] Where the female is antenatal, collect the "Date of start of last menstruation" 
_________
- [ ] Right after that, also add "Is Post-partum(< 6 weeks)"- Yes/No
- [ ] If yes, collect date of delivery.

### PR DESCRIPTION
**Pull request by Omkar76**
## Proposed Changes

- Fixes #6943 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

[postpartum.webm](https://github.com/coronasafe/care_fe/assets/56870381/6353f2f6-2a2a-4641-a4d8-3875da592a4e)

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
Added a comment on the related backend PR

**Comment by Omkar76** [comment]
@rithviknishad i think we can remove "waiting for backend" label. backend pr is merged https://github.com/coronasafe/care/pull/1811

**Review by rithviknishad — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Comment by Omkar76** [comment]
Looks like after merging develop into this some test if failing. Will look into it.

**Comment by nihal467** [comment]
@aparnacoronasafe the data are currently only recorded in the patient registration form, but it's not being reflected anywhere on the patient details page, where should we be showing it?

**Comment by nihal467** [comment]
@Omkar76 once the aparna mentions the reflection, make the necessary change and add a single cypress test to the patient_registration.cy.ts file, covering all this data recording and reflection

**Comment by aparnacoronasafe** [comment]
@nihal467 Good point Nihal!

- [x] On the patient dashboard (https://care.coronasafe.in/facility/997c7f30-8e2f-4d62-8b58-2a8771e658d6/patient/8ac01387-84ce-4bc6-b836-b2e2387804d3/consultation/7ee96a05-556d-44ff-af20-d326e1a24baf) show labels for both "Antenatal"  and "Post-partum". This label should be added to the banner on top with patient name and basic details.

- [x] Add a card in patient dashboard "update" tab, under Basic information, before "Symptoms" . Title of the card must be "Perinatal Status" containing the information on whether the patient is antenatal (date of last menstruation) and post-partum (with date of delivery)

**Comment by Omkar76** [comment]
@aparnacoronasafe can you please check which one looks better in updates tab. I prefer last one.
One
image
Two
image
Three
image

**Comment by aparnacoronasafe** [comment]
Last one is great @Omkar76 
Please go ahead

**Comment by Omkar76** [comment]
@aparnacoronasafe 
Please correct me if I'm misunderstanding your second statement.
> Add a card in patient dashboard "update" tab, under Basic information, before "Symptoms" . Title of the card must be "Perinatal Status" containing the information on whether the patient is antenatal (date of last menstruation) and post-partum (with date of delivery)

The place where you are suggesting to add the "Perinatal status" card is only shown when a consultation if filed for patient. (check the link you provided - it says consultation). We are currently collecting the perinatal details per patient and not per consultation. So showing it only when consultation is created seems odd to me. I realized this only when writing tests that I'll have to first create a consultation in order to verify perinatal info.

I think it'll be more appropriate to add the details in "Medical" card (see the screenshot). We are already showing is "Is pregnant" field there. Let me know what you think. Thanks.

image

**Comment by nihal467** [comment]
@rithviknishad can you take over the PR, and clear the issues , make sure they are visible in discharge summary as well

**Comment by nihal467** [comment]
@rithviknishad 
image
image


- [ ] modify the cypress test to check both last menstruation and date of delivery dates reflection using cypress

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
