### PR TITLE
Fixed if someone types incorrect URL it shows Error404 Component

### LINKED ISSUE #2668: When an incorrect URL is typed it should be redirected to Error Page
# Bugs

## 1) When we visit a facility page if a random facility id is passed to the URL then it shows the following:
image

###  instead it should show the error page
image

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2668 

# Bugs Fixed

### Facility Page
https://user-images.githubusercontent.com/59426397/173176321-c9287d50-d3d3-4913-96dc-a4f9745859a1.mp4

### Patient Page
https://user-images.githubusercontent.com/59426397/173176418-5f8cae18-ced1-4724-9ee2-efa03ab30408.mp4

### Assets Page
https://user-images.githubusercontent.com/59426397/173176470-273d3278-e355-4ecb-a18b-b1d8d89ba8c6.mp4

### Sample Test Page
https://user-images.githubusercontent.com/59426397/173176596-41c422b9-a4ec-4006-87cd-a861bcf9ac57.mp4

### Shifting Page
https://user-images.githubusercontent.com/59426397/173176692-7e141627-e8a0-4a4d-9b0f-7e41767ee977.mp4

### Resource Page
https://user-images.githubusercontent.com/59426397/173176705-c1b27237-3f13-4a6d-8519-c8ea118e28e3.mp4

### CODE REVIEW

**Comment by patelaryan7751** [comment]
Deploy Preview Ready https://deploy-preview-2674--care-net.netlify.app/

**Comment by nihal467** [comment]
@patelaryan7751 @gigincg test failed

wpokddw

we are having three error notifications, can we make it one error notification

**Comment by nihal467** [comment]
@patelaryan7751 what is the status of the PR

**Comment by patelaryan7751** [comment]
Hey, @nihal467 to solve the issue some major changes need to be done . I discussed it with @gigincg once in an EOD meet.

**Pull request closed without merging**
