### PR TITLE
Minor UI enhancement

### PR DESCRIPTION
**Pull request by Pranshu1902**
Added icon for Doctor Connect
http://localhost:4000/patients
After:
image

Before:
image

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
I think a call/communicate related icon would be better than a link icon.

cc: @nihal467

**Comment by nihal467** [comment]
@Pranshu1902 @aparnacoronasafe @rithviknishad the chain icon doesn't look good, can you try using a phone icon, which will be much more related to the feature

**Comment by Pranshu1902** [comment]
@nihal467 @rithviknishad Updated view:
image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
