### PR TITLE
Proxy camera feed PTZ requests through backend

### LINKED ISSUE #3512: Proxy all camera feed PTZ requests through back end
Proxy all camera feed PTZ requests through back end.
Currently all requests are directly made to the middleware server.

### PR DESCRIPTION
**Pull request by rabilrbl**
Resolves #3512
## Proposed Changes

- Proxy all camera feed PTZ requests through backend

### CODE REVIEW

**Comment by nihal467** [comment]
image

@khavinshankar it looks good to me, can you give it a detailed look

**Comment by nihal467** [comment]
@rabilrbl 
image
when we click on the default presets , the page goes white

**Comment by rabilrbl** [comment]
@nihal467 I haven't made any UI changes in this PR.
 Could you please verify if the same issue persist in default staging server?

**Comment by nihal467** [comment]
@rabilrbl 
image

https://care.coronasafe.in/assets/e0744026-5017-489d-9636-72379436ca1c/configure
https://deploy-preview-3767--care-net.netlify.app/assets/e0744026-5017-489d-9636-72379436ca1c/configure

the issue this persist, when you click on default presets, the page goes white and this issue is only happening in your PR not in the current staging

**Review by developedBySJ — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
