### PR TITLE
Made the tooltip of linked facility visible in Users page

### LINKED ISSUE #4537: Linked facility tooltip clipping out
**Describe the bug**
The tooltip for View linked facility is clipping out.

image

**To Reproduce**

1. Go to Users page
2. Hover over the eye icon for "Moh Nihal"

### PR DESCRIPTION
**Pull request by patelaryan7751**
## Proposed Changes

- Fixes #4537 
Made the tooltip of linked facility visible in Users page
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@patelaryan7751 
image

in 14inch laptop, the tooltip is not fully visible

**Comment by patelaryan7751** [comment]
Hey @nihal467 it is fixed now
image

**Comment by nihal467** [comment]
@patelaryan7751 can you merge the latest development branch, i can't find the deployment preview

**Comment by patelaryan7751** [comment]
Hey @nihal467 it's done
deploy preview: https://deploy-preview-4564--care-net.netlify.app/

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
