### PR TITLE
Add tooltip for expand logout profile

### PR DESCRIPTION
**Pull request by anandaashish74711**
## Sidebar Tooltip Enhancement

This pull request addresses an issue where tooltips were missing for the "Expand", "Profile", and "Logout" icons when the sidebar is minimized. This resulted in users accidentally clicking the "Logout" icon instead of the "Expand" icon.

@rithviknishad 

### Changes:
- **Fixes Issue:** Replace `#8585` with the actual issue number.
- Added tooltips for the following icons in minimized sidebar mode:
  - **Expand**
  - **Profile**
  - **Logout**
- Ensured tooltips are properly visible and accessible when the sidebar is minimized.

## Reason for the Change

In the minimized sidebar, users were accidentally clicking the "Logout" button when they intended to click the "Expand" button. Adding tooltips for these icons improves the user experience by providing descriptive labels, helping users differentiate between the buttons.

## Merge Checklist

- [x] Added tests or specs to verify that the tooltips work correctly in both minimized and expanded sidebar modes.
- [x] Updated product documentation if needed to reflect the change.
- [x] Ensured that all UI text (tooltips) is properly localized using I18n files.
- [x] Prepared and attached a screenshot or demo video showcasing the tooltips for inclusion in the changelog.
- [x] Requested peer reviews for code validation.
- [x] Completed QA verification to ensure the feature works as expected in different scenarios.
## How to Use

After the merge, the new tooltips will appear in the sidebar when it is minimized. When hovering over the icons for "Expand", "Profile", or "Logout", users will now see descriptive tooltips to guide them in making the correct selection.

### Screenshot

https://github.com/user-attachments/assets/6c34afd2-6a45-4033-9163-5743aec2b29b

---

### Testing Instructions:

1. Open the sidebar in its minimized mode.
2. Hover over the "Expand", "Profile", and "Logout" icons to see the tooltips.
3. Verify that the tooltips display the correct information.
4. Test on different screen sizes to ensure the tooltips are accessible and behave consistently.

### CODE REVIEW

**Review by bodhish — CHANGES_REQUESTED** [review]
We have another PR that actually changes the layout of the sidebar. Please branch out from that branch keeping it the base. 
#8680

**Comment by anandaashish74711** [comment]
> We have another PR that actually changes the layout of the sidebar. Please branch out from that branch keeping it the base. #8680

#8680 branch (Re-build sidebar UI) has already been merged into develop. it is giving me error ,(fatal: 'origin/Re-build-sidebar-UI-#8680' is not a commit and a branch 'Add-tooltip-to-expand-profile-logout' cannot be created from it) is there another branch I should base my changes on? Please let me know

**Comment by rithviknishad** [comment]
It'd be easier to create a fresh PR from using latest develop branch

**Comment by nihal467** [comment]
@anandaashish74711 any update on this PR,

**Comment by anandaashish74711** [comment]
I added a fresh pr but getting Cypress error

**Comment by rithviknishad** [comment]
Closing as duplicate of #8747

**Pull request closed without merging**
