### PR TITLE
Enhancements to care config #8470

### LINKED ISSUE #8470: Enhancements to care config
https://github.com/ohcnetwork/care_fe/pull/8445 Introduces `care.config.ts` for making CARE configurable from ENVs. However there are couple of enhancements that can be done:

- [ ] Perform config validation during vite build so that build fails thus preventing exceptions from being thrown during runtime if any.
- [ ] Sentry config to be optional and enable sentry only if configured.
- [ ] Plausible config to be optional and enable plausible only if configured.

### PR DESCRIPTION
**Pull request by Sulochan-khadka**
## Proposed Changes

- Fixes #8470 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by Sulochan-khadka** [comment]
New to this kind of Issues, so kindly let me know if there's something needed, or if there are mistakes.

**Comment by khavinshankar** [comment]
@Sulochan-khadka can you please fix the failing cypress tests

**Comment by Sulochan-khadka** [comment]
> @Sulochan-khadka can you please fix the failing cypress tests

i have fixed all cypress tests but dont know why one is failing. May you help!

**Comment by bodhish** [comment]
Not sure if this is the right approach, i was thinking that we would add some sort of json validator that would be run before the build step. 🤔 

@rithviknishad please review the PR

**Review by rithviknishad — CHANGES_REQUESTED** [review]
This does not validate the env's during the build stage. That is the main requirement mentioned in the issue.

image



We could add a script and call that script (that imports `care.config.ts`) before the vite build. If validation fails, exit with a non-zero status code so that vite build does not start (as vite build should happen only after the validation script runs).

**Comment by Sulochan-khadka** [comment]
> This does not validate the env's during the build stage. That is the main requirement mentioned in the issue.
> 
> image
> We could add a script and call that script (that imports `care.config.ts`) before the vite build. If validation fails, exit with a non-zero status code so that vite build does not start (as vite build should happen only after the validation script runs).

Ok so the required task is to create some script like "validate-env.ts" that imports care.config.ts and checks if the necessary environment variables are defined or valid.
And then run through this script before vite build and only proceeds to vite build if the script approves.
Am i on the right track now? If yes, should i close this PR and raise a new one?

**Comment by rithviknishad** [comment]
Yes; you are right

**Pull request closed without merging**
