### PR TITLE
fix: Enhancement of the patient doctor connect

### LINKED ISSUE #4786: Enhancement of the patient doctor connect
image

the following enhancement are to be done inside the doctor connect feature

- [x] remove the qualification of the user to be shown in the doctor connect
- [x] Add an option to call both ways ( whatsapp & voice call )
- [x] Add an option to copy the doctor number

### PR DESCRIPTION
**Pull request by cp-Coder**
# Bug Fix

## Proposed Changes

- Added Voice and WhatsApp call options
- Removed doctor qualifications from connect feature
- Added a clipboard to copy the phone number

## Associated Issue

- Fixes #4786

## Screenshot

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug/test a new feature.
- [x] Update product [documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [x] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by Pranshu1902 — APPROVED** [review]

**Comment by nihal467** [comment]
@cp-Coder 

https://deploy-preview-4819--care-net.netlify.app/facility/2797dc82-4216-47fa-969b-47f02019b6ca/patient/124b749e-8c86-4d3e-8631-53f66a4926f1/consultation/e6acf370-4dce-443e-b4be-9b9198b64cbc

image

marking it for discussion for discussing following points

- [x] icon size is really call
- [x] add a tooltip to the icons
- [x] Currently, the card is not clickable, will it be a problem for the user, since going towards a small call icon and clicking, it doesn't feel like a good experience? I believe, along with the icons any card should be clickable, and we should be redirected to whatsapp calls.

**Comment by aparnacoronasafe** [comment]
lets discuss in EOD

**Comment by nihal467** [comment]
@cp-Coder after the EOD, change the following ASAP

- [x] make the icons bigger
- [x] add a tooltip to the icon
- [x] when someone clicks anywhere in the card, similar to the existing staging, by default, WhatsApp redirection should work

**Comment by nihal467** [comment]
@cp-Coder 
image

the copy button is not working

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
