### PR TITLE
Fix comment overflow and ensure content fits within div

### LINKED ISSUE #8699: UI Bug in the Shifting Section and Resource Section- Comment Box Display Issue
**Describe the bug**
The content inside the comment box is overflowing and not contained within the boundaries of the comment box, causing layout issues.
This affects the display of comments and the overall user interface, as it disrupts the intended design and user experience.

**To Reproduce**

1. Go to Sidebar
2. Click on Shifting and click on All Details on any card 
3. Scroll down to comment section
4. See overflow text

**Expected behavior**
Contain comments within the boundaries of the comment box.

**Screenshots**
Image
Image

### PR DESCRIPTION
**Pull request by chakribontha**
## Proposed Changes

- Fixes #8699
- Resolved the comment overflow issue in shifting and resource sections to ensure content remains within the div.
image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [X] Add specs that demonstrate bug / test a new feature.
- [X] Update [product documentation](https://docs.ohc.network).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [X] Completion of QA

### CODE REVIEW

**Review by bodhish — CHANGES_REQUESTED** [review]
I think we should add `@tailwindcss/typography` and add `prose` class to fix it.

**Comment by chakribontha** [comment]
Hey @bodhish ,

I've made the necessary changes to address the comment-wrapping issue and linked it to issue #8743 . Please check it out. 

Thanks for the feedback!

**Comment by bodhish** [comment]
why create another PR? Just add the commit to this branch and it should solve the issue.

**Review by bodhish — COMMENTED** [review]
Do you need text justify?

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
@chakribontha 
image

- [ ] in the resource page, the text in the comments are properly utilising the right area

**Review by bodhish — APPROVED** [review]

**Comment by samholics** [comment]
tested, working fine @nihal467 
comments on resource is utilizing the right hand side area
image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
