### PR TITLE
View user facility in users tab as a slide over

### LINKED ISSUE #4116: Create slideover component for editing linked facilities of a user
Switch to using a slideover component for editing and viewing linked facilities for a user.
image

### LINKED ISSUE #4585: Slide over for facilities in users page

### PR DESCRIPTION
**Pull request by Pragati1610**
- fixes #4585
- fixes #4116

### CODE REVIEW

**Comment by nihal467** [comment]
@Pragati1610 
image

i need to click twice, for the slide over come in, was it intentional

**Comment by nihal467** [comment]
@Pragati1610 LGTM, marking it as team discussion required for UI final approval

image

**Comment by nihal467** [comment]
Follow-up for the PR

- proportions are wrong and alignment is to be made proper
- the home facility icon needs a tooltip
- the home facility and linked facility need to be separated by a head

**Comment by Pragati1610** [comment]
removed the merge conflict
PR is ready

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
