### PR TITLE
Added patient search by IP number

### LINKED ISSUE #3749: Patient Search: IP No.
Please add the option to search patents by IP No. in the Patient List (https://care.mn.gov.in/patients)

### PR DESCRIPTION
**Pull request by Ashesh3**
Resolves #3749

## Proposed Changes

- Reorganized the patient search and filtering section
- Added a search field to find a patient by the IP number
- Moved the "Select a 7-day period" to a tooltip

msedge_1qu7zEeFE3

image

msedge_HQeDG1udpC

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 
image

the add details of a patient button is not aligned to the other text boxes, can you make it aligned

image

make the badges left aligned

**Comment by Ashesh3** [comment]
Fixed.
image

image

image

**Comment by nihal467** [comment]
@Ashesh3 
image

the white spacing in the page, still look weird, can you take this issue in the EOD call, to have a better approach to this issue

**Comment by Ashesh3** [comment]
@nihal467 After discussion with Aparna, this is the finalized design:

image

I've made the changes to reflect the new design.

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]
LGTM

**Pull request merged**
