### PR TITLE
Remove Extra Spaces

### LINKED ISSUE #2048: UI Change : Consultation Update page
efpkwe

It is center aligned and lots of white space are been wasted

### PR DESCRIPTION
**Pull request by shrihari689**
## 💪 Changes

- Removed Extras Spaces

## 🔍 Preview
 
image

🔨 Resolves #2048

### CODE REVIEW

**Comment by nihal467** [comment]
poefkweopfe

@shrihari689 @gigincg 
in the mobile view, can you increase little bit the following marked heading and the filling area space

**Comment by shrihari689** [comment]
Made the required changes ⛳ @nihal467 

image

**Comment by nihal467** [comment]
test approved

**Comment by nihal467** [comment]
wepfokewof

@shrihari689 @gigincg increase the space for the white padding from both border, start the padding as aligned to the top button

**Pull request closed without merging**
