### PR TITLE
fix: Discharging patients

### LINKED ISSUE #4499: Discharging patients
When a patient is discharged from CARE, There are 4 reasons for discharge. ie, Recovery, Expiry, Referral, LAMA. Currently, we only take additional notes for discharge upon any of these reasons.

Enhance this to have different behavior for each of the reasons for discharge.

1. RECOVERED
When the reason for discharge is selected as "recovered"
- [x] Add field for discharge date. add data validation so that the discharge date is between the admission date and the present date. autofill this to the present date. This must be a mandatory field.
- [x] Rename "Notes" to discharge advice
- [x] Add a prescription and PRN Prescription module below to note discharge medication. give the heading above the modules as "Discharge medication". The whole section shall be non-mandatory

2. EXPIRED
- [x] Add a field before the cause of death to note the date and time of death. Make the date field mandatory and the time field optional
- [x] Add field below Cause of death to say "Death Confirmed By". this field shall have the name of the doctor that confirmed the death. This shall also be a mandatory field.

For REFERRED and LAMA we need not add more details for now

### PR DESCRIPTION
**Pull request by cp-Coder**
# Bug Fix

## Proposed Changes

- Added new fields for recovered and expired discharged patient

## Associated Issue

- Fixes #4499

## Associated PRs

- Backend PR coronasafe/care#1155

## Screenshot

image
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update product [documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [ ] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder 
image

- [x] the medicine applied is not fully visible

image

- [x] the buttons are overlapping with the data

image

- [x] add a validator, if the mandatory field is empty

**Comment by aparnacoronasafe** [comment]
The above issues pointed out by Nihal need to be fixed before deploying. This doesn't meet our quality expectation

**Comment by aparnacoronasafe** [comment]
A few more changes would be nice in this. Only for the form when "Recovered" is selected.
1) Rename "Prescription medication" to "Discharge Prescription"
2) Change the order to "Reason for discharge", "Discharge Date", "Discharge Prescription including PRN" and "Discharge advice"

**Comment by nihal467** [comment]
@cp-Coder @khavinshankar @gigincg  the deployment is failed, check it

**Comment by nihal467** [comment]
@cp-Coder 

image

unable to discharge a patient

**Comment by aeswibon** [comment]
@nihal467 Fixed it

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
