### PR TITLE
Added PatientHomeNonCovid

### LINKED ISSUE #2008: Improve Patient Dashboard for Critical Care
A lot of space in the Patient Page is currently consumed by COVID specific details, such as Testing, Location etc. The needs to be changed to improve the experience for Caregivers treating non-COVID patients.

The dashboard should contain:
 - A flag on the top right if the Patient has some Allergies
 - Vitals from Last Consultation Update (The Last Consultation Update will be Joined with consultation update) -> BE Pending
 - Move Address/Location to Header Area, along with the Name of the Patient
 
> Note: Do not delete the existing Patient Page. We might need to use the same for COVID Patients.

### PR DESCRIPTION
**Pull request by khavinshankar**
New Patient dashboard for non-covid patients

Fixes #2008 

- [x] add `Has Allergies` badge in the patient info section
- [x] move location details to patient info section
- [x] replace Location section with last consultation vitals/notes
- [x] ~remove Frontline Worker and Medical Worker from Tracing section~
- [x] wire the PatientHome for covid patients and PatientHomeNonCovid for non-covid patients

### CODE REVIEW

**Review by gigincg — CHANGES_REQUESTED** [review]
Errored out while testing. @khavinshankar 

image

**Comment by nihal467** [comment]
@khavinshankar @gigincg  test failed



after hard-refreshing i can't find the change

**Comment by khavinshankar** [comment]
@nihal467 it's working fine

> if the patients are covid positive, the UI is the usual one

image

> if the patients are not covid positive then we show vitals instead of 

image

**Comment by nihal467** [comment]
@khavinshankar @gigincg test approved but the merging is blocked, can you check it

**Comment by nihal467** [comment]
@khavinshankar can you check the alignment

**Comment by khavinshankar** [comment]
@nihal467 the **_right side section_** and **_left side section_** is made to center themselves based on the section that is lengthy, i.e if the **_left side section_** is lengthy then the **_right side section_** is centered with respect to the **_left side section_** and vice versa

**Comment by nihal467** [comment]
test approved

**Review by gigincg — CHANGES_REQUESTED** [review]
@khavinshankar Can you make a new Component Named PatientHome and Replace the existing PatientHome as CovidPatientHome, so that you can abstract the logic of selecting between these two in the right place.

**Comment by aparnacoronasafe** [comment]
@khavinshankar 

This is regarding showing vitals for non-covid patients instead of the location. There is one major issue. This change implies that we consider vitals of COVID patients not important. 

Vitals are a key parameter for the treatment of any patient, COVID or Non-COVID. hence it must be visible in the same place for all patients, COVID or non-COVID. 

Also, I suggest that vitals appear above shifting details, for all patients. 

Also, with respect to showing location/tracking details etc. It may be a good idea to show this information for all patients, COVID or NON-COVID in the same manner. What may be smarter is to hide such surveillance-related details from certain users like Doctors. 

The doctors need not see the following details on a patient dashboard:
1. Location, 
2. Tracing details
3. Shifting details


@gigincg

**Comment by gigincg** [comment]
@khavinshankar Can you make the requested changes?

**Comment by khavinshankar** [comment]
- [x] show vital details for COVID patients also
- [x] move shifting-details section below vitals section
- [x] remove shifting from Non-COVID patients
- [x] add the address in the main section for COVID patients

We are currently having 2 components for Patient Dashboard (CovidPatientHome and PatientHome), the only difference between them is that PatientHome doesn't have a shifting details section, 

So we can merge 2 components into 1, but maybe later having 2 components can be beneficial when we have to make drastic changes, Like to know your opinions @gigincg

**Comment by gigincg** [comment]
There is a possibility of removing the covidpatienthome altogether at a later stage, so let them be different

**Pull request closed without merging**
