### PR TITLE
fixes Code Refactor: ConsultationDetails.tsx #5830

### PR DESCRIPTION
**Pull request by nazrul7711**
### <samp>🤖 Generated by Copilot at 68d8064</samp>

The pull request adds several new components to the `src/Components/Facility` directory, each corresponding to a different tab for displaying consultation data. The components use the `ConsultationTabProps` type and the `Page` component from `src/Common/constants.tsx`. The components render various plots, tables, diagrams, and files related to the consultation, such as blood gas analysis, dialysis, nursing, nutrition, pressure sore, and ventilator data.
The pull request adds several new components to the src/Components/Facility directory, each corresponding to a different tab for displaying consultation data. The components use a common interface defined in src/Common/constants.tsx to receive props from the parent component. The components also import and render various plot, table, and file upload components from other directories. The purpose of the changes is to enhance the user interface and functionality of the consultation feature.
The task was to break ConsultationDetails.tsx files into smaller components.

## Proposed Changes
I made the following components.

ConsultationUpdatesTab
ConsultationFeedTab
ConsultationSummaryTab
ConsultationMedicinesTab
ConsultationFilesTab
ConsultationABGTab
ConsultationNursingTab
ConsultationNeurologicalMonitoringTab
ConsultationVentilatorTab
ConsultationNutritionTab
ConsultationPressureSoreTab
ConsultationDialysisTab
ConsultationInvestigationsTab

- Fixes #issue?
- https://github.com/coronasafe/care_fe/issues/5830
- Change 1
- apart from making above components I defined ConsultationTabProps interface in common/constants folder that works as type for props
- Change 2
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 68d8064</samp>

*  Create `ConsultationTabProps` interface to define common props for consultation tabs ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-37705b30476b14631124ce42dd5c3500d43fbede16f0e91f9ae2905e4adc6376R21-R30))
*  Import `ConsultationModel` and `PatientModel` interfaces to use in props ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-37705b30476b14631124ce42dd5c3500d43fbede16f0e91f9ae2905e4adc6376L2-R9))
*  Create `ConsultationABGTab` component to render arterial blood gas analysis plots ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-37cbab8206f9b275c81cca15f1943740761155b8701f37d3fda8ad400243504aR1-R18))
*  Create `ConsultationDialysisTab` component to render dialysis plots ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-e230d3bf9ef5b5894ef4438c3477424447e8ea5a47ec5f3581e4330f5118f682R1-R12))
*  Create `ConsultationFeedTab` component to render camera feed ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-317a7d01218cf9da242585534f43a5642b4605a4ecc6602e59508d5012a47f03R1-R23))
*  Create `ConsultationFilesTab` component to render file upload and view ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-e1b9a44c274ac216cdafc32292c6df224ac088f6e4315bef4eed4b536e76938eR1-R22))
*  Create `ConsultationInvestigationsTab` component to render investigations and test results ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-3a71b0570d5ba337265aa75a1ed4f9db1cb9127ac90ee5d8fbf434fbf4954ffaR1-R44))
*  Create `ConsultationMedicinesTab` component to render prescribed and administered medicines ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-1671491462b930c7046a47a077dbaf44df06d778dc0ca8d1cd9fe4946d85b02aR1-R38))
*  Create `ConsultationNeurologicalMonitoringTab` component to render neurological monitoring data ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-e4f97f07588f5b7bc54342edaeaf73669efce9afc32de7d1117a05d8297eb6edR1-R18))
*  Create `ConsultationNursingTab` component to render nursing analysis plot ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-eab95771feac126dce3fa203fe1814744397adefd8977e115be003826c471b90R1-R19))
*  Create `ConsultationNutritionTab` component to render nutrition plots ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-cb8acdf295f8c509f491fcac4056f195d5a053ffe55c2227f2ff38e71f771d64R1-R18))
*  Create `ConsultationPressureSoreTab` component to render pressure sore diagrams ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-f19bc797d9d21daa0b1e6629886e48ec8a61f14775e0ba061376793de70070f1R1-R18))
*  Create `ConsultationSummaryTab` component to render primary parameters plot ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-688b5343afa5fd0f25b3d38f39c5c274891b80e12b6ba9f70131035249a9774bR1-R24))
*  Create `ConsultationVentilatorTab` component to render respiratory support plot ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-ecefa1bf4d08a7a28d05a6eab655fee08fea6e2ba90bfd9916988d69d5b1108dR1-R18))
*  Pass `ConsultationTabProps` to each tab component as props ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-37cbab8206f9b275c81cca15f1943740761155b8701f37d3fda8ad400243504aR1-R18), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-e230d3bf9ef5b5894ef4438c3477424447e8ea5a47ec5f3581e4330f5118f682R1-R12), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-317a7d01218cf9da242585534f43a5642b4605a4ecc6602e59508d5012a47f03R1-R23), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-e1b9a44c274ac216cdafc32292c6df224ac088f6e4315bef4eed4b536e76938eR1-R22), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-3a71b0570d5ba337265aa75a1ed4f9db1cb9127ac90ee5d8fbf434fbf4954ffaR1-R44), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-1671491462b930c7046a47a077dbaf44df06d778dc0ca8d1cd9fe4946d85b02aR1-R38), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-e4f97f07588f5b7bc54342edaeaf73669efce9afc32de7d1117a05d8297eb6edR1-R18), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-eab95771feac126dce3fa203fe1814744397adefd8977e115be003826c471b90R1-R19), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-cb8acdf295f8c509f491fcac4056f195d5a053ffe55c2227f2ff38e71f771d64R1-R18), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-f19bc797d9d21daa0b1e6629886e48ec8a61f14775e0ba061376793de70070f1R1-R18), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-688b5343afa5fd0f25b3d38f39c5c274891b80e12b6ba9f70131035249a9774bR1-R24), [link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-ecefa1bf4d08a7a28d05a6eab655fee08fea6e2ba90bfd9916988d69d5b1108dR1-R18))
*  Add button to log lab results in `ConsultationInvestigationsTab` with authorization and navigation logic ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-3a71b0570d5ba337265aa75a1ed4f9db1cb9127ac90ee5d8fbf434fbf4954ffaR1-R44))
*  Use state variable to re-render medicine tables when prescriptions change in `ConsultationMedicinesTab` ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-1671491462b930c7046a47a077dbaf44df06d778dc0ca8d1cd9fe4946d85b02aR1-R38))
*  Make medicine tables read-only if consultation is discharged in `ConsultationMedicinesTab` ([link](https://github.com/coronasafe/care_fe/pull/5885/files?diff=unified&w=0#diff-1671491462b930c7046a47a077dbaf44df06d778dc0ca8d1cd9fe4946d85b02aR1-R38))

### CODE REVIEW

**Comment by nazrul7711** [comment]
@rithviknishad Kindly review this PR. I have implemented all the suggested points from previous PR

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@nazrul7711 can you resolve the merge conflict

**Comment by nazrul7711** [comment]
hey @nihal467 I have resolved the conflicts.

**Comment by nihal467** [comment]
@nazrul7711 can you clear the merge conflict

**Comment by nazrul7711** [comment]
hey @nihal467  i have resolved conflicts again . I don't know why m seeing these conflicts some are the same conflicts which I resolved yesterday.

**Comment by rithviknishad** [comment]
@nazrul7711 fix the build

image

**Pull request closed without merging**
