### PR TITLE
Added link from facility page to /facility/<external_id>/users/

### PR DESCRIPTION
**Pull request by siddnikh**
Solves #2955 
Part of https://github.com/coronasafe/care/issues/785

### CODE REVIEW

**Comment by siddnikh** [comment]
Corresponding backend pr: https://github.com/coronasafe/care/pull/905

**Comment by siddnikh** [comment]
to see: Go to a facility home page and click on view users

**Review by naman114 — COMMENTED** [review]
The view users button directs to a 404 page @siddnikh 

image

**Comment by nihal467** [comment]
@siddnikh update it to need testing once completed

**Review by naman114 — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
