### PR TITLE
[FIXED] Total Discharge patients Number is made Visible for all user type

### LINKED ISSUE #7570: Total Discharge patients Number to be made Visible for all user type
Total Discharge Patient Number is evanesce after the reposition the Discharge Patients module. 
There's Need to show the total number of Discharge patient Counts on Clicking "Discharge" in the total Patients list like how it is seen for Live Patients for the purpose understand and analytics for all user Types. 
Since Currently the total counts(numbers) of Discharged patients is only visible for State Admin User type.

Screenshot 2024-04-08 172442

### PR DESCRIPTION
**Pull request by r-nikhilkumar**
- Fixes #7570 
- Total Discharge patients Number is made Visible for all user type
Screenshot 2024-04-13 172618

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by Ashesh3 — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@r-nikhilkumar 
image

- [ ] In your current deploy preview, it is not communicating the total number of discharged patients effectively. Think of a better consistent UI, and build a mockup, discuss it during the call. For example, in the screenshot above, the total count is shown across the platform.

**Comment by r-nikhilkumar** [comment]
@nihal467 It won't show any number if there's no discharged patient available there, and in the current ui, the number will be visible once you will go in discharged section, in the screenshot you are in live section, I discussed with mentor then after I implemented this.

**Comment by r-nikhilkumar** [comment]
@nihal467 you are saying in live it should only show live patients who isn't discharged yet but it's showing total counts including discharged also??

**Comment by r-nikhilkumar** [comment]
@aparnacoronasafe, @gigincg @nihal467
Here are some examples of UI, as @nihal467 said in today's meeting to share these three UIs, kindly have a look and check

image
image-2
image-1

**Comment by aparnacoronasafe** [comment]
Design to be kept consistent with patient live listing

**Comment by r-nikhilkumar** [comment]
@aparnacoronasafe so which design should I implement?

**Comment by rithviknishad** [comment]
> so which design should I implement?

@r-nikhilkumar As mentioned, designs to be kept consistent like how we have in the Live patients list page.

None of the designs shown above are consistent with the live patients list page.

**Comment by rithviknishad** [comment]
Closing as no activity and completed in #7744

**Pull request closed without merging**
