### PR TITLE
AutoCompleteAsync: make button and input as peers instead of parent children

### LINKED ISSUE #3937: Unable to correct inputted data in Patient and user management tab
**Describe the bug**

- [ ] When we input a data inside a patient filters, we cant click in between the data and correct any one letter. For example, we inputted kozhikode and we want to replace o with k. Without removing the entire inputted data, it is not possible. ( By using arrow keys in keywords, it is possible but initially by clicking using mouse in the middle of the inputted data and correcting it is not possible )
- [ ] Similarly in the facility pop-up coming after clicking add patient button in the patient tab
- [ ] Similarly in the link facility pop-up coming after clicking link facility button in the user card
- [ ] similarly in the add user page in the user tab
 
**To Reproduce**

- https://care.coronasafe.in/patients
- https://care.coronasafe.in/users

**Expected behavior**

we should be able to edit it

**Screenshots**

image
image
image
image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Resolves #3937 

https://user-images.githubusercontent.com/25143503/199979463-c1095719-5ba6-4e2c-8e3d-7b9c2bb14a68.mp4

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 

image

- [ ] the text box are not fully visible

image

- [ ] once a option is selected, Trivandrum, i can't click in between trivandrum and edit it,

**Comment by rithviknishad** [comment]
@nihal467 fixed :)

https://user-images.githubusercontent.com/25143503/199979463-c1095719-5ba6-4e2c-8e3d-7b9c2bb14a68.mp4

**Comment by nihal467** [comment]
@rithviknishad 
image

the asset page filters are not working properly

**Comment by nihal467** [comment]
@rithviknishad 
image

it is breaking the add user droplist

**Comment by rithviknishad** [comment]
@nihal467 could you check it now

**Comment by nihal467** [comment]
@rithviknishad can you merge the latest branch

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
