### PR TITLE
Popups for "Edit/ Add Bed Capacity" & "Edit/Add Doctor Capacity"

### LINKED ISSUE #4425: New Popups for "Edit/ Add Bed Capacity" & "Edit/Add Doctor Capacity"
**Replacing separate pages with popups**
Now, if we want to add / edit bed capacity or doctor capacity we are directed to separate other pages. I think it will be a lot easier if we can give a way to update them on the "Facility page" itself b giving a modal/Popup

**Present Design**

image

**New Design**

image
image
image

Link to figma; https://www.figma.com/file/fqDMgeN2m4TCSz5KobZaKW/CoronaSafe-Network-Care?node-id=2065%3A1200&t=6hPGONdVWgJTMBya-1

### PR DESCRIPTION
**Pull request by Ashesh3**
Resolves #4425 

image
image
image
image

Onboarding after facility creation:

image
image
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 as per our slack communication, you have mentioned about minor changes, so changing this to work in progress

**Comment by Ashesh3** [comment]
> @Ashesh3 as per our slack communication, you have mentioned about minor changes, so changing this to work in progress

Changes are done.
image

image

**Comment by nihal467** [comment]
@Ashesh3 
image

can you get the alignment to the left for both pop-up

**Comment by Ashesh3** [comment]
> @Ashesh3 image
> 
> can you get the alignment to the left for both pop-up

Fixed.

**Comment by nihal467** [comment]
@Ashesh3 is the PR ready for testing and check the merge conflict

**Comment by Ashesh3** [comment]
> @Ashesh3 is the PR ready for testing and check the merge conflict

It's ready now, changes are made.

> Requires #4557 to be merged before

image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
