### PR TITLE
Removed the Tracing and Testing sections from the 'Patient Details' Page

### LINKED ISSUE #2762: Patient details- cleanup
Remove the sections from "Patient details" page (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/b836f81a-0031-48a3-bb1a-63b6cba35d23)

- [ ] Testing
- [ ] Tracing

### PR DESCRIPTION
**Pull request by GokulramGHV**
Fixes #2762 

The Testing section and the Tracing section are removed from the Patient Details Page.

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

**Comment by cp-Coder** [comment]
@GokulramGHV You haven't updated your netlify.toml file. [Here is the link for the correct file](https://github.com/cp-Coder/care_fe/blob/develop/netlify.toml).

**Comment by aeswibon** [comment]
@GokulramGHV You have to reset Gigin's recent commit in netlify.toml. Gigin recently updated netlify.toml to use NPM.

**Comment by aeswibon** [comment]
@GokulramGHV Now you can merge upstream/develop and it will work

**Review by patelaryan7751 — APPROVED** [review]

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
