### PR TITLE
Add Test suit for Image Upload Functionality

### LINKED ISSUE #9109: Refactor the existing cypress test to upload cover image
**Description**

Enhance the existing test suite to include functionality for uploading, editing, and deleting the facility cover image.

**General Instruction**

- Code should follow the POM structure.
- Reuse existing custom functions and those in commands.ts where possible. Before creating a new function, check for an existing one that matches the element's ID to avoid redundancy.
- Add API request verification wherever required using cy.intercept();
- Add the tests in the facilityManage.cy.ts file and any new page objects in the facilityManage.ts file.

**Test Workflows**

**Test 1: District Admin** 

1. Log in as a district admin and navigate to any facility.
2. Open the facility cover image pop-up, then click the Cancel button to verify it functions correctly.
3. Reopen the cover image pop-up and upload an image, verifying the API response.
4. Edit the current cover image by uploading a new one, and verify the API response.
5. Delete the existing cover image, confirming the API response.

**Test 2: Access Verification with Non-Admin User**

1. Log in as the devdoctor user.
2. Repeat the steps from Test 1 to verify functionality consistency across user roles.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by JavidSumra**
## Proposed Changes

- Fixes #9109
- Added Test Suit to Ensure Functionality of Upload Image
- Updated Ratio of Image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Introduced functionality to upload, edit, and delete cover images for facilities.
	- Added a delete button for avatar management in the AvatarEditModal component.

- **Bug Fixes**
	- Improved accessibility by updating button IDs for better targeting in tests and styles.

- **Tests**
	- Implemented a comprehensive end-to-end test suite for cover image functionalities. 

- **Enhancements**
	- Enhanced methods for managing facility capacities and network request verification in the FacilityManage class.

### CODE REVIEW

**Comment by rithviknishad** [comment]
Closing due to no activity

**Comment by JavidSumra** [comment]
Hey @rithviknishad got some college work so due to that not able to contribute can you please open it again?

**Comment by JavidSumra** [comment]
Hey @nihal467, I have a doubt regarding this test suite. Since the upload and edit cover image procedures use the same API call, can we replace the edit procedure test with a test for an invalid image width instead?

**Comment by nihal467** [comment]
> Hey @nihal467, I have a doubt regarding this test suite. Since the upload and edit cover image procedures use the same API call, can we replace the edit procedure test with a test for an invalid image width instead?

You can do that: verify the error message, replace the existing image with a new one, and complete the test.

**Comment by rithviknishad** [comment]
no longer relevant in new architecture

cc: @nihal467

**Pull request closed without merging**
