### PR TITLE
Added privacy toggle for a consultation bed and lock camera controls when used by a user

### LINKED ISSUE #5892: User Notification for Concurrent Viewers under Live Camera Feed Enhancement
**Is your feature request related to a problem? Please describe.**
Make a locking mechanism for assets. This will notify other users when an asset is already under use and allow for better concurrency. 

**Describe the solution you'd like**
- Implement an in-memory key-value pair in CARE backend  to implement occupancy status of an asset.
- Valdiate all api requests to the asset based on this lock.
- Notify the user if the the asset is locked.

**Additional context**
This is a sub issue related to the original issue #5494  under the C4GT program.

### PR DESCRIPTION
**Pull request by khavinshankar**
- Fixes ohcnetwork/care_teleicu_devices_fe#11 
- Fixes ohcnetwork/care_teleicu_devices_fe#9 

@ohcnetwork/care-fe-code-reviewers

## Release Notes

- **New Features**
	- Introduced a user management and notification system in the CameraFeed component for better interaction.
	- Added a PrivacyToggle component for managing privacy settings of consultation beds.
	- Enhanced localization support with dynamic translations for button labels and messages.

- **Bug Fixes**
	- Improved error handling and user feedback for camera operations and privacy settings.

- **Documentation**
	- Updated localization files with new keys for camera functionality and privacy management.

These changes enhance user experience by improving functionality, interaction, and accessibility across the application.

### CODE REVIEW

**Comment by nihal467** [comment]
image

- [x] Even though the camera feed is live, there is a frontend notification thrown mentioning that the camera is locked

image

- [ ] assetbed API is failing and we are not able to create a new camera preset 

image

- [ ] Currently, the camera feed component is not showing multiple icons to represent that there are multiple users are viewing the feed

image

- [x] when a user request for a camera access, it is get auto-granted without notification

**Comment by nihal467** [comment]
@khavinshankar the basic functionality is failing across, can you fix everything and attach a QA video

**Comment by khavinshankar** [comment]
@nihal467 I have added a demo video explaining the feature https://drive.google.com/file/d/1hPv1wdme2n87dFL95KwoDwAuOSQPt0pd/view?usp=sharing

> Even though the camera feed is live, there is a frontend notification thrown mentioning that the camera is locked

This is an expected notification but the content was misleading, so I updated the wording.

> assetbed API is failing and we are not able to create a new camera preset

I was not able to replicate this, this could have happened due to the backend having migrations from other PRs, please removing the existing database and creating a new one with fresh migrations.

> Currently, the camera feed component is not showing multiple icons to represent that there are multiple users are viewing the feed

Can we make this as a new good-first issue, so that the basic version of patient privacy and camera control locking can be merged.

**Comment by nihal467** [comment]
image

- [x] whenever we open, it still sends two notification in the frontend, i think its due to the operate_asset api is been called from frontend, can you check that issue, rest looks good

**Comment by nihal467** [comment]
image


@khavinshankar each time when i open the camera and viewing this notification kind of weird, but we can think of a enhancement once the PR is merged, open an issue and look for a better UX

**Comment by nihal467** [comment]
except the previous comment, rest LGTM

**Review by rithviknishad — APPROVED** [review]

**Review by shivankacker — APPROVED** [review]

**Comment by bodhish** [comment]
@khavinshankar lets get this merged.

**Comment by khavinshankar** [comment]
Blocking this PR till the [camera plug](https://github.com/ohcnetwork/care/pull/2610) is merged.

**Pull request closed without merging**
