### PR TITLE
Generalize Import and Export + Add create asset button on asset list page + Fix patients page padding

### LINKED ISSUE #4252: Generalize the Download/Import/Export design to use Dropdown
**Is your feature request related to a problem? Please describe.**
Currently the download / export of various pages does not have uniform design.

**Describe the solution you'd like**
Use consistent design: Dropdown Menu for Import/Export/Download buttons

**Tasks:**
- [x] Dropdown for Facilities (Export Facilities, Export Facility Capacity List, Export...)
- [x] Dropdown for Patients (Export and Import)
- [x] Dropdown for Assets (Export and Import)
- [x] Export Icon with Tooltip for Samples
- [x] Export Icon with Tooltip for Shift Requests
- [x] Export Icon with Tooltip for Resource
- [x] Dropdown for External Results (Export and Import)

**Additional context**

1. Facilities (to use Dropdown)
image

2. Patients (to use Dropdown)
image

3. Assets (to use Dropdown)
image

4. Samples (to use export icon with tooltip)
image

5. Shift Requests (to use export icon with tooltip)
image

6. Resource (to use export icon with tooltip)
image

7. External Results (to use Dropdown)
image

### LINKED ISSUE #4290: Add Create asset button in asset view page
**Is your feature request related to a problem? Please describe.**

Currently, the Create asset button is only present on the facility page

**Describe the solution you'd like**

Add a button to Create asset button on the asset view page.

image

### LINKED ISSUE #4311: Incosistent padding for patients list page
**Describe the bug**
The patients' list page has abnormal padding when compared to other pages that have consistent padding.

**To Reproduce**

1. Go to the patients list page

**Expected behavior**
The patients' list page should have consistent padding as other pages do.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- [x] Resolves #4252
- [x] Resolves #4290 (by @Ashesh3)
- [x] Resolves #4311 

### Generalization of Import / Export
- [x] Facilities
- [x] Patients
- [x] Assets: Import and Export for District and State Admins
- [x] Sample Test
- [x] Shifting (for both list and board view)
- [x] Resource (for both list and board view)
- [x] External Results

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

image

image

image

image

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad PR LGTM, marking it for Team discussion required for final UI Approval.

@rithviknishad check the cypress deplyment

**Comment by rithviknishad** [comment]
@nihal467 I've updated the cypress test for external results

**Comment by khavinshankar** [comment]
@nihal467 this pr was already discussed in yesterday's EOD I guess, wasn't it already approved @rithviknishad?

**Comment by rithviknishad** [comment]
@khavinshankar yes, kindly review it :)

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
