### PR TITLE
Add search groups and investigation in one search bar

### LINKED ISSUE #1671: Add search bar to ICU Log Update
A lot of times, the data entry may be done by a non-medico.

hence it is important to have a search bar to search for parameters across all heads

### PR DESCRIPTION
**Pull request by abhinandanarya06**
### Issue:  #1671 

0e2dfbea-02ca-49d4-8287-a7f510fcdabe

closes #1671

### CODE REVIEW

**Comment by nihal467** [comment]
@abhinandanarya06 searching two times is not practical, can we make it to one search

**Comment by ghost** [comment]
@nihal467 
Done, Can you test again?

**Comment by samholics** [comment]
tested, verified

**Comment by bodhish** [comment]
@developedBySJ can you review the PR?

**Comment by nihal467** [comment]
test approved

**Review by gigincg — APPROVED** [review]

**Pull request merged**
