### PR TITLE
TeleICU Patient Page

### LINKED ISSUE #2108: TeleICU Hub Patient Page
There needs to be a separate page for a hub to monitor a certain Patient

Here's a reference wireframe:
image

The Diagnosis can be a separate Card on the right hand side and the Medical History can be cloned from the existing Medical History Component in the Patient Registration Page

### PR DESCRIPTION
**Pull request by shrihari689**
## 💪 Changes

- Add required Images and Icons 🚀
- Add Types and Utility functions 🔨
- Add UI for Patient Details Page 🎨

## 🖼 Preview 

image

⛳ Resolves #2108

### CODE REVIEW

**Comment by nihal467** [comment]
@shrihari689 can you post a video, how it is working !

**Comment by shrihari689** [comment]
@nihal467 This is just the UI for the TeleICU Patient Page.
https://github.com/coronasafe/care_fe/issues/2109

**Comment by gigincg** [comment]
@shrihari689 The Links on Top are not wired (Doctor Video should be shown only if there's an Assigned Doctor. It should work similar to this in Patient Page
image

Also the Camera Feed button should be linked to the Camera Page not the 5 Para Monitor button

**Comment by gigincg** [comment]
@nihal467 You can access the page to test at /teleicu/facility/facilityId/patient/patientId

**Comment by shrihari689** [comment]
@gigincg  

## 🚀 Changes

- Corrected Camera Button to Feed Page 📷
- Doctor Video button is linked as of now, because of https://github.com/coronasafe/care_fe/issues/2137

**Pull request merged**
