### PR TITLE
fix spacing of time div

### LINKED ISSUE #2195: Overlapping Issue : Consultation page
Screenshot 2022-03-31 164137

- the 2 days and the date is been overlapping
- the spacing of the box is also irregular, lot of space wasted in the bottom of the box

### PR DESCRIPTION
**Pull request by arpancodes**
fix #2195 
Before:
Before

After:
image

### CODE REVIEW

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
@gigincg @arpancodes the deployment preview is showing failed !

**Comment by gigincg** [comment]
@arpancodes Can you merge develop into the branch?

**Comment by nihal467** [comment]
@gigincg @arpancodes the deployment still is failed

**Comment by arpancodes** [comment]
@gigincg merged with develop, added `*.toml` file for `eslintrc` to ignore.

**Comment by arpancodes** [comment]
@nihal467 branch is deployed now...

**Pull request closed without merging**
