### PR TITLE
Issue#2807 - District filter for Users.

### PR DESCRIPTION
**Pull request by siddnikh**
Solves https://github.com/coronasafe/care_fe/issues/2807

### CODE REVIEW

**Comment by nihal467** [comment]
@siddnikh once the work is completed, change the label to need testing

**Comment by nihal467** [comment]
@siddnikh test failed, as it is not aligned to others

**Comment by nihal467** [comment]
@siddnikh 



- [ ] i have selected Ernakulam district and the badge is showing number 7
- [ ] resolve the merging issue

**Comment by siddnikh** [comment]
@nihal467 Changes done as asked. Good for review!

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
image

@siddnikh  the selected value is not showing

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
