### PR TITLE
Remove admitted_to filter

### LINKED ISSUE #2642: Patient list filter "Last Admitted" fails
Applying the filter `Last Admitted to (Bed Type)` fails the search, erroring out as follows:

```
File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/query.py", line 1243, in build_filter
    raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
django.core.exceptions.FieldError: Related Field got invalid lookup: admitted_to
```

image

### PR DESCRIPTION
**Pull request by Ashesh3**
Closes #2642
Backend change: https://github.com/coronasafe/care/pull/841

The attribute this filter is referring to is removed from the backend, hence applying this filter fails. This change will remove the filter from the UI and also clean it up from the backend.

### CODE REVIEW

**Comment by aeswibon** [comment]
@Ashesh3 I think we need to add this filter in the backend because @aparnacoronasafe opened an issue #2752 regarding this filter.

**Comment by nihal467** [comment]
@Ashesh3 what is the PR status

**Comment by Ashesh3** [comment]
> @Ashesh3 what is the PR status

Backend change was merged, We can proceed to test out this PR.

**Comment by nihal467** [comment]
@Ashesh3 @gigincg is the admit_to filter getting removed or not, i can see @aparnacoronasafe comments been mentioned in it, can i get some clarity on this PR

**Comment by Ashesh3** [comment]
Dependent PR: https://github.com/coronasafe/care/pull/924

**Comment by mathew-alex** [comment]
:wave: Hi, @Ashesh3,
Conflicts have been detected against the base branch. Please rebase your branch against the base branch.

***

This message is automatically generated by [prince-chrismc/label-merge-conflicts-action](https://github.com/prince-chrismc/label-merge-conflicts-action) so don't hesitate to report issues/improvements there.

**Comment by khavinshankar** [comment]
@Ashesh3 is the issue fixed, why was this pr closed?

**Comment by Ashesh3** [comment]
> @Ashesh3 is the issue fixed, why was this pr closed?

Yep, this was fixed by @sainak on the backend and as for the frontend, @aparnacoronasafe stated removing the admitted to isn't an option so this PR is not applicable.

**Pull request closed without merging**
