### PR TITLE
fixes "Created-at" section peeping out of "Doctor's discussion"

### LINKED ISSUE #8795: "Created-at" section peeping out of "Doctor's discussion"
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Sulochan-khadka**
## Proposed Changes

- Fixes #8795 
- Change z-index to 10

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

@Sulochan-khadka the issue still persist

**Comment by bodhish** [comment]
@Sulochan-khadka when you are making a PR please make sure that its working. I would highly recommend you to complete the Merge checklist when you submit a PR. 

- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.

☝️ we have added this in the merge checklist for the author to catch accidental bugs that he maynot have caught, a demo would actually be help them discover it better.

**Comment by Sulochan-khadka** [comment]
@nihal467 @bodhish Apologies for the inconvenience caused. Actually i only explored the bug in patient's notes and not in discussion notes. Therefore, was a bit confused. Have solved both the bugs...

Patent's notes:
 
Screenshot 2024-10-21 at 4 23 56 PM

Discussion notes:

Screenshot 2024-10-21 at 4 25 34 PM

**Comment by Jacobjeevan** [comment]
@Sulochan-khadka Can you resolve the conflicts?

**Comment by Sulochan-khadka** [comment]
> @Sulochan-khadka Can you resolve the conflicts?

While merging , it is showing error in this line :
"import { pluginMap } from "./pluginMap"; " Does this file exists. @nihal467 @rithviknishad

**Comment by Jacobjeevan** [comment]
> While merging , it is showing error in this line : "import { pluginMap } from "./pluginMap"; " Does this file exists. @nihal467 @rithviknishad

https://github.com/ohcnetwork/care_fe?tab=readme-ov-file#install-the-required-dependencies will create the file

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
