### PR TITLE
Adds support for printing 🖨️ prescriptions 💊

### LINKED ISSUE #8258: Feat: Print Prescriptions
#### Description:
A high-priority request has been made to expedite the feature for printing current prescriptions. This functionality is urgently needed to support field operations until the pharmacy system is fully integrated.

#### Requirements:
- Implement functionality to print current prescriptions.
- No additional features related to administration or timelines are required at this stage.

#### Implementation
As a temporary solution, a Front-end first Print Layout for the current prescriptions should solve the field difficulties.

#### Notes:
- This feature will be a temporary but critical for the field operations.

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Resolves #8258

**Print Outputs:**

- v1: [Prescriptions - Gigin C George _ CARE.pdf](https://github.com/user-attachments/files/16510911/Prescriptions.-.Gigin.C.George._.CARE.pdf)
- v2: [Prescriptions - Gigin C George _ CARE.pdf](https://github.com/user-attachments/files/16529088/Prescriptions.-.Gigin.C.George._.CARE.pdf)
- v3 (latest): [Prescriptions - Gigin C George _ CARE.pdf](https://github.com/user-attachments/files/16539245/Prescriptions.-.Gigin.C.George._.CARE.pdf)

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by samholics** [comment]
Tested  Working. However
No indications for Titrate Dosage are mentioned in the table if Titrate is enabled . also the Dosage column is empty for the titrate medicine @nihal467 
image

**Comment by rithviknishad** [comment]
Looking into it @samholics 

Few things to that needs to be discussed:

- [x] Should date of print be mentioned in the print?
- [x] Should any other patient details has to be included? (Address has been seen in many sample images on google)

**Comment by gigincg** [comment]
@rithviknishad Date of Print is good to have.

Can we remove the Rx and put a Care Logo

Additionally Lets just have the info of their admission/care. Facility, Location, Bed Number.

**Comment by rithviknishad** [comment]
@gigincg I've updated with all those just before your comment. Could you re-check.

Taken inspiration from: https://docs.google.com/document/d/1mF9GDLx-3wgf-ayvcAXPy428lVaZbvO8T8y_LD50nXA/edit

**Comment by nihal467** [comment]
image

@rithviknishad disable the print button, if there is no active prescriptions

image
image

- [x] instruction of titration is missing in the format

image

- [x] the print button is not fully responsive

image

- [x] for domicilary care patient, its not DOA , it will be date of domicilary care commencement right, take a confirmation from gigin or aparna what to do on this case

image

- [x] as per suggested format, keep the name of the facility of top

**Comment by rithviknishad** [comment]
@nihal467 Updated

image

**Comment by nihal467** [comment]
@rithviknishad can you look into the cypress failure

**Comment by rithviknishad** [comment]
Unrelated; due to a recent backend change.

Caused by: https://github.com/coronasafe/care/pull/2324
Sentry issue: https://coronasafe-network.sentry.io/issues/5690167888/?project=5182842&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=1

Tracked in: https://github.com/coronasafe/care/issues/2347

cc: @sainak

**Comment by nihal467** [comment]
the cypress failure was due to the events backend PR, so conditionally approving this PR as this is unrelated.

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
