### PR TITLE
Fix: Added location for linked facility

### LINKED ISSUE #9367: List facility details in the user facilites page
Image

Currently we are only showing the name of the facility, it would have been nice if we could have shown the facility name and location.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #9367 

@ohcnetwork/care-fe-code-reviewers

# Screenshot
Screenshot 2024-12-11 at 7 37 20 PM

## Merge Checklist

- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews

## Summary by CodeRabbit

- **New Features**
	- Enhanced display of facility names with improved styling, including bold names and smaller gray district and state names for better user context.
	- Improved visual alignment and styling of facility buttons for a more user-friendly interface.
- **Bug Fixes**
	- Updated handling of facility selection to ensure proper functionality when setting a home facility.

### CODE REVIEW

**Comment by Jacobjeevan** [comment]
Hmm, maybe we could display the local body name as well...but both in a tool tip? 🤔  I'll ping the design channel for ideas.

**Comment by Jacobjeevan** [comment]
@AdityaJ2305 Try this:

image

**Comment by AdityaJ2305** [comment]
> @AdityaJ2305 Try this:
> 
> image

👍

**Comment by AdityaJ2305** [comment]
@Jacobjeevan, Done 

Screenshot 2024-12-12 at 4 13 03 PM

**Comment by rithviknishad** [comment]
1. `gray` shade is the right shade that we use from figma. Let's switch to using that?
2. Ensure font weights are similar to the one in the design.
3. The "Add Facility" button, let's swap that to using `Button` from shadcn UI instead of `ButtonV2`
4. Let's use full width cards in mobile view. Looks weird in mobile as of now.
image

**Comment by AdityaJ2305** [comment]
@rithviknishad 

Screenshot 2024-12-12 at 8 14 22 PM
Screenshot 2024-12-12 at 8 13 51 PM

**Comment by rithviknishad** [comment]
Awesome!

**Review by Jacobjeevan — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
