### PR TITLE
Vitals in Consultation Update for Normal rounds

### LINKED ISSUE #1863: Changes in Log Update : Consultation Page
,s;,df

when we are selecting Round Type as Normal we want to list  :
1.  Hemodynamic Parameter (Vitals)
2.  SPO2

in the same page and, when the round type is Critical Care, then only, we need to be redirected to the whole critical care sections

### LINKED ISSUE #1910: Rearrange Parameters when selecting "Normal_care" In Consultation updates.
rearrange the parameters when selecting Normal_care in Daily rounds (Consultation Updates)
the issue regarding PR #1873 

Also please refer below attached file for more idea, vitals has to be simple and looks the same size as existing parameters in the form. 

[consultation normal concept (1).pdf](https://github.com/coronasafe/care_fe/files/7323808/consultation.normal.concept.1.pdf)

@gigincg @Sandra3657 @nihal467

### PR DESCRIPTION
**Pull request by Sandra3657**
Resolves #1863
Resolves #1910 

In the consultation update, when user selects the normal rounds type,  the following fields can also be filled in the same page

- Hemodynamic Parameter (Vitals)
- SPO2

https://user-images.githubusercontent.com/62461536/135402751-8fe37953-a598-435f-b73e-ad6e5befbe9d.mp4

### CODE REVIEW

**Comment by nihal467** [comment]
@Sandra3657 the page look so bulky, does we have a way to optimize it

**Comment by nihal467** [comment]
@Sandra3657 the sheet is becoming lengthy, can we do something about it ?

**Comment by Sandra3657** [comment]
Will look into it.

**Comment by nihal467** [comment]
@Sandra3657 @gigincg can you make it small, like we can have two each reading in one  row each

**Comment by samholics** [comment]
@Sandra3657 Can you remove the Decimal places from the vitals except "Temperature". Only temperature is measured at decimal places. Also Temperature value has to be 99.5 or 101.7 etc. no need to put two decimal places.

**Comment by gigincg** [comment]
@Sandra3657 Nice work with this one! Looking great. When you're done with it make sure you mark it as "needs testing" so that it gets pushed out quick!

**Comment by samholics** [comment]
tested, failed

1) Still the decimal places present in BP,respiratory,pulse.spo2. theses vitals has to be digits without decimal places.( pls remove the ".00" . 

2) Temperature is the only vital needs decimal place after digits. But it has to be one degree decimal. eg:) 97.5 , 96.5 , remove the zero after the decimal digit.

image

3) when trying to type vitals, its not visible when click submit or any field, But only when selecting values from the dropdown. So enable dropdown only when clicking the "downward arrow" and also avail type and submitting of values in all vitals filed.

@Sandra3657 @nihal467

**Comment by nihal467** [comment]
@Sandra3657 !

**Comment by amruthavijay88** [comment]
@sam9111 - Sandra says that you agreed to pick this up. Could you please share updates on this ?

**Comment by sam9111** [comment]
> @sam9111 - Sandra says that you agreed to pick this up. Could you please share updates on this ?

yes working on it

**Comment by Sandra3657** [comment]
image
 The decimal places are not there except for temperature.
@samholics

**Comment by samholics** [comment]
ok now the decimal place issue is resolved...but
- when we enter the values and click submit, the page directed to the critical care parameters.
image

its needs to go back to the consultation page i think..bcoz when we select "normal" from the rounds there is no need to fill up the critical care parameters. @sam9111 @Sandra3657

**Comment by amruthavijay88** [comment]
@sam9111 - Could you please look into the issue Sam has quoted.

**Comment by sam9111** [comment]
chrome-capture


I have added changes to modify the flow. Do let me know if this is correct.

RoundType="Normal" and copyValues="No" -> Go to Consultation Update View Details page
RoundType="Normal" and copyValues="Yes" -> Go to Basic Editor(Info) page
RoundType="Critical" and copyValues="No" ->  Go to Record Updates page
RoundType="Critical" and copyValues="Yes" -> Go to Basic Editor(Info) page

@samholics

**Comment by samholics** [comment]
when selecting Normal round type and updated vitals, the page needs to go back to consultation page only. 
but if we select critical care the has to go the record updates page or the critical care vitals. @sam9111

**Comment by sam9111** [comment]
> when selecting Normal round type and updated vitals, the page needs to go back to consultation page only. but if we select critical care the has to go the record updates page or the critical care vitals. @sam9111

Whats the critical care vitals page? @samholics

**Comment by nihal467** [comment]
test approved

**Review by gigincg — APPROVED** [review]
Nice Work in this one!

**Pull request merged**
