### PR TITLE
changed dosages to days in Medicines in ConsultationDetails

### LINKED ISSUE #1646: Dosage and Days looks  SAME !!!!!!!!!!
in patient medicine prescription, the dosage and days looks same as dosage!!!!!

it can be shown ok in consultation creation page but when you access from consultation history the dosage and days are same as dosage....

image

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #1646 

The UI:
image

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Review by peeyush14goyal — APPROVED** [review]

**Comment by samholics** [comment]
The issue came back and dosage and days looks same as   #1646

**Comment by nihal467** [comment]
@samholics did you hard refresh your browser, ctrl+f5 and done the testing ?

**Comment by nihal467** [comment]
gsepgojoes
rkd hp drktgp dr

it is working for me

**Pull request merged**
