### PR TITLE
Search box implementation for listing #228

### PR DESCRIPTION
**Pull request by amitbhoj-fc**
Signed-off-by: amit.01@freecharge.com <amit.01@freecharge.com>

### CODE REVIEW

**Comment by dauntlessnomad** [comment]
fix the conflicts @amitbhoj-fc

**Comment by amitbhoj-fc** [comment]
resolved. @tomahawk-pilot

**Comment by dauntlessnomad** [comment]
Make the district search a drop down. instead of a text box

**Comment by amitbhoj-fc** [comment]
sure. I will do it in separate PR.

**Pull request merged**
