### PR TITLE
fixes: #7813. Removed COVID Status and added Last Discharged Reason with better alignment in Patient details page

### LINKED ISSUE #7813: remove COVID Status from Patient details page
Remove COVID status from patient details page (https://care.coronasafe.in/facility/06518832-e181-477d-9c0a-e46b3186edf3/patient/2ce2d39b-3be9-44f7-b1cf-d618d44f53ef)
Screenshot 2024-05-14 at 12 58 32 PM

Instead show "status- discharged" and "Last Discharge Reason- ....." on the left and the right section

### PR DESCRIPTION
**Pull request by Sulochan-khadka**
remove COVID Status from Patient details page #7813

## Proposed Changes

- Fixes #7813 
- Removed Covid Status
- Added Last Discharged Reason

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]
Awesome, LGTM!

**Comment by rithviknishad** [comment]
@Sulochan-khadka It'd be great if you could give a meaningful title to the PR as this would be part of the changelog entry. 

+1 for attaching screenshots of the updated UI too! 😄

**Comment by Sulochan-khadka** [comment]
> @Sulochan-khadka It'd be great if you could give a meaningful title to the PR as this would be part of the changelog entry.
> 
> +1 for attaching screenshots of the updated UI too! 😄

Ohh... this just somehow escaped from my focus... I will surely...

**Comment by Sulochan-khadka** [comment]
@rithviknishad have changed the title to the PR.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
