### PR TITLE
Upgraded to mui v5

### LINKED ISSUE #2380: Replace react-dates with material ui date picker
replace with mui; https://mui.com/x/react-date-pickers/date-range-picker/#main-content

### LINKED ISSUE #2424: Upgrade material-ui to to v5

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #2424
- [x] Fixes #2380
- [x] Upgraded to mui v5
- [x] Updated code to support mui v5

### CODE REVIEW

**Comment by cp-Coder** [comment]
@rithviknishad Has there been any update on netlify issue? I am also facing some issue in this PR.

**Comment by aeswibon** [comment]
@rithviknishad Has there been any update on netlify issue? I am also facing same issue in this PR.

**Comment by rithviknishad** [comment]
@cp-Coder @gigincg tried clearing cache in netlify. Still failing.
I have modified vercel deploy command and redeployed it. Vercel works as of now.

https://vercel.com/coronasafe/care-fe/36hpN1noe1QJK7tQxqZvPszZaRzb

**Comment by aeswibon** [comment]
Resolved merge conflict. This PR is good for testing.

**Comment by aeswibon** [comment]
Resolved all the conflicts. This PR is now good for testing.

**Comment by nihal467** [comment]
@cp-Coder  test failed



- [ ] Cancel creation button color is missing in add patient



- [ ] patient creation form is stretched and so much extra space are been wasted and they are misaligned [ other forms also have this program ]
- [ ] date of birth is unable to type manually in patient creation form



- [ ] date of onset is overlapping with the icon on the consultation page



- [ ] the heading and content are not properly aligned in the investigation page
- [ ] when we are clicking the value box to edit value, a blue box is coming up, in the existing UI, it is a black border itself [ doctor note page box also have the same program ]



- [ ] inventory summary buttons are green, not blue and all the button inside it also have the same program for example min quantity button 



- [ ] the emergency radio button is red in colour not green



- [ ] user page, the cross button colour should be red

**Comment by aeswibon** [comment]
# Updates

- [x] Cancel creation button color is missing in add patient
- [x] patient creation form is stretched and so much extra space are been wasted and they are misaligned [ other forms also have this program ]
- [x] date of birth is unable to type manually in the patient creation form
- [x] date of onset is overlapping with the icon on the consultation page
- [x] the heading and content are not properly aligned on the investigation page 
- [x] when we are clicking the value box to edit the value, a blue box is coming up, in the existing UI, it is a black border itself [ doctor note page box also has the same program ]
- [x] inventory summary buttons are green, not blue and all the buttons inside it also have the same program, for example, the min quantity button
- [x] the emergency radio button is red in color not green
- [x] user page, the cross button color should be red

**Comment by aeswibon** [comment]
@nihal467 I have made all the changes. This PR is good for testing

**Pull request closed without merging**
