### PR TITLE
Use relative time for audit log details.

### LINKED ISSUE #6638: Use relative time / RecordMeta component for audit log details in shift details
**Describe the bug**
Most of the places we use relative time with absolute time in tooltip and user shown through `RecordMeta` component. But that's not the case in audit log details in shift details page.

**Expected behavior**
Use relative time / RecordMeta component for audit log details in shift details

**Screenshots**
image

### PR DESCRIPTION
**Pull request by AshrafMd-1**
### <samp>🤖 Generated by Copilot at f7dfbc3</samp>

Refactored UI code for shift record dates using `RecordMeta` component in `ShiftDetails.tsx`. This improved the code quality and user experience.

## Proposed Changes

- Fixes #6638 
- Convert absolute time to relative time by using RecordMeta component.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at f7dfbc3</samp>

*  Refactor the created and modified date display to use a custom `RecordMeta` component ([link](https://github.com/coronasafe/care_fe/pull/6640/files?diff=unified&w=0#diff-4527d63b6d6de451c456dcdf926baf86485751803245f1096d673b937d7c4862L804-R804), [link](https://github.com/coronasafe/care_fe/pull/6640/files?diff=unified&w=0#diff-4527d63b6d6de451c456dcdf926baf86485751803245f1096d673b937d7c4862L814-R823), [link](https://github.com/coronasafe/care_fe/pull/6640/files?diff=unified&w=0#diff-4527d63b6d6de451c456dcdf926baf86485751803245f1096d673b937d7c4862L828-R838))

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
The created and last edited by object can also be specified to RecordMeta itself

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@AshrafMd-1 
image

- [ ] dont use two different row, make use of only one row similar to the existing UI

**Comment by nihal467** [comment]
@AshrafMd-1 once you complete the UI, we discussed on the EOD call,  mark it for testing

**Comment by AshrafMd-1** [comment]
@rithviknishad can u check once

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
