### PR TITLE
Adds Asset Class field and Improve Asset Type option's descriptions

### LINKED ISSUE #2431: Create a new Field in CreateAsset Form to update the asset_class for the asset

### LINKED ISSUE #2432: Create a Hint next the Asset Type field (Internal/External) that specifies the difference

### PR DESCRIPTION
**Pull request by rithviknishad**
Closes #2431 
Closes #2432 

Re-work of #2552 as I'm unable to develop on that branch as system freezes every time I do `yarn start` on that.

https://user-images.githubusercontent.com/25143503/172146818-6e59fe1e-c12e-47dc-a79b-025aec05598e.mp4

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad @gigincg test failed, the UI doesn't look good

**Comment by rithviknishad** [comment]
@nihal467 I'm using the native rendering which was used originally 🥲 Just used a better description instead of External and Internal.

Could you give me some suggestions to improve?

**Comment by nihal467** [comment]
172045750-1654c71d-96fe-4be1-93cc-2826956df84b

@rithviknishad @gigincg this one looks good, just my opinion @gigincg what do you think

**Comment by rithviknishad** [comment]
@nihal467 will try working on it. 
that one was using non-native rendering and had issues with different browsers when you tested in #2552 so decided to use the original style itself.

**Comment by rithviknishad** [comment]
@nihal467 @gigincg  how about this one?
If mobile, shows the asset type's hint below the selected option.
If not mobile, shows a tooltip on hover.

Couldn't get the above design to work on chrome.

image

**Comment by gigincg** [comment]
@rithviknishad lets do the tailwind dropdown that we discussed. Ping me if you need any help

**Comment by rithviknishad** [comment]
image

**Comment by rithviknishad** [comment]
Select menu implemented as part of #2776

**Comment by rithviknishad** [comment]
https://www.loom.com/share/b977af4cd5bb4f2baaec02146be56ecc

**Comment by nihal467** [comment]
test approved

**Pull request merged**
