### PR TITLE
rearranged buttons in ConsultationDetails

### PR DESCRIPTION
**Pull request by khavinshankar**
before:
image

now:
image

### CODE REVIEW

**Comment by aparnacoronasafe** [comment]
Tested in preview

**Comment by amruthavijay88** [comment]
Tested - buttons seems to have not changed. Screenshot below - 

image

**Comment by khavinshankar** [comment]
@amruthavijay88 can you please check it once again,
link: https://deploy-preview-1365--care-net.netlify.app/facility/fdad4400-bd11-49dd-9da1-5be0e79fa14e/patient/2a741eb3-b0d2-4eac-a70d-7724b65d92ca/consultation/b9249d57-44a8-4b7d-be28-6418bf632a68

**Comment by nihal467** [comment]
test approved

**Pull request merged**
