### PR TITLE
🛠 Upgrade the colors of tailwind input components + 🛠 Tailwind Consultation Form + 🛠 Tailiwnd discharge patient dialog

### LINKED ISSUE #3594: Tailwind Consultation Form
Update Consultation Form (And eventually the other Forms) to Reflect the following

image

### LINKED ISSUE #4271: Text box and borderline are different across the platform
**Describe the bug**

Currently, in multiple text box across the platform, the borderline and box outterline are in different spaces.

- [x] patient discharge notes
- [x] patient consultation page

**To Reproduce**

https://care.coronasafe.in/facility/f77a909d-95d3-4f4f-bb0d-18a715af82e4/patient/84c35aa2-1f32-412a-a461-6b97d1645c22/consultation/dd8ab0e5-156d-49d1-8b71-c3ac88d36d52

https://care.coronasafe.in/facility/f77a909d-95d3-4f4f-bb0d-18a715af82e4/patient/84c35aa2-1f32-412a-a461-6b97d1645c22/consultation/dd8ab0e5-156d-49d1-8b71-c3ac88d36d52/update

**Expected behavior**

the outline border and text-box border should be same.

**Screenshots**

image
image

### LINKED ISSUE #4277: Update the colors used by the new tailwind input components
**Is your feature request related to a problem? Please describe.**

image

**Describe the solution you'd like**
- [x] `TextFormField`
- [x] `TextAreaFormField`
- [x] `SelectMenuV2`
- [x] `MultiSelectMenuV2`
- [x] `AutoCompleteAsync`
- [x] `DateInputV2`
- [x] `PhoneInput`

### LINKED ISSUE #4318: Migrate to TextAreaFormField Part 1 (9 migrations)
- Consultation Form (completed via #4309)

- Consultation Details (completed via #4309 )

- Facility Create (completed via #4315 )

### LINKED ISSUE #4328: Diagnosis Select causes to select/unselect unintended option when dropdown goes out of focus
**Describe the bug**

**To Reproduce**

1. Go to consultation page
2. Click on diagnosis dropdown
3. Click outside diagnosis dropdown

**Expected behavior**
The original selection should be maintained

**Screenshots**

https://user-images.githubusercontent.com/25143503/208229604-27df78c7-401b-4b92-93fd-774951a0c6ba.mp4

### LINKED ISSUE #4336: Create consultation button is misaligned
**Describe the bug**

the icon and the text inside the create consultation button are misaligned 

**To Reproduce**

https://care.coronasafe.in/facility/0fd9dfa1-e4fb-4bbb-936d-c3cb05fa5e33/patient/edfcb863-c12e-4aab-933b-bf60cd490ca7/consultation/20ba1ed8-6c3f-4680-b3af-d23084de3756/update

**Expected behavior**

the icon and text button should be aligned

**Screenshots**

image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- [x] Resolves #3594 
- [x] Resolves #4271 
- [x] Resolves #4277 
- [x] Closes #4318 
- [x] Fixes #4328 
- [x] Fixes #4336 
- Tailwind the Consultation form partially
- Tailwind the Discharge from care dialog box.
- Upgrade colors of:
  - `TextFormField`
  - `TextAreaFormField`
  - `SelectMenuV2`
  - `MultiSelectMenuV2`
  - `AutoCompleteAsync`
  - `DateInputV2`
  - `PhoneInput`
- `TextAreaFormField`'s colours have been upgraded to the latest design.
- Replaced all material UI's `InputLabel` and `MultilineInputField` to tailwind components `FieldLabel` and `TextFormField` in the Consultation form.

# Upgrades the colors of tailwind input components and reverted to original grey shades

image

### So far we had 3 shades of gray, and now 1 remains.

1. Tailwind's gray accessible through `secondary`
  image

2. The CARE gray
  image

3. The CARE gray that got deviated to match Figma (thinking Figma had correct colors) in #3744
  image

### Before
image

### After
image

## `useAsyncOptions` hook helps compose async autocompletes with ease and type-safety :)
image

# New Components 🚀 

## 1. `SymptomsSelect`
(because ASYMPTOMATIC is listed under symptoms)

image

image

### Screenshots

image

image

image

## 2. `PatientCategorySelect`
(_because it has category-specific colors_)

image

image

image

--------------------

## 3. `DiagnosisSelect`
(_because earlier one had issues, and wasn't FormField compliant_)

image

image

image

### 4. `SelectFormField` 

```jsx
{/* A FormField compliant component of SelectMenuV2 */}
<SelectFormField
  required
  label="Decision after consultation"
  {...selectField("suggestion")}
  options={CONSULTATION_SUGGESTION}
/>
```

image

--------------------

### 5. `MultiSelectFormField`

```jsx
{/* A FormField compliant component of MultiSelectMenuV2 */}
<MultiSelectFormField
  required
  label="Decision after consultation"
  {...selectField("suggestion")}
  options={CONSULTATION_SUGGESTION}
/>
```

(_No screenshot for this, as it's not directly used anywhere so far_)

--------------------

## 6. `AutocompleteV2`
(_not used anywhere so far, built it now itself because AutocompleteMultiselect was built parallely_)

--------------------

## 7. `AutocompleteMultiSelectV2`

--------------------

## 8. `AutocompleteMultiSelectFormField`

(_Same usage and as the `DiagnosisSelect` mentioned above_)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Screenshots
image

image

image

image

image

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 
image

- [x] verified by heading is missing on consultation page

image

- [x] upgrade telemedicine dropdown to custom dropdowns

image

- [ ] Diagnosis  and Provisional diagnosis text box area and borderline are different

**Comment by nihal467** [comment]
@rithviknishad what is the status on the PR

**Comment by rithviknishad** [comment]
@nihal467 just letting you know that this alignment will be fixed automatically with https://github.com/coronasafe/care_fe/pull/4358

image

**Comment by nihal467** [comment]
@rithviknishad 
image

when someone selecting any symptoms, all the times, if we are seeing this alert statement, feel like it will confuse a normal user a bit, can you take this up in the EOD, and the opinion

**Comment by nihal467** [comment]
@rithviknishad 
image

make the border green

**Comment by nihal467** [comment]
@rithviknishad 

https://app.flonnect.com/view/video/nihalcct/63a2bd33f31aaa756efa33bb

in the diagnosis, if I select anything starting with 1A, the multi-select are working properly, but when I select something of 3A, then the already selected 1A starting diagnosis are getting unselected

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
