### PR TITLE
Migrate `useDispatch` with `useQuery/request` in `src/Components/Common/**`

### LINKED ISSUE #6888: 🛠️ Replace `useDispatch` w. `useQuery`/`request`: Common (`src/Components/Common/**`)

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Fixes #6888 

### Affects
- Fetching options in Asset Select Dropdown
- Fetching options in Bed Select Dropdown
- Fetching options in State, District, LocalBody Autocomplete Dropdown
- Fetching options in Facility Locations Autocomplete Dropdown
- Fetching options in Skill Select Dropdown
- Fetching options in Investigation Builder of Consultation Form
- Fetching uptime status records in Asset Availability
- Fetching options in Facility Select dropdown

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad fix the cypress test

**Comment by rithviknishad** [comment]
@nihal467 patient crud is failing for an unrelated reason and a parallel PR seems to be fixing it as discussed https://rebuildearth.slack.com/archives/C010GQC5UE9/p1704126513851419

The originally failing asset manage and asset create tests has been addressed.

**Comment by nihal467** [comment]
@rithviknishad 
image

https://deploy-preview-6889--care-net.netlify.app/facility/fe1b9b4b-def3-488a-808a-a5776222f65b/assets/48e768c6-237a-4235-97e6-4ab63a8f04ad

- [ ] asset uptime operational details are malfunctioning

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
