### PR TITLE
Other browser

### PR DESCRIPTION
**Pull request by Yash12Bansal**
I had made the changes but forgot to make a pr as I was working on other issues. So, sorry for that delay
I have made all the changes and it now supports all major browsers. I have also untracked package-lock.json files 
So please review and accept the pr

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
In the previous PR also I've requested the changes saying that, do this for all browsers regardless of Firefox or not right?

**Comment by rithviknishad** [comment]
Kindly link the issue in the PR with closing tags

**Comment by rithviknishad** [comment]
Also update the PR title to something meaningful. "Other browser" doesn't make any sense

**Comment by gigincg** [comment]
@Yash12Bansal Please update with a relavant PR Description

**Comment by khavinshankar** [comment]
@rithviknishad is this relevant?

**Comment by rithviknishad** [comment]
The issue related to this is #5611 however I'm unable to reproduce in firefox nor chrome. Closing.

**Pull request closed without merging**
