### PR TITLE
Add medico-legal case toggle and filter

### LINKED ISSUE #6367: Medico-Legal Case
**Is your feature request related to a problem? Please describe.**
We need to mark an encounter as a "Medico-Legal Case"

**Describe the solution you'd like**

- [ ] Mark an encounter as a "Medico-Legal Case" 
Any encounter (active or closed)  will be marked as a "Medico-Legal Case" 

Have a toggle added at the Patient dashboard (https://care.coronasafe.in/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/adefe869-7b9a-44ab-bffe-8fb115d8265a/consultation/17ca4172-4b08-404b-934f-b3ad77ae2a6f)  "Is this a medico-legal case?" Yes/No- The default option will be "No"

- [ ] Have filter in patient list to filter patients whose latest encounter is marked as a medico-legal case. The advanced filter to have a new filter added at the end of "Patient details based". 

- [x] #6439

- [ ] Metabase dashboard to have "No. of medico-legal cases" across each hospital.

### PR DESCRIPTION
**Pull request by Ashesh3**
Backend PR: https://github.com/coronasafe/care/pull/1669

### <samp>🤖 Generated by Copilot at 38c0d4d</samp>

This pull request adds a new feature to filter and update patients by their medico-legal status, which is a boolean flag indicating whether their last consultation was a legal case or not. It also improves the SwitchTabs component by renaming its props and using a boolean value for the active tab. The changes affect the PatientManager, PatientFilter, PatientInfoCard, ResourceBoardView, and BoardView components, as well as the ConsultationModel interface and the partial update consultation API route.

## Proposed Changes

- Fixes #6367 
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### <samp>🤖 Generated by Copilot at 38c0d4d</samp>

*  Rename props of SwitchTabs component to use camelCase and boolean values ([link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-496c84feeecc2c8878e77fdf0fbb641b0e484f9dd292ce0dbe20222f6b5d46b4L2-R6), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-496c84feeecc2c8878e77fdf0fbb641b0e484f9dd292ce0dbe20222f6b5d46b4L12-R17), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-496c84feeecc2c8878e77fdf0fbb641b0e484f9dd292ce0dbe20222f6b5d46b4L23-R27), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-496c84feeecc2c8878e77fdf0fbb641b0e484f9dd292ce0dbe20222f6b5d46b4L33-R33), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-6a60fce2df893cf91c0457f6445b903c1d6667b6a86fc21c38a9e8fc385c7575L771-R778), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-72363d4a4cc81142bd2db278c3c1e17ee14614fc4be0af317cc60db25f4be79cL62-R66), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-fc18d7013fcb5787812d6865749dd91966308ccf3493ab227001b2ca0079f600L88-R92))
*  Add medico_legal_case property to ConsultationModel interface to store the medico-legal status of the consultation ([link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfR146), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cL3-R6))
*  Add last_consultation_medico_legal_case property to PatientManager component to filter patients by medico-legal status ([link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-6a60fce2df893cf91c0457f6445b903c1d6667b6a86fc21c38a9e8fc385c7575R188-R189), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-6a60fce2df893cf91c0457f6445b903c1d6667b6a86fc21c38a9e8fc385c7575R338), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-6a60fce2df893cf91c0457f6445b903c1d6667b6a86fc21c38a9e8fc385c7575R938-R941))
*  Add last_consultation_medico_legal_case property to PatientFilter component to store and pass the filter value ([link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-c2cb85d3cdc89692ee11a2f37a159ecb45eec9e1148bb2e9a779d2bcf7cd7c8aR68-R69), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-c2cb85d3cdc89692ee11a2f37a159ecb45eec9e1148bb2e9a779d2bcf7cd7c8aR125), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-c2cb85d3cdc89692ee11a2f37a159ecb45eec9e1148bb2e9a779d2bcf7cd7c8aR235), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-c2cb85d3cdc89692ee11a2f37a159ecb45eec9e1148bb2e9a779d2bcf7cd7c8aR273-R274))
*  Add SelectMenuV2 component for Is Medico-Legal Case filter to PatientFilter component to allow user to choose filter option ([link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-c2cb85d3cdc89692ee11a2f37a159ecb45eec9e1148bb2e9a779d2bcf7cd7c8aR482-R498))
*  Add SwitchTabs component for Is Medico-Legal Case toggle to PatientInfoCard component to allow user to change medico-legal status of consultation ([link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-474c76838170cd340f215b026249385e32a2d8263bd30a568c2b02b38d272948R25-R27), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-474c76838170cd340f215b026249385e32a2d8263bd30a568c2b02b38d272948R48-R51), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-474c76838170cd340f215b026249385e32a2d8263bd30a568c2b02b38d272948R64-R82), [link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-474c76838170cd340f215b026249385e32a2d8263bd30a568c2b02b38d272948R462-R475))
*  Add switchMedicoLegalCase function to PatientInfoCard component to make API call to update medico-legal status of consultation and handle responses ([link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-474c76838170cd340f215b026249385e32a2d8263bd30a568c2b02b38d272948R64-R82))
*  Add TRes and TBody types to partial update consultation API route in `routes` module to specify expected response and request body types ([link](https://github.com/coronasafe/care_fe/pull/6440/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cR364-R365))

### CODE REVIEW

**Comment by nihal467** [comment]
UI Approved by @aparnacoronasafe

**Comment by nihal467** [comment]
LGTM the functionality have few thoughts in the UI

**Comment by nihal467** [comment]
@Ashesh3 are the UI changes implemented

**Comment by Ashesh3** [comment]
> @Ashesh3 are the UI changes implemented

Yes, Implemented.

**Comment by nihal467** [comment]
@Ashesh3 
image

- [ ] link abha number UI is fully black, keep it consistent like other icons
- [ ] resolve the merge conflict
- [ ] get the UI opinion from @gigincg

**Comment by Ashesh3** [comment]
> @Ashesh3 image
> 
> * [ ]  link abha number UI is fully black, keep it consistent like other icons
> * [ ]  resolve the merge conflict
> * [ ]  get the UI opinion from @gigincg

Resolved and design approved.
image

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
