### PR TITLE
Increased the respiratory rate

### LINKED ISSUE #7121: To increase the respiratory rate in log update page
**Is your feature request related to a problem? Please describe.**
Not able to enter correct respiratory rate during log update as the existing value is not high enough. Patients with heart condition , especially Paediatric patients, experiences respiratory rate higher than 70.

**Describe the solution you'd like**
It seems necessary to increase the respiratory rate in log update.

### PR DESCRIPTION
**Pull request by konavivekramakrishna**
## Proposed Changes

- Fixes #7121 
-To increase the respiratory rate in log update page upto 150
https://www.loom.com/share/c9be1af59c8b414280b197beebe94df6?sid=fff8c854-30b7-48ae-bfe9-eade33d86d48
image

backend pr: https://github.com/coronasafe/care/pull/1878

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Comment by nihal467** [comment]
@konavivekramakrishna 

image

change the RR rate in the vitals section of critical care log update because currently the slide still considers 70 as the maximum limit

Note: Don't change it in the Respiratory Support Section

CC: @rithviknishad @Ashesh3

**Comment by vivramkrishna** [comment]
image

**Comment by konavivekramakrishna** [comment]
image


@nihal467 

should I update the readme in this pr
image

**Comment by vivramkrishna** [comment]
@Ashesh3 @rithviknishad 

could you please review it

**Review by rithviknishad — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
