### PR TITLE
add: disable none volunteers assigning

### LINKED ISSUE #2695: Bug in assiging to a volunter
URL: http://localhost:4000/facility/7a560e62-6aae-4293-8f1a-0ba840e3449f/patient/192fdee9-397f-49bd-833a-10f700416da8

I am able to click the assign to volunteer option even tho no volunteer are selected
image

Solution could be to add a alert like "Select the volunteer" and disable submit

### PR DESCRIPTION
**Pull request by kunatastic**
closes #2695 and #2771

Updation 
image

### CODE REVIEW

**Review by patelaryan7751 — APPROVED** [review]
LGTM

**Comment by kunatastic** [comment]
Also #2771 has been resolved in same PR

**Review by cp-Coder — APPROVED** [review]

**Comment by nihal467** [comment]
@kunatastic test failed,

if i assign a volunteer to a patient once, and it unable to unassign the patient from volunteer by clicking clear and submit button is not possible.

**Comment by nihal467** [comment]
@kunatastic what is the PR status

**Comment by mathew-alex** [comment]
:wave: Hi, @kunatastic,
Conflicts have been detected against the base branch. Please rebase your branch against the base branch.

***

This message is automatically generated by [prince-chrismc/label-merge-conflicts-action](https://github.com/prince-chrismc/label-merge-conflicts-action) so don't hesitate to report issues/improvements there.

**Pull request closed without merging**
