### PR TITLE
Solved the responsiveness issue of Administer medicine Slide-Over

### LINKED ISSUE #6768: Prescriptions Details Card is not responsive in Bulk Administer Medicines slideover
**Describe the bug**
Prescriptions Details Card is not responsive in Bulk Administer Medicines slideover

**To Reproduce**

1. Go to medicines section of a consultation
2. Add a prescription if none is present.
3. Open Bulk Administration view

**Expected behavior**
The Prescription Details Card should be responsive.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by sagarkori143**
### WHAT
Solved the responsiveness issue of Administer medicine Slide-Over

## Proposed Changes

- Fixes #6768 
- Changed the styling of bulk administer slide-over
From:

WhatsApp Image 2023-12-03 at 16 34 28_40ae166a

To :

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at dd24fca</samp>

*  Adjust the width of the medicine administration component based on the screen size ([link](https://github.com/coronasafe/care_fe/pull/6854/files?diff=unified&w=0#diff-20fe2da85cb48e713c7f8cdbec4385740a4c0fbe37a1a915389bccee6b7e8453L90-R90))

### CODE REVIEW

**Comment by sagarkori143** [comment]
@rithviknishad Please review.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@sagarkori143 

image

the route field is not properly responsive

**Comment by sagarkori143** [comment]
@nihal467 What I'm supposed to do now? Should I decrease the width of administration section to some more extent as the prescription card can't be altered being a reusable component? Please give some clarification about it.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Increase the width of the slideover a bit more, that should solve it right?

Instead of 1300px, we can go 1400px maybe?

**Comment by sagarkori143** [comment]
@rithviknishad Sure, Thanks!

**Comment by sagarkori143** [comment]
@rithviknishad 
If I'm operating a device having this much width:

image

You can see that the slide-over is covering whole screen. If I increase the width of slide-over then the user have to slide left and right to see the slide-over content completely. Is it ok doing so?

**Comment by rithviknishad** [comment]
Select for administration section can come below the prescriptions detail card whenever there is not enough screen space.

**Comment by sagarkori143** [comment]
@nihal467 Is it OK if I do overflow hidden for these boxes content as I have seen the same thing on some other pages too.

image

**Comment by sagarkori143** [comment]
@nihal467 A friendly reminder. Please let me know if I can move ahead with this solution and commit the changes.

**Comment by rithviknishad** [comment]
I don't think it's okay to hide information (especially in a reusable component where that is the only component that shows the detailed view of the prescription).

Was there any issues in achieving the following?

> Select for administration section can come below the prescriptions detail card whenever there is not enough screen space.

**Comment by sagarkori143** [comment]
Hey @rithviknishad  please reopen this issue. I was in bad health conditions so couldn't give it time again. I am looking forward to work on this and raise a pr again

**Pull request closed without merging**
