### PR TITLE
Added sidebar indicator

### PR DESCRIPTION
**Pull request by skks1212**
Added a sidebar indicator that animates on page change. Made buttons rounded and decreased horizontal padding.

image

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@skks1212 two issues:

1. when no sidebar item is selected, it is showing the indicator near the care logo, can u hide it instead?
image

2. The mobile sidebar is affected badly.
image

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@skks1212 i can see many pushes after its been marked for testing, is it good for testing now

**Comment by shivankacker** [comment]
> @skks1212 i can see many pushes after its been marked for testing, is it good for testing now

Yes it is 👍

**Comment by nihal467** [comment]
PR LGTM, Marking it as team discussion required for final UI approval

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
