### PR TITLE
Migrate to Headless UI v2

### PR DESCRIPTION
**Pull request by khavinshankar**
## Proposed Changes

- Migrated to Headless UI v2 (ref: https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Freact%40v2.0.0#user-content-upgrading-from-v1)
- Removed postcss loader package (no longer needed, it was meant for webpack)

@nihal467 no visible ui changes but all the components should be rendered as before

https://github.com/coronasafe/care_fe/issues/7849#event-13849249207

Mentioning the issue here as a reminder: we can work on issue 7849 only after merging this V2 PR

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar the dropdown behavior has some anima effect and is closing slowly, try to checking for each elements presence post selection from dropdown, might solve the issue, post fixing the cypress, mark it for testing

**Comment by nihal467** [comment]
https://github.com/coronasafe/care_fe/issues/7849#event-13849249207

Mentioning the issue here as a reminder: we can work on issue 7849 only after merging this V2 PR.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

@khavinshankar when we multi-select from dropdown in advance filters and, then click apply, it just closes the dropdown, but that shouldn't be the behavior , it should allow users to use apply button directly

**Comment by nihal467** [comment]
conditional approving it, will be opening a new issue to fix the multi-select component mentioned in the previous comment

**Pull request merged**
