### PR TITLE
Add bed occupancy to facility card

### LINKED ISSUE #4885: Facility List: Adding bed occupancy
**Is your feature request related to a problem? Please describe.**
CARE has a list of facilities at https://care.coronasafe.in/facility 
The cards for each facility show some basic static details about the facility.

For hospitals, an important piece of information is about the No. of beds, it has, and the occupancy. This information is, not easily available to the user.

**Describe the solution you'd like**

- [ ] add space for three icons on the right side of the facility card (we will only be adding one icon now, two more icons to be added subsequently.)
Screenshot 2023-02-25 at 12 30 36 PM

- [ ] Wherever the facility has registered beds (in bed management module within Location management module- https://care.coronasafe.in/facility/36f4f9e7-9e37-441f-904c-89562f24163f/location), an appropriate icon for occupied bed should appear as icon on top right corner of the facility card with **No. of live patients/ Total No. of beds** No. below it. 

**NOTE:** The No. of live patients must be fetched from the Live Patient List at https://care.coronasafe.in/patients?facility=36f4f9e7-9e37-441f-904c-89562f24163f, and bed no should be sum of beds registered under all locations at https://care.coronasafe.in/facility/36f4f9e7-9e37-441f-904c-89562f24163f/location

- [ ] The icon must be in green, and when occupancy goes above 85%, color of icon turns red.

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #4885 
Backend PR: https://github.com/coronasafe/care/pull/1223

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM, marking it as discussion for final UI approval

**Comment by nihal467** [comment]
@Ashesh3 work on the changes mentioned in the EOD

**Comment by Ashesh3** [comment]
Updated Design:
image
image
image

**Comment by nihal467** [comment]
@Ashesh3 marking it work in progress since the discussion is going on in slack

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
