### PR TITLE
fix: reorder and group the patient filters

### LINKED ISSUE #4888: Advanced Filter: patient list- group and reorder
**Is your feature request related to a problem? Please describe.**
The advanced filter in the patient list (https://care.coronasafe.in/patients) now has many fields making it confusing and hard to browse through. 

- Reorder the existing filters 
- Group the existing filters and give headers

**Describe the solution you'd like**
reorder the filters and add a header to various sections in the manner below:

Patient Details based:
- Gender
- Category
- Age
- Admitted to (bed type)
- Telemedicine
- Is antenatal?

Date-based:
- Registration date (created date)
- Modified Date
- Admitted date
- Discharge date
- Dt. of onset of symptoms

Geography based:
- Facility
- Facility type
- LSG Body
- District

COVID Details based:
- COVID Disease status
- COVID vaccinated
- declared as COVID positive
- SRF ID
- COWIN ID
- Date of result of COVID test
- Date declared COVID positive
- Date of COVID vaccination

**NOTE**: Some fields are renamed in #4887 . please refer to that if the fields here are not matching exactly with the ones in CARE

### PR DESCRIPTION
**Pull request by cp-Coder**
# Bug Fix

## Proposed Changes

- Reordered and categorized the patient filters
- Added header to each section

## Associated Issue

- Fixes #4888

## Screenshot

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug/test a new feature.
- [x] Update product [documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [ ] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder 
image

- [x] the UI doesn't look good in my view, so marking it for discussion in EOD
- [x] when a filter is applied, to see the applied filter in the advance filter, a user has to expand all the header, which seem be not good

**Comment by aeswibon** [comment]
After discussing in the EOD:
- [x] Make all the sections expandable by default
- [x] Change the UI of the Accordion

**Comment by nihal467** [comment]
@cp-Coder 
image
image
- [x] the droplist is not visible in the advanced filters, it is happening with most of the fields

image
- [x] the sides of the droplist are getting cut out

**note: Make sure you run a QA, before marking it for "Need testing"**

**Comment by nihal467** [comment]
@cp-Coder 
image

- [x] when we minimize one header, the fields overlap the other header.
- [x] As mentioned in my previous comment, Add a QA video along with this PR, checking all the whole functions related to this PR.

**Comment by aeswibon** [comment]
@nihal467 the QA video:

https://user-images.githubusercontent.com/77210185/229527031-b1e2c45b-19fd-48f3-b25a-91cf5fa5a199.mp4

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
