### PR TITLE
Make Patient summary plots responsive

### LINKED ISSUE #3642: Data in graphs in summary page is being hidden in mobile devices
**Describe the bug**
Data in graphs in summary page is being hidden in mobile devices

**To Reproduce**

1. Go to any Patient
2. Click on Summary
3. Scroll down below

**Expected behavior**
The data should be visible

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #3642

## Now
image

## Before
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by patelaryan7751 — COMMENTED** [review]
Hey @Ashesh3 Everything seems fine.
A bit enhancement if possible the september is being hidden a bit. Rest all is Good.
image

**Comment by nihal467** [comment]
@Ashesh3 once the work is completed , change it to need testing

**Comment by Ashesh3** [comment]
Fixed.
image
image
image

**Comment by nihal467** [comment]
@Ashesh3 
image

the graph icons are overlapping

**Comment by Ashesh3** [comment]
@nihal467 Should be fixed now.

image

**Comment by nihal467** [comment]
@Ashesh3 
image

https://deploy-preview-3699--care-net.netlify.app/facility/ee6d73a9-ac6e-4b80-a370-abce9e41d159/patient/25ea51b1-fedc-432a-a9df-9071a07862c6/consultation/1999ef08-edcd-455d-91a9-68c401209c3e/summary

the graph is breaking in normal view

**Comment by Ashesh3** [comment]
> @Ashesh3 image
> 
> https://deploy-preview-3699--care-net.netlify.app/facility/ee6d73a9-ac6e-4b80-a370-abce9e41d159/patient/25ea51b1-fedc-432a-a9df-9071a07862c6/consultation/1999ef08-edcd-455d-91a9-68c401209c3e/summary
> 
> the graph is breaking in normal view

It works fine here, I think the page is cached for you? Could you check again?
gif_graph

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
