### PR TITLE
Generalize Filters Slideover

### LINKED ISSUE #3995: Redesign and generalization for SlideOver components.
image

### LINKED ISSUE #4479: Localizations for texts in `Facility/FacilityFilter`

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Resolves #3995 
- Resolves #4479 

### Just to make it simple to review:
- Added a component: `FiltersSlideover` that wraps `Slideover` with Advanced filter specific common things.
- Upgrades all Advanced Filters to use the new `FiltersSlideover`.

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by shivankacker** [comment]
@rithviknishad some filters have base dropdowns and inputs rather than CAREUI. Is that out of the scope of this PR?

**Comment by rithviknishad** [comment]
@skks1212 yes, let's do it as separate PR. Didn't want to make it difficult to test and review. I've only migrated the labels momentarily to keep the gaps between each field consistent.

#5006 tracks all migrations necessary for this

**Review by skks1212 — APPROVED** [review]
Looks good to me

**Comment by nihal467** [comment]
@rithviknishad 
image

- [ ] the slide over is not responsive

**Comment by nihal467** [comment]
@rithviknishad 
image

- [ ] when I clear the advanced filters, which are been applied, the button always remains dark green

image

- [ ] even after I clear the applied advanced filters, the pre-selected options remain in the filters

**Comment by nihal467** [comment]
@rithviknishad 
image

LGTM, but in the asset page, the applied filter of the location, is not showing, the slide-over, can you check it ASAP

**Comment by nihal467** [comment]
LGTM

**Comment by khavinshankar** [comment]
@rithviknishad can you clear out merge conflicts

**Comment by rithviknishad** [comment]
@khavinshankar done

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
