### PR TITLE
Add Patient Page Translations

### PR DESCRIPTION
**Pull request by shrihari689**
## Proposed Changes 🎯

- Add Patient Translation
- Populate JSONs to other language from EN

Wiki: https://github.com/coronasafe/care_fe/wiki 📍

Update: Updated in Google Sheets 😁

### CODE REVIEW

**Comment by bodhish** [comment]
conflicts @shrihari689

**Comment by shrihari689** [comment]
Done @bodhish  ! 🚀

**Comment by samholics** [comment]
tested 
but some titiles only traslated in the patient card. (selected Tamil)

https://deploy-preview-1383--dreamy-fermat-b5024e.netlify.app/facility/01810c32-ec26-494a-9e65-40e5547a7746/patient/7e97fc39-e829-4cf2-ad65-de4489b0c5d9

**Comment by nihal467** [comment]
@gigincg the translation is already in the platform, and particular PR seems old, what to do!

**Comment by gigincg** [comment]
Alternate implementation of Translations already built

**Pull request closed without merging**
