### PR TITLE
Added new waveforms

### PR DESCRIPTION
**Pull request by skks1212**
image
Added 2 new waveforms

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 

- [ ] what is the issue, i can't find anything linked to it, 
- [ ] cypress is also failing

**Comment by shivankacker** [comment]
@nihal467 I have added more information to the PR

**Comment by nihal467** [comment]
@skks1212 
image

- [ ] unable to see the data, when we are hovering over it ( Pulse Rate )
- [ ] Does Pulse rate and pleth are the same?
- [ ] Does SPO2 and II are the same?

image

- [ ] why are waveform breaking, when we are initially opening it up

**Comment by nihal467** [comment]
@skks1212 reply to my comment and check the cypress too !

**Comment by shivankacker** [comment]
@nihal467 this PR will still need more changes. Sorry to bother you 😅. Will remove work in progress once issues have been resolved!

**Comment by shivankacker** [comment]
@nihal467 Please test now. Cypress tests are breaking because of network timeouts (backend is rate limiting requests most probably)

**Review by rabilrbl — APPROVED** [review]

**Pull request merged**
