### PR TITLE
Removed action buttons and indicated for discharged patients

### PR DESCRIPTION
**Pull request by skks1212**
Closes [https://github.com/coronasafe/care_fe/issues/2330](https://github.com/coronasafe/care_fe/issues/2330)

image

### CODE REVIEW

**Comment by gigincg** [comment]
@skks1212 Can you make it "CARE" instead of "care"

Also, can you make an issue to better handle the size of the buttons on the right when all buttons aren't being shown

**Comment by shivankacker** [comment]
> @skks1212 Can you make it "CARE" instead of "care"
> 
> Also, can you make an issue to better handle the size of the buttons on the right when all buttons aren't being shown

Sure! Do I make a new PR for the buttons or do I amalgamate that in this one?

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Comment by gigincg** [comment]
@skks1212 Do make a separate issue for handling the buttons properly if you haven't done that yet

**Comment by shivankacker** [comment]
> @skks1212 Do make a separate issue for handling the buttons properly if you haven't done that yet

Yes doing it!

**Pull request merged**
