### PR TITLE
Make the switch bed card styling consistent.

### LINKED ISSUE #7719: Make the switch bed card consistent
**Describe the bug**

" the no-bed alloted yet " card is not having consistent design with other existing similar card

**To Reproduce**

1. Go to patient consultation page and click switch bed
2. See error

**Expected behavior**

Make it consistent similar to the existing design , add a white card, with related text

image

**Screenshots**

image

### PR DESCRIPTION
**Pull request by AshrafMd-1**
## Proposed Changes

- Fixes #7719

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by AshrafMd-1** [comment]
@nihal467 is this design okay ?

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@AshrafMd-1 add a white padding as mention in the issue 

image

**Comment by AshrafMd-1** [comment]
@nihal467 can you check once 

Here is the image
image


cc: @rithviknishad

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
