### PR TITLE
scroll to mandatory empty fields

### LINKED ISSUE #8222: Implement Auto-scroll for missing mandatory fields in log update form
**Describe the bug**

When I click save button in the log update and if there are any mandatory fields left blank, the platform is not auto-scrolling to the fields so that user can locate the error easily

**To Reproduce**

1. Go to log update and click save button without selecting any patient category
2. See error

**Expected behavior**

the form should auto-scroll to the error field in the log update form up-on trying to save the form

**Screenshots**

image

### PR DESCRIPTION
**Pull request by kushalbhana**
## Proposed Changes

- Fixes #8222
- Scroll to mandatory empty fields while validating the form.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by samholics** [comment]
Test Failed
not auto-scrolling to missed mandatory field

**Comment by nihal467** [comment]
@kushalbhana the issue still exist, can you fix it

**Comment by kushalbhana** [comment]
Fixed the issue now Please check it once

**Comment by samholics** [comment]
Tested Working @nihal467

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
