### PR TITLE
Add OP number to treatment summary.

### LINKED ISSUE #6885: Add IP Number in Treatment Summary
In the Treatment Summary Page, show the IP or OP Number of the Consultation

### PR DESCRIPTION
**Pull request by AshrafMd-1**
## Proposed Changes

- Fixes #6885 
- Add field OP

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@AshrafMd-1 

image

- above is the staging print preview of the current staging

image

- above is the current PR deployment print preview

make the below changes in the PR:

- [ ] make the print preview proper width proportion, in your deploy preview, the left side and right side width usage in print preview is not uniform
image

- [ ] add the IP no column next to the age

**Comment by nihal467** [comment]
@AshrafMd-1 can you push the fix before Tomorrow EOD, we need to close it this week

**Comment by AshrafMd-1** [comment]
Done

**Comment by AshrafMd-1** [comment]
@nihal467 once can u check.

**Comment by AshrafMd-1** [comment]
@rithviknishad can u change the label

**Comment by nihal467** [comment]
@AshrafMd-1 
image

the bug still exist, the borders are not uniform, keep it as it is in current staging

**Comment by AshrafMd-1** [comment]
@nihal467 I tried multiple ways and this is the only way it worked by adding an extra column 
image
Already pushed the update 
can u check if its okay .

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
