### PR TITLE
Patient Consultation: Route to Facility 🏥, Admission Date & Time 🕚

### LINKED ISSUE #6280: Consultation Form: Refactoring "Status during consultation"
- [x] https://github.com/coronasafe/care/issues/1662
- [x] https://github.com/coronasafe/care/issues/1671

### PR DESCRIPTION
**Pull request by rithviknishad**
### <samp>🤖 Generated by Copilot at 8be51d1</samp>

This pull request updates the UI and logic for the consultation form and details page, as well as the treatment summary and patient info card components. It adds new fields and options for the route to facility, ICU admission date, referral and transfer history, and treating physician. It also improves the date and time formatting and removes unused constants.

### Required Backend PRs
- https://github.com/coronasafe/care/pull/1678

## Proposed Changes

- Fixes #6280 
- Fixes https://github.com/coronasafe/care/issues/1618

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 8be51d1</samp>

*  Replace the consultation status field with the route to facility field in the consultation form and details page ([link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-7fa643001511b285907c43213d442bb8b709ab276d7b050d4355e5f95cb38418L3-R3), [link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-9cc33bf4b562de366bf592787b6034eaab934ecf138ee398272d6fb9e820bc04R1-R31), [link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-8a3d15fd6d3361688d96f67af80b867cc60bfbd6bc7642555fd6b5fd04d63901L433-R433), [link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfR6), [link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfL105-R118))
*  Replace the verified by field with the treating physician field in the consultation form and details page ([link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-7fa643001511b285907c43213d442bb8b709ab276d7b050d4355e5f95cb38418L64-R64), [link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-8a3d15fd6d3361688d96f67af80b867cc60bfbd6bc7642555fd6b5fd04d63901L439-R440), [link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfL118-R127))
*  Add new fields and options for referral and transfer in the consultation form and details page ([link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfL105-R118), [link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfR87))
*  Show the admission date with time instead of just date in the treatment summary page and the patient info card ([link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-ac9463aa3ab35a08c12bb0f4159e678378fd1bc43d37e9ce6a475437dbf63cebL142-R142), [link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-474c76838170cd340f215b026249385e32a2d8263bd30a568c2b02b38d272948L242-R242), [link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-5903b23c9778624d9c178b9779024a4265e5fc365714fed34d49225ee6b8dc73L81-R95))
*  Remove the unused `CONSULTATION_STATUS` constant from the `constants.tsx` file ([link](https://github.com/coronasafe/care_fe/pull/6458/files?diff=unified&w=0#diff-37705b30476b14631124ce42dd5c3500d43fbede16f0e91f9ae2905e4adc6376L335-L342))

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 
image

- keep the Name of the referring Facility and the Name of the referring Doctor in two rows

image

- [ ] when the admission date to facility is 16/08/2023, the dates for the ICU limited to 16/08/2023, even though today's date is 18/10/2023, is it a intentional behaviour

**Comment by rithviknishad** [comment]
@nihal467 nope, that's not an intentional behaviour as per discussions made. My bad, I had accidentally forgot to remove the range constraints.

**Comment by rithviknishad** [comment]
@nihal467 ready for testing

**Comment by nihal467** [comment]
@rithviknishad functionality looks good to me, but the cypress and backend test are failing, update it

**Comment by rithviknishad** [comment]
@nihal467 backend tests fixed, cypress will require the backend to be merged to pass.

**Comment by rithviknishad** [comment]
cypress passing locally with backend

image

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
