### PR TITLE
Assign volunteer to a patient 2

### LINKED ISSUE #1148: assigning volunteer to patient
Any volunteer in the facility may be assigned to a patient. 

This can be done by any staff or the district administrator. Have the option on the patient dashboard.

once a volunteer is assigned to a patient, he should be able to assign a doctor to the patient or edit the patient details.

The volunteer must also be able to filter out only the patients assigned to him in the patient list

### PR DESCRIPTION
**Pull request by shaileshaanand**
closes #1148 

Now a user can assign a volunteer to a patient. The option is present on dashboard.
For searching volunteer I have used `OnlineDoctorSelect` component and changed it accordingly.

https://www.loom.com/share/43cca23cdf424859be62ac59a8852a86

### CODE REVIEW

**Comment by bodhish** [comment]
Please fix the merge conflicts

**Comment by shaileshaanand** [comment]
> Please fix the merge conflicts

Merged branch develop into this branch @bodhish

**Comment by nihal467** [comment]
eokwpofkwef

test failed, the clear button is not working. 

We are not able to clear and keep the field empty if we have already assigned a volunteer to a patient

**Comment by divyagar** [comment]
@nihal467 I have made changes

**Comment by samholics** [comment]
tested, failed

now can clear assigned volunteer, but shows the message as  "volunteer assigned succesfully"
also the selected mark remains on the previous selected volunteer

https://user-images.githubusercontent.com/75214902/122679621-36270e80-d209-11eb-856c-0d73e94a6b48.mp4

**Comment by samholics** [comment]
tested, verified
 now can assign a volunteer for a patient and clear the volunteer succesfully

**Pull request merged**
