### PR TITLE
📖 Storybook + 🛠 Tailwind Patient Filters

### LINKED ISSUE #2880: Revamp Advanced Filters in Patients
https://www.loom.com/share/66e8b7570b9c4fb6862d32ea4efccd1f

the advance filters are looking so messy and lengthy,

### LINKED ISSUE #3686: Improve `SelectMenu` tailwind component.
- [x] Support option specific icons.
- [x] Update the interface to be consistent with other tailwind components.

Follow-up of:
- #3121

### LINKED ISSUE #3743: Storybook integration to document, visualize and test individual components.
Integrate [Storybook.js](https://storybook.js.org/)

### LINKED ISSUE #3784: Unable to select a year with `DateInputV2` tailwind component
- Follow up of #3744

**Describe the bug**
Suppose I need to enter the date of birth of a 70-year-old person, then it's practically difficult to press the left arrow 70 times to reach the expected year.

**Expected behavior**
The year button should be clickable and grid of years shall be shown

**Screenshots**
image

### PR DESCRIPTION
**Pull request by rithviknishad**
- Part of the epic https://github.com/coronasafe/care_fe/issues/3742
- _Storybook preview deployment for this branch until its merged can be viewed at: https://care-fe-storybook.vercel.app_

⚠️ _There are additional packages in this PR, for the storybook._
Working on this PR may require you to run `npm i --legacy-peer-deps` or `yarn install` again.

## Post Merge Tasks
- [ ] Update vercel deploy config to use `develop` branch instead of this PR branch.
- [ ] Update README.md with the storybook staging deploy URL.

## Proposed Changes
- [x] Deploy to vercel. (will change to deploy for develop branch once merged)
- [x] Closes #3743
- [x] Closes #2880  
- [x] Resolves #3686 
- [x] Add existing tailwind components to storybook.
- [x] Make Apply/Cancel/Clear filter buttons persistent in advanced filters when scrolling.
- [x] Closes #3784

## Storybook

Write stories of components inside `src/stories` directory, ending with `*.stories.tsx` or `*.stories.mdx`.

Example:
```tsx
// Button.stories.tsx

import { ComponentStory } from "@storybook/react";
import ButtonV2 from "../Components/Common/components/ButtonV2";

export default {
  title: "Care UI / Button", // having '/' in title organizes the stories in a grouped/directory structure.
  component: ButtonV2,
};

const Template: ComponentStory<typeof ButtonV2> = (args) => (
  <ButtonV2 {...args}>Label</ButtonV2>
);

export const Button = Template.bind({});
```

### References
- [Install storybook](https://storybook.js.org/docs/react/get-started/install)
- [PostCSS 8 Wiki](https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users)
- [Configuring for tailwind](https://stackoverflow.com/a/65709909/7887936)

### To run storybook locally:
```sh
npm install --legacy-peer-deps # install new packages required
npm run storybook # launch storybook
```
open [http://localhost:6006](http://localhost:6006) in your browser

_Storybook preview deployment for this branch until its merged can be viewed at: https://care-fe-storybook.vercel.app_

### VS Code Extensions that might be helpful when working with Storybook `.mdx` stories:
- [MDX unifiedjs.vscode-mdx](https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx)

### Additional add-ons in Storybook
- [storybook-dark-mode](https://storybook.js.org/addons/storybook-dark-mode)

## New Components
_See storybook for component API documentation._

  ### `SelectMenuV2`
  Rebuilt to be consistent with other components' API and support for option icons.
  image
  
  ### `MultiSelectMenuV2`
  image
  image

  ### `AutoCompleteAsync`
  by @khavinshankar 
  image
  
  ### `TextFormField` and `TextAreaFormField`
  image
  image
  
  ### `DatePicker` and `DateRangePicker`
  by @Ritesh-Aggarwal 
  image

## Patient Filters Redesigned

As per [figma design](https://www.figma.com/file/fqDMgeN2m4TCSz5KobZaKW/CoronaSafe-Network-Care?node-id=1150%3A9)

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad there is a lot of merge conflict, check it

**Comment by nihal467** [comment]
@khavinshankar can you check this

**Comment by nihal467** [comment]
@rithviknishad 
image

unable to type in the lsg body filters or any other filters

**Comment by nihal467** [comment]
Patient Filter LGTM @khavinshankar go through story book

**Review by khavinshankar — APPROVED** [review]
@rithviknishad 
- shouldn't we remove or customize the introduction page in the storybook?
- and in storybook, can't pick a date in date range component

merging this pr, pickup the issues in a new pr

**Pull request merged**
