### PR TITLE
Make sidebar collapsible | Issue#2101

### PR DESCRIPTION
**Pull request by developedBySJ**
## Changes
- Refactor App router sidebar component (Current Version uses single sidebar component for mobile and desktop)
- Add collapsible sidebar

#### Collapsed sidebar
image

#### Expaned sidebar (hover to expand sidebar)
image

### CODE REVIEW

**Comment by nihal467** [comment]
@developedBySJ @gigincg  by default, keep it in expanded mode and if a user wants to collapse the sidebar, add a button for that

**Comment by gigincg** [comment]
@developedBySJ Also keep a different Logo (Without "Care") for the collapsed mode

**Comment by developedBySJ** [comment]
## Changes
- Add side bar preference option
- Fix collapse logo

## Preview
image

**Comment by nihal467** [comment]
@developedBySJ @gigincg 

- keep the distance between the button the same as the existing version
- the green colour is also different, so keep the green colour as in the existing version

**Comment by developedBySJ** [comment]
> 

@nihal467 
- Green colour is matching the colour in the design mockup which different from the previous green colour
- I have added some extra spacing to look clean and neat. Reducing spacing might look messy.

**Comment by nihal467** [comment]
Untitled presentation (1)

@gigincg what we should be doing!

**Comment by nihal467** [comment]
pejfwepf

@gigincg what we should be doing!

**Comment by gigincg** [comment]
@developedBySJ The Design Mockup referred from Care. So it wouldn've been the mismatch of the  mockup. Let's stay with the existing colour scheme

**Comment by nihal467** [comment]
test approved

**Pull request merged**
