### PR TITLE
Enhancements to Camera Feed Component

### LINKED ISSUE #7999: InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source  ### Details
### Error Description

**InvalidStateError**: This error occurs when trying to execute `appendBuffer` on a `SourceBuffer` that has been removed from the parent media source. It happens in the `useMSEplayer` hook.

### Steps to Reproduce

1. User navigates to the patient consultation feed page.
2. Media playback starts using `useMSEplayer`.
3. Error occurs during buffer append operation.

### Stacktrace

```plaintext
ws.onmessage (src/Common/hooks/useMSEplayer) at ../../src/Common/hooks/useMSEplayer.ts:172:17
readPacket at ../../src/Common/hooks/useMSEplayer.ts:131:18
pushPacket at ../../src/Common/hooks/useMSEplayer.ts:109:25
```

Additional Information
The error seems to be related to media streaming in the useMSEplayer hook.

### LINKED ISSUE #8040: URGENT NEED: Improve camera feed
**Is your feature request related to a problem? Please describe.**
The new camera feed component is getting a lot of negative feedbacks for the following reason:

- [ ] The aspect ratio has changed. The width is increased with respect to the height. This reduces the feed space on phone screens.
- [ ] Is it possible that the new component is slower and requires a better internet speed to work? Many complaints of camera feed freezing with internet speed dips. Users say this was not the case before
- [x] #8085

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Fixes #8040
- Improved visual experience of the feed component
- Moved feed controls outside the feed view for mobile displays in portrait mode.
- Hide top bar in fullscreen to maximize utilisation of screen space for the video feed
- Fixes camera stream reset logic stuck at loading at times.
- Fixes #7999
- More changes would be done as a follow up PR. Refer [comment](https://github.com/coronasafe/care_fe/pull/8140#issuecomment-2232717849)

### Desktop View

image

#### Portrait

image

#### Landscape

image

#### Landscape - Fullscreen

image

#### Live Monitoring

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by gayann-au** [comment]
Short Cut Key Information for  Diagonal Cursors Should be added

**Comment by gayann-au** [comment]
Network Ping information is not available for Camera feed view in Smart Phones(Used device: iPhone 14 pro, Used Browser: Chrome and Safari)

**Comment by gayann-au** [comment]
Directional Movement Cursors are not available when full screen is enabled in Mobile Phones
 (Used device: iPhone 14 pro, Used Browser: Chrome and Safari)

**Comment by gayann-au** [comment]
Lag in Visual experience in feed Component is found in Smart Phones.
This observations are noted comparingly Laptop and Mobile Phone previews.
*For Example when any of the preset Request is clicked from Mobile Phone, respective present is seen/Camera Movement is first found in Laptop and after certain delay it is found in Smart Phones.(delay noted at this instance was 10 Seconds from Laptop to Smart Phones). 
*Here Both the device are present in same network and both are availed with with Same Network Speed
ref:  Used device: iPhone 14 pro, Used Browser: Chrome and Safari- Used Laptop OS: Windows 11,Used Browser: Chrome

**Comment by Howni** [comment]
The camera goes into loading mode after a few minutes of live monitoring. However, after refreshing the page (both on the laptop and the smartphone), the camera feed becomes live again.
Also there is a lag in camera feed visual between mobile phone and laptop.

**Comment by Howni** [comment]
Before it goes to Loading mode the latency is very high
Before it goes to Loading

**Comment by Howni** [comment]
Camera feed is on Loading mode.

**Comment by Howni** [comment]
Camera feed in Loading mode.
Camera feed is Loading mode

**Comment by Howni** [comment]
After refreshing the page, the Camera feed is live again.
After refreshing the page

**Comment by Jrl0** [comment]
Screenshot_2024-07-16-15-07-40-28_40deb401b9ffe8e1df2f1cc5ba480b12

Device tested on Mobile  Realme GT2 Os:ANDROID v14
Browser:Chrome

1.The camera feed automatically returns to the most recently added preset for the bed, rather than the last preset that was viewed.

2.In landscape full-screen mode on mobile, the aspect ratio is off, making the viewing screen too small.(Better embed the button onto the viewing screen)

**Comment by rithviknishad** [comment]
### Changes that would be solved in this PR

- [x] Inline PTZ controls are not being used for certain screen sizes in landscape full-screen view causing it to show a reduced-sized feed. ([ref](https://github.com/coronasafe/care_fe/pull/8140#issuecomment-2230497790))
- [x] Camera feed is not always auto-restarting after crossing the latency threshold. Stuck in a loading state. (all devices, desktop and mobile) ([ref](https://github.com/coronasafe/care_fe/pull/8140#issuecomment-2230309395))
- [x] Add shortcut keys for diagonal movement controls. ([ref](https://github.com/coronasafe/care_fe/pull/8140#issuecomment-2230117857))

### Changes that would be addressed as a separate issue

- [ ] Add network ping information for _iOS devices_. ([ref](https://github.com/coronasafe/care_fe/pull/8140#issuecomment-2230121465))
- [ ] Showing PTZ Controls for _iOS devices_ in fullscreen. ([ref](https://github.com/coronasafe/care_fe/pull/8140#issuecomment-2230135691))
- [ ] Lag in feed for mobile displays compared to desktop feed. ([ref](https://github.com/coronasafe/care_fe/pull/8140#issuecomment-2230163555))
- [ ] Move to the last used preset instead of the first available preset when opening the patient feed. ([ref](https://github.com/coronasafe/care_fe/pull/8140#issuecomment-2230497790))

**Comment by Santoshdevale** [comment]
feed visual is not good unlike existing cameras visuals were far better

**Comment by nihal467** [comment]
**QA Test [in-progress]**

- [x] patient consultation feed
- [x] live camera feed
- [x] Asset configuration feed

**Comment by nihal467** [comment]
@rithviknishad 

- [ ] The borders of more preset dropdown and save buttons is so much towards grey so in white background, its hard to view it

**Comment by nihal467** [comment]
@rithviknishad the windows 11 is blocking ctrl + shift combination, so can you fix shortcuts on a new PR

**Comment by nihal467** [comment]
@rithviknishad other than shortcut, LGTM @aparnacoronasafe can you look into the Pr and approve it for merging

**Comment by rithviknishad** [comment]
Shortcuts have been disabled momentarily as @nihal467 reported that it is not working in windows as expected. This will be fixed in an upcoming PR

**Comment by nihal467** [comment]
IMG_8319
IMG_8318

- [ ] the internet speed symbol is missing on real iphone but the issue cant be replicated on a stimulated device
- [ ] The preset bar is overlapping with the nav bar on top while rotating the phone

**Comment by nihal467** [comment]
@rithviknishad

**Comment by rithviknishad** [comment]
@nihal467 the padding issue for webkit based browsers has been fixed. However the network signal was disabled for webkit based browsers as it was not supported as mentioned in an earlier comment. We can bring this back in a separate issue.

**Comment by nihal467** [comment]
@rithviknishad mark it for re-testing once the UI is approved

**Comment by nihal467** [comment]
LGTM

**Review by gigincg — APPROVED** [review]

**Review by gigincg — APPROVED** [review]

**Comment by gayann-au** [comment]
Misalignments of Texts in the Preset name  is observed
PFA ref. snapshot 
Screenshot 2024-08-01 185443

**Comment by nihal467** [comment]
@gayann-au 

- [ ] Can you share an example of the maximum length of the preset you created?

image

note: To share a recent change, we added an alert in the asset configuration page advising the user to keep the preset name under 12 characters,

**Pull request merged**
