### PR TITLE
Added Preview Page UI, migrated to SlideOver Component & icons updated.

### PR DESCRIPTION
**Pull request by yogeshbhutkar**
Issue Addressed: #6221 

### <samp>🤖 Generated by Copilot at c74eb25</samp>

Refactored the file preview dialog component to use a slide over UI and added more functionality. Replaced the `Dialog` component with the `SlideOver` component in `FilePreviewDialog.tsx` and simplified the props. Added zoom, rotate, and download buttons using `ButtonV2` and `CareIcon`.

## Proposed Changes

- Fixes #6221 
- Updated the UI
- Migrated the Modal to use Care's SlideOver component
- Updated the icons to use CareUI's Icons than to use font-awesome icons.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at c74eb25</samp>

*  Refactor `FilePreviewDialog` component to use `SlideOver` component instead of `Dialog` component ([link](https://github.com/coronasafe/care_fe/pull/6296/files?diff=unified&w=0#diff-54c239f5693dcce454bb02b533a03b41fc9d4c5998bf3b1ce0aef9fafbe5ceb2L1-R7), [link](https://github.com/coronasafe/care_fe/pull/6296/files?diff=unified&w=0#diff-54c239f5693dcce454bb02b533a03b41fc9d4c5998bf3b1ce0aef9fafbe5ceb2L32-R34), [link](https://github.com/coronasafe/care_fe/pull/6296/files?diff=unified&w=0#diff-54c239f5693dcce454bb02b533a03b41fc9d4c5998bf3b1ce0aef9fafbe5ceb2L69-R156))
  - Update imports to remove unused components and add new components ([link](https://github.com/coronasafe/care_fe/pull/6296/files?diff=unified&w=0#diff-54c239f5693dcce454bb02b533a03b41fc9d4c5998bf3b1ce0aef9fafbe5ceb2L1-R7))
  - Simplify props to only keep essential ones for file preview functionality ([link](https://github.com/coronasafe/care_fe/pull/6296/files?diff=unified&w=0#diff-54c239f5693dcce454bb02b533a03b41fc9d4c5998bf3b1ce0aef9fafbe5ceb2L32-R34))
  - Replace main content with `SlideOver` component that renders file as image or iframe ([link](https://github.com/coronasafe/care_fe/pull/6296/files?diff=unified&w=0#diff-54c239f5693dcce454bb02b533a03b41fc9d4c5998bf3b1ce0aef9fafbe5ceb2L69-R156))
  - Add buttons for zooming, rotating, and downloading file using `ButtonV2` and `CareIcon` components ([link](https://github.com/coronasafe/care_fe/pull/6296/files?diff=unified&w=0#diff-54c239f5693dcce454bb02b533a03b41fc9d4c5998bf3b1ce0aef9fafbe5ceb2L69-R156))
  - Remove `Transition` and `Dialog` components as they are no longer needed ([link](https://github.com/coronasafe/care_fe/pull/6296/files?diff=unified&w=0#diff-54c239f5693dcce454bb02b533a03b41fc9d4c5998bf3b1ce0aef9fafbe5ceb2L69-R156))

### CODE REVIEW

**Comment by nihal467** [comment]
@yogeshbhutkar marking it as discussion for UI in EOD Call

**Comment by yogeshbhutkar** [comment]
Updated the preview component, TBD in EOD call 26/09/23

Moved the buttons on top of the image, the buttons are rather fixed at a particular position now.
image

Another proposed update with the stock backdrop effect, and title. Migrated all the icons to use the CareUI's Icons.
image

Probably with a BG to the title's div...
image

**Comment by nihal467** [comment]
@yogeshbhutkar is this PR, good for testing

**Comment by yogeshbhutkar** [comment]
> @yogeshbhutkar is this PR, good for testing

Yes @nihal467, the design was approved in the last EOD call, you can go ahead and test it out.

**Comment by nihal467** [comment]
@yogeshbhutkar 
image

- [ ] When you rotate a landscape image 90 degrees and zoom in, the button to rotate again is getting covered, it is causing an issue to the user that we need to zoom out all the way back and rotate again.

image

image
image

- [ ] In the first image, you can see the image is already fully zoomed, and when you click again zoom in, it makes the image fully to the initial size, ( this is an issue with the current staging preview and your PR, try to solve it along with this PR if possible )

**Pull request closed without merging**
