### PR TITLE
Added validations for Age and Gender

### PR DESCRIPTION
**Pull request by peeyush14goyal**
Closes Issue #1377

Issue:
Earlier form was accepting any value in Age. And Gender with Value Select. 

Fixes:
Added appropriate validations and also added * in Required fields

image

### CODE REVIEW

**Comment by nihal467** [comment]
@peeyush14goyal can you mention which form is this?

**Comment by peeyush14goyal** [comment]
@nihal467 Profile form

**Comment by nihal467** [comment]
@peeyush14goyal WhatsApp number is not a mandatory field

**Comment by peeyush14goyal** [comment]
@nihal467 Fixed

**Comment by nihal467** [comment]
error  22

@peeyush14goyal While Adding a user, Currently, it is mandatory to enter WhatsApp number but we want WhatsApp number as not mandatory, can you make the necessary change

**Comment by peeyush14goyal** [comment]
@vigneshhari Have you made Whatsapp Field not required in backend? In get Request I am getting this error
image

**Comment by nihal467** [comment]
error  2222

Test failed, alerting is poping-up

**Comment by nihal467** [comment]
@vigneshhari @bodhish can you comment on this?

**Comment by vigneshhari** [comment]
Can you try again now, it should be fixed.

**Comment by nihal467** [comment]
test approved

**Pull request merged**
