### PR TITLE
Show Asset Downtime on assets lists page

### LINKED ISSUE #6819: Show "Asset Down" in asset list if asset's last uptime status is down
**Describe the bug**
To find out which assets are down, we'll have to manually open individual assets to see which are down.

**Expected behavior**
Show "Asset Down" in asset list page itself if asset's last uptime status is down

**Screenshots**
image

## To Discuss:

- [ ] Working status could be confused with this?

### PR DESCRIPTION
**Pull request by Pranshu1902**
## Proposed Changes

- Fixes #6819 
Show Asset Downtime on the assets lists page if last uptime status was "down"
image

Backend PR: [#1794](https://github.com/coronasafe/care/pull/1794)
@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by Pranshu1902** [comment]
Backend PR: [#1794](https://github.com/coronasafe/care/pull/1794)

**Review by rithviknishad — CHANGES_REQUESTED** [review]
I don't think this is the right way to do it. The asset list page now fetches paginated assets in one call, and paginated availability records in another call. 

This does not ensure that you have the availability records of all the assets of the current assets in view.

I think the solution is to add a serializer-level field in the asset list API's serializer that says whether it is down or not.

cc: @Ashesh3

**Comment by rithviknishad** [comment]
Also, some other icon would be better. A setting cog icon does not suit for indicating downtime.

**Comment by Ashesh3** [comment]
> I don't think this is the right way to do it. The asset list page now fetches paginated assets in one call, and paginated availability records in another call.
> 
> This does not ensure that you have the availability records of all the assets of the current assets in view.
> 
> I think the solution is to add a serializer-level field in the asset list API's serializer that says whether it is down or not.
> 
> cc: @Ashesh3

I agree with you here.

> I think the solution is to add a serializer-level field in the asset list API's serializer that says whether it is down or not.

^ this is the ideal solution

**Comment by Pranshu1902** [comment]
@rithviknishad is this icon ok?

image

**Comment by nihal467** [comment]
@Pranshu1902 the backend review is still going on, posting the test to next week

CC: @rithviknishad @Ashesh3 @sainak

**Review by rithviknishad — APPROVED** [review]
LGTM

**Review by Ashesh3 — APPROVED** [review]

**Comment by Pranshu1902** [comment]
@nihal467 @khavinshankar the backend PR has been merged, this PR is good to merge

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
