### PR TITLE
Add Abdominal Drain and Change Rules to Ryles on Ouptput DropDown

### LINKED ISSUE #8305: Add "abdominal drain" and corrrect spelling for "Ryles tube aspiration" on Output dropdown on IO Balance
**Describe the bug**
Add "Abdominal Drain" on Output dropdown.
Correct the spelling of Ryles tube aspiration on the dropdown. currently its mentioned as 'Rules tube aspiration"

**To Reproduce**

1. Go to logupdate
2. Click on detailed update
3. Scroll down to save and select IO balance parameter
4. goto  output
5. see error

image

**Screenshots**

### PR DESCRIPTION
**Pull request by aSriram199**
## Required Backends
- https://github.com/coronasafe/care/pull/2366

## Proposed Changes

- Fixes #8305
- Add "Abdominal Drain" on Output dropdown.
- Correct the spelling of Ryles tube aspiration on the dropdown.

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by rithviknishad** [comment]
@aSriram199 existing data would need migration for the spelling correction 

https://deploy-preview-8328--care-egov-staging.netlify.app/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7a3e40fb-da2a-42cc-b424-621273e3b197/consultation/b70e90f0-f43a-4b46-9f06-18bddb24f44e/daily_rounds/50ae957d-9f7b-4bda-8589-81d819729700

**Comment by rithviknishad** [comment]
Let me know if you'll be updating the backend or facing any difficulties in it.

**Comment by aSriram199** [comment]
Hello @rithviknishad, I'll go ahead and update it. I'll reach out if I encounter any issues

**Comment by aSriram199** [comment]
Hello @rithviknishad,

I’m having trouble accessing the link you provided earlier.

**Comment by rithviknishad** [comment]
Try with username password:

```
rithviknishad
Coronasafe@123
```

**Comment by samholics** [comment]
Tested working fine @nihal467

**Comment by aSriram199** [comment]
Hello @rithviknishad,
I'm facing some issues with the migration. Would it be possible to assign it to someone else to handle? I would really appreciate the help.

**Comment by nihal467** [comment]
@rithviknishad can you create a migration for existing data

**Comment by rithviknishad** [comment]
@aSriram199 I've made the backend PR: https://github.com/coronasafe/care/pull/2366

**Comment by aSriram199** [comment]
> @aSriram199 I've made the backend PR: [coronasafe/care#2366](https://github.com/coronasafe/care/pull/2366)

Thank you! @rithviknishad

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
