### PR TITLE
fixed popup scrolling and closing problem

### LINKED ISSUE #5088: Pressure pop-up not scrolling along with page
**Describe the bug**
- [ ] When we open a pressure sore pop-up and scroll, the pop-up doesn't scroll along with it.
- [ ] Pop-up does not close when clicked outside

**To Reproduce**

1. Go to a patient's pressure sore tab
2. Click on any body part.
3. Scroll / click outside.

**Expected behavior**
- [ ] Pop-up may scroll along with the page.
- [ ] Pop-up may close when clicked outside.

**Screenshots**
image

image

### PR DESCRIPTION
**Pull request by sghosh28**
## Proposed Changes

- Fixes #5088?
- Pop-up may scroll along with the page.
- Pop-up may close when clicked outside.

@rithviknishad @nihal467 

### HOW
- Pop-up may close when clicked outside.
  Used onClick event listener to close popup when clicked outside
- Pop-up may scroll along with the page.
   Made pop-up relative to a parent body and used getBoundingClientRect to get X Y value for popup relative to parent.

### CODE REVIEW

**Comment by nihal467** [comment]
image

- When I type something on width and height, it auto-closes suddenly, and the pop-up is not working properly

**Comment by nihal467** [comment]
@sghosh28

**Comment by sghosh28** [comment]
> image
> * When I type something on width and height, it auto-closes suddenly, and the pop-up is not working properly

Hello @nihal467 ,

Could you please guide me on how to access the popup for editing details? I'm looking to understand how to address the issue.

Thank you!

**Comment by sghosh28** [comment]
> @sghosh28

Found the issue, working on it

**Comment by sghosh28** [comment]
@nihal467 
Done with new changes

**Comment by nihal467** [comment]
@sghosh28 
image

- now the dropdowns are not closing post selecting an option

**Comment by gigincg** [comment]
Closing the issue, since the PressureSore component has been rebuilt in TypeScript, making this PR unsalvageable

**Pull request closed without merging**
