### PR TITLE
Fixed Filters in Facilities Page

### LINKED ISSUE #2845: Filter are malfunctioning : Facility Page
https://www.loom.com/share/fc615f453af54570a067d8e5795602b0

Once we apply advance filters in the facility page , and search the facility using its name, the advance filters are auto removed

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #2845
- [x] Fixed `Filters option` in Facilities page

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder test failed, the badges are in multiple size and have no space between each other

**Comment by aeswibon** [comment]
@nihal467 fixed the problem

**Comment by nihal467** [comment]
@cp-Coder 



make it aligned

**Comment by nihal467** [comment]
@cp-Coder what is the status ?

**Comment by aeswibon** [comment]
@nihal467 I have fixed the issue
image

**Comment by nihal467** [comment]
@cp-Coder 
image

the alignment of the a badges are bit off, correct it,

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
