### PR TITLE
Completed patient details section for read-only user 🥁

### LINKED ISSUE #2636: improve patient details section for read-only users
### Enhancements required

**For read-only user type**
**In Pateint details section**

- [x] Disable "Update Details" Button
- [x] Disable "Allow Transfer" Button
- [x] Disable "Add Consultation Updates" Button
- [x] Disable updates on Patient Test sample **(Backend Done ✅)**
- ~[ ] Disable Record and Upload button inside "View/Upload Consultation Files" **(Need backend fixes)**~
- ~[ ] Disable Record and Upload button inside "View/Upload Patient Files" **(Need backend fixes)**~
- [x] Disable "Shift Patient" Button
- [x] Disable "Request Sample Test"
- [x] Disable "Post your notes" in View Patient notes **(Backend Done ✅)**
- [x] Disable "Discharge Summary" Button
- [x] Disable "Discharge from care" Button
- [x] Disable "Assign to a volunteer"

### PR DESCRIPTION
**Pull request by ishanExtreme**
### Issue fixed
closes #2636 

### Updates
**for route facility/facilityID/patient/patientID**(Patient Details)
**Credentails->readonly:Welcome@123**
- Disabled "Post Notes" for read-only users
- Disabled "Update Sample Test Status" button for read-only users

### Note ✨
"Something went wrong" will be currenly displayed in patient details section, PR for fixing this issue is already made in backend
[#871(backend)](https://github.com/coronasafe/care/pull/871).This issue is because read-only staffs are not permitted to GET list of sample tests, read this [issue](https://github.com/coronasafe/care/issues/869).
**Its safe to merge this PR before backend is merged**

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

**Comment by nihal467** [comment]
test approved

**Comment by nihal467** [comment]
@ishanExtreme what is the status of PR

**Comment by khavinshankar** [comment]
@ishanExtreme can you please check this pr once and make the necessary changes?

**Comment by ishanExtreme** [comment]
@khavinshankar sorry for delay, onto fixing the PR

**Comment by ishanExtreme** [comment]
@khavinshankar PR updated to this https://github.com/coronasafe/care_fe/pull/3485. I am closing this one

**Pull request closed without merging**
