### PR TITLE
Added `AccordionV2`  and `CollapseV2` components to replace MUI's Accordion and Collapse components

### LINKED ISSUE #3763: Tailwind Component: `Collapse` (Accordion)
Component API for reference: https://vercel.com/design/collapse
Component design / color scheme: as followed in #3744

### PR DESCRIPTION
**Pull request by GokulramGHV**
fixes #3763 

## Proposed Changes

- Added `AccordionV2`  and `CollapseV2` components
- Replaced all code where the MUI's Accordion was used to `AccordionV2` Component.
-  Replaced all code where the MUI's Collapse  was used to `CollapseV2` Component.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by GokulramGHV** [comment]
Part of #3742

**Review by rithviknishad — APPROVED** [review]
Nice :) LGTM

**Comment by rithviknishad** [comment]
@nihal467 can this be tested ASAP? required by https://github.com/coronasafe/care_fe/pull/3744

**Comment by nihal467** [comment]
@GokulramGHV @rithviknishad there is lot of white spacing and alignment issue occurring due to this PR when compared to the existing staging

image

- [ ] the current address is changed from the row of gender to the row of permanent address. it is breaking the alignment of the whole personal detail page compared to existing staging

image

- [ ] the health details alignment is changed from the existing staging, and there is a lot of white space been wasted
- [ ] some of the options are not been visible in normal view

**Comment by nihal467** [comment]
@GokulramGHV 
image

health section is completely breaking

**Comment by nihal467** [comment]
tested

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
