### PR TITLE
Fixes: Add Health Details in Consultation form

### LINKED ISSUE #2738: Changes to be made in the consultation form : Add Health Details
Part of #2218 
HEALTH DETAILS

 - Add a new collapsable section to the consultation form on top. This section will contain all health details of the Patient.
 - The first field is "Allergy"- YES/NO. If YES, a short text box for details. (the text field already exists in the patient registration form. the same may be migrated)
 - Second field will be for "Vaccinations". The user must be able to select multe inputs from the options. The Options would be: COVID (1 dose, 2 dose), Hep B, Hep A. (The field for COVID Vaccinationa already exists in patient registration form)
 - "Blood Group" With dropdown. (The field already exists in the patient registration form and may be migrated here)
 - Field for "Weight" and "Height" existing at the bottom of the consultation form may be moved up to the top after blood group.
 - Add a Long Text Field for "Familty Details"

### LINKED ISSUE #3332: Allergies: to be added to health details
Note: #3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

- [ ] Health details must contain a toggle button (Yes/NO) for "Allergies".  Default selection to be NO

- [ ] If selected "Yes"- a short text box must appear for description.
NOTE: A short text box for allergies already exists in the Medical History section. The same may be moved and used here. 

This shall be placed as the first field in Health details

- [ ] Wherever allergy is selected to YES, make the allergy details appear on patient dashboard (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0) below diagnosis.

- [ ] Create a label for allergies to appear in the patient list

@gigincg to review
Issue is part of #2218

### LINKED ISSUE #3333: Vaccinations: in Health details
Note: https://github.com/coronasafe/care_fe/issues/3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

Add a section for vaccinations. 

- [ ] The first field would be to select the type of Vaccine. The options would be "COVID", "Hep A"  "Hep B". The options may be expanded later. The user should be able to select multiple options. 
- [ ] Once a vaccine in selected, there must be the option for a dose for certain options. In this case for COVID the option of doses are going to be 1,2,and 3. For the other options, the field for dosage will not appear.
- [ ] Date of the last dose- this must appear for all options. The field for the date must accept the exact date (DD/MM/YYYY), Month and year (MM/YYYY) or even just year (YYYY)

The design of the field may mimic the prescription module where one vaccine may be entered along with details, and another row may be added to add a second vaccine. This is only a suggestion, you may use your creativity to come up with better layouts

- [ ] The information thus collected must be shown in the Patient Details Page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/aefb147a-eb09-4dd0-8390-e2cd5a05f326) on the right side of Bloof Group below the Patient Name.

NOTE: 5 fields relating to COVID vaccines already appear in health details. The field are "Is the patient vaccinated against COVID?" "COWIN ID", "No. of doses", "Vaccine Name" and "last date of vaccination". These fields may be repurposed/ removed with this new vaccine section that covers a wider range of vaccines.

@gigincg to review
This is part of #2218

### LINKED ISSUE #3335: Blood Group: reposition
Note: https://github.com/coronasafe/care_fe/issues/3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

The blood group field with dropdown is currently under the "Medical History" Section. 
It must be moved to the "health details" section

@gigincg Please review
Part of #2218

### LINKED ISSUE #3336: Height and Weight : Reposition
Note: https://github.com/coronasafe/care_fe/issues/3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

The fields for Height and Weight fields exist in consultation.

Move the same to "Health Details"

Part of #2218 
@gigincg please review

### LINKED ISSUE #3338: Family Details- add field in health details
Note: https://github.com/coronasafe/care_fe/issues/3331 moves the health details and medical history section from the patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update) to Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

- [ ] As the last field in "Health Details" add a long text field for "Family Details"
The field will be non-mandatory

- [ ] Show the information in Patient details page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0) as a separate heading "Family Details" below "Medical"
Screenshot 2022-08-06 at 12 59 03 AM

Issue is part of #2218 
@gigincg please review

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #2738
- [x] Fixes #3332
- [x] Fixes #3333
- [x] Fixes #3335
- [x] Fixes #3336
- [x] Fixes #3338

### CODE REVIEW

**Comment by rithviknishad** [comment]
😢 thats a major change im gonna face in my consultation form tailwind update. I'll keep my PRs for (#3698 #3594) on hold until this is merged.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@cp-Coder is it ready?
when I click Edit Consultation, I get a blank screen:

image

**Comment by rithviknishad** [comment]
Oh my bad... Backend is required too.

**Comment by aeswibon** [comment]
Will open a new PR squashing all the commits

**Pull request closed without merging**
