### PR TITLE
fix: patient creation form back button

### PR DESCRIPTION
**Pull request by Pragati1610**
fixes https://github.com/coronasafe/care_fe/issues/3854

### CODE REVIEW

**Comment by nihal467** [comment]
@Pragati1610 what is the status on this PR

**Comment by Pragati1610** [comment]
Done

**Comment by nihal467** [comment]
@Pragati1610 is it good for testing

**Comment by Pragati1610** [comment]
yes

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
