### PR TITLE
Showing spinner only for assets list while loading

### LINKED ISSUE #3576: Fix Loading in AssetsList
**Describe the bug**
When we search some asset in AssetList, the entire page is loading i.e., the spinner is shown for the entire page

**Expected behavior**
Show the spinner only for the asset list i.e, it should not effect serach bar and others

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #3576 

## Proposed Changes

- Showing spinner only for assets list while loading

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Comment by developedBySJ** [comment]
@khavinshankar Deploy preview is failing. 
can you take look into it?

**Comment by nihal467** [comment]
@khavinshankar check the deployment preview

**Comment by khavinshankar** [comment]
@nihal467 fixed the deploy failure, missed a bracket while resolving merge conflict in the browser, its is now ready to be tested

**Comment by nihal467** [comment]
test approved

**Pull request merged**
