### PR TITLE
Added buttons for users card

### LINKED ISSUE #5132: Revamp Show User linked skills button
**Describe the bug**
Revamp Show User linked skills button

**To Reproduce**

1. Go to http://localhost:4000/users
2. See error

**Expected behavior**
Make it similar to that of the Linked Facility button

**Sample Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #5132 
Replaced text with buttons for linked facilities and skills
http://localhost:4000/users
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
Marking it for final approval on UI

**Comment by nihal467** [comment]
@Pranshu1902 add icons in the buttons

**Comment by Pranshu1902** [comment]
@nihal467 
Updated view:
image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
