### PR TITLE
Fixed Styling Issue : Patient Notes

### LINKED ISSUE #2860: Styling Issue : Patient Notes
the add notes box is having a blue box as the border, change the effect and make it black or anything suitable to UI

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2860 
# Bugs Fixed

## Made the outline color green
image

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
test approved

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@patelaryan7751 I think it's better to use colors like `focus:ring-primary-500 focus:border-primary-500` instead of `focus:ring-green-500 focus:border-green-500`.

This shall help change the color from one place if at all we need to modify it later.

Also see the `tailwind.config.js` file where the primary is designed.

**Comment by patelaryan7751** [comment]
@rithviknishad  I have made the required changes.

**Review by rithviknishad — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
