### PR TITLE
Added cypress tests for Facility cover image button functionality 

### LINKED ISSUE #9109: Refactor the existing cypress test to upload cover image
**Description**

Enhance the existing test suite to include functionality for uploading, editing, and deleting the facility cover image.

**General Instruction**

- Code should follow the POM structure.
- Reuse existing custom functions and those in commands.ts where possible. Before creating a new function, check for an existing one that matches the element's ID to avoid redundancy.
- Add API request verification wherever required using cy.intercept();
- Add the tests in the facilityManage.cy.ts file and any new page objects in the facilityManage.ts file.

**Test Workflows**

**Test 1: District Admin** 

1. Log in as a district admin and navigate to any facility.
2. Open the facility cover image pop-up, then click the Cancel button to verify it functions correctly.
3. Reopen the cover image pop-up and upload an image, verifying the API response.
4. Edit the current cover image by uploading a new one, and verify the API response.
5. Delete the existing cover image, confirming the API response.

**Test 2: Access Verification with Non-Admin User**

1. Log in as the devdoctor user.
2. Repeat the steps from Test 1 to verify functionality consistency across user roles.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by rohitlingarker**
## Proposed Changes

- Fixes #9109 
- Added functions (verifyCoverImageModalClosed, clickDeleteCoverImage) and cypress Intercepts to api calls in pageobject/Facility/FacilityManage.ts.
- Written tests using the already existing functions to test upload, edit and deletion of facility cover image in FacilityManage.cy.ts.
- Added roles in the FacilityManage.cy.ts for testing the functionality across different user roles
- Added `id = "delete-cover-page"` to the delete cover page button element.

@ohcnetwork/care-fe-code-reviewers

## Release Notes

- **New Features**
	- Introduced a new test suite for "Facility Cover Image Functionality" to enhance testing coverage.
	- Added methods to improve the functionality of the Facility Management interface, including handling cover image uploads and deletions.

- **Bug Fixes**
	- Removed a non-functional test case related to the "Facility Cover Image" button to streamline testing.

- **Improvements**
	- Enhanced accessibility of the Avatar Edit Modal with new `id` attributes for buttons, improving integration with testing frameworks.

### CODE REVIEW

**Comment by nihal467** [comment]
@rohitlingarker since the PR is under draft removing the review PR

**Comment by khavinshankar** [comment]
We should consider making each test atomic i.e., 1 test shouldn't influence the other, as this is making debugging and developing harder. We should clean up after or during each test and create the necessary resources before or during the test. There is no need to refactor anything for now, maybe we should enforce this for newer tests.

@nihal467 thoughts?

**Comment by nihal467** [comment]
@rohitlingarker 

- Create a new test file under the `facility_spec` folder itself.
- Dynamically select a new facility for each user in the test, making sure that the same set of code and logic runs for different users in different facilities.

this way like @khavinshankar mention they will be independent test

**Comment by nihal467** [comment]
@rohitlingarker look into the code rabbit review, 

- As per issue, the API verification is not done once the file upload is completed [Also it was flag by the AI review]

image
image

- Remove the manually hardcoded password usage in the test file. Using the existing login function, try to implement a solution where the password is dynamically allocated. The screenshot is a solution provided by ChatGPT to handle this kind of situation, though I wouldn't say it's well optimized. Think of a better solution that can scale and avoid hardcoded values.
- remove the unused image you push to this PR " facility-cover-image1 "

**Comment by nihal467** [comment]
@rohitlingarker any update

**Comment by nihal467** [comment]
@rohitlingarker Closing the PR due to inactivity and unassigning you from the issue. Feel free to reopen the PR and get reassigned if you are still working on it.

**Pull request closed without merging**
