### PR TITLE
Upgraded to mui v5

### LINKED ISSUE #2380: Replace react-dates with material ui date picker
replace with mui; https://mui.com/x/react-date-pickers/date-range-picker/#main-content

### LINKED ISSUE #2424: Upgrade material-ui to to v5

### PR DESCRIPTION
**Pull request by cp-Coder**
## Updates
- [x] Fixes #2424
- [x] Fixes #2380
- [x] Upgraded to mui v5
- [x] Upgraded code to support mui v5

### CODE REVIEW

**Comment by sainak** [comment]
@cp-Coder update https://www.npmjs.com/package/rescript-material-ui as well

**Comment by aeswibon** [comment]
@gigincg Can you clear the netlify cache??

**Comment by nihal467** [comment]
@cp-Coder @gigincg is it good for testing?

**Comment by gigincg** [comment]
> @gigincg Can you clear the netlify cache??

@rithviknishad

**Comment by aeswibon** [comment]
@nihal467 

> @cp-Coder @gigincg is it good for testing?

Yes

**Comment by rithviknishad** [comment]
@cp-Coder cleared cache and deployed!

**Comment by gigincg** [comment]
@nihal467 Can you test this PR end to end (All Screens and all Forms)

**Comment by nihal467** [comment]
@cp-Coder @gigincg 

test failed, 


1. the text box is big now and the password show icon is off-aligned

wokt4

the add patient tab goes white screen

step to reproduce:

1. Go to the patient tab
2. click on  add detail of a patient button
3.  type a facility name, then the screen goes white

**Comment by aeswibon** [comment]
# Updates

- [x] Fixed patient tab goes white screen
- [x] Fixed Text Box is big now and the password icon is off aligned

**Comment by aeswibon** [comment]
@nihal467 The netlify build is failing because the cache is not cleared.
@rithviknishad Can you clear the netlify cache and deploy this pr???

**Comment by rithviknishad** [comment]
@cp-Coder the issue has been fixed in latest develop 7c4c16a
Could you merge that?

**Comment by cp-Coder** [comment]
@nihal This is my login screen(local)
image
I will ask @gigincg today in the EOD call.

**Comment by aeswibon** [comment]
Opening a new PR

**Comment by aeswibon** [comment]
Tracked in [pr#2748](https://github.com/coronasafe/care_fe/pull/2748)

**Pull request closed without merging**
