### PR TITLE
Assign volunteer to a patient

### LINKED ISSUE #1148: assigning volunteer to patient
Any volunteer in the facility may be assigned to a patient. 

This can be done by any staff or the district administrator. Have the option on the patient dashboard.

once a volunteer is assigned to a patient, he should be able to assign a doctor to the patient or edit the patient details.

The volunteer must also be able to filter out only the patients assigned to him in the patient list

### PR DESCRIPTION
**Pull request by divyagar**
closes #1148 

Now a user can assign a volunteer to a patient. The option is present on dashboard.
For searching volunteer I have used `OnlineDoctorSelect` component and changed it accordingly.

https://www.loom.com/share/43cca23cdf424859be62ac59a8852a86

### CODE REVIEW

**Comment by nihal467** [comment]
@divyagar if I assign a volunteer to a patient, where can I see the assigned volunteer detail in the patient card ?

**Comment by divyagar** [comment]
@nihal467 We have added the assigned volunteer info. You can see it at the top of patient page, where assigned doctor is shown.

**Comment by nihal467** [comment]
Uploading Untitled Project.mp4…

@divyagar  test failed, when we try to reassign a patient to another volunteer, the data is getting accepting and updated, but we can't see change appear in the top of the patient detail unless we refresh the page manually.

**Comment by nihal467** [comment]
https://user-images.githubusercontent.com/57055998/122408443-06290280-cfa0-11eb-8dae-468c0d66bc6e.mp4

@divyagar  test failed, when we try to reassign a patient to another volunteer, the data is getting accepting and updated, but we can't see change appear in the top of the patient detail unless we refresh the page manually.

**Comment by divyagar** [comment]
@nihal467 I have made necessary changes.

**Comment by nihal467** [comment]
test approved

**Comment by nihal467** [comment]
@bodhish @divyagar there is a branch conflict, have a check on it...!

**Comment by shaileshaanand** [comment]
This branch was messed up with merge from develop. #1438 is created with all the commits from this branch on top of develop.
Please refer #1438

**Pull request closed without merging**
