### PR TITLE
Disable past dates for warranty expiry date on create assets page

### LINKED ISSUE #4326: Don't allow past dates for Waranty Expiry on Asset Creating form
**Describe the bug**
- The `Warranty / AMC Expiry` field accepts dates in the past as well.
- Make buttons full width on assets page

**To Reproduce**
https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/assets/new

**Expected behaviour**
Past dates shouldn't be allowed.

**Screenshots**
image

image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #4326 
- Disabled acceptance of past dates as expiry dates.
http://localhost:4000/facility/ea9a2fbe-74f3-446b-bdb0-e038766bfb09/assets/new
image

- Made buttons full-width on the Assets page
image

### CODE REVIEW

**Comment by nihal467** [comment]
@Pranshu1902 
image

- today is the 19th, and the date is greyed out in the calender, which shouldn't be
- unable to submit the form, there coming up a error

**Comment by Pranshu1902** [comment]
@nihal467 Error resolved!

**Comment by nihal467** [comment]
@Pranshu1902 
image

https://deploy-preview-4327--care-net.netlify.app/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/assets/ab12b691-5769-4e6f-a6d1-d6d2028dca07/update

when we open a existing asset for updating, the screen goes white

**Comment by Pranshu1902** [comment]
@nihal467 All bugs resolved!

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
