### PR TITLE
Care UI Slideover, upgrades Notifications List and Mobile Sidebar

### LINKED ISSUE #4387: Notifications sidebar is not responsive
**Describe the bug**
The Notifications sidebar panel is not responsive

**Screenshots**
image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Fixes #4387
- New component: `SlideOver`
- Replaces the custom slide-over of the mobile sidebar with the new slide-over component.

Co-authored by @skks1212 via #3996

### Desktop view (notifications)

image

### Mobile view (sidebar and notifications)

image

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by skks1212 — APPROVED** [review]
LGTM!

**Comment by naman114** [comment]
I am not able to see the back arrow even though it can be pressed @rithviknishad 

https://user-images.githubusercontent.com/57593654/210555516-418a697d-263f-492d-b3b2-afadfc83219f.mp4

**Comment by rithviknishad** [comment]
@naman114 the video recording you have is #3996 which uses unicons, and it has been removed from care. This PR is #4487 and uses Care Icons.

**Comment by nihal467** [comment]
LGTM, marking it for "Team discussion required" for final UI approval

**Comment by nihal467** [comment]
@khavinshankar the UI is approved in yesterday's EOD. You can merge it

**Review by gigincg — APPROVED** [review]

**Pull request merged**
