### PR TITLE
Added AMC Warranty filters and expiry labels for assets

### LINKED ISSUE #6241: Tracking Expiry of AMC/Warranty in CARE
**Is your feature request related to a problem? Please describe.**
In Asset management module we collect date of expiry of AMC/warranty of an asset. However there are no others features for users to get notified of when AMC/warranty is expiring soon.

**Describe the solution you'd like**
Introduce 2 kinds of alerts for AMC/warranty expiry.
**Yellow Alert**- starts 3 months before expiry and changes to a 
**Orange Alert** - starting 1 month before expiry
After Expiry of AMC/Warranty, a **Red Alert** must show till the AMC/warranty expiry date is updated to a future date.

- [ ] Show label on Asset list (https://care.coronasafe.in/assets) and asset page (https://care.coronasafe.in/facility/1210229b-711a-46e6-ab0a-207c4808e32e/assets/fe3295e6-0893-4024-99a8-3f2b981ea1c6) for 
- "AMC/Warranty expiring soon"- in yellow and orange colours respectively
- "AMC/Warranty expired"- in red colour.

- [ ] Add filter for "AMC Warranty Status" and have options (Multi-select) to show: 
- Expired
- Expiring within 1 month
- Expiring in 1-3 Months
- Expiring in 3-12 Months
- Expiring in 12-24 Months

- [ ] Notification must go to all Users for AMC/Warranty expiry.
- Create a new type of Notification. "Asset- AMC/Warranty"
- As and when 1 or more assets' AMC/Warranties are due to expire in 1-3 months the Notification must read as below:
HEADING: AMC/Warranty expiring in 3 months! 
BODY: AMC/Warranty for 15 Assets are expiring in 3 months. Contact vendor to extend AMC/Warranty now.
"Open" button should lead user to the asset list with filter showing "Expiring within 1 month" and "Expiring in 1-3 Months"
Its good to also show a Yellow alert Icon on the notification.
- As and when 1 or more assets' AMC/Warranties are due to expire in 1 month the Notification must read as below:
HEADING: AMC/Warranty expiring in 1 month! 
BODY: AMC/Warranty for 15 Assets are expiring in 1 month. Contact vendor to extend AMC/Warranty immediately.
"Open" button should lead the user to the asset list with filter showing "Expiring within 1 month" 
Its good to also show an Orang alert Icon on the notification.
- When 1 or more Assets' AMC/Warranty expires, send a similar notifications alerting that AMC/Warranties of so many assets have expired in a similar fashion with Red Alert icon
- If there are 1 or more expired AMC/Warranties, on 1st of every month send a notification with No. of assets with expired AMCs warranties with Red Alert icon

### PR DESCRIPTION
**Pull request by GokulramGHV**
### <samp>🤖 Generated by Copilot at e18d241</samp>

The pull request adds a new feature to manage assets by their warranty or AMC end of validity. It allows users to filter assets by date range, see the status of the warranty or AMC in a chip component, and export the filtered data. It modifies the files `AssetFilter.tsx`, `AssetManage.tsx`, and `AssetsList.tsx` to implement this feature.

## Proposed Changes

- Fixes #6241

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at e18d241</samp>

*  Add a new feature to filter assets by warranty or AMC end of validity date range ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R17-R21), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R33-R35), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R51-R54), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R127-R130), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R143-R149), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R229-R239), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d3677127a55934962254fa660ba9b01a59fdb23bee06c9160832527f36c8bf20R38), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d3677127a55934962254fa660ba9b01a59fdb23bee06c9160832527f36c8bf20R396-R398), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R77-R80), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R110-R111), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R297), [link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R438-R447))
  * Import modules and components for date range form field, date library, type definition, and utility function in `AssetFilter.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R17-R21))
  * Define a helper function to convert a value to a valid date object in `AssetFilter.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R33-R35))
  * Add a state variable to store the before and after values of the date range filter in `AssetFilter.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R51-R54))
  * Add the state values to the query parameters for fetching the filtered assets from the API in `AssetFilter.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R127-R130))
  * Define a handler function to update the state when the date range form field changes in `AssetFilter.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R143-R149))
  * Render a date range form field component with the name, label, value, onChange, and errorClassName props in `AssetFilter.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96R229-R239))
  * Import a function to render a chip component based on the warranty or AMC end of validity value in `AssetManage.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d3677127a55934962254fa660ba9b01a59fdb23bee06c9160832527f36c8bf20R38))
  * Render the chip component using the imported function and the asset's warranty or AMC end of validity value in `AssetManage.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d3677127a55934962254fa660ba9b01a59fdb23bee06c9160832527f36c8bf20R396-R398))
  * Add the warranty or AMC end of validity before and after values to the query parameters object for fetching the assets from the API in `AssetsList.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R77-R80))
  * Add the warranty or AMC end of validity before and after values to the dependency array of the useEffect hook for fetching the assets from the API in `AssetsList.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R110-R111))
  * Render the chip component using the same function and the asset's warranty or AMC end of validity value in the table row of each asset in `AssetsList.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R297))
  * Add the warranty or AMC end of validity before and after values to the CSV export data for the filtered assets in `AssetsList.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R438-R447))
* Define and export a function to render a chip component based on the warranty or AMC end of validity value in `AssetsList.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6364/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R504-R543))

### CODE REVIEW

**Comment by nihal467** [comment]
@GokulramGHV 
image

https://deploy-preview-6364--care-net.netlify.app/facility/45d45bb6-c48e-4883-984d-ac602ef7df1e/assets/2e961231-56cd-4b1b-abc2-0154ca96b660/update

the above asset has a warranty (31/01/2024) and today's date is (03/10/2023), as per the issue, the label should be coming from 3 months, but the above asset has more than 3 months exactly saying and the expiring label is shown to this asset

Note: if i make the warranty to any date in February, the warning is disappeared.

1. Was it intentional behavior, and discussed in the EOD call?

**Comment by nihal467** [comment]
@GokulramGHV add a cypress test to verify this functionality

**Comment by nihal467** [comment]
@GokulramGHV i have assigned you the cypress issue for this feature, work on it as a separate PR or along with this PR

**Comment by nihal467** [comment]
@GokulramGHV 
image

it is less than 3 months, and the alert is not working properly, make sure you cover all the edge cases, and mark it or testing

**Comment by GokulramGHV** [comment]
> @GokulramGHV image
> 
> it is less than 3 months, and the alert is not working properly, make sure you cover all the edge cases, and mark it or testing

@nihal467 the no. of days between today and 8th of january is 91 days, I'm considering 90 days to be 3 months. So that is the reason why it doesn't show the label

**Comment by nihal467** [comment]
LGTM, @GokulramGHV i have assigned you the cypress test related to this, you can create a separate PR for that

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
