### PR TITLE
Added max height limit on facility card

### LINKED ISSUE #4625: Facility card is having excess whitespace for random rows of cards
**Describe the bug**
Facility card is having excess whitespace for random rows of cards

**To Reproduce**
1. Go to facility list

Possible reason: Incorrect image ratio

**Expected behavior**
No excess whitespace

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #4625 
Added max-height limit
Before:
image

After:
image

### CODE REVIEW

**Comment by nihal467** [comment]
@Pranshu1902 
image

in the responsive, all the datas are not visible

**Comment by Pranshu1902** [comment]
@nihal467 
Updated view:
image

Desktop view:
image

**Comment by nihal467** [comment]
@Pranshu1902 
image

the card buttons are not properly placed

**Comment by Pranshu1902** [comment]
@nihal467 Updated view:
image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
