### PR TITLE
Added functionality to add name to audio files in Consultaion Files Tab

### LINKED ISSUE #2855: Unable to custom name audio file
when we are uploading a audio file, we can't custom name the file

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2855 
# Added Feature

## Added functionality to add a name to audio files in Consultaion Files Tab
https://user-images.githubusercontent.com/59426397/176910376-8f6db32b-97e7-49ee-94cb-42ef186ea7f7.mp4

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Review by cp-Coder — APPROVED** [review]

**Comment by khavinshankar** [comment]
@patelaryan7751 make the name field optional or have a default value for the name field like suggested by Bodhi in weekly meet

**Comment by patelaryan7751** [comment]
@khavinshankar i have made it optional now
image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
