### PR TITLE
Patient Registration form is now submitttable only when all the fields are filled

### LINKED ISSUE #1465: Confusing Error Message in Patient Card
error

When you create a patient card and fill in the details except for gender, the error message on the top, says 'Please enter the correct date of birth for the patient'. A message 'field is required' is displayed under the gender field but it will not be noticed quickly.

### PR DESCRIPTION
**Pull request by khavinshankar**
Resolves #1465

- [x] Changed the color of the alert message from red to yellow.
image

- [x] Added functionality such that, the submit button shows up only when all the required fields are filled.

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar can we have something like a pop-up or any mentioning above the grey button the missing field, currently, the button is just greyed and we have to look for the missing field manually

**Comment by nihal467** [comment]
@khavinshankar @shaileshaanand you guys will be pairing up and will be working on this solution right, so until you guys are finished, I have to put this PR untested right?

**Comment by khavinshankar** [comment]
- [x] Removed the grey button functionality (the submit button shows up only when all the required fields are filled).
- [x] Added auto-scroll to error field functionality.

auto-scroll in action:
https://www.loom.com/share/ea288f4bee5e40e0a1dcf9cc2bfdb061

**Comment by nihal467** [comment]
test approved

**Comment by bodhish** [comment]
@khavinshankar can you fix the merge conflicts 😄

**Pull request merged**
