### PR TITLE
Advanced Filter UI change

### PR DESCRIPTION
**Pull request by sam9111**
#1171 
The district and local bodies can now be selected from a dropdown and depending on the selection of the state and district respectively. Clicking "Clear Filter" will now also remove the previously filled state.

### CODE REVIEW

**Comment by samholics** [comment]
tested, verified

**Comment by bodhish** [comment]
@sam9111 can you fix the merge conflicts

**Comment by bodhish** [comment]
Also cleanup comments

**Comment by bodhish** [comment]
Can you also resolve conflicts

**Comment by bodhish** [comment]
@sam9111 This PR reverts almost all the new changes that were done in development. This can't be merged. 

Addition 18,908 
Deletions 1,802

Please check and create PR with just this change.

**Comment by sam9111** [comment]
> @sam9111 This PR reverts almost all the new changes that were done in development. This can't be merged.
> 
> Addition 18,908
> Deletions 1,802
> 
> Please check and create PR with just this change.

yes will create new PR

**Pull request closed without merging**
