### PR TITLE
Fixed datepicker alignment in Consultation Page

### LINKED ISSUE #1613: Alignment Issue : Consulation Page
bug 1

the highlight ' Date of onset of the symptoms ' is overlapping with the calendar icon

### PR DESCRIPTION
**Pull request by Sandra3657**
Resolves #1613 

The alignment issue for date picker in Add Consultation Form has been fixed.

### CODE REVIEW

**Comment by nihal467** [comment]
@Sandra3657 
dsfd

check the spacing, the gap between the calendar icon and field is really big

**Comment by Sandra3657** [comment]
image

The spacing been reduced.

**Comment by nihal467** [comment]
test approved

**Comment by bodhish** [comment]
@nihal467 test this on your mobile too.

**Comment by nihal467** [comment]
oefkpowekf

test failed, in mobile view, it is over lapping

**Comment by nihal467** [comment]
vkwepvke

@Sandra3657 Still the overlapping is happening in the desktop view and mobile view

**Comment by Sandra3657** [comment]
Can the label be changed to this form? Its difficult to resize since the label lies outside the input div. @bodhish 
image

**Comment by nihal467** [comment]
test approved

**Pull request merged**
