### PR TITLE
Added new UI to log additional details in PressureSore

### LINKED ISSUE #3432: Pressure Sore: Enhancement (PUSH score)
In the pressure sore section (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/779a961f-9045-4a1f-b996-d4af459d7c59/update)

Instead of simply marking the intensity of the pressure sore on a scale of 5, we should introduce the PUSH score to assess a pressure sore. Each pressure sore on the body must be independently evaluated. 

So each selected section must have a separate pop-up window with the PUSH score.

PUSH score is calculated based on 3 parameters:
1 (a): Length (b): Width - Both these parameters will be collected in CMs with decimal places up to 1. 
2. Exudate Amount: Dropdown [ None, Light, Moderate, Heavy]
3. Tissue Type: Dropdown [ Closed, Epithelial tissue, Granulation Tissue, Slough, Necrotic tissue]

Once the user adds these parameters, the system must automatically assign scores to these inputs and calculate a total score to be shown in the UI. 

The scoring will be based on the below table:
Screenshot 2022-08-19 at 8 01 46 PM

To help the user give better input for the three parameters, The following explanation may be shown near the input fields
Screenshot 2022-08-19 at 8 07 43 PM

There must also be a description field (long text field) to give additional details about each of the pressure sore.

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #3432 

## Proposed Changes

- Added new UI to log additional details in PressureSore 

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar 
image
unable to scroll and use it in responsive view

**Comment by nihal467** [comment]
@khavinshankar 
image

- [x] the push score is so close to the buttons, can anything be done to that in the mobile view

image

- [ ] in the summary page, how to view this push score, as of now, cant find anything saying about push score
- [x] merge the latest development branch

**Comment by khavinshankar** [comment]
@nihal467 

> @khavinshankar image
> 
> * [x]  the push score is so close to the buttons, can anything be done to that in the mobile view

That is already fixed, try hard refresh or try it in incognito tab


> image
> 
> * [ ]  in the summary page, how to view this push score, as of now, cant find anything saying about push score

let's make this a new issue, so that this can be pushed out

> * [x]  merge the latest development branch
done

**Comment by nihal467** [comment]
test approved

**Pull request merged**
