### PR TITLE
Print Preview for Report Table

### PR DESCRIPTION
**Pull request by sam9111**
Screenshot 2021-05-28 at 9 42 01 PM

Now, this is the print preview of the report table in the investigation summary for a patient.

### CODE REVIEW

**Comment by sam9111** [comment]
Is there any other information to be included in the print preview? @aparnacoronasafe @bodhish

**Comment by nihal467** [comment]
test approved

**Review by bodhish — APPROVED** [review]
LGTM

**Comment by bodhish** [comment]
Can you resolve merge conflicts

**Pull request merged**
