### PR TITLE
Switch to ButtonV2 for Location and Bed management

### LINKED ISSUE #4042: Use custom button in location management and bed management page for consistency
**Describe the bug**

- [ ] buttons are not consistent in the add location management page 
- [ ] buttons are not consistent in the add bed page

**To Reproduce**

- https://care.coronasafe.in/facility/9a96c9d3-1ae6-4a69-ad1e-162d0e318d31/location/add
- https://care.coronasafe.in/facility/9a96c9d3-1ae6-4a69-ad1e-162d0e318d31/location/39ab5730-e113-410f-8273-816c5e7a1dad/beds/add

**Expected behavior**

use the custom button in add location management page and bed page

**Screenshots**

image
image

### PR DESCRIPTION
**Pull request by Ashesh3**
## Proposed Changes

- Fixes #4042
- Switch to the new Tailwind button for consistency

image
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Use unicons instead of material ui icons

**Comment by nihal467** [comment]
@Ashesh3 
image

both the buttons are misaligned with cancel button

**Comment by Ashesh3** [comment]
> @Ashesh3 image
> 
> both the buttons are misaligned with cancel button

Fixed.

image

image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
