### PR TITLE
Fix #8858: Allow decimal places for pCO2, pO2,. Fix #8859: Add additional unit of measure for pCO2 and pO2.

### LINKED ISSUE #8858: Allow Decimal places to ABG parameters (Pco2 , Po2 and pH)
**Describe the bug**
Need to allow two decimal places to Pco2 and Po2 parameters on ABG, currently on the input field its showing as decimal places are allowed but when you enter values with decimals and submit, its throwing the error saying decimal values are not allowed.
usually these two above mentioned parameters are with two decimal places. But for pH  it should be three decimal places.

Image

**To Reproduce**

1. Go to patient card
2. Click on log update and select round type as Detailed Update
3. select Arterial Blood  Gas analysis parameter
4. update the values to Pco2 , Po2 and pH fields with decimal places and submit
5. see the error

**Expected behavior**

- [ ] Allow Pco2 and Po2 fields to accept two decimal places. 
eg:) Pco2 : 29.81 

Image

- [ ] Allow pH field to accept values with three decimal places
eg:) pH: 7.499

Image

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #8859: Add another unit of measure to Pco2 and Po2 fields on ABG analysis
**Is your feature request related to a problem? Please describe.**
Currently there is only one unit of measurement is available to the fields "Pco2 and Po2" on Arterial Blood Gas analysis parameter on Detailed round type (mmHg). But there is another unit is also commonly used for the same, ie "kPa" . 
Image
Image

- [ ]  Add the other unit  "kPa" to the fields
- [ ] Allow switch between "mmHg to kPa" units  ( make it switchable option like Fahrenheit to Celsius on Temperature field)  this makes the users to select the unit of measure which they are using on their ABG results.
- [ ] The Normal Range for Pco2 and po2 are;
     pCO2: 5.1 to 5.6 kPa
     pO2: 10.5 to 13.5 kPa

- [ ] Min and Maximum unit range should be 0 - 20 kPa 

- [ ]  Allow two decimal places for the same (refer the related issue for more on this point https://github.com/ohcnetwork/care_fe/issues/8858)

### PR DESCRIPTION
**Pull request by abhip161**
## Proposed Changes

Fix #8858: Allowed decimal places for pCO2, pO2, and pH, enabling more precise input values.
Fix #8859: Added the option to switch units for pCO2 and pO2 between kPa and mmHg on ABG analysis fields.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Introduced functions for converting pressure measurements between mmHg and kPa.
	- Enhanced the `ABGAnalysis` component to support multiple unit options and conversion functions.

- **Improvements**
	- Adjusted field properties in the `ABGAnalysis` component for better flexibility and usability.
	- Made the `PropsWithUnits` type publicly accessible for broader use in other components.

- **Bug Fixes**
	- Updated min/max values and step values for specific fields to ensure accurate data entry.

### CODE REVIEW

**Comment by samholics** [comment]
- [ ] Decimal places are autocompleting. 
eg: when I type 96 and decimal as 2 it automatically completes to 20. not able to enter second place decimal.
- [ ] not able to clear input if decimal places are typed in
- [ ] max unit mentioned on wrong input message should be proper
image

- [ ] cannot increase or decrease decimal values using upward and downward arrows in the field box.

**Comment by nihal467** [comment]
image

- [ ] the values are not being accepted at all

image

- [ ] if you are adding additional units, along with reflection of the data in events, view details page of the log update and abg section, the units are also shown along with the data

**Comment by nihal467** [comment]
@abhip161 what is the status on this PR

**Comment by Jacobjeevan** [comment]
@abhip161 Any updates on this?

**Comment by nihal467** [comment]
@abhip161 what is the status on this PR

**Comment by Jacobjeevan** [comment]
Since Abhishek hasn't replied in 3 weeks, I'm gonna go ahead and take over 👍

**Pull request closed without merging**
