### PR TITLE
Added "No Medical Found" on patients page & uniformity on Update Patient Page Issue#2585

### LINKED ISSUE #2585: Showing empty space instead of "No Medical" in the medical section
- [x] https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/5d34f7a4-1a82-481b-aeb7-6ab670c02e20

Screenshot (343)

- [x] The Allergy Input field is not uniform

https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/5d34f7a4-1a82-481b-aeb7-6ab670c02e20/update
Screenshot (344)

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #2585 
Screenshot (346)
Screenshot (345)

### CODE REVIEW

**Comment by nihal467** [comment]
@Pranshu1902 @gigincg deploy preview is failed

**Review by developedBySJ — APPROVED** [review]
LGTM

**Comment by rithviknishad** [comment]
@Pranshu1902 deploy preview is failing. merge the latest develop branch.

**Comment by nihal467** [comment]
test failed, 
error

- when we are filling with allergies only, the error occurs 
- reduces the size of no medical 
- is it better to change the "no medical" to "no medical history available". what is your opinion @gigincg

**Comment by Pranshu1902** [comment]
Updated view 
Screenshot (363)

**Comment by Pranshu1902** [comment]
> test failed, error
> 
>     * when we are filling with allergies only, the error occurs
> 
>     * reduces the size of no medical
> 
>     * is it better to change the "no medical" to "no medical history available". what is your opinion @gigincg

Is the font better now?

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
