### PR TITLE
Add Uptime tracking to Location Management

### PR DESCRIPTION
**Pull request by Ashesh3**
This pull request adds the functionality to track the uptime of locations in the Location Management component. It includes changes to the AssetManage and Uptime components, as well as the api file.

image

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@Ashesh3 clear the merge conflict

**Comment by Ashesh3** [comment]
> @Ashesh3 clear the merge conflict

cleared

**Comment by nihal467** [comment]
@Ashesh3 
image

the UI is breaking

**Comment by Ashesh3** [comment]
> @Ashesh3 image
> 
> the UI is breaking

Hey, fixed.

image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
