### PR TITLE
Add support for freeflow text in Referred To Facility

### LINKED ISSUE #4876: Referred to another hospital- capture to which hospital
**Is your feature request related to a problem? Please describe.**
When a patient is referred to another hospital, the same is noted in the "Decision after Consultation" field in the consultation form (https://care.coronasafe.in/facility/7ab27974-32c8-4e36-bdf9-dbf102524718/patient/36cdd810-c3e1-45dd-993c-2877a46e35de/consultation/48f289bb-8ae2-46d8-b6b1-4840fa6f2385/update)

Currently, when this is done, a field for "Referred to Facility" comes up with a dropdown to select other hospitals registered with CARE.

But what if the patient is actually referred to a hospital outside of the CARE network? How do you capture the data? 

**Describe the solution you'd like**
Add an option in the dropdown in "Referred to Facility" for "Others" and then a short free text space for the user to type in the name of the hospital.

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #4876 
Backend PR: https://github.com/coronasafe/care/pull/1228

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 the backend is merged , clear the merge conflict and prep it for testing

**Comment by nihal467** [comment]
@Ashesh3 
image

- [ ] The droplist has unwanted spacing between the list and text field

image

- [ ] the IP field and referred to another facility text fields are close, can you add spacing in between the fields

**Comment by Ashesh3** [comment]
@nihal467 fixed the issues.

image

image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
