### PR TITLE
Added User info in Consulation Update card

### LINKED ISSUE #1712: Consultation update: user
Make visible the user that enters each consultation update

### PR DESCRIPTION
**Pull request by Apurva-Nagar**
Adds user created by and updated by information to Update cards visible on the View Consultation page.

image

fixes #1712

### CODE REVIEW

**Comment by nihal467** [comment]
wkgoerfk

@Apurva-Nagar in mobile view it look's okay, but in desktop view, it is showing a lot of spacing

**Comment by Apurva-Nagar** [comment]
> 
> 
> wkgoerfk
> 
> @Apurva-Nagar in mobile view it look's okay, but in desktop view, it is showing a lot of spacing

Hey Nihal, could you please tell the user for which this was happening in staging, because there seems to be no problem with styling on my and @abhinandanarya06 systems.

### Desktop View
image

**Comment by nihal467** [comment]
@Apurva-Nagar simply save log update without data(simply mark the category) and you will see the large space

**Comment by Apurva-Nagar** [comment]
@nihal467 Tried, still fine on my end.
image

Can you share the Patient on which this is happening, I'll check once more then.

**Comment by nihal467** [comment]
test approved

**Pull request merged**
