### PR TITLE
Add Brand Color

### LINKED ISSUE #210: Have a brand color
**Is your feature request related to a problem? Please describe.**

It would be great if the platform has a brand color!

Currently, the site is using default color for all Input boxes and buttons

Screenshot

It would be cool if the button is applied with some brand color!

### PR DESCRIPTION
**Pull request by yohix**
Here are some screenshots

Screenshot

Screenshot

Closes #210

### CODE REVIEW

**Comment by SandeepThomas** [comment]
@yohix we are using tailwind css as well. can you make both material and tailwind use similar color theme?

**Comment by yohix** [comment]
@SandeepThomas I answered here https://github.com/coronasafe/care_fe/issues/210#issuecomment-609828979

**Comment by yohix** [comment]
@SandeepThomas The site uses color only in border, I added it in App.scss file

Screenshot

**Comment by SandeepThomas** [comment]
@yohix i have set indigo as primary color for now, since red is confusing in case of input error which is also red.

**Comment by yohix** [comment]
💜 Thanks for **Merging** @SandeepThomas

**Pull request merged**
