### PR TITLE
Added missing badges for search based filters

### LINKED ISSUE #1555: Add missing badges for search based filters
Some search based filters are not having badges, 

- [x] In `Facilities`, `Facility / District Name` filter
- [x] In `Assets`, `Asset Name` filter
- [x] In `Sample Test`, `Name` filter
- [x] In `Sample Test`, `District Name` filter
- [x] In `External Result`, `Name` filter
- [x] In `External Result`, `Phone Number` filter

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #1555 

Added following Badges:

- [x]  In Facilities, Facility / District Name filter
- [x]  In Assets, Asset Name filter
- [x]  In Sample Test, Name filter
- [x]  In Sample Test, District Name filter
- [x]  In External Result, Name filter
- [x]  In External Result, Phone Number filter

### CODE REVIEW

**Comment by nihal467** [comment]
test failed,

Case 1 :

erro 2

the alignment is not proper in the facility, assets, and sample test

Case 2 : 

https://user-images.githubusercontent.com/57055998/125848826-10e2bbd2-b1e0-45b5-a349-0b364b6b06e9.mp4

even after removing the badge in the external result, the inputted data still remain in the box

**Comment by khavinshankar** [comment]
- Align the badges
    - [x]  in `Facilities`
    - [x] in `Assets`
    - [x] in `Sample Test`

- - [x] clear the search box when the filter is cleared

**Comment by nihal467** [comment]
bug 1

test failed, I am facing all the errors again and the multiple badge size are different now

**Comment by khavinshankar** [comment]
@nihal467 Can you try this deploy instead, https://deploy-preview-1556--care-net.netlify.app/facility

image

**Comment by nihal467** [comment]
test failed, 

Case 1:

spacing

the badge and the card is so close, can you check the spacing.

Case 2:

aspdjasd

Two badges are in two sizes

**Comment by khavinshankar** [comment]
- [x] Aligned badges in External Results
- [x] Added margins for Facilities badges

**Comment by nihal467** [comment]
bug 1
bug 2

test failed, facing same issue 

1. In facility, the badge and the card spacing need to be checked
2. In external result, the badges are in two sizes

**Comment by khavinshankar** [comment]
@nihal467 Can you try this deploy instead, https://deploy-preview-1556--care-net.netlify.app/facility

**Comment by nihal467** [comment]
test approved

**Pull request merged**
