### PR TITLE
Add pagination for dialysis and modify rhythm table ui

### LINKED ISSUE #1719: Add Missing Pagination and Modify Rhythm Table UI
Pagination has not been added for Dialysis Plots.

Also, the UI of rhythm table is different from the table in medicine and neurological monitoring.

### PR DESCRIPTION
**Pull request by Sandra3657**
Resolves #1719

Added pagination that was missing for the dialysis plots.

Also, modified the rhythm table UI to match the rest.

### CODE REVIEW

**Comment by nihal467** [comment]
test failed, 
poewfewp

the UI modification and the pagination is unable to see, !

**Comment by nihal467** [comment]
@divyagar 
pokefopwefkew
unable to see the pagination,

**Comment by Sandra3657** [comment]
Which patient is it?
It is visible in the deploy preview.

Maybe for that particular patient there is no extra data to be displayed, so there will be no pagination.

image

**Comment by nihal467** [comment]
test approved

**Pull request merged**
