### PR TITLE
Added local storage support for filters in Resources

### LINKED ISSUE #1969: Setup local Storage for the filters in Resources
When we move out of resources and come back to resources, the filters used should be still present.

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #1969 

https://www.loom.com/share/1766f04a81e84ab3abaea668e147dec5

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar @gigincg can you check the merge conflict!

**Review by Ramprakash333 — COMMENTED** [review]
useMemo would optimize the performance by reading from local storage only on initial rendering.
 
  const local = useMemo(
    () => JSON.parse(localStorage.getItem("resource-filters") || "{}"),
    []
  );

**Comment by nihal467** [comment]
test approved

**Comment by gigincg** [comment]
> useMemo would optimize the performance by reading from local storage only on initial rendering. Can you add those please.
> 
> const local = useMemo( () => JSON.parse(localStorage.getItem("resource-filters") || "{}"), [] );

@khavinshankar Can you address this?

**Comment by khavinshankar** [comment]
@gigincg made the suggested changes

**Pull request merged**
