### PR TITLE
Add Medicine Prescription Log Summary Section

### LINKED ISSUE #7354: prescription- Log of change
**Is your feature request related to a problem? Please describe.**
Currently, the medicine tab in the patient file only shows the list of active and discontinued medications. There is no log of change visible to the users. 

**Describe the solution you'd like**
Below the medicine table, add separate cards for each change made to the prescription.

Follow the design of the investigation tab where table summary is available on top and below user can click and open individual tests updated.

### PR DESCRIPTION
**Pull request by Pranshu1902**
## Proposed Changes

- Fixes #7354 
Backend PR: [2068](https://github.com/coronasafe/care/pull/2068)
Add a section of summary of Medicine Prescriptions for each consultation

image

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
image

@Pranshu1902 the dosage is shown twice in the frontend

image

- [ ] when i discontinue a prescription and add the same medicine in prn prescription, the following things are not understandable from this summary .
1. when is the medicine discontinued
2. whether its a PRN prescription or a Prescription

**Comment by Pranshu1902** [comment]
@nihal467 Updated view:
image

**Comment by nihal467** [comment]
@Pranshu1902 its still not mentioning its PRN or prescription

**Comment by Pranshu1902** [comment]
@nihal467 Added Prescription Type in the description as well
image

**Comment by nihal467** [comment]
@Pranshu1902 

image
image

- [ ] failed the test , follow the below step to replicate it : 

Step 1 : Add a dolo medicine with prescription
step 2 : Change the medicine to titrated dosage
step 3 : Discontinue the medicine
Step 4 : Add the same medicine in PRN Prescription

the medicine summary is missing the discontinue in the timeline

- [ ] when there is no summary, add a text in the bottom "no medicine summary" with white padding similar to the card we show when there is no consultation

Note: Please conduct a full QA of your PR, before marking it again for testing

**Comment by Pranshu1902** [comment]
@nihal467 done!
Updated view:

- Show Medicine Discontinued in timeline
https://deploy-preview-7584--care-egov-staging.netlify.app/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/261a9866-1366-4575-9272-6f3b5f4b3d57/consultation/77d32891-d017-431c-8b72-440ec62b7050/medicines
image

- Added a "No Medicine Summary" card for patients with no prescriptions
https://deploy-preview-7584--care-egov-staging.netlify.app/facility/997c7f30-8e2f-4d62-8b58-2a8771e658d6/patient/0b4d3cd9-9def-4c43-b4e1-9a02a0de419d/consultation/88e119f6-b841-46ef-b1af-4201d198c04b/medicines
image

**Comment by nihal467** [comment]
@Pranshu1902 
image

- [ ] For PRN prescription and prescription, the regular and PRN should be shown in the prescription type, not in the dosage type
- [ ] replace base dosage as Dosage
- [ ] in titrated dosage replace base dosage as start dosage

**Comment by Pranshu1902** [comment]
@nihal467 done
Updated view:
image

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
Approving. We could switch to rendering this from events instead in an upcoming PR.

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
