### PR TITLE
Changed add consultation button disable logic in PatientHome

### LINKED ISSUE #3058: Patient Consultation Creation : Malfunction
after readmitting a patient to a facility, the add consultation button is still greyed out, so the consultation can't be created

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #3058

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar the issue persist same

**Comment by nihal467** [comment]
@khavinshankar when we have a active consultation, the add consultation button be greyed out and when we readmit a patient, we have no active consultation, so the add consultation button should be green

**Comment by khavinshankar** [comment]
@nihal467 can you please give a patient's link where it is still going wrong

**Comment by nihal467** [comment]
@khavinshankar https://deploy-preview-3064--care-net.netlify.app/facility/273fe202-5325-4d5f-9a20-f7da9cb79e4d/patient/5aad79f2-b33f-4074-a900-0a7587b1cd55/consultation/83ab2676-b37b-4614-9ab3-8fa3d01f1a62

**Comment by nihal467** [comment]
test approved

**Review by gigincg — APPROVED** [review]

**Pull request merged**
