### PR TITLE
Add Cypress Test Suite for Facility Notice Board Functionality Verification

### LINKED ISSUE #9041: Add New Cypress Test for Verifying Notice Board Functionality
**Description**

Add a new Cypress test to verify the notice board function for sending a message.

**General Instruction**

- Use all reusable functions from the commands.ts file and other existing tests.
- To understand if a custom function used in other existing tests exists, search using their element ID in the codebase.
- Use the POM approach; refer to the Patient_Spec folder for guidance.
- Add necessary API verifications and verify notifications and text to avoid flaky tests.
- Add the new test in the FacilityHomepage.cy.ts file and create a new file FacilityNotify.ts in the pageobject folder

**Context About Notice Board**

This feature is used exclusively by the admin to send messages to facilities through the platform. The message will be received by all linked IDs, but they will not be able to reply to it.

**Workflow Of the Notice Board**

- Log in as a district admin, load the page, and search for the facility "dummy facility 40".
- Assert the text in the facility card for the facility name and the visibility of the notify board button.
- Click on the notify button and verify the pop-up displays the facility name from the card.
- Without typing anything, click on the notify button and verify it throws a front-end error since the field is blank.
- Click the cancel button and verify the pop-up is closed.
- Click the notify button again, type a message, and send it.
- Once the message is sent, verify the necessary API is triggered using cy.intercept, and verify a notification is shown using cy.verifyNotification.
- Log out, log in as dummynurse1, load the page, and open the notice board from the sidebar.
- Verify the sent message is present in the notice board, then click on notifications from the sidebar and verify the message is present there as well.

Note: Note: Once the test is built, remove the two lines where we verify the notify button redirection in the existing test, "Verify the facility card button function."

### PR DESCRIPTION
**Pull request by JavidSumra**
## Proposed Changes

- Fixes #9041
- Added Cypress test to verify the notice board functionality for sending messages.
- Created `FacilityNotify.ts` in the pageobject folder following the POM structure.
- Implemented API verification and notification checks to ensure reliable test execution.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Release Notes

- **New Features**
	- Enhanced end-to-end testing for facility notifications, including verification of the notice board functionality.
	- Introduced a new class for managing facility notifications, improving interaction with the notification system.

- **Improvements**
	- Added optional `id` properties to various components for better accessibility and targeting.
	- Updated notification message rendering for improved identification within the UI.
	- Enhanced visibility checks for the facility notify button to improve interaction reliability.
	- Improved facility search operations with request interception and response verification.

- **Bug Fixes**
	- Improved user session management with a new sign-out method in the login process.

### CODE REVIEW

**Comment by nihal467** [comment]
@JavidSumra your test is failing on actions

**Comment by JavidSumra** [comment]
Yup but it's passing on the local environment can you please provide images of that if possible @nihal467

**Comment by nihal467** [comment]
image

- [ ] its failing in my local, recheck your PR

**Comment by JavidSumra** [comment]
Ok sorry I'll check it again.

**Comment by JavidSumra** [comment]
Hey @nihal467 as you can see below all test cases are passing in my local environment can you please guide me what should I do next?
image
if possible can you please provide a video or failure point?

**Comment by JavidSumra** [comment]
Hey @nihal467, could you help me debug this issue? I'm new to this and would really appreciate your guidance. I've tried multiple solutions, but it's still not passing in GitHub CI. Thank you!

**Comment by JavidSumra** [comment]
Hey @nihal467 I tried so many solutions can you please guide me what should I do to correct this test suit behavior?

**Comment by JavidSumra** [comment]
Hey @nihal467, it seems like you've already fixed this issue. Could you please let me know what changes you made?

**Review by nihal467 — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Comment by JavidSumra** [comment]
Hey @rithviknishad can you please assign 2 story points for this.
cc : @nihal467

**Pull request merged**
