### PR TITLE
Added an alert when no CSV file is uploaded in Upload External Results Page.

### LINKED ISSUE #2678: No alert is shown when no CSV file is selected and save button is clicked
# Bugs

## No alert is shown when no CSV file is selected and the save button is clicked
https://user-images.githubusercontent.com/59426397/173178952-74144482-44d1-4e93-a999-00acacb07f17.mp4

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2678 

# Bugs

## Added an alert when no CSV file is uploaded to Upload External Results Page.
https://user-images.githubusercontent.com/59426397/173220063-42853754-3124-46c5-83fe-18c91e17f95a.mp4

### CODE REVIEW

**Comment by patelaryan7751** [comment]
Deploy Preview Ready https://deploy-preview-2689--care-net.netlify.app/

**Review by skks1212 — APPROVED** [review]

**Review by developedBySJ — CHANGES_REQUESTED** [review]
@patelaryan7751 Can you work on UI?
Align the button properly.

**Comment by patelaryan7751** [comment]
Hey @developedBySJ , I have improved  the UI
image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@patelaryan7751 just a suggestion, usually in care we have all of the action buttons to the right especially in forms, so I think it would be better if the button is right aligned instead of the center, 🤔  what do you think?

**Review by cp-Coder — APPROVED** [review]

**Comment by patelaryan7751** [comment]
> @patelaryan7751 just a suggestion, usually in care we have all of the action buttons to the right especially in forms, so I think it would be better if the button is right aligned instead of the center, thinking what do you think?

@khavinshankar I think it would look odd as there is only one input field but if you want I can do it :)

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
