### PR TITLE
Fix(cypress): Patient spec test

### LINKED ISSUE #4233: Cypress: New Patient Creation

### LINKED ISSUE #4234: Cypress: Update Existing Patient

### LINKED ISSUE #4235: Cypress: Add doctor's note to a patient page

### PR DESCRIPTION
**Pull request by rabilrbl**
## Proposed Changes

- Fixes #4233 
- Fixes #4234 
- Fixes #4235 
- Fix patient creation, update
- Add test for doctor notes 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar can you check this PR

**Comment by nihal467** [comment]
@rabilrbl check the cypress

**Comment by nihal467** [comment]
@rabilrbl what is the status on this PR

**Comment by nihal467** [comment]
@rabilrbl check the cypress and once it is fully ready for testing, mark it for testing

**Comment by nihal467** [comment]
@rabilrbl what is the status of the PR

**Comment by rabilrbl** [comment]
The patient crud from multiple user type is failing. 

The backend docker image doesn't have these new user credentials. 

cc: @GokulramGHV

**Comment by rabilrbl** [comment]
@GokulramGHV Any updates?

**Comment by nihal467** [comment]
@GokulramGHV @rabilrbl get this PR ready for testing ASAP

**Comment by nihal467** [comment]
@GokulramGHV what is the status on this PR

**Comment by khavinshankar** [comment]
@GokulramGHV can you check if this pr is still relevant now?

**Comment by nihal467** [comment]
@rabilrbl @SahilSingh177 We are re-writing the whole patient test in the POM approach, so closing this PR

**Pull request closed without merging**
