### PR TITLE
Hide Facility link and unlink button for non-admin users

### LINKED ISSUE #7604: Refactor user privileges in linked facility functionality
**Describe the bug**

- [ ] When the nurse user trying to unlink themselves from a home facility, they are not allowed to perform this action and there are multiple error thrown in the frontend, which is little bit confusing
- [ ] When the nurse user try to unlink themselves from a linked facility, they are allowed to do that action

**To Reproduce**

1. Go to user tab. and click facilities button ( With nurse user ID)
2. Click on clear the home facility icon
3. See error

**Expected behavior**

- [ ] When the nurse user trying to unlink themselves from a home facility, they should be able to do it.
- [ ] When the nurse user try to unlink themselves from a linked facility, they should be able to do it.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Pranshu1902**
## Proposed Changes

- Fixes #7604 
Hide the Facility link and unlink button for non-admin users.

Hide Clear Home Facility button:
image

Give Error notification for link and unlink buttons
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@Pranshu1902 

image

above is the current stage screenshot

image

above is the PR deployment

- the PR is not showing the home facility page, can you check into this issue and reverify the code change you made while clearing the merge conflict

**Comment by Pranshu1902** [comment]
@nihal467 resolved the conflicts
updated view:
image

**Comment by nihal467** [comment]
@Pranshu1902 
image

as per the issue, the button was suggested to be hidden, as non-admin users have no privilege to use it

**Comment by Pranshu1902** [comment]
@nihal467 Updated view:
image

**Comment by nihal467** [comment]
@Pranshu1902 blocking it for further clarification from @aparnacoronasafe

**Comment by nihal467** [comment]
@Pranshu1902 can you modify the PR based on the latest expected behavior

**Comment by Pranshu1902** [comment]
@nihal467 done
image

**Comment by nihal467** [comment]
@Pranshu1902 
image

- [ ] admin are not able to see the unlink or link button, do recheck your PR and do basic functionality check before marking it for review

**Comment by Pranshu1902** [comment]
@nihal467 done

Admin View:
image

Nurse View:
image

Nurse View for their profile:
image

**Comment by nihal467** [comment]
@Pranshu1902 

image

nurse is not able to clear his own home facility access

**Comment by Pranshu1902** [comment]
@nihal467 the backend is rejecting the request for nurse user type.

Raised a backend PR for that: [#2206](https://github.com/coronasafe/care/pull/2206)

Screenshot from 2024-05-29 13-22-05

**Comment by nihal467** [comment]
LGTM

**Comment by Pranshu1902** [comment]
@nihal467 the backend PR has been merged

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
