### PR TITLE
Integrates Medibase Medicines (Pre-optimization version)

### PR DESCRIPTION
**Pull request by rithviknishad**
- Same as #5599; Just that this branch is cherry picked from the version before optimization (https://github.com/coronasafe/care/pull/1439)

### CODE REVIEW

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
@khavinshankar @rithviknishad 
image

1. there is a badge not in proper shape
2. i search one medicine and erase it and search another medicine, the whole thing stop working

**Comment by rithviknishad** [comment]
fixed in other branch; will fix here too

**Comment by nihal467** [comment]
@rithviknishad 
image

the page itself is not loading 

cc: @khavinshankar

**Comment by rithviknishad** [comment]
medibase endpoints in staging is being profiled currently; ETA: 100 minutes

**Comment by rithviknishad** [comment]
staging will be slow

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
