### PR TITLE
Fixed: Issue in facility select during add user

### LINKED ISSUE #3159: Issue in facility select in add user
when we have selected facilities, and we focus and unfocus by clicking cursor somewhere else, the last selected facility pops out

https://user-images.githubusercontent.com/44599895/179466563-96dc090c-12f4-4310-9024-a89472c304ec.mov

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #3159
- [x] Removed `autoSelect` value for `FacilitySelect`

### CODE REVIEW

**Review by developedBySJ — COMMENTED** [review]
@cp-Coder can you create a type for autocomplete component props?

**Comment by nihal467** [comment]
@cp-Coder @developedBySJ once it done, mark it for testing

**Comment by aeswibon** [comment]
@developedBySJ I have added props for autocomplete component

**Comment by aeswibon** [comment]
@nihal467 This PR is now good for testing

**Review by Marmik2003 — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
