### PR TITLE
Disabling Push Notification subscription for iOS users

### LINKED ISSUE #1890: Error Notification Poping Up and Not able to Opening Care
photo_2021-10-07_16-19-42

when we are opening care from iPhone google chrome mobile browser, this error keep on popping up and unable to operate care

### PR DESCRIPTION
**Pull request by Apurva-Nagar**
- Using `userAgent` to check for iOS devices (iPad, iPhone, iPod). 
- Disabling `subscribe` button and not fetching `initialSubscriptionState` if device is an iOS device.

### CODE REVIEW

**Comment by nihal467** [comment]
@Apurva-Nagar @gigincg  test failed, when we are opening assets tab, it is showing something went wrong

**Comment by nihal467** [comment]
test approved

**Comment by developedBySJ** [comment]
@Apurva-Nagar Getting error on iPad

**Comment by nihal467** [comment]
@khavinshankar @developedBySJ @gigincg what is the status of the PR

**Comment by mathew-alex** [comment]
:wave: Hi, @Apurva-Nagar,
Conflicts have been detected against the base branch. Please rebase your branch against the base branch.

***

This message is automatically generated by [prince-chrismc/label-merge-conflicts-action](https://github.com/prince-chrismc/label-merge-conflicts-action) so don't hesitate to report issues/improvements there.

**Pull request closed without merging**
