### PR TITLE
Enabled multiselect in diagnosis in ConsultationForm

### LINKED ISSUE #3506: ICD-11: Multi Select
The diagnosis field in consultation is not enabled with ICD-11 seach. 

Enable multi-select

### PR DESCRIPTION
**Pull request by khavinshankar**
## Proposed Changes

- Enabled multiselect in diagnosis

Fixes #3506 

Screenshots
image
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [x] Completion of QA

### CODE REVIEW

**Comment by khavinshankar** [comment]
Only 3 diagnosis is shown initially, but can be expanded to show others, also there might be 1 extra in the initial showing, which shows the old diagnosis data.
image
image

**Comment by khavinshankar** [comment]
@nihal467 can you test this pr, so that it can be merged for today's release

**Comment by nihal467** [comment]
@khavinshankar LGTM, but cypress is failing

**Comment by nihal467** [comment]
@khavinshankar 
image

image

multiple cypresses is failing, can you correct this, before merging this PR

**Comment by nihal467** [comment]
@khavinshankar check the message in the slack GDC channel and can you merge the latest development branch to this PR

**Comment by khavinshankar** [comment]
@nihal467 sure, I'll check that out

**Review by gigincg — APPROVED** [review]

**Pull request merged**
