### PR TITLE
Add sorting by declared status

### PR DESCRIPTION
**Pull request by smartclash**
Co-authored-by: Arpan Abhishek <arpanforbusiness@gmail.com>

### CODE REVIEW

**Comment by bodhish** [comment]
@smartclash is this good to merge?
(The status is still draft)

**Comment by smartclash** [comment]
@bodhish, we're still waiting for a small API change from @vigneshhari https://github.com/coronasafe/care_fe/issues/813#issuecomment-843128758

**Comment by arpancodes** [comment]
@bodhish Added DateRangeField component for date declared positive, completing the issue requirement

**Review by bodhish — CHANGES_REQUESTED** [review]
Use prettier to format code. We use `"` instead of `'`

**Comment by arpancodes** [comment]
@bodhish done

**Comment by samholics** [comment]
tested, failed

**Comment by arpancodes** [comment]
@samholics Fixed! Please test again :)

1.
patient_adv_filter

2.
patient_declared_positive

**Pull request merged**
