### PR TITLE
Adjusted SpO2 thresholds and labels in DailyRounds component to match medical standards

### LINKED ISSUE #9102: Adjust SpO2 thresholds and labels in DailyRounds component to match medical standards
We need to update the SpO2 thresholds and labels in the DailyRounds component to better align with medical standards.

This issue was identified during PR review: https://github.com/ohcnetwork/care_fe/pull/8907

Related comment by @rithviknishad: https://github.com/ohcnetwork/care_fe/pull/8907#discussion_r1838456697

@rithviknishad

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #9102 

@ohcnetwork/care-fe-code-reviewers
@rithviknishad 

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Updated labels for the `ventilator_spo2` input field to enhance clarity, now displaying "Severe Hypoxemia," "Moderate Hypoxemia," "Mild Hypoxemia," and "Normal."
	- Added new localization entries for SpO2 levels to improve user interface descriptions.

- **Bug Fixes**
	- Ensured that the validation logic remains intact for the form fields prior to submission.

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
keep texts in i18n locale files

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Why was things changed for `resp` field? Changes only need to be there for SpO2 field right?

**Comment by AdityaJ2305** [comment]
> Why was things changed for `resp` field? Changes only need to be there for SpO2 field right?

my bad,  fixed it

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad, I noticed the spo2 field component is written twice, and I’ve updated the thresholds for one instance. Should I raise another PR tagging the same issue number to address this?

**Comment by AdityaJ2305** [comment]
Hey @rithviknishad, I noticed the spo2 field component now appears twice, but previously it was just one instance. The other instance seems to have been added by another [PR](https://github.com/ohcnetwork/care_fe/pull/8907#issuecomment-2482840851) Should I raise a new PR tagging the same issue number to address this?

cc: @Jacobjeevan

**Comment by Jacobjeevan** [comment]
> Hey @rithviknishad, I noticed the spo2 field component now appears twice, but previously it was just one instance. The other instance seems to have been added by another [PR](https://github.com/ohcnetwork/care_fe/pull/8907#issuecomment-2482840851) Should I raise a new PR tagging the same issue number to address this?
> 
> cc: @Jacobjeevan

Go ahead and raise an issue. Remove the Textformfield and ensure thresholds labels in RangeAutocompleteFormField match the latest changes.

**Pull request merged**
