### PR TITLE
feat: revamp location management page, improve responsiveness

### LINKED ISSUE #2477: Location management page is not mobile responsive
image

### PR DESCRIPTION
**Pull request by naman114**
Fixes #2477

- Revamped the design of the Location Management page. 
- Replaced the existing table with a list view to improve responsiveness on mobile screens. 
- Created a separate route to edit a location's details, replacing the current method of updating the values in the table itself

https://user-images.githubusercontent.com/57593654/174405549-4a1f08c5-a63f-47c3-b9a7-afcbfac54f0d.mp4

 Update:
- Made the add/update location form a single column in desktop view (like the Edit Consultation page)
- Upon creating a new location, the form will now redirect to the Location list view instead of the Add Bed form

https://user-images.githubusercontent.com/57593654/174451642-f44e6643-c528-4f02-b258-e2c043060f9a.mp4

### CODE REVIEW

**Comment by nihal467** [comment]
@naman114 



test failed, the content is overlapping the button

**Comment by naman114** [comment]
Fixed the special case of text overflow for very long words @nihal467 

image

**Comment by nihal467** [comment]
14a


@naman114 can you keep the details is 3 sections itself, like the one i wrote in the screenshot

**Comment by naman114** [comment]
Modified the design to 3 column view @nihal467 

image

**Comment by nihal467** [comment]
26a

@naman114 the buttons on right feel like misaligned and dragged downwards, can you lift the buttons a bit

**Comment by naman114** [comment]
Fixed the button alignment @nihal467 

image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
