### PR TITLE
Upgrade to mui v5

### LINKED ISSUE #2380: Replace react-dates with material ui date picker
replace with mui; https://mui.com/x/react-date-pickers/date-range-picker/#main-content

### LINKED ISSUE #2424: Upgrade material-ui to to v5

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #2424
- [x] Fixes #2380
- [x] Upgraded to mui v5
- [x] Updated code to support mui v5

### CODE REVIEW

**Comment by aeswibon** [comment]
@nihal467 Sorry by mistake that PR was closed. I was going to checkout the PR but instead accidentally closed the PR.

**Comment by aeswibon** [comment]
@nihal467 Can you tell me why you added the "test-failed" label before??

**Comment by aeswibon** [comment]
@nihal467 Merged the develop branch. This PR is good for testing.

**Comment by nihal467** [comment]
17a
17b
17c

@cp-Coder  test failed

- [ ] address in facility create page starting from the second line
- [ ] the latitude and longitude are off the alignment
- [ ] patient page is misaligned
- [ ] update button color not working in inventory management
- [ ] description in the add location is starting from second line

**Comment by nihal467** [comment]
@cp-Coder what is the status

**Comment by aeswibon** [comment]
# Updates

- [x] address in facility create page starting from the second line
- [x] the latitude and longitude are off the alignment
- [x] patient page is misaligned
- [x] update button color not working in inventory management
- [x] description in the add location is starting from second line

**Comment by nihal467** [comment]
@cp-Coder can you check the merge conflict

**Comment by nihal467** [comment]
@cp-Coder can you check the merge conflict

**Pull request closed without merging**
