### PR TITLE
feat: create, retrieve and delete skills of users from users tab

### PR DESCRIPTION
**Pull request by Pragati1610**
fixes https://github.com/coronasafe/care_fe/issues/4248

### CODE REVIEW

**Comment by nihal467** [comment]
@Pragati1610 
image

- the UI is a little bit confusing because it looks similar to the old linked facility

image

- the three skills are by default applied to all the users across the platform, it doesn't feel good
- there is no data in the droplist, for user to select it

**Comment by nihal467** [comment]
@Pragati1610 once its completely fixed, mark it for testing

**Comment by nihal467** [comment]
@Pragati1610 check the merge conflict

**Comment by nihal467** [comment]
@Pragati1610 
image

- when you are adding a skill for a user, it is been getting added to all the user across the platform

**Comment by nihal467** [comment]
@Pragati1610 what is the status on this PR

**Comment by khavinshankar** [comment]
@nihal467 i have made some changes, I'll push it shortly (around 3pm today)

**Comment by khavinshankar** [comment]
@Pragati1610 resolve the merge conflict

**Comment by nihal467** [comment]
@Pragati1610 @khavinshankar 
image

when you add a skill for a user id, the skill is been added to all the users

**Comment by khavinshankar** [comment]
@Pragati1610 any reasons for force pushing?

**Comment by khavinshankar** [comment]
@nihal467 can you retest this pr

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by Pragati1610** [comment]
> @Pragati1610 any reasons for force pushing?

Because of merge conflicts when rebased the branch

**Pull request merged**
