### PR TITLE
Prescription changes

### LINKED ISSUE #3102: Prescription: Dosage
In consultation page, https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/c3e588d5-583f-4711-907b-e3d46fb914cf/consultation/b20d8c85-51b6-4835-b729-db216b1e8190/update

The consultation module currently has Medicine (name), dosage and days.
Screenshot 2022-07-11 at 6 20 49 PM

Make the following changes 

- [ ] Rename the "dosage" into "Frequency"
- [ ] Add a new field called "dosage" with a small text field to allow input of 3 digit number followed by Unit options in drop-down. The options would be mg, ml, drops. 

**Why are we doing this?**  Dosage ideally is the strength of the medicine- eg: The doctor wants to prescribe Dolo 650mg to the patient to take once a day. Here the medicine is "Dolo/Paracetamol", Dosage is 650mg, and the frequency is Once a Day (OD). 

An indicative design of the prescription section is as follows. The other features in the prescription are taken care of in subsequent issues. 
Screenshot 2022-07-11 at 9 05 14 PM

### LINKED ISSUE #3104: Prescription- Route
In consultation page, https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/c3e588d5-583f-4711-907b-e3d46fb914cf/consultation/b20d8c85-51b6-4835-b729-db216b1e8190/update

The consultation module currently has Medicine (name), dosage and days.
Screenshot 2022-07-11 at 6 20 49 PM

Make the following changes 

- [ ] Add a field for "Route" with dropdown option- "Oral, IV, IM, S/C"

An indicative design of the prescription section is as follows. The other features in the prescription are taken care of in other issues. 
Screenshot 2022-07-11 at 9 05 14 PM

### LINKED ISSUE #3105: Prescription- Notes
In consultation page, https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/c3e588d5-583f-4711-907b-e3d46fb914cf/consultation/b20d8c85-51b6-4835-b729-db216b1e8190/update

The consultation module currently has Medicine (name), dosage and days.
Screenshot 2022-07-11 at 6 20 49 PM

Make the following changes 

- [ ] Add a field for "Notes" with text field to accommodate 100 (approx) characters.

An indicative design of the prescription section is as follows. The other features in the prescription are taken care of in other issues. 
Screenshot 2022-07-11 at 9 05 14 PM

Feel free to make design amendments to give enough space for Notes

### PR DESCRIPTION
**Pull request by skks1212**
closes #3105
closes #3104 
closes #3102
image

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 
image

- [ ] it will be hard to read the notes typed, can we have any alternative?

**Comment by shivankacker** [comment]
> @skks1212 
> image
> 
> - [ ] it will be hard to read the notes typed, can we have any alternative?

@nihal467 There is going to be an addition to this PR, I will change the UI

**Comment by nihal467** [comment]
@skks1212 
image

- [ ] remove the blue colour border and change it to green border

image

- [ ] MAKE IT RESPONSIVE

**Comment by nihal467** [comment]
test approved

**Comment by nihal467** [comment]
@skks1212 test failed,


image

- [ ] restrict the numbers to 0 and +ve number **( Consultation Page )**

image

- [ ] unable to read the medicine name fully, in the mobile view **( Consultation Page )**

**Comment by nihal467** [comment]
@skks1212 

image

make the prescription in the critical care, responsive

**Comment by nihal467** [comment]
@skks1212 
image

- [ ] make it responsive, unable to view the dosage, both in consultation and critical care

[screen-capture.webm](https://user-images.githubusercontent.com/57055998/181722208-5080b2a8-354c-4d4b-bace-2771788d646a.webm)

- [ ] unable to update a consultation file, by inputting medicine data to it

**Comment by shivankacker** [comment]
@nihal467 I have made new changes. Regarding the form not submitting issue.. I think it was because you did not enter the admission date which was required.

**Comment by nihal467** [comment]
@skks1212 
image

when I keep a blank medicine column and save it,( Critical Care ) it is been saved, which is causing the below problem 

image

**Comment by nihal467** [comment]
@skks1212 

image

- [ ] Choose one alignment for both, by checking the effective utilization of space
- [ ] consultation update is having all the heading and data having grey, make it black

**Review by gigincg — APPROVED** [review]

**Pull request merged**
