### PR TITLE
[Bed revision] Switching UI

### PR DESCRIPTION
**Pull request by arpancodes**
- [x] Created form to change bed for the consultation
- [x] Created Table to show the previous beds associated to the consultation.

### CODE REVIEW

**Comment by gigincg** [comment]
@arpancodes Merge develop into the branch

**Comment by samholics** [comment]
test failed, not able to change or select bed from "edit consultation details" @arpancodes

**Comment by arpancodes** [comment]
@samholics moved the component inside "edit consultation details".

**Comment by arpancodes** [comment]
moved below patient name.
image

**Comment by nihal467** [comment]
wlefwef'

@arpancodes @gigincg even after I move the patient from the existing bed, it is saying, it is in use

**Comment by nihal467** [comment]
test approved

**Pull request merged**
