### PR TITLE
Updated UI for Patient info card. Also shifted patient discharge buttons under the info card

### LINKED ISSUE #2316: Discharge and Discharge Summary
The "Discharge Summary" and "Discharge from CARE" buttons on the Patients details page (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0) needs to move to the patient dashboard (https://care.coronasafe.in/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/76742faa-30dd-4eb9-9649-fe718f947ec0/consultation/2ad89b7c-7bff-4035-a3c6-36d53551a8f0)

The arrangements of the components may be altered to look like the below:
Screenshot 2022-05-12 at 10 55 24 AM

### LINKED ISSUE #2405: Update UI for patient info card buttons
Current UI is not so user friendly

### PR DESCRIPTION
**Pull request by skks1212**
closes #2316
closes #2405 

image
image

Reduced card height as much as possible.

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 @gigincg the deploy preview is failed

**Comment by rithviknishad** [comment]
@skks1212 deploy preview is failing. merge the latest develop branch.

**Comment by nihal467** [comment]
@skks1212 @gigincg can you align the right side and left side equally on the top and bottom? I feel it is in a different alignment, what are your opinions!

**Comment by shivankacker** [comment]
@nihal467 I feel we should not center align it as per design. If you say we should, il add a commit, but I personally think this looks better and more "profiley"

**Comment by nihal467** [comment]
@skks1212 @gigincg I meant to bring the left side a little bit lower so that it is aligned with the right side

**Comment by shivankacker** [comment]
@nihal467 changes done

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
@skks1212 please do work on the merge conflict

**Comment by shivankacker** [comment]
> @skks1212 please do work on the merge conflict

@khavinshankar done

**Comment by khavinshankar** [comment]
@skks1212 please do check out the deploy issue and also do work on the merge conflict

**Comment by khavinshankar** [comment]
@skks1212 can you please check this out,
image
the build is failing because of this

The problem most likely is there is no onClick in RoleButton component, maybe named different

**Comment by shivankacker** [comment]
@khavinshankar hopefully that solves it.

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
