### PR TITLE
Added consent indicators and filters

### LINKED ISSUE #7972: flag on patient live encounter with no consent for admission
Live Encounters , marked as admitted must have at least 1 consent for admission filed.

Wherever that is not the case,

- [ ] Have flag in red appear on live patient list (add a blinker to the flag: eg: look at flag for no consultation filed)
- [ ] Add flag to patient dashboard

Good to have:

- [ ] On live patient list, Add a card citing "24 patients admitted without consent" on top in red. When clicked only the patient files with no consultation must appear. It must applied as a filter. user to have option to remove the filter by closing the filter flag

### LINKED ISSUE #7993: Improvements to Consent Records
> Explore the possibility of Joining Applicable Files with the Consent Records on the backend
> Explore the possibility to Associate Files to consentRecord State, rather than using a separate state for consent and files
> Can be rendered when consentRecords Load, and the Card can be further enriched with files ones that's available in the state

Follow up from comments from @gigincg https://github.com/coronasafe/care_fe/pull/7946#discussion_r1629507818

### PR DESCRIPTION
**Pull request by shivankacker**
Dependent on https://github.com/coronasafe/care/pull/2255

## Proposed Changes

- Fixes #7972
- Fixes #7993

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Screenshots
Screenshot 2024-06-09 at 5 03 49 AM
Screenshot 2024-06-09 at 5 04 10 AM

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA

### CODE REVIEW

**Comment by aparnacoronasafe** [comment]
@skks1212 The message on patient list "16 patients admitted without consent" may be edited to say "16 patients admitted missing consent records"

**Comment by nihal467** [comment]
@skks1212 
image
image


- [ ] in the badge we mention None, and in the advance filters, the dropdown mention the option as no consents, keep it consistent, in both places

image

- [ ] if a user have multiple facility access and use the advance filter in the patient tab to view only patient list of a particular facility, during this scenario, the missing consent banner count should also filter along with it to just show missing consent of that particular facility.

similar, user apply any advance filter, in the patient tab, it should filter the missing patient consent banner based on that

**Comment by shivankacker** [comment]
@nihal467, are you sure the filters apart from facility filters should change the number shown in the alerts? I believe it is to show patients in that facility (or everywhere) that have no consents regardless of filters. @aparnacoronasafe can you confirm?

**Comment by aparnacoronasafe** [comment]
The experience is better when the number on alert responds to all filters. 

If user applies a filter with list showing on 2 results but alert on top says "10 records with no consent record" doesn't look very convincing. 

Is there challenge to make it respond to all filters? 

You are correct in saying that the need to be able to filter based on facility is not valuable in this case.

**Comment by shivankacker** [comment]
@aparnacoronasafe no challenge, just had a doubt. Made the changes

**Review by khavinshankar — COMMENTED** [review]
@skks1212 seems multiple cypress tests are failing, please fix those

**Review by rithviknishad — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
