### PR TITLE
Increase debound time for input search box

### LINKED ISSUE #1539: Lag in Search : External Results
https://user-images.githubusercontent.com/57055998/125130462-a6e18c80-e11e-11eb-8ce8-fbd2d5897308.mp4

When we edit the inputted patient name inside the search bar, there is lag.

### LINKED ISSUE #1619: Unable to Filter with Patient Name : Shift Module
https://user-images.githubusercontent.com/57055998/126768306-68a35abe-0376-4111-a626-a63272f6d690.mp4

since the page is kept on refreshing faster, unable to search the patient

### PR DESCRIPTION
**Pull request by abhinandanarya06**
357a02d0-2db7-424b-b08c-1f3439357434

closes #1619 
closes #1539

### CODE REVIEW

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
test failed, still facing the same issue

**Comment by nihal467** [comment]
@abhinandanarya06 now I feel like the system is a bit slow, can you check a bit

**Comment by ghost** [comment]
> @abhinandanarya06 now I feel like the system is a bit slow, can you check a bit

Yeah I tried with 1 second according to average best debounce time on article. We can add enter key press option but user should know that feature. Let's try with 1.2 second or something😅.

**Comment by nihal467** [comment]
@abhinandanarya06 let's try with 1.2 seconds then

**Comment by nihal467** [comment]
test approved

**Pull request merged**
