### PR TITLE
Updated blood pressure range and remove hyphen for infusion "nor-adrenaline"

### LINKED ISSUE #8397: Update range of diastolic blood pressure in detailed log update
**Describe the bug**
Currently normal log update has 0-250 as the range for both systolic and diastolic blood pressure fields. However, detailed log update has range 30-180 for diastolic and 0-250 for systolic.

(Ranges confirmed with @aparnacoronasafe)

**To Reproduce**

1. From the consultation dashboard, file a normal log update with blood pressure (observe the ranges). 
2. Also file a detailed log update, and enter vitals section. Observe the ranges for the blood pressure field.

https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/daily_rounds/06b17319-7ec3-4c56-a1f0-ffbceaa7d4a5/update

**Expected behavior**
- [x] Update range of diastolic blood pressure field in detailed log update to 0-250

**Screenshots**

image

image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Required Backends

- https://github.com/ohcnetwork/care/pull/2386

## Proposed Changes

- Fixes #8397

image

image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by bodhish** [comment]
@rithviknishad the ux assumes that not measurable is a very common scenario; do we need it? How valuable is not measurable information? Can't that be part of the notes?

CC: @gigincg @aparnacoronasafe

**Comment by aparnacoronasafe** [comment]
The layout of the short vitals form (with text box and not slider) looks very bad. 

Can we have "Not measurable" come below the text field? 

The text spaces for systolic and diastolic must come together as "____/_____"- having the checkbox come in between the field is not ideal.

**Comment by aparnacoronasafe** [comment]
> @rithviknishad the ux assumes that not measurable is a very common scenario; do we need it? How valuable is not measurable information? Can't that be part of the notes?
> 
> CC: @gigincg @aparnacoronasafe

"Not measurable" is not a very common scenario. design to be improved to have the option come up below BP fields, not above

**Comment by nihal467** [comment]
@rithviknishad 
image

- [x] when you click on the vital section, the entire page crashes

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
