### PR TITLE
Bed Management System Redesign

### LINKED ISSUE #6974: Design Enhancement for Bed Management
We have recently redesigned the Location Management. It'd be nice to have a similar design for Bed Management too.

Current:
image

Expected:
image

### PR DESCRIPTION
**Pull request by parthksingh1**
## Proposed Changes
This pull request proposes a redesign of the Bed Management system to improve efficiency within healthcare facilities

- Fixes #6974 
- Increased size between cards for improved visual clarity and separation
- Added hover effect to cards for enhanced interactivity

Screenshot 2024-02-23 005917

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [X] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [X] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [X] Completion of QA

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Let's go with the card-based grid layout like we have on the location management page. 
Keeping it identical to the location management page would be ideal.

**Comment by rithviknishad** [comment]
Refer: https://github.com/coronasafe/care_fe/blob/develop/src/Components/Facility/LocationManagement.tsx

**Comment by parthksingh1** [comment]
Hi @rithviknishad ,Thanks for the reference! I'll review the card-based grid layout on the location management page and aim to maintain it in Bed Managment, Appreciate your input!

**Review by rithviknishad — CHANGES_REQUESTED** [review]
It is not showing any beds.
https://github.com/coronasafe/care_fe/issues/7369#issue-2177553743

**Comment by parthksingh1** [comment]
@rithviknishad PTAL

**Comment by rithviknishad** [comment]
This still does not look any close to the location management page and looks almost like how the bed management page is in staging

**Comment by rithviknishad** [comment]
@parthksingh1 here is the expected design as mentioned in the issue:

image

**Pull request closed without merging**
