### PR TITLE
Fix: Disable delete bed button if bed is occupied

### LINKED ISSUE #5513: Disable delete bed button if bed is occupied
**Describe the bug**
If a bed is occupied the delete button is not disabled. https://github.com/coronasafe/care/pull/1312 disallows deletion of such beds.

**To Reproduce**

1. Go to a facilities location management page
2. Open bed management page of a location
3. Attempt to delete an occupied bed.

**Expected behavior**
The button should be disabled and a tooltip should be shown on why it is disabled.

#### Tasks
- [ ] Add chip/indicator whether a particular bed is occupied or not.
- [ ] Disable Delete bed button if bed is occupied.
- [ ] Show a tooltip saying its not allowed as it is occupied.
- [ ] Migrate html buttons in that page to use `ButtonV2` so that tooltip also can be added easily.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Bhavik-ag**
### <samp>🤖 Generated by Copilot at dae86af</samp>

Enhance bed row UI and prevent deleting occupied beds in `BedManagement.tsx`. Use custom button component and `isOccupied` property to show bed status and disable delete option.

## Proposed Changes

- Fixes #5513 
- Disable Delete bed button if bed is occupied.
- Migrate html buttons in that page to use ButtonV2 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [x] Completion of QA

### <samp>🤖 Generated by Copilot at dae86af</samp>

*  Import and use custom button component for bed row delete button ([link](https://github.com/coronasafe/care_fe/pull/5514/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaR13), [link](https://github.com/coronasafe/care_fe/pull/5514/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaL113-R126))
*  Add and pass `isOccupied` prop to bed row component to disable delete button and show tooltip for occupied beds ([link](https://github.com/coronasafe/care_fe/pull/5514/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaR36), [link](https://github.com/coronasafe/care_fe/pull/5514/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaR48), [link](https://github.com/coronasafe/care_fe/pull/5514/files?diff=unified&w=0#diff-53ec6fe91fcb892cb08c1ff573b13dea07d1bee5b9f5f269b808a0b12e26abdaR214))

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
You haven't added a chip/indicator whether its occupied or not to the bed tile. You can add it maybe beside the bed name?

**Review by rithviknishad — APPROVED** [review]
Awesome!

**Comment by nihal467** [comment]
@Bhavik-ag 
image

- [ ] change the badges to the second row in mobile view only
- [ ] make the delete button full width as similar to edit button
- [ ] make the vacant badge colour as primary and occupied badge colour as warning

**Review by rithviknishad — APPROVED** [review]
Nice work @Bhavik-ag

**Comment by nihal467** [comment]
@Bhavik-ag 
image

LGTM, nice work !

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
