### PR TITLE
Update packages and remove obsolete dependencies

### LINKED ISSUE #3738: Cleanup Dependencies
There seems to be a lot of dependencies that are no longer used in CARE that are still lingering around in the `package.json`, an example for this being `@types/react-select`

Clean up all dependencies in `package.json` After using the global find in VS Code to check for usage.

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #3738 

Added Dependencies:
- `lodash` [added as we have multiple imports for it already, it replaces some of the removed packages below]

Removed Dependencies:
- `@babel/core`
- `@types/react-select`
- `@types/react-slick`
- `lodash.isempty`
- `lodash.debounce`
- `lodash.get`
- `react-virtualized`
- `resolve`
- `save`
- `tslib`
- `autoprefixer`
- `jest-resolve`
- `@testing-library/react`
- `@testing-library/user-event`
- `@types/draft-js`
- `@types/draftjs-to-html`
- `@types/html-to-draftjs`
- `@types/jest`
- `@types/mocha`

Updated Packages:
- `@types/echarts@4.9.16`
- `@types/lodash@4.14.186`
- `@types/react@18.0.21`
- `@types/react-csv@1.1.3`
- `@types/react-dom@18.0.6`
- `date-fns-tz@1.3.7`
- `i18next-browser-languagedetector@6.1.8`
- `libphonenumber-js@1.10.13`
- `moment@2.29.4`
- `raviger@4.1.1`
- `react-csv-reader@3.5.2`
- `react-phone-input-2@2.15.1`
- `react-transition-group@4.4.5`
- `use-keyboard-shortcut@1.1.6`
- `@testing-library/jest-dom@5.16.5`
- `@types/react-copy-to-clipboard@5.0.4`
- `cypress-localstorage-commands@2.2.1`
- `local-cypress@1.2.6`
- `postcss@8.4.17`
- `react-scripts@5.0.1`
- `@headlessui/react@1.7.3`
- `clsx@1.2.1`
- `date-fns@2.29.3`
- `echarts@5.4.0`
- `react@18.2.0`
- `react-csv@2.2.2`
- `react-dom@18.2.0`
- `react-i18next@11.18.6`
- `react-player@2.11.0`
- `typescript@4.8.4`
- `@typescript-eslint/eslint-plugin@5.40.0`
- `@typescript-eslint/parser@5.40.0`
- `cypress@10.9.0`
- `eslint-plugin-jsx-a11y@6.6.1`
- `eslint-plugin-prettier@4.2.1`
- `eslint-plugin-react@7.31.10`
- `eslint-plugin-react-hooks@4.6.0`
- `gentype@4.5.0`
- `prettier@2.7.1`
- `snyk@1.1026.0`

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Comment by Ashesh3** [comment]
~~TODO: add back `autoprefixer` as a devdependency~~

**Comment by nihal467** [comment]
@Ashesh3 can you merge the latest development

**Comment by Ashesh3** [comment]
@nihal467 Done.

**Comment by nihal467** [comment]
LGTM, all the basic functionality are working

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
