### PR TITLE
Pain Scale for Basic editor

### PR DESCRIPTION
**Pull request by sam9111**

### CODE REVIEW

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
@sam9111 @gigincg in yesterdays call, there was some discussion regarding this, shall I test it, does the rectification are made

**Comment by gigincg** [comment]
@sam9111 @nihal467 Talked to Dr Athul on this. It should be with the vital signs. Pain is the fifth vital sign.

**Comment by sam9111** [comment]
> @sam9111 @nihal467 Talked to Dr Athul on this. It should be with the vital signs. Pain is the fifth vital sign.
Screenshot 2022-02-09 at 3 10 52 PM
 Do you mean here? @gigincg

**Comment by gigincg** [comment]
@sam9111 Let it be with the Vitals editor for Critical Care entries.

**Pull request closed without merging**
