### PR TITLE
Changed name of the label Active to transfer status: active in asset page

### LINKED ISSUE #3646: Change Active label to Transfer Status : Active in Asstes Page
**Describe the bug**
Change Active label to Transfer Status : Active in Asstes Page

image

### PR DESCRIPTION
**Pull request by patelaryan7751**
## Proposed Changes
Fixes #3646 
Changed name of the label Active to transfer status: active in asset page as discussed in eod
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

**Comment by nihal467** [comment]
@patelaryan7751 
image
can we have it same row, rather than two row

**Review by Ashesh3 — APPROVED** [review]
LGTM, but personally, for me, adding the whole term "Transfer Status: " makes the badge look bulky. Is there any better way we can achieve the same effect? Maybe something like how we have on the Patient's page?

image

**Comment by patelaryan7751** [comment]
Hey @Ashesh3 @nihal467 is this okay ?
image

**Review by Ashesh3 — APPROVED** [review]
That looks good to me!

**Comment by nihal467** [comment]
@patelaryan7751 
image

when the not working badge comes it, in become two row, can we do anything about it

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Can we have consistent casing for the badges too?

**Comment by nihal467** [comment]
@patelaryan7751 once the work is completed, change it to need testing

**Comment by patelaryan7751** [comment]
This issue would be disscussed in next eod and resolved in next eod.

**Pull request closed without merging**
