### PR TITLE
Improved Shifting letter Ui

### LINKED ISSUE #2857: Revamp Referral Letter : Shifting
the referral letter data looks so much scattered and misaligned

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2857 

# Bugs Fixes

##  Improved Shifting letter Ui
image

Hey, @nihal467 is this okay?

### CODE REVIEW

**Comment by nihal467** [comment]
@patelaryan7751 the right and left side margins of the page are not equal, make it well equal

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@patelaryan7751 what is the status

**Comment by patelaryan7751** [comment]
Hey @nihal467  is this okay?

shift

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
