### PR TITLE
Added test of patient_crud.cy.ts

### LINKED ISSUE #5865: Add test for patient_crud.cy.ts
## Tasks

- [ ] Add consultation details of a newly created patient.
- [ ] Edit consultation details of an already-created patient.
- [ ] Create Patient shift requests.
- [ ] Post doctor notes for an already created patient.
- [ ] Create and verify the generated treatment summary.
- [ ] Edit prescriptions for a patient.
- [ ] Discharge a patient.

### PR DESCRIPTION
**Pull request by ShivamJhaa**
### <samp>🤖 Generated by Copilot at 84680a9</samp>

This pull request improves the test code quality and coverage for the patient, asset, and consultation features of the frontend application. It refactors the existing test files to use the page object pattern and the standard cypress library, and adds new test cases and page object classes for the UI interactions and assertions. It also adds or modifies some attributes to the UI elements in the frontend components to enable cypress testing. It changes the proxy target for the `/api` path in `vite.config.ts` to use the local backend server for testing purposes.

## Proposed Changes

- Fixes #5865 part of #5491
- Change 1
- Change 2
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 84680a9</samp>

*  Add and modify cypress tests for asset management, patient creation, and patient consultation features ([link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-db4292fd03626d0a4e5a0e899dbceffb54fab4da3fd02e455598e6627248e746R122-R145), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-85edc6c535fd4c7cef250d5a68bb562c3fd75a82654e2de0b0227413d5840bfaL2-R6), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-85edc6c535fd4c7cef250d5a68bb562c3fd75a82654e2de0b0227413d5840bfaL16-R22), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-85edc6c535fd4c7cef250d5a68bb562c3fd75a82654e2de0b0227413d5840bfaL27-R85), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-85edc6c535fd4c7cef250d5a68bb562c3fd75a82654e2de0b0227413d5840bfaL152-R190))
*  Add and modify page object classes for asset management, patient creation, and patient consultation features ([link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-af0a7140a23fb3b1c3379fe2880ce31bab589501929f22c83d2b253753971707R119-R147), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-af0a7140a23fb3b1c3379fe2880ce31bab589501929f22c83d2b253753971707R191-R218), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-7fa643001511b285907c43213d442bb8b709ab276d7b050d4355e5f95cb38418R1-R176), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-c2094fdd7523aa87ec9c08561ebb379280c6a2b9968b3cac566d71c77dfc467dR1-R106), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-347162a770d89026e1666bacbed1593ec27d0dd2c6cffd86e69a8f924280815fR1-R77))
*  Add `data-testid`, `id`, and `className` attributes to UI elements for locating and interacting with them in cypress tests ([link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-abdb9a86f18dd154c547c5b8884c695e30d12d0e9b8775bbff93cdcfcd7b6132L214-R214), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-abdb9a86f18dd154c547c5b8884c695e30d12d0e9b8775bbff93cdcfcd7b6132R311), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-d3677127a55934962254fa660ba9b01a59fdb23bee06c9160832527f36c8bf20R352), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49L313-R313), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49L320-R322), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-e487f280661a7995b9602b6ded894fcd6612af833435ab16aeefdcd41268cab7R124), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-f6f40e1b249471f1821a43cd90bfdce470f563c22b22272a154f9bd7a2de599cL139-R142), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-f6f40e1b249471f1821a43cd90bfdce470f563c22b22272a154f9bd7a2de599cR331), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-f6f40e1b249471f1821a43cd90bfdce470f563c22b22272a154f9bd7a2de599cR374), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-f6f40e1b249471f1821a43cd90bfdce470f563c22b22272a154f9bd7a2de599cR476), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-f6f40e1b249471f1821a43cd90bfdce470f563c22b22272a154f9bd7a2de599cL519-R526), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-329491648052c140490b697045689a6f7235a2ffc97610874e026b9a1972655cR121), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-329491648052c140490b697045689a6f7235a2ffc97610874e026b9a1972655cR129))
*  Fix a syntax error in the `ConsultationDetails` component ([link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-f6f40e1b249471f1821a43cd90bfdce470f563c22b22272a154f9bd7a2de599cL139-R142))
*  Modify the proxy target for the `/api` path in the `vite.config.ts` file to use the local backend server for testing ([link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddL83-R84), [link](https://github.com/coronasafe/care_fe/pull/6135/files?diff=unified&w=0#diff-6a3b01ba97829c9566ef2d8dc466ffcffb4bdac08706d3d6319e42e0aa6890ddL92-R94))

### CODE REVIEW

**Comment by nihal467** [comment]
@ShivamJhaa the test's are failing in GitHub actions

**Comment by khavinshankar** [comment]
@nihal467 the cypress is failing, can you give it a another look

**Comment by ShivamJhaa** [comment]
@khavinshankar There was some issue in submitting the consultation, that's why the test was failing.
Please take a look, now test are passing.

**Review by nihal467 — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
