### PR TITLE
fix: misalignment of No Assets Found text

### LINKED ISSUE #3759: No Asset Found text is misaligned in asset page
**Describe the bug**

No asset found text in the asset page is misaligned

**To Reproduce**

https://care.coronasafe.in/assets?facility=49225e44-8b02-4fdc-b6e5-2c2f051e94c1&asset_type=EXTERNAL&status=ACTIVE&location=

**Expected behavior**

make it left aligned

**Screenshots**

image

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #3759
- [x] Fixed alignment of `No Assets Found` text

### CODE REVIEW

**Review by Ashesh3 — APPROVED** [review]
Looks good but I believe it'd be better if we could make it similar to the no results text on the sample test page.

image

**Comment by nihal467** [comment]
@cp-Coder i can see a comment of ashesh once it completed, mark it as need testing

**Comment by khavinshankar** [comment]
@rithviknishad can you check out the vercel error

**Comment by rithviknishad** [comment]
@khavinshankar can be ignored, or merge the latest develop for the storybook.
Storybook is currently not there in this branch, that's why deploy is failing.

**Comment by nihal467** [comment]
@cp-Coder 
image

the white box should be streched  like all other page

**Comment by nihal467** [comment]
@cp-Coder 
image

the icons are not visible in your PR and in staging, it is working fine

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
