### PR TITLE
Enhanced Ui of Choose File in Upload External Results Page

### LINKED ISSUE #3095: Ui enhancement of "Choose file" button in Upload External Results Page
# Bugs

## Ui enhancement of "Choose file" button in Upload External Results Page

image

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #3095 

# Bugs Fixed

## Enhanced Ui of Choose File in Upload External Results Page

image

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

**Review by skks1212 — APPROVED** [review]

**Comment by nihal467** [comment]
@patelaryan7751 make it responsive

**Comment by nihal467** [comment]
@patelaryan7751 what is PR status

**Comment by patelaryan7751** [comment]
@nihal467  made the button responsive 
Upload External Results _ CARE - Google Chrome 03-08-2022 01_49_27

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
