### PR TITLE
Added spaces on resource page in mobile view

### LINKED ISSUE #2666: Buttons overlap on resources page in mobile view
https://www.loom.com/share/e4ea5850168d4b9a961c4801f334c5b4

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #2666 
Screenshot (368)

### CODE REVIEW

**Review by skks1212 — CHANGES_REQUESTED** [review]
The same problem occurs in the shifting page too, can you do the same changes there?
Also can you try centering everything?

**Comment by nihal467** [comment]
@Pranshu1902 @skks1212  is it good for testing

**Comment by Pranshu1902** [comment]
@nihal467 I am adding the recommended changes

**Comment by Pranshu1902** [comment]
**Shifting page mobile view:**
Before:
Screenshot (370)
After:
Screenshot (371)

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
