### PR TITLE
Added discharge_reason and discharge_notes in discharge modal

### LINKED ISSUE #2385: Patient: Discharge Flow: URGENT
When a patient is discharged from CARE, 

i.e, when selecting "Discharge from CARE" here https://care.coronasafe.in/facility/7a560e62-6aae-4293-8f1a-0ba840e3449f/patient/192fdee9-397f-49bd-833a-10f700416da8

A pop up window appears with the following content 
Screenshot 2022-05-17 at 1 03 30 PM

Instead, the pop-up window must have a question "Reason for discharge" with dropdown options as " Recovered(downshift)/ Expired/ Referred (upshift)" and a long text field to add "Discharge Notes". The pop-up window will have "Close" and "Proceed with Discharge" options at the bottom. 

@gigincg Please review

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #2385 

image

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@khavinshankar 

How about using the new select menu for discharge reason as we are slowly moving towards using tailwind components.

Example preview:
image

**Comment by nihal467** [comment]
@khavinshankar is it good for testing ?

**Comment by khavinshankar** [comment]
@rithviknishad  the new component looks awesome, I'll refactor it, thanks

**Comment by nihal467** [comment]
test approved

**Pull request merged**
