### PR TITLE
Improve Sample Test page and Voice Recorder

### LINKED ISSUE #2418: Improve Sample Test History page
Currently the Sample Test history status fields look technical and are not user friendly. 

image

Changes should be done to remove the "_" and make it more user friendly by title casing it.

### PR DESCRIPTION
**Pull request by Ashesh3**
Closes #2418 

## /sample
- Capitalized "title: "
- Changed hover border to black, since green hover on green cards blend and do not give a immersive hover effect.

Previous Hover color:
image

Updated Hover color:
image

## /sample/<sample_id>

Updated:

image

## Recorder

When the user denies the browser's microphone permission, appropriate message is shown to the user and the recording indicator is stopped. It only works when the user has granted it the required permission.

- Refer to the GIF below

ILvP8RHQb5

Side Note:
image

Seems like the above field is no longer used for a patient, In that case no new patients will have this field displayed on their profile under Sample Test page. Would it be okay to just leave it as it is then?

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 @gigincg can you check the merge conflict

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
@Ashesh3 please do work on the merge conflict

**Comment by Ashesh3** [comment]
@khavinshankar Done! thanks for the ping.

**Pull request merged**
