### PR TITLE
Resolve page scroll resets in consultations tabs.

### LINKED ISSUE #6765: Page scroll resets to top when switching to medicines tab
**Describe the bug**
Page scroll resets to top when switching to medicines tab

**To Reproduce**

1. Go to a consultation dashboard
2. Scroll down a bit
3. Switch to medicines tab.

**Expected behavior**
When we switch tabs in the consultation dashboard, page scroll should not be reset for any tabs (except Feed tab where it scrolls to fit feed in view).

**Screenshots**
image

### PR DESCRIPTION
**Pull request by AshrafMd-1**
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at bdb8057</samp>

Fix UI bug in consultation details tabs. Add a `div` element with a `min-h-screen` class to ensure the tab content fills the screen height in `src/Components/Facility/ConsultationDetails/index.tsx`.

## Proposed Changes

- Fixes #6765
- Added `min-h-screen`

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at bdb8057</samp>

*  Add a `div` element with a `min-h-screen` class to fix a UI bug in the tab content height ([link](https://github.com/coronasafe/care_fe/pull/6825/files?diff=unified&w=0#diff-8a3d15fd6d3361688d96f67af80b867cc60bfbd6bc7642555fd6b5fd04d63901L465-R467))

### CODE REVIEW

**Comment by AshrafMd-1** [comment]
@rithviknishad once can u check

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

@AshrafMd-1 the page is getting unwanted white space under the PRN prescriptions

**Comment by AshrafMd-1** [comment]
@rithviknishad can you check the tabs once

**Review by rithviknishad — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
