### PR TITLE
Remove default ordering value

### LINKED ISSUE #6635: Sort "No Consultation Filed" patients to the top of Patient List page
- Related to https://github.com/coronasafe/care_fe/issues/6423

**Describe the bug**
> However, we also know that some nurses forget to, or leave out filing consultation. - @aparnacoronasafe 

No consultation filed patients are scattered around

**Proposed solution**
Sort "No Consultation Filed" patients to the top of Patient List page (when no sort is specified)

**Screenshots**
image

### PR DESCRIPTION
**Pull request by GokulramGHV**
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at c1c850b</samp>

Fixed patient list sorting bug by removing default ordering value. The `ordering` parameter for the `PatientManager` component is now determined by the `TableHeader` component.

## Proposed Changes

- Fixes #6635
- Backend PR: coronasafe/care#1718

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at c1c850b</samp>

* Change the default value of `ordering` in `PatientManager` to undefined to fix sorting bug ([link](https://github.com/coronasafe/care_fe/pull/6656/files?diff=unified&w=0#diff-6a60fce2df893cf91c0457f6445b903c1d6667b6a86fc21c38a9e8fc385c7575L184-R184))

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

It is not working for readmission patients  @GokulramGHV @rithviknishad

**Comment by nihal467** [comment]
@GokulramGHV can you fix the issue ASAP

**Comment by GokulramGHV** [comment]
@nihal467 I'll fix it by today

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
