### PR TITLE
Upgrade Prescription dropdowns in Consultation form

### LINKED ISSUE #3859: PRN Prescription and Prescription Medicine Section text box searching malfunctioning
**Describe the bug**

the drop list in the PRN Prescription and Prescription Medicine Section in the consultation form is not searching for the words we inputted in the box

**To Reproduce**

https://care.coronasafe.in/facility/c7fd946e-f852-4574-a5d3-cc7f590bffa8/patient/bde81302-5fe7-4b32-a18e-bf957ba2501e/consultation

**Expected behavior**

when we input text inside the box, it should be crossmatching with the droplist and show particular matching results only in the droplist

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #3859

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 @gigincg @khavinshankar 

image

- [ ] was removing tooltip intentional !
- [ ] the UI doesn't look good to me, big scroller feel weird

**Comment by Ashesh3** [comment]
> @Ashesh3 @gigincg @khavinshankar image
> 
> was removing tooltip intentional !

The tooltip is integrated in the option itself. This is intentional, as per the new select menu component. The tooltip is still there but as a helper text below the option.

Would increasing the width of the frequency select menu help? So that it appears more spaced out. Something like:
image

I am afraid there wouldn't be a way to alter how the select menu itself is displayed unless we modify the new component itself. Which might be an overkill for this issue.

**Comment by khavinshankar** [comment]
@nihal467 @Ashesh3 the ui does look off, can we have icon that shows the tooltip like before

For such a small drop-down tool tip would be ideal

**Comment by Ashesh3** [comment]
> @nihal467 @Ashesh3 the ui does look off, can we have icon that shows the tooltip like before
> 
> For such a small drop-down tool tip would be ideal

We can, but then I'll have to make changes directly to the new select component, and this change will affect all the instances of the select menu used anywhere, regardless of the dropdown being small or not. Otherwise, we could have a flag for showing compact tooltips but that might be unnecessary overall, need some inputs on this. @gigincg

**Comment by gigincg** [comment]
> @Ashesh3 @gigincg @khavinshankar
> 
> image
> 
>     * [ ]  was removing tooltip intentional !
> 
>     * [ ]  the UI doesn't look good to me, big scroller feel weird

When you're referring to a tooltip. Please use a screenshot to help others understand what you're talking about

**Comment by Ashesh3** [comment]
> > @Ashesh3 @gigincg @khavinshankar
> > image
> > ```
> > * [ ]  was removing tooltip intentional !
> > 
> > * [ ]  the UI doesn't look good to me, big scroller feel weird
> > ```
> 
> When you're referring to a tooltip. Please use a screenshot to help others understand what you're talking about

I'll be happy to provide the screenshot Nihal was talking about. 😄

So earlier it looked something like this:
image

And with the new component the tooltips are embedded below the option itself as shown here:
 
image

The question being, is the new design with embedded tooltips acceptable or ~we need to modify the component to add support for~ hidden tooltips which reveal themselves on hovering the "i" icon.

**Comment by khavinshankar** [comment]
The current UI
image

**Comment by Ashesh3** [comment]
> The current UI image

The tooltip appears to be clipping for me,

image

**Comment by khavinshankar** [comment]
> The tooltip appears to be clipping for me,
> 
> image

@Ashesh3 should be fixed now, :sweat_smile: forgot to stage the latest before pushing

**Comment by nihal467** [comment]
@khavinshankar @Ashesh3 
image

make the PRN responsive

**Comment by khavinshankar** [comment]
Responsive UI
image

**Comment by nihal467** [comment]
conditionally approving it , the minor issues are #3887

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
