### PR TITLE
feat: skills in profile section

### PR DESCRIPTION
**Pull request by Pragati1610**
fixes https://github.com/coronasafe/care_fe/issues/4594

### CODE REVIEW

**Comment by nihal467** [comment]
@Pragati1610  once you clear this PR #4455  will be test this, since it is co-related PR.

**Comment by nihal467** [comment]
@Pragati1610 
image

the whole user page is blank

**Comment by khavinshankar** [comment]
@nihal467 can you retest this, fixed the issue

image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
