### PR TITLE
Fix alignment in COVID Disease Status

### LINKED ISSUE #1922: Covid Patient Status : Alignment Issue
djioasids

### PR DESCRIPTION
**Pull request by shaileshaanand**
closes #1922

This PR renames COVID Disease Status to "COVID Status" on Patient Home page.

cds

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Comment by gigincg** [comment]
@nihal467 I thought @aparnacoronasafe mentioned that it needs to be "COVID Disease Status"

**Comment by gigincg** [comment]
@aparnacoronasafe @nihal467 @samholics Can you confirm this?

**Comment by aparnacoronasafe** [comment]
@gigincg Earlier the field was called "Disease Status". in the context of COVID it made sense. But now that we are opening the tool for other patients, COVID needs to be specifically added there. Hence "COVID Disease Status". But like Nihal rightly pointed out, With "COVID disease Status" since it is occupying 2 lines, the alignment is off. Hence, COVID Status should work better.

Good to merge.

**Review by gigincg — APPROVED** [review]

**Pull request merged**
