### PR TITLE
Auto-close dropdown when single select option is selected in a multi select dropdown 

### LINKED ISSUE #5944: Auto-close Symptoms dropdown when "ASYMPTOMATIC" selected
**Describe the bug**
When "Asymptomatic" is selected, the dropdown does not close automatically. Asymptomatic is a single select option and other options are multi-select options.

**To Reproduce**

1. Attempt to create a consultation
2. Select Asymptomatic symptom

**Expected behavior**
- [ ] Symptom dropdown should close automatically when "Asymptomatic" is selected.
- [ ] Symptom dropdown should NOT close automatically when any other option is selected.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by UdaySagar-Git**
## Proposed Changes

- Fixes #5944 
- Closes drop down when a single select drop down is selected in a multi select drop down 

**Before :**

image

**After :**

[Screencast from 23-02-24 04:01:34 AM IST.webm](https://github.com/coronasafe/care_fe/assets/111575806/29d073ad-0142-4b41-86ed-38110a558a21)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Nice work @UdaySagar-Git 🚀 

Could we make it like

- When asymptomatic is selected, close the dropdown as the user will not select any more options.
- But when asymptomatic is unselected, keep the dropdown opened, as the user is expected to continue by selecting one or more symptoms.

**Comment by UdaySagar-Git** [comment]
[Screencast from 23-02-24 11:52:34 AM IST.webm](https://github.com/coronasafe/care_fe/assets/111575806/4144fef3-6186-4f65-a283-6a861b19db11)

@rithviknishad I hope this fixes the issue , let me know if it requires any more changes

**Review by rithviknishad — COMMENTED** [review]
Awesome! LGTM!

**Review by rithviknishad — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Comment by nihal467** [comment]
@UdaySagar-Git the cypress test is failing, can you fix it

**Comment by UdaySagar-Git** [comment]
@nihal467 
image
image
image

I think Dummy Facility 40 is not present and creating tests to fail 

after running tests locally by changing Dummy Facility 40 to James , I was able to pass all tests  
image


reference https://github.com/coronasafe/care_fe/blob/bda15df327003b9bf741edc004fe1eb5d111f463/cypress/e2e/patient_spec/patient_consultation.cy.ts#L22

**Comment by UdaySagar-Git** [comment]
@nihal467 
I think "Dummy Facility 40" is not present causing tests to fail 
image
Screenshot from 2024-02-28 02-35-59

https://github.com/coronasafe/care_fe/blob/bda15df327003b9bf741edc004fe1eb5d111f463/cypress/e2e/patient_spec/patient_consultation.cy.ts#L22
I ran tests locally by changing "Dummy Facility 40" to "James" and able to pass all the tests 
Screenshot from 2024-02-28 02-49-02

**Comment by rithviknishad** [comment]
@UdaySagar-Git to run the cypress locally, you'll have to run the backend locally too and load the dummy data onto it. And connect your local FE to the local BE to run cypress

**Comment by UdaySagar-Git** [comment]
@nihal467 can you please help me fix this
image

**Comment by nihal467** [comment]
@UdaySagar-Git i will look into it, and will let you know by tomorrow EOD

**Comment by nihal467** [comment]
@UdaySagar-Git the failing test is due to a frontend bug in the staging, upon merging ( #7257 ) tomorrow morning will fix the test

**Comment by UdaySagar-Git** [comment]
@nihal467 sure !

**Comment by nihal467** [comment]
LGTM

**Review by nihal467 — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
