### PR TITLE
Fixes #7458

### LINKED ISSUE #7458: Multiple issues with validateFileUpload function in src/patient/fileUpload.ts
**Describe the bug**
The validation function could be rewritten to ensure more reliability.
**To Reproduce**

1. Go to 'facility/:facilityId/patient/patientId/files/'
2. Click on 'Choose File'
3. Issue1-
a.  Try to upload a file with some extension like .exe
b. Notice that the validateFileUpload function actually returns true in this case and later on while actually making the api call to /api/v1/files we get the error that the filetype is inaccurate, the expected behavior here should be to reject the file when it is getting uploaded in the first place instead of sending it over to the fileupload api to reduce unneccesary api calls.
Issue2-
a. Try changing the file extension of some .exe to .pdf
b. It will get uploaded normally, this should not be the case, the filetype only gets validated via the extension whereas a more reliable mechanism should be used to verify the filetype.
Issue3-
a. After uploading an unsupported file type and getting the error when we click on the cross button, the form fields get grayed out, it should get reset instead

**Expected Behavior**

image

- [ ] When an invalid format file is selected, the upload button should be grayed out, and an error message should be shown in the frontend indicating that it is an invalid format.

make sure this same behavior is applicable in patient consultation page and patient files as well

**steps to enter patient consultation file** 

1. go to the patient tab
2. select any patient with active consultation 
3. now from the nav bar under-diagnosis card, select the files
4. try to upload the .exe file and see the error

**steps to enter patient files** 

5. after the above steps, in the top right corner, select the patient details button
6. then select the upload patient files
7. try to upload the .exe file and see the error

**Screenshots**

Screenshot_12

### PR DESCRIPTION
**Pull request by kabirrajsingh**
## Proposed Changes

[- Fixes #7458
- Fixes issue 1 and 2 by adding a new isFileTypeSupported function which uses the file signature's header to check for the file type.
- Only when the filetype is verified, the api call to backend is made
- Fixes issue 3 by adding reset functions

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist
1. Discussion for finalizing the supported file types. Currently supported file types are .png, .jpeg, .jpg, .mp3, .midi, .wav, .pdf

### CODE REVIEW

**Comment by kabirrajsingh** [comment]
@rithviknishad pease review this

**Comment by nihal467** [comment]
@kabirrajsingh there is a deploy failure, might be a type check failing, check it

**Comment by kabirrajsingh** [comment]
@nihal467 yes I will fix this and #7309  by end of the week. Sorry for the delay, little busy with final year exams.

**Comment by nihal467** [comment]
@kabirrajsingh can you provide an update on this PR

**Pull request closed without merging**
