### PR TITLE
Made Resource page responsive in Ipad

### LINKED ISSUE #2829: resource page is not responsive
4-f

the resource page is not responsive, and it is tested in the iPad dimension

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2829 

# Bugs Fixed

## Made Resource page responsive in Ipad Air
image

## Made Resource page responsive on Ipad Mini
image

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@patelaryan7751 

Maybe fix this too? The column is being chopped.

image

**Comment by patelaryan7751** [comment]
> @patelaryan7751
> 
> Maybe fix this too? The column is being chopped.
> 
> image

Hey @rithviknishad can you give the screen length at which you are viewing?

**Comment by rithviknishad** [comment]
@patelaryan7751 

Issue is noticeable in window sizes between the following:

image

**Comment by patelaryan7751** [comment]
@rithviknishad  can you check it now i guess it is fixed.

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
