### PR TITLE
Show icu admission date on consultations dashboard

### LINKED ISSUE #6731: Show ICU Admission Date and Time in Discharge Summary / Consultation Page
**Describe the bug**
Currently, ICU admission date is shown only in Edit Consultation Details

**To Reproduce**

1. Create a consultation with Transfer within Facility

**Expected behavior**
- [ ] Show ICU admission date in Discharge Summary
- [ ] Show ICU admission date in consultation page
- [ ] Show ICU admission date in post discharge timestamp details

image

### PR DESCRIPTION
**Pull request by Pranshu1902**
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 8527c7b</samp>

Add admission date and ICU date to `ConsultationUpdatesTab`. This change enhances the patient's hospitalization information in the consultation details page.

## Proposed Changes

- Fixes #6731 
Display the Admission Date and ICU Admission date on the consultations dashboard
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 8527c7b</samp>

* Add a new section to show admission date and ICU admission date and time of the patient ([link](https://github.com/coronasafe/care_fe/pull/6779/files?diff=unified&w=0#diff-a1ae41968a05e24ed2d94c91009fbb88f1319a60a3b965773b3395130d27658bR365-R381))

### CODE REVIEW

**Comment by rithviknishad** [comment]
The PR: https://github.com/coronasafe/care_fe/pull/6719 has 2 changes that are conflicting to this PR.

1. `admission_date` is renamed to `encounter_date`
2. Label "Admission Date" has been white-labelled to encounter specific labels

**Comment by nihal467** [comment]
@Pranshu1902 as per the latest discussion on yesterdays EOD call, make the following changes 

- [ ] don't show any date or time ( admission, icu, discharge ) in the info card 
- [ ] show the admission and icu, time and date as same as the banner shown below when the patient is live
image

note: currently the banner in the screenshot is shown only when the patient is discharge, so we are trying to implement the same when the patient is live

**Comment by Pranshu1902** [comment]
@nihal467 updated view:
Live patient:
image

Discharged patient:
image

**Comment by nihal467** [comment]
image

- [ ] when the ICU admission details comes in, the whole UI looks weird
- [ ] keep the whole thing in one row
- [ ] keep the ICU admission on as same font as the admission on

**Comment by Pranshu1902** [comment]
@nihal467 Updated view:
image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
