### PR TITLE
Bed type

### PR DESCRIPTION
**Pull request by peeyush14goyal**
Reordered Bed Type List in Facility - Issue #1141

### CODE REVIEW

**Review by bodhish — APPROVED** [review]

**Review by gigincg — CHANGES_REQUESTED** [review]
@peeyush14goyal Could you elaborate on what you were trying to change in the gentype generated file? It's supposed to be a generated file and will be overwritten with the version that gets generated from the Reason File on build.

If you needed to change something, make the change in the .re file

If you didn't intend to change anything please revert the changes in the .gen file

**Comment by peeyush14goyal** [comment]
@gigincg By default on running `npm start` the path is
 `import {t as Prescription__Prescription_t} from './Prescription__Prescription.gen';` 

and it breaks. But when I change it to

 `import { t as Prescription__Prescription_t } from "@coronasafe/prescription-builder/src/Types/Prescription__Prescription.gen";`. 

It works. 
I am using Windows. Maybe this issue is in windows only because @Sandra3657 is also facing the same issue

**Comment by peeyush14goyal** [comment]
@gigincg Any fixes for this?

**Review by bodhish — APPROVED** [review]
LGTM

**Pull request merged**
