### PR TITLE
Fixed Minor UI bug in User page

### LINKED ISSUE #2676: Minor Ui Enhancement in User Page in mobile devices
# BUGS

## The user name bar in mobile devices should be fit to the content but it is not.
image

### It should be like this
image

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2676

# Bugs Fixed

## Username div's width set to fit the content
Screenshot from 2022-06-11 13-09-24

### CODE REVIEW

**Comment by patelaryan7751** [comment]
Deploy Preview Ready https://deploy-preview-2677--care-net.netlify.app/

**Review by skks1212 — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
test approved

**Review by developedBySJ — APPROVED** [review]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
