### PR TITLE
Added validation so that users can see users of the same district only on the Users Page

### LINKED ISSUE #3169: User Mangement Malfunction
image

image

the user is a wayanad district admin and he shouldn't be seeing users in the ernakulam district

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #3169 
# Bugs Fixed

## Added validation so that users can see users of the same district only on the Users Page

 now wayand district users are not visible

### CODE REVIEW

**Review by developedBySJ — CHANGES_REQUESTED** [review]
Instead of filtering users on the client, user filters in URL i.e. pass `district_id` as query

Checkout swagger doc for [`/api/v1/users`](https://careapi.coronasafe.in/swagger/)

**Comment by patelaryan7751** [comment]
@developedBySJ i have done the changes.

**Review by developedBySJ — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
