### PR TITLE
Alignment adjusted and UI minor updates

### LINKED ISSUE #8826: Design the List View in Shifting Page
Designing the List Layout in shifting.

Image

Refernce UI:
Image

I would like to work on improving this by aligning the components in a consistent manner and possibly rewording the tabs for better clarity. This will make it easier for users to identify actions and reduce any confusion.

### PR DESCRIPTION
**Pull request by AnveshNalimela**
## Proposed Changes
-Moved the grid and board view to end after the advanced filter 
-Aligned all the items accordingly
-In list view Instead of 2 colums updated to 3 columns to remove extra white space 
Before
image
After

{576227FF-AFD1-4E60-A814-6376C510561A}

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by bodhish** [comment]
@AnveshNalimela whats the actual issue here? Can you reference it to the PR?

**Comment by AnveshNalimela** [comment]
The issue #8826
Minor enhancements of UI in shifting and resources page

**Comment by AnveshNalimela** [comment]
There is merge conflcit due to package-lock.json But havent modified the that file

**Comment by rithviknishad** [comment]
Why was the package-lock.json changed in this PR in the first place?

**Comment by AnveshNalimela** [comment]
No idea sir. I havent made any changes in package-lock.json

**Pull request closed without merging**
