### PR TITLE
expanded the medical conditions the patient has (comorbidities)

### LINKED ISSUE #6944: Expanding Comorbidities: Medical History
**Is your feature request related to a problem? Please describe.**
CARE gathers all underlying medical conditions the patient has (Comorbidities) in the patient registration form, under medical history (https://care.coronasafe.in/facility/eeb23cb7-1524-479a-825e-660311386b47/patient/51ff0682-065d-4e25-bcc6-fb1b682642fb/update). The list is limited.

**Describe the solution you'd like**
Expand the option to include:

- [ ] COPD
- [ ] Bronchitis
- [ ] Chronic neurological or neuromuscular disease
- [ ] Immunocompromised condition
- [ ] Liver Disease
- [ ] TB, if selected "Active/Old" and "treated duration"

- [ ] Kidney diseases to be renamed as "Chronic Renal Disease"

- [ ] Lung diseases/Asthma may be hidden from the list as "Lung diseases" is a very large set of diseases including COPD. Instead, introduce a new item for "Asthma" and "other chronic lung diseases"

- [ ] When "cancer" is selected, have options for "Type of cancer" to select from "Breast (show option only for females)/ Lung/ Skin/ Colorectal/ Uterus (show option only for females)/ Leukaemia/ Bladder/ Prostate (show option only for males)/ Melanoma/ Lymphoma/ Brain/ Liver/ thyroid/ Others)

### PR DESCRIPTION
**Pull request by shramanpaul**
## Proposed Changes

- Fixes #6944 
- added the medical conditions (comorbidities) as specified

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

[expanding comorbidities.webm](https://github.com/coronasafe/care_fe/assets/110323017/f85608d7-9acc-4da4-8832-53cacab03b94)

please have a review and suggest changes if required

### CODE REVIEW

**Comment by shramanpaul** [comment]
[expanding comorbidities.webm](https://github.com/coronasafe/care_fe/assets/110323017/aa8a7cc2-38c7-4447-a456-70b85b89d9e1)

**Comment by shramanpaul** [comment]
@rithviknishad please have a review and suggest changes if some

**Review by rithviknishad — CHANGES_REQUESTED** [review]
As mentioned in the issue, this requires backend changes to be made. However, no backend PR is referenced in the PR comment.

Changes needs to be made in https://github.com/coronasafe/care/blob/master/care/facility/models/patient_base.py#L59-L68

**Comment by rithviknishad** [comment]
Cypress tests also needs to be fixed

**Comment by shramanpaul** [comment]
Hi @rithviknishad, just wanted to let you know that I have college exams for the next week. I'll make the PR and update the changes suggested, once they're over. Thanks for your understanding!

**Comment by shramanpaul** [comment]
i will be making the pr by today

**Pull request closed without merging**
