### PR TITLE
cleared Patient Name input field on removing the badge in Shifting

### LINKED ISSUE #1620: Data remains in the search even after removing the badge : Shift
https://user-images.githubusercontent.com/57055998/126768813-3a93c121-fb29-44dd-a23b-808adc58a822.mp4

When we remove the badge in the shifting, the data in the search column remain the same

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #1620 

https://www.loom.com/share/c2ecc8305a8b478f9425dc95df01c1a3

### CODE REVIEW

**Review by abhinandanarya06 — APPROVED** [review]

**Comment by nihal467** [comment]
test failed, when we are typing the patient name, at a normal speed, the page is kept on refreshing, which make it hard to type

**Comment by khavinshankar** [comment]
@nihal467 this debounce issue is been handled in different or #1624

**Comment by nihal467** [comment]
@khavinshankar my mistake, the debouncing is been handled in #1624

**Comment by nihal467** [comment]
test approved

**Pull request merged**
