### PR TITLE
fix: add loader to external results section

### LINKED ISSUE #2454: Add loader to external results section
The external results section shows "Np result found" until the data is fetched from the server, the other section shows a coronasafe loader. Add the corona safe loader to external results section.

Screenshot from 2022-05-20 16-20-04

### PR DESCRIPTION
**Pull request by Pragati1610**
fix #2454

### CODE REVIEW

**Review by naman114 — CHANGES_REQUESTED** [review]
@Pragati1610 In the `External Results` section, `Total Results` shows 0 till the data is fetched from the backend. Can you add a loader instead? (just like there is one for `Total Patients` in the `Patients` section)

**Comment by Pragati1610** [comment]
> @Pragati1610 In the `External Results` section, `Total Results` shows 0 till the data is fetched from the backend. Can you add a loader instead? (just like there is one for `Total Patients` in the `Patients` section)

This is exactly the changes in this PR does. Is there another place?

**Comment by mathew-alex** [comment]
:wave: Hi, @Pragati1610,
Conflicts have been detected against the base branch. Please rebase your branch against the base branch.

***

This message is automatically generated by [prince-chrismc/label-merge-conflicts-action](https://github.com/prince-chrismc/label-merge-conflicts-action) so don't hesitate to report issues/improvements there.

**Comment by Pragati1610** [comment]
There is a github test `Auto Label Conflicts / auto-label (pull_request)` is failing

Is this change mentioned in this article required: [resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac](https://stackoverflow.com/questions/70435286/resource-not-accessible-by-integration-on-github-post-repos-owner-repo-ac)

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Wouldn't this show the loading component even when the external results list from the backend is empty?

**Comment by Pragati1610** [comment]
> Wouldn't this show the loading component even when the external results list from the backend is empty?

There is no other way to know about it otherwise

If it is empty, it will show the loader and then show that no results found.

Technically a loader is to wait for results irrespective of what is in the results I suppose, so ig it shouldn't be a problem though if you have any ideas on making this better in user experience do share.

**Comment by khavinshankar** [comment]
@Pragati1610 this doesn't seem relevant anymore, if the issue persists, feel free to reopen it or create a new pr

**Pull request closed without merging**
