### PR TITLE
#49 Added type definitions for Common components

### PR DESCRIPTION
**Pull request by MathewtheCoder**

### CODE REVIEW

**Comment by dauntlessnomad** [comment]
Build Failed.  @MathewtheCoder you dont have to do this. 
The code is already woking with out the type definition changes ,
Are you sure you need it

**Comment by dauntlessnomad** [comment]
https://app.circleci.com/pipelines/github/coronasafe/care_fe/125/workflows/19c8fc57-a235-45da-925f-70a24433cad1/jobs/158/parallel-runs/0/steps/0-107

**Comment by SandeepThomas** [comment]
Type definition is really helpful for development. It should be added in my opinion.

@MathewtheCoder could you please fix the issue in your local after pulling the latest changes from develop branch?

**Comment by MathewtheCoder** [comment]
Sure i have taken the pull and will work on solving the issues.

**Comment by MathewtheCoder** [comment]
@SandeepThomas @tomahawk-pilot I have pushed the fixes and the build is successful now.

**Comment by dauntlessnomad** [comment]
will wait for @GodlyBGeorge to review

**Pull request merged**
