### PR TITLE
📷 Support for linking multiple cameras to a bed

### LINKED ISSUE #7511: Improving Asset-Bed and Camera Preset relations and enabling monitoring of a bed via multiple cameras
Currently, each camera bed preset is stored as an individual AssetBed record (1 preset => 1 AssetBed record; 10 presets => 10 AssetBed records). This is not very efficient. Instead a camera (asset) can be linked to a bed (which represents an AssetBed record), and multiple presets can be added for this AssetBed record.

### Action Items

- [x] Create a new model `CameraPreset` (having many-to-one relation with `AssetBed` model).
- [x] Add fields for tracking modifications made to the CameraPreset records (created_by and modified_by along with created and updated at datetime fields)
- [x] Necessary changes in FE to reflect these.
- [x] Enforce unique names for a Bed<>Preset, across cameras.
- [x] Enable monitoring of 1 bed through multiple cameras.

-------------

Originally reported issue

>**Describe the bug**
The Camera Feed option do not appear on most patient pages. This has been observed randomly in many patients cards.
Initially we though it to be dependent on assigning a bed to the patient. 
But later we are observing that, inspire of assigning the beds, and under *View Facility>Live Monitoring* all 3 cameras are functional. But under *View Patient>select patient*  the feed option will not appear.
It must be a bug or it is dependent on some other data entry field, apart from assigning bed to a patient.
>
>**To Reproduce**
>1. Go to 'Facility > GH Nagamangala'
>2. Click on 'view patients'
>3. Scroll down to 'Patient Name Narayana Swamy Bed 5'
>4. See error Camera Feed option not seen
>
>1. Go to View Facility > GH Nagamanagala
>2. Click on Live Monitoring
>3. All 3 cameras are Live
>
>**Expected behavior**
Camera Feed option should be available for all patients with beds assigned.
>
>**Screenshots**
Camera Feed Feature not appearing
WhatsApp Image 2024-04-01 at 14 33 54_65bf55b9
>
>All 3 cameras are live
WhatsApp Image 2024-04-01 at 14 33 18_79daf601
>
>
>**Desktop (please complete the following information):**
>- OS: [e.g. windows ]
>- Browser [e.g. chrome]

### LINKED ISSUE #7535: Add highlight for in-use preset in asset configure page
**Describe the bug**

When we click on a existing preset, and the camera feed is showing that particular feed, the preset is not being showing any highlight 

**To Reproduce**

1. Go to any camera configuration page
2. Click on any existing camera configuration
3. See error

**Expected behavior**

- [ ]  When we click on an existing preset and the camera feed is being shown, the preset should be highlighted.
- [ ] By adding this, an extra advantage is provided to the user, allowing them to know which preset they are modifying using the update preset button.

**Screenshots**

image

### LINKED ISSUE #7620: Add proper error message for Camera configuration page
**Describe the bug**

When we enter the wrong middleware for a camera configuration, it throws "something went wrong" error

**To Reproduce**

1. Go to camera asset configuration page
2. input wrong middleware and submit
3. See error

**Expected behavior**

It should be throwing a proper error

**Screenshots**

image

### LINKED ISSUE #7635: Modify the error message in the asset configuration page
**Describe the bug**

When we try to input the same IP address, into an asset within a facility, it throws multiple errors

**To Reproduce**

1. Create two assets with the same IP configuration
2. See error

**Expected behavior**

It should only be throwing one proper error  for example in the screenshot it should be: "IP Conflict: 192.168.68.116 is in-use by 'test-camera' asset within the facility"

**Screenshots**

image

### LINKED ISSUE #8633: Asset Camera Configuration Page is throwing unwanted request and error
**Describe the bug**

When you open the camera asset configuration page, and stay on that page for 5 seconds, you keep on receiving an "Object Object" error in the frontend

- /api/v1/asset/d5e008e8-2ce6-4c0a-9262-68d910601d42/operate_assets/ request is send on a loop with response 400

**To Reproduce**

1. Go to asset tab
2. Open any camera asset
3. open the configuration page, make sure that they don't have any configuration

**Expected behavior**

- [ ] unwanted requests shouldn't fire from the frontend
- [ ] all related relevant errors thrown should be users readable

**Screenshots**

image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Required Backend

- https://github.com/ohcnetwork/care/pull/2387

## Proposed Changes

- [x] Fixes #7620
- [x] Fixes #7635
- [x] Fixes #7535
- [x] Removed old live feed component implementations
- [x] Required by #6376
- [x] Fixes #7511
- [x] Fixes #8633

image

image

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
image

- [x] add the option to configure the beds in the asset configuration page itself

image

- [x] add pagination to the bed management page, as not all the camera are visible now

image

- [x] this button should be only accessible for admins and doctors as per our current staging, so hide it for other users

image

- [x] configuration buttons are properly positioned in laptop views

image

- [x] the mobile responsive view in the manage camera page is breaking

image

- [x] the camera linking and creating presets kind of confusing, even with knowledge of the process, because you need to scroll down a lot of time, to see presets related to the camera, if there are a lot of camera present in the location

image

- [x] the existing preset's name or the preset position can't be edited using the configure button
- [x] the buttons in the existing UI is also kind of confusing, whether its configuration or editing or adding, 

Note: 

- we should think of keeping linking camera to bed on configuration page and creating presets in the bed management page.

**Comment by nihal467** [comment]
Enhancement

image

- [ ] keep the feed monitor and the right side card height consistent

**Comment by nihal467** [comment]
**Bug**

image
image


- [ ] when i click on a preset, the respective camera name should also keep on changing in the camera feed component
- [ ] currently in the screenshot it says camera 30, but the selected preset is from camera 29, now , after selecting the preset and try to move the camera individually, its not working

@rithviknishad

**Comment by nihal467** [comment]
image

- [ ] preset saving in the patient consultation page is not working

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
