### PR TITLE
show details of patient in live feed monitoring

### LINKED ISSUE #6667: Show Patient details of selected Preset in Location Live Feed Monitoring
**Describe the bug**
Currently, we are not showing the patient in the selected bed in Live Feed monitoring as there's no efficient way to fetch which patient is present on a particular bed.

**To Reproduce**

1. Go to a location live feed monitoring page

**Expected behavior**
Show Patient name, age gender as shown in the mockup

**Screenshots**
image

### PR DESCRIPTION
**Pull request by rash-27**
## Proposed Changes

- Fixes #6667 
- lInked patient to AssetBed 
- Display patient name, age , gender in the live feed monitoring page

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers
- Ater changes 
[Screencast from 05-04-24 08:49:30 AM IST.webm](https://github.com/coronasafe/care_fe/assets/146672184/cf24adc3-8e90-496e-baa2-3daadbb58628)

### CODE REVIEW

**Comment by nihal467** [comment]
@rash-27 fix the lint issue

**Comment by rash-27** [comment]
hey @nihal467 I tried using `npm run lint-fix` and while performing `npm run lint` I got 0 errors and i also did `npm run format` and corrected prettier errors even though the lint is failing , am i missing something ?

**Comment by rash-27** [comment]
@nihal lint issued fixed, please have a look

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — CHANGES_REQUESTED** [review]
1. The alignments of the preset selects seems to be broken. Ensure it's properly centered.
2. Can we improve the design? Placing name, age and gender in a congested manner while lot of space is available besides it, seems to look not good.

**Comment by rash-27** [comment]
Yup , will improve the design ASAP .

**Comment by rash-27** [comment]
hey @rithviknishad is this ok? , Can we also display no patient text whenever a patient is not present ?
[Screencast from 25-04-24 08:00:58 PM IST.webm](https://github.com/coronasafe/care_fe/assets/146672184/05116118-4242-43ff-91e7-50276fac3732)

**Pull request closed without merging**
