### PR TITLE
Improving the UI for notice board

### LINKED ISSUE #2711: Revamping notice board page UI

### PR DESCRIPTION
**Pull request by kunatastic**
closes #2711 

Previously 
image

Updated 
image

### CODE REVIEW

**Review by skks1212 — APPROVED** [review]
Looks good! You can also add filters as a separate PR or in this one itself.

**Comment by kunatastic** [comment]
What filters are required?? @skks1212

**Comment by shivankacker** [comment]
> What filters are required?? @skks1212

Id say date, sender, sender type and message contents. But you should really ask @gigincg

**Review by cp-Coder — APPROVED** [review]

**Comment by nihal467** [comment]
test approved

**Pull request merged**
