### PR TITLE
Download Discharge Summary, Medicine Administration Records and upgraded Prescriptions

### LINKED ISSUE #3437: Medicine Administration Record
**Context**: 
We will be incorporating a more detailed module to track medicine administration for a patient inside the current I/O Balance within Log Update (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/80e1429f-4b91-44f2-9dbd-03c427920f54/update).

**Changes required:** 

- [x] Rename I/O Balance as "Administration Record" in critical care index (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/80e1429f-4b91-44f2-9dbd-03c427920f54/update)
- [x] Change the header of the I/O Balance section to "administration record (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/80e1429f-4b91-44f2-9dbd-03c427920f54/update)
- [x] The existing I/O balance will remain as a section within the page
- [x] Add another section on top called "Medicine Administration Record"
- [x] This section will contain the prescriptions already entered in the latest consultation. Both "Prescription and "PNR Prescription" in consultation (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/update) must be available here. (PNR prescription is yet to be merged #3194 )
- [x] The section will contain a table against each of the medicine in the prescription to note the administration of such a medicine. The table must contain simple checkboxes to note that the medicine is already given. These checkboxes must be in line with the "Frequency" suggested in the prescription.
- [x] For PNR prescription, instead of table to note administration, you can have a field to capture the time and date when it is administered. 

- [x] There should also be an option to Add more medicine. This must show the user all fields in the prescription module (in consultation). Once the user added details of a new medicine, the prescription in consultation must also be edited accordingly.

- [x] There must be an option to Discontinue a prescription by clicking on the red cross on the right side of each prescription. This must prompt a confirmation pop-up window stating "You are editing the treatment plan for the patient. Are you sure you want to discontinue the selected medication for the patient?"
Once discontinued, the medication must appear faded at the bottom with the name of Medication, dosage, frequency and administered from [date] to [ date]- these dates will be the date of first dose administered and the last dose administered. There must also be an option to restart the medication. 

A suggestive design is as below:

Screenshot 2022-08-19 at 9 51 10 PM

### LINKED ISSUE #5237: Can we get discharged summary in printable format instead of sending to an email?
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### LINKED ISSUE #5246: Discharge summary is missing multiple information
points to be discussed are below :

[test-march-fifthweek-Discharge_Summary.pdf](https://github.com/coronasafe/care_fe/files/11158912/test-march-fifthweek-Discharge_Summary.pdf)

image

- symptoms are recorded in the summary report, but the date on onset symptoms are not shown in the discharge summary

image

- weight, height, and category are not showing in the patient discharge summary
- provisional diagnosis and diagnosis are not showing in the patient discharge summary

image

- only prescription medicine are shown and no PRN prescriptions are shown in the discharge summary
- in consultation history, only admitted dates are showing, there is no info on previous discharge history

image

- present health condition, ongoing medication, allergies, blood group, insurance details are not mentioned in the discharge summary

[test-march-fifthweek-Discharge_Summary (after discharge).pdf](https://github.com/coronasafe/care_fe/files/11159319/test-march-fifthweek-Discharge_Summary.after.discharge.pdf)

image

- once we discharge a patient, the medicine entered in the discharge pop-up is not visible in the discharge summary
- once we discharge a patient, the medicine we entered while create a patient consultation is not visible in discharge summary
- the discharge note, and discharge reason is not visible in the discharge summary 

image

- current health is not recorded anywhere in the platform anymore

### PR DESCRIPTION
**Pull request by rithviknishad**
Some parts were co-authored by @sainak, @shivankacker 

## Associated Backend PRs
- https://github.com/coronasafe/care/pull/1247
- https://github.com/coronasafe/care/pull/1252

## Associated Issues
- Fixes #3437

### New FormField Component: `NumericWithUnitsFormField`

Example Usage:

```jsx
<NumericWithUnitsFormField
  className="flex-1"
  label="Dosage"
  {...field("dosage", RequiredFieldValidator())}
  required
  units={["mg", "g", "ml", "drop(s)", "ampule(s)", "tsp"]}
  min={0}
/>
```
image

### Create Prescription Form uses the new Form higher order component.

1. Create a form context
2. Pass `onSubmit` (async) and `onCancel` callbacks.
3. Write validation
4. Compose the parts of the form using the `field` method.
5. And forget about managing the state by yourself from now on 😄 

image

### Manage Prescription Medications and PRN Prescriptions specific to a consultation

image
image
image

### Administer a prescription
image

### Discontinue a prescription
image

### View list of Normal and PRN Prescriptions
image

### Click on a row/entry to view detailed information about a prescription
image

### View Medicine Administration History
image

### Select multiple prescriptions to be administered at once
image

### Prescriptions during Discharge
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
Tested via cloudflare tunnel of @rithviknishad

**Comment by rithviknishad** [comment]
### Migrations Testing procedure
```sh
cd ~/ohc.network/care
make down
dokcer volume rm care_postgres-data
git checkout master
make up
docker exec care python manage.py load_dummy_data

cd ~/ohc.network/care_fe
git checkout develop
npm run dev

# populate data from front-end (with develop branch FE and master branch BE)
# create patient and consultation with 1 prescription, 1 prn prescription
# add daily round medicines

cd ~/ohc.network/care
make down
git checkout med-admin-record
make up

cd ~/ohc.network/care_fe
git checkout prescriptions-v2
npm run dev

# see if existing prescriptions is persisted
# see if daily round medicines are persisted
```

## Before Migrations (with `master` BE, `develop` FE; Added prescription, prn prescription, critical care medicine)

Testing with two patient (one would not be discharged and so would not have any discharge prescriptions, second would be discharged before migration with prescriptions added during discharge)

### Patient that's not discharged
image

### To be discharged patient
image
image


## ⚠️ Failed to migrate

1. `medicines_given` should be `medication_given`
image

2. `created_at` should be `created_date`
image

3. key error `indicator` (and other nullable fields)
image

4. key error for medicine name????
image

**Comment by rithviknishad** [comment]
### Post migrations (after resolving all migration issues)

#### Patient that's not discharged

image


#### Patient that's discharged
image

### Observations

- We lose the original last updated/created time data and the values would be the time at which migration was performed since `Prescription` records are created during the migration.
- For a discharged patient with prescriptions, Prescriptions added during a patient discharge are missing.
- For an undischarged patient, their regular prescriptions are marked as discharge prescriptions.

**Comment by rithviknishad** [comment]
### Date Migration Test

#### Before Migration: Last updated: `11:29 AM; 12/05/2023`
image


#### Migrations run on: `11:30 AM; 12/05/2023`
image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
@rithviknishad 
image

when i select the " Select for Administration " in the administer medicine,

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
