### PR TITLE
Fix: create asset asking to select a facility when viewing asset of filtered facility

### LINKED ISSUE #4386: Create Asset in asset list page should not ask to select a facility if view assets is clicked from a facility home page
**Describe the bug**
When we arrive at asset list page from the facility home page by clicking view assets (same as applying a facility filter in the advanced filters), Create Asset should not ask to select a facility again.

**To Reproduce**

1.1 Go to Facilities
1.2 Click on any facility and view assets in manage facility
1.3 Click on Create Asset

OR

2.1 Go to Assets
2.2 Filter by facility
2.3 Click create asset

**Expected behavior**
It should automatically take the filtered facility as the selected facility for creating asset.

**Screenshots**

https://user-images.githubusercontent.com/25143503/208980747-508ff7bb-9421-4e17-89b5-4374e109ae4d.mp4

### PR DESCRIPTION
**Pull request by cp-Coder**
# Bug Fix

## Proposed Changes

- Added filtered facility as the selected facility for creating asset

## Associated Issue

- Fixes #4386

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update product [documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [ ] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder merge the latest development branch

**Comment by aeswibon** [comment]
@rithviknishad can you attach a video where the problem is still persist. I am not able to find it in the deployed preview.

**Comment by rithviknishad** [comment]
@cp-Coder the pop-up dialogue is an unnecessary step present if we are viewing assets after landing from the facility home page.

cc: @nihal467 

https://user-images.githubusercontent.com/25143503/210740685-2c15a4e1-c833-469e-abe7-8b09bab3cd83.mp4

**Comment by nihal467** [comment]
@cp-Coder 
image

when we apply the filter and click create an asset. Even though, the pop-up is not showing up, but unable to make a asset

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@rithviknishad can you rereview this

**Comment by khavinshankar** [comment]
@cp-Coder can you work on @rithviknishad's comments

**Comment by nihal467** [comment]
@cp-Coder is it good for testing

**Review by rithviknishad — APPROVED** [review]

**Comment by rithviknishad** [comment]
@nihal467 only unused localizations were removed. Good to be merged since it's already been tested.

cc: @khavinshankar

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
