### PR TITLE
Replace pain scale slider with pain editor component

### LINKED ISSUE #3430: Hemodynamic Parameters (vitals): Pain Scale
The Vitals section in critical care log (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/779a961f-9045-4a1f-b996-d4af459d7c59/update) 

- [ ] Must have a section called "Pain"
- [ ] It must contain text "Mark region and intensity of pain" and have the anatomy of a human with sections that can be selected ( as given in the pressure sore section https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/05d1be0f-51e6-4eab-8682-bc5515f5c863/consultation/aea6e0ab-7405-4186-b76e-b4e1aa3bbdca/daily_rounds/779a961f-9045-4a1f-b996-d4af459d7c59/update) 
- [ ] remove current Pain score slider. It will be replaced with the selection of the human anatomy to mark pain on a scale of 5.
- [ ] A description box for each selected area must appear to describe the pain in that specific section (NOTE: build the description box as a component which can be added to the "Pressure sore" section too)

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #3430

Editor:
image

View Update:
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 
image


it is functioning good, but it is not responsive in mobile view

**Comment by nihal467** [comment]
@aparnacoronasafe comment on the following issues

image

- [ ] now, we are recording the pain in the critical care log update. Still, it is not reflected in any of the tabs in the summary pages, where we should place it, either as a new dedicated tab as we gave for pressure sore, or inside some other tab.

image
image
image

https://deploy-preview-5039--care-net.netlify.app/facility/98375114-038b-4c95-a580-86d9ad09d06a/patient/e20f56a7-f822-4087-80e7-ec85d05849c8/consultation/411a34f3-aa20-4b09-8d9f-0f38b5ee3ff2/daily_rounds/93ddf759-8f70-470d-88a2-853e9ae8af36

- [ ] when we open the view details page of an existing filed update of a patient, the pain scale is reflected in a human anatomy manner and the pressure sore is given in a tabular manner, which one we should be following?

**Comment by Ashesh3** [comment]
> @Ashesh3 image
> 
> it is functioning good, but it is not responsive in mobile view

Fixed.

image

image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
