### PR TITLE
Camera Feed: Optimize for mobile usage

### LINKED ISSUE #4558: Optimize Camera Feed for Mobile Usage

### PR DESCRIPTION
**Pull request by rabilrbl**
## Proposed Changes

- Fixes #4558 
- Seperate PTZ buttons for desktop and mobile
- Fix camera presets view with horizontal overflow menu

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

| Before | After |
|-|-|
|image|image|
|image|image|

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rabilrbl 
image

https://deploy-preview-4748--care-net.netlify.app/facility/520cfdc5-971d-4943-b545-81c9681ef093/patient/73ab43b2-fa30-4eaf-9a05-9b7351a95cb8/consultation/4eebabe0-251f-4cca-9dac-cd1f183b15f3/feed

when I am trying to check the feed in responsive view, the whole page turns to white

**Comment by nihal467** [comment]
@rabilrbl marking it for discussion in EOD, since the UI change doesn't look to me

**Comment by nihal467** [comment]
@rabilrbl can you work on the bug ASAP and mark it for need testing

**Comment by rabilrbl** [comment]
> @rabilrbl can you work on the bug ASAP and mark it for need testing

Will do

**Pull request closed without merging**
