### PR TITLE
enhanced Date Time component

### LINKED ISSUE #8994: Improve the Date and Time component in the CARE
**Describe the bug**

- [ ] Regardless of the user's system time preference, the text field displays time in 24-hour format, while the selection component defaults to a 12-hour format. This inconsistent behavior is not ideal for a component.
- [ ] It is not possible to input "01" in the minutes part of the component; the input text area always shows "1," automatically removing the "0" for single-digit entries.

**To Reproduce**

1. Go to patient consultation page
2. Click on edit consultation consultation
3. Scroll down to admission date

**Expected behavior**

- [ ] The text area and selection component for date and time should align with the user’s system time preference.
- [ ] Users should be allowed to enter "01" in the minutes part of the component. Similarly, this behavior should be allowed for all other date and hour parts as well

**Screenshots**

Image
Image

### PR DESCRIPTION
**Pull request by saikiranpatil**
## Proposed Changes

- Closes #8994 
- [x] Change 1: The text area and selection component for date and time should align with the user’s system time preference.

- [x] Change 2: Users should be allowed to enter "01" in the minutes part of the component. Similarly, this behavior should be allowed for all other date and hour parts as well
  - this error was causing because when we finished writing minutes, cursor was pointing back to minutes. I made changes such that after typing minutes, cursor loops back to day, making it easier to change date completely if needed without changing cursor position with mouse.

image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced hour input functionality now supports both 12-hour and 24-hour formats based on user locale.
	- Improved navigation logic between input fields with an increased index range for smoother transitions.
	- Streamlined input change handling for easier transitions between fields, simplifying the conditions for moving to the next input.
	- Date input component now adapts to user preferences for time formats, improving flexibility.

- **Bug Fixes**
	- Resolved issues with input navigation that previously restricted field transitions based on index.

### CODE REVIEW

**Comment by saikiranpatil** [comment]
@ohcnetwork/care-fe-code-reviewers 

I had made commit with time taking hour as 12 for 12 am or pm, it failed 1 test, but when i reverted it back to 00 it passed all the test cases.

I tried to run cypress tests locally, but, in all tests, page was loading till timeout

Please guide me on how to proceed further

**Comment by nihal467** [comment]
image

- [ ] user system preference is still not taken account by the component, its one of the issue pointers look into it
- [ ] check the code rabbit flagged issues
- [ ] look into the cypress failure in your PR

**Comment by saikiranpatil** [comment]
@nihal467 @rithviknishad please review this

**Comment by saikiranpatil** [comment]
so happy by your support to new contributor's. thank you

**Pull request closed without merging**
