### PR TITLE
Disable submit button in round type normal if no value selected

### LINKED ISSUE #6787: Disable Submit button in normal log update
**Describe the bug**
Related to PR : #6738 

when we merge the above PR, user will be able to create blank normal log update, so it will be creating blank records in the normal log-update

**To Reproduce**

**Expected behavior**

- [ ] disable the submit button for the normal log update unless anyone of the fields shown in the screenshot have data inputted by the user

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Pranshu1902**
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at f3c1ec2</samp>

Enable different rounds types and form validation for daily rounds. Refactor `Submit` component in `DailyRounds.tsx`.

## Proposed Changes

- Fixes #6787 
Disable submit button in round type normal if no value is modified in the form for at least any 1 field
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at f3c1ec2</samp>

*  Add a `disabled` state to control the submit button for daily rounds form ([link](https://github.com/coronasafe/care_fe/pull/6793/files?diff=unified&w=0#diff-2b725d1dcc3aabbc0438aff687d8c29b79847cde3ea5e171e86ca113a4e6a612R111))
*  Enable the submit button when the rounds type is not "NORMAL" ([link](https://github.com/coronasafe/care_fe/pull/6793/files?diff=unified&w=0#diff-2b725d1dcc3aabbc0438aff687d8c29b79847cde3ea5e171e86ca113a4e6a612R364))
*  Pass the `disabled` state and the `rounds_type` value to the `Submit` component as props ([link](https://github.com/coronasafe/care_fe/pull/6793/files?diff=unified&w=0#diff-2b725d1dcc3aabbc0438aff687d8c29b79847cde3ea5e171e86ca113a4e6a612L630-R636))
*  Disable the submit button in the `Submit` component when the rounds type is "NORMAL" and the form is not filled ([link](https://github.com/coronasafe/care_fe/pull/6793/files?diff=unified&w=0#diff-2b725d1dcc3aabbc0438aff687d8c29b79847cde3ea5e171e86ca113a4e6a612L630-R636))
*  Fix the indentation of the code in `DailyRounds.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6793/files?diff=unified&w=0#diff-2b725d1dcc3aabbc0438aff687d8c29b79847cde3ea5e171e86ca113a4e6a612L630-R636))

### CODE REVIEW

**Comment by nihal467** [comment]
@Pranshu1902 
image

the above patient have previous record, i haven't copied any record, i didn't filled any fields from physical examination info till rhythm description, still the save button is active, 

it is expected to be disabled if no data was entered in any of the fields

**Comment by Pranshu1902** [comment]
@nihal467 Bug resolved
image

**Comment by nihal467** [comment]
image

@Pranshu1902 @rithviknishad marking it for discussion as now in critical care, the above fields a mandatory thing to fill any of the field, need to get a final confirmation from @gigincg

**Comment by rithviknishad** [comment]
@nihal467 @Pranshu1902 as discussed, 

- Critical care is an exception, you can skip this validation in Daily Rounds form.
- However, in Critical Care editor, this similar validation is to be present. Any one fields must be changed (apart from the "Basic Editor").

cc: @aparnacoronasafe

**Review by rithviknishad — APPROVED** [review]

**Comment by Pranshu1902** [comment]
@nihal467 the form now isn't disabled for `CRITICAL CARE`

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
