### PR TITLE
Fixes Issue#2471

### PR DESCRIPTION
**Pull request by Pranshu1902**
Added margin for mobile view
image

### CODE REVIEW

**Comment by Pranshu1902** [comment]
fixes #2471

**Comment by nihal467** [comment]
@Pranshu1902 @gigincg there is merge conflicts, check it

**Comment by Pranshu1902** [comment]
> @Pranshu1902 @gigincg there is merge conflicts, check it

resolved!

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
