### PR TITLE
Replace SVGs used by login-hero with PNGs to stop consuming lots of memory in firefox

### LINKED ISSUE #4374: Very high memory usage!
**Describe the bug**
When [care.coronasafe.in](https://care.coronasafe.in/) is opened, a lot of the system resource is taken away :/ 

Memory usage in my system:
- Before opening care: **13.0 GB**
- After landing in care: **15.5 GB** (this would be biased with my OBS screen recording too).
- After closing care: **13.2 GB** (with screen recorder continued to be on).

So it's using **2.3 GB**!!???

**To Reproduce**

1. Go to care.coronasafe.in

**Screenshots**

https://user-images.githubusercontent.com/25143503/208592169-cc7d4782-15a7-406b-ac6c-d53d7670c3b3.mp4

**Desktop:**

- OS: Ubuntu 22.10
- Browser: Mozilla Firefox 107.0.1

cc: @gigincg

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Fixes #4374 

@nihal467 when testing could you test in all browsers?

image

https://user-images.githubusercontent.com/25143503/209055891-1565082e-81f0-49dc-a589-6ddf3508ad23.mp4

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by Ashesh3 — APPROVED** [review]
image

LGTM

**Comment by rithviknishad** [comment]
The cypress test is failing here for the external result (which is not at all related to the PR). locally too, coz the update care prompt is hiding the active button.

It fails for my other PR branch too locally, but not sure how it's passing in CI in those PRs.

cc: @khavinshankar

**Comment by rithviknishad** [comment]
Nah, nevermind 😅 
It was failing locally because in my local I had the git ignored `/build-meta.json` being served and forgot to remove it after completing the work with Update CARE prompt PR.

The update available prompt wouldn't be triggered if it failed to fetch the `/build-meta.json` file.

**Review by khavinshankar — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
