### PR TITLE
Fix: Clearing Facilities Field Causes White Screen #8610

### LINKED ISSUE #8610: [Bug] Add New User - Clearing Facilities Field Causes White Screen
**Describe the bug**
In Add New User after selecting the Facilities field with any input and clearing it shows a blank white page.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Users in the sidebar
2. Click on User and right top you will see Add New User
3. select any input in the Facilities field and clear it using [x] inside the field
4. See the error in the console

**Expected behaviour**
even after clearing data in the Facilities input field in Add new user, it should not crash it should not show a white page. And it should only clear input which the user gives.

**Screenshots**

https://github.com/user-attachments/assets/d02bffde-3652-420e-93d8-93e3124b5e6d

### PR DESCRIPTION
**Pull request by AdityaJ2305**
- Fixes #8610 
- The `selectedFacility` state was encountering issues due to a `null` value being passed by the `AutoCompleteAsync` component when clicking the clear icon. To address this, I added a check to ensure that if the value is `null`, an empty array is passed instead. 

### Screenshot of the `AutoCompleteAsync` Component:
AutoCompleteAsync Component Screenshot

### Video Recording:
[Watch the demo video here](https://github.com/user-attachments/assets/606eba4a-53d1-4542-889f-32d0e2e863c1)

### Reviewers:
@nihal467 
@ohcnetwork/care-fe-code-reviewers

## Merge Checklist:

- [x] Add specifications that demonstrate the bug fix or test the new feature.
- [x] Prepare a screenshot or demo video for the changelog entry and attach it to the issue.
- [x] Request peer reviews.

### CODE REVIEW

**Comment by chakribontha** [comment]
@AdityaJ2305 It seems like you've made some partial changes. When you're clearing the input text, it should not remove the selected values from the dropdown. Instead, it should only clear the input field. This is the desired behavior from the user's perspective. Could you please adjust this accordingly?

**Comment by AdityaJ2305** [comment]
> @AdityaJ2305 It seems like you've made some partial changes. When you're clearing the input text, it should not remove the selected values from the dropdown. Instead, it should only clear the input field. This is the desired behavior from the user's perspective. Could you please adjust this accordingly?

 @chakribontha, in the screenshot, three facilities are selected: `testing, Thiruvananthapuram`  `Testing Other, Thiruvananthapuram` and `Testing Other12313, Thiruvananthapuram` with “3 selected” shown as text. Clicking the clear icon should only remove the “3 selected” text, not the selected facilities below. If I understand correctly, the clear icon is meant to allow users to reset and choose facilities again. By only clearing the text, this purpose isn’t fully met.
 
Screenshot 2024-09-25 at 10 39 39 PM

**Comment by rithviknishad** [comment]
@AdityaJ2305 lint checks and cypress tests are failing.

**Comment by rithviknishad** [comment]
@AdityaJ2305 could you ensure prettier is working locally? Noticed code not formatted in a previous PR from you too.

**Comment by AdityaJ2305** [comment]
> @AdityaJ2305 could you ensure prettier is working locally? Noticed code not formatted in a previous PR from you too.

Thank you for the feedback! I'll ensure Prettier is set up and working locally for future PRs and going to make changes in current PR

**Comment by nihal467** [comment]
@AdityaJ2305 Could you please prioritize pushing the fix by the end of today? We need to address this issue as soon as possible before our upcoming weekly release.

**Review by rithviknishad — APPROVED** [review]

**Comment by AdityaJ2305** [comment]
@rithviknishad Apologies my bad

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by nihal467 — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
