### PR TITLE
fixed navigation issues in create and edit investigation

### LINKED ISSUE #1231: Saving investigation
https://care.coronasafe.in/facility/711bd31a-feeb-4a9e-9893-b317579bfff8/patient/90e9d4ec-d4ff-4e15-b21f-ffdfdd2f9914/consultation/24ba3490-b296-4319-8f9e-d5f72bb02d6e/

logged in as district admin.

Tried saving a new page on biochemistry tests. once i click the save button, a green alert for sucessfull saving comes up, but the rest of the screen remains blank. only the sidenav is visible

### PR DESCRIPTION
**Pull request by khavinshankar**
this fixes #1231

### CODE REVIEW

**Comment by samholics** [comment]
tested, verified

**Comment by bodhish** [comment]
@khavinshankar the users is always taken to the investigations in the last consultation.

Their will be other investigations in other consultations.

It looks like the fix is completely blocking preview for older investigations in old consultations

**Comment by khavinshankar** [comment]
> @khavinshankar the users is always taken to the investigations in the last consultation.
> 
> Their will be other investigations in other consultations.
> 
> It looks like the fix is completely blocking preview for older investigations in old consultations

@bodhish It seems to work fine,
I checked it out for the patient _**Bodhish Thomas - 33**_
link: https://deploy-preview-1235--care-net.netlify.app/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/f4720b52-87e2-49a5-a9d4-28645714d155

can you please recheck it once again and if there is an issue, please attach the link.

**Review by smartclash — APPROVED** [review]

**Comment by bodhish** [comment]
@khavinshankar did you get time to work on this?

**Comment by khavinshankar** [comment]
@bodhish its fixed, can you please review it once

**Comment by samholics** [comment]
tested, verified

**Pull request merged**
