### PR TITLE
Fixed misalignment in resource approval letter

### LINKED ISSUE #2977: Revamp : Resource Approval Letter
the alignments are not proper in the resource approval letter

### PR DESCRIPTION
**Pull request by GokulramGHV**
Fixes #2977 

Preview:
image

### CODE REVIEW

**Comment by GokulramGHV** [comment]
@nihal467 Are the alignments okay?

**Comment by nihal467** [comment]
@GokulramGHV start the content under approved by without space from left side

**Comment by GokulramGHV** [comment]
@nihal467 I've made the changes..

image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
