### PR TITLE
Added "No Data Found" on Samples Page Issue#2604

### LINKED ISSUE #2604: Nothing visible under "View Sample Report" section
It should say "No Reports"
Screenshot (349)

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #2604 
Screenshot (350)

### CODE REVIEW

**Comment by nihal467** [comment]
@Pranshu1902 @gigincg rather than simply putting no data available, put it inside a white box to match with the above UI. @gigincg what do you think

**Comment by Pranshu1902** [comment]
http://localhost:4000/sample/22e36198-0c6c-4ffa-9c0a-3a35aeac684e

Added UI for "No Data Found"
Screenshot (351)

**Comment by nihal467** [comment]
@Pranshu1902 deployment preview is failed

**Comment by nihal467** [comment]
@Pranshu1902 @gigincg can you check the deploy preview

**Comment by Pranshu1902** [comment]
@nihal467 error resolved!

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
