### PR TITLE
Created a patient detail card in sample details.

### LINKED ISSUE #1772: Patient details in sample report details.
Add details of patient in sample report details in a card like shifting details.

### PR DESCRIPTION
**Pull request by Apurva-Nagar**
- Added a Patient Details card in Sample Details
- Removed patient details button
- Refactored `test_sample` routes
- Refactored `FileUpload` logic

fixes #1772

### CODE REVIEW

**Comment by samholics** [comment]
there is a patient info card like in shifting, but  i couldnt see the patient info,getting permission denied , and couldnt upload files inthe new patient info page and also inthe test completed interface.
image

**Comment by Apurva-Nagar** [comment]
@samholics The backend changes are in another PR (on the Care repository) that was just merged 1 hour back. Can you please test this again now?

**Comment by samholics** [comment]
tested, verified

* now able to see patients basic info as shifting interface
* now able to upload files 
* permission denied is cleared
* now can select newly added sample test type.

**Comment by samholics** [comment]
The patient detail section is visible but with no data error   "not found" @Apurva-Nagar

**Comment by Apurva-Nagar** [comment]
@samholics Patient details visible for me (https://deploy-preview-1774--dreamy-fermat-b5024e.netlify.app/sample/bb26cc2a-2ab8-4d23-a056-5a732593aeba)
image . Can you please share the exact user with which this is happening?

**Comment by samholics** [comment]
@Apurva-Nagar 

Patient detail tab is still there,

image

url

https://care.coronasafe.in/facility/01810c32-ec26-494a-9e65-40e5547a7746/patient/aaeb3f87-d49d-4ff7-b178-2cc4084ca52e

**Comment by arpancodes** [comment]
Hey @samholics, the PR is still open so it is not deployed to the staging... please check on this deployment: https://deploy-preview-1774--dreamy-fermat-b5024e.netlify.app/ with your credentials and let us know if you are facing any issue.

**Comment by samholics** [comment]
oh okay, i thought its all deployed

**Review by gigincg — APPROVED** [review]

**Pull request merged**
