### PR TITLE
Change Patient homepage back button to go back in history

### LINKED ISSUE #1865: Filter is not constant in patient list.
* logged in as district admin
* select patients
* select advanced filters
* select any values on any field ( for eg; selected antenatal)
* open any patient card
* click back and then the filter is removed from the patient list
* now showing all patient list.

This is very time consuming and very difficult to put filters again and again.

### LINKED ISSUE #1866: Redirecting to patient list when a patient card opened and click "back" from 'shifting' module.
when a patient card opened from shifing request, after opened consultation details and click back the page redirecting to patient list.

* logged in as district admin
* selected shifting
* open any shifting request from the shifting module

image

* click on Patient Name from the shifting details page

image

* open consultations of the patient and go back to patient card

* click back from patient card 

* now the page goes to whole patient list  instead of  "shifting_details" page.

This bug is very difficult when trying to shift a patient. Mainly shifting control room is using this path and now they have to spend more time on click shifting and find that particular patient from the whole shifting module once again for further updations. if any more queries comes up regarding this issue pls ping me

### PR DESCRIPTION
**Pull request by shaileshaanand**
Change Patient homepage back button to go back in history instead of hard-coded "/patients"

Fixes #1865, Fixes #1866

patienthomeback

### CODE REVIEW

**Comment by samholics** [comment]
tested

#1865 is working


But #1866  Now having a loop between consultation history page and patient card ,still not going back to shift details page. @shaileshaanand 

https://deploy-preview-1867--dreamy-fermat-b5024e.netlify.app/facility/3447b03d-7522-4525-9e14-58d7628b1e9e/patient/25eacf39-f7a3-4263-aa36-c4d7cf2aa1e5

**Review by gigincg — COMMENTED** [review]
The changes look good, but doesn't seem to fix all linked issues.

**Comment by shaileshaanand** [comment]
@samholics I have commited a fix, please test.

**Comment by nihal467** [comment]
@gigincg we are having breadcrumbs in place, so, shall we close it

**Pull request closed without merging**
