### PR TITLE
Fix responsiveness of FacilityCard and ManagePatients components

### LINKED ISSUE #9156: fix the responsive ness
Image
Image
in the above pic the header is not responsive
Image
in the above pic the red button and green outlined button are collapsed 
and the three buttons are not good at down the 3rd button should be the center.
Like this there are many issues i want to work on this issues .
assign this issue to me i will fix.

### PR DESCRIPTION
**Pull request by ayushpatil2122**
## Proposed Changes

- Fixes #9156
- Change 1
image
- fixed the in the above pic the header responsive
- Change 2 
image
- fixed the in the above pic the header responsive

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced responsiveness and visual alignment in the Manage Patients interface.
	- Improved layout for buttons and filters for better user experience on various screen sizes.

- **Bug Fixes**
	- Adjusted button layouts to ensure consistent alignment and spacing across devices.

- **Style**
	- Updated styles for buttons to enhance appearance and responsiveness in the Facility Card and Manage Patients components.

### CODE REVIEW

**Comment by Jacobjeevan** [comment]
Duplicate of #9161

**Comment by rithviknishad** [comment]
the add patient button is thrown off...

image

**Comment by rithviknishad** [comment]
Closing as duplicate as mentioned in https://github.com/ohcnetwork/care_fe/pull/9276#issuecomment-2512346977

**Comment by rithviknishad** [comment]
@ayushpatil2122 avoid working on issues without getting them assigned. We can avoid duplicate PRs that way.

**Pull request closed without merging**
