### PR TITLE
Tooltip added for treating docter skills in Patient details page

### LINKED ISSUE #9253: Tooltip for Treating doctor skills in Patient Details Page
**Tooltip is required for Treating doctor skills in Patient Details Page** 

Before : 
Image

Recommended :
Image

### PR DESCRIPTION
**Pull request by Mahendar0701**
## Proposed Changes

- Fixes #9253 
- Added tooltip for treating docter in patient details page

Image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced display of treating physician's skills with tooltips for better user experience.
	- Improved state management for assigned volunteers.
	- Streamlined error handling for volunteer assignments.

- **Bug Fixes**
	- Refined response handling in approval and patient transfer processes to ensure accurate notifications.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by Mahendar0701** [comment]
@rithviknishad are there any changes required for this PR?

**Comment by Jacobjeevan** [comment]
> @rithviknishad are there any changes required for this PR?

Just needs testing 👍

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by Mahendar0701** [comment]
Hey @rithviknishad can you assign story point for this issue

**Comment by rithviknishad** [comment]
Done

**Pull request merged**
