### PR TITLE
Fixed Password Reset Malfunction

### LINKED ISSUE #3120: Password Reset : Malfunctioning
the link received for resetting a user password at email is not working properly

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #3120

# Bugs Fixed

## Fixed Password Reset Malfunction

image

### CODE REVIEW

**Comment by nihal467** [comment]
@patelaryan7751 

image

when we click on forget password, and request for the reset, this is the mail we get to our inbox, to reset our password. But, when we click on the link, 

image

this is the redirected page from the link. So, in short, none can reset there user id password with link reached in our mail id

**Comment by patelaryan7751** [comment]
@nihal467 the reset link is working now.

**Comment by nihal467** [comment]
@patelaryan7751 it is working now, can you close the PR

**Comment by patelaryan7751** [comment]
@nihal467 but image was not showing up this PR is fixing that problem shall i close it or make a new issue regarding this . What do you think 🤔?

**Comment by nihal467** [comment]
@patelaryan7751 CLOSE THIS AND MAKE NEW ISSUE

**Pull request closed without merging**
