### PR TITLE
Resolved overlapping Icon and Goal content

### LINKED ISSUE #4797: The Icon and goal content is overlapping in homepage
**Describe the bug**

The icon and the goal content are overlapping on the homepage ( 14-inch laptop )

**To Reproduce**

1. https://care.coronasafe.in/

**Expected behavior**

the icon and goal content should be properly aligned and doesn't overlap each other

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Pranshu1902**
FIxes #4797 
Resolved overlapping Icon and Goal content on the home page
Screenshot from 2023-02-10 12-40-55

### CODE REVIEW

**Comment by nihal467** [comment]
@Pranshu1902 
image

the bug still there in 14inch screen laptop

**Comment by Pranshu1902** [comment]
@nihal467 Updated view:
image

**Comment by nihal467** [comment]
@khavinshankar LGTM

**Comment by nihal467** [comment]
@khavinshankar LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
