### PR TITLE
Removes unicons support and introduces `CareIcons` library for internal use

### LINKED ISSUE #3850: Improve how we consume icons in care
As discussed in EOD and slack

- [x] Copy [`pf-icon`](https://github.com/pupilfirst/pupilfirst/tree/master/app/frontend/packages/pf-icon) implementation to care, so that icons that are not present in unicons can be added with the help of this.

## Tasks to be accomplished eventually: 
- [ ] Replace material ui icons.
- [ ] Replace fontawesome icons.

cc: @bodhish @skks1212 @gigincg

### LINKED ISSUE #4065: Use SVGs Instead of Unicons
Unicons doesn't seem to be maintained.

- [ ] Remove unicons dependency
- [ ] Replace all usages of unicons with equivalent SVG Files

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Resolves #3850
- Fixes #4065 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 
image
image

- [ ] neonatal care logo in current staging and this PR is different, was it intentionally changed 

image

- [ ] the icon in the search bar, seems to be misaligned and colour is also really dark

**Comment by Ashesh3** [comment]
> @rithviknishad image image
> 
> * [ ]  neonatal care logo in current staging and this PR is different, was it intentionally changed
> 
> image
> 
> * [ ]  the icon in the search bar, seems to be misaligned and colour is also really dark

Not intentional! I will take a look.
Edit: @nihal467 Resolved.

**Comment by nihal467** [comment]
@Ashesh3 @rithviknishad 
image

i think you haven't pushed the changes, once the work Is done, change it to need testing

**Comment by Ashesh3** [comment]
@nihal467 Yep, my bad! should be fixed now.

**Comment by nihal467** [comment]
@Ashesh3 @rithviknishad 

Untitled

the search icon is still dark and feels misaligned, it was already mentioned in a previous comment, did you forget to push the change?

**Comment by Ashesh3** [comment]
> @Ashesh3 @rithviknishad
> 
> Untitled
> 
> the search icon is still dark and feels misaligned, it was already mentioned in a previous comment, did you forget to push the change?

I accidently pushed it to my fork :/ Fixed now.

image

**Comment by nihal467** [comment]
LGTM

**Review by gigincg — APPROVED** [review]

**Pull request merged**
