### PR TITLE
Adds regex validation for `PhoneNumberFormField` same as in backend and validate `onBlur` instead of `onSubmit`

### LINKED ISSUE #5788: add phone number as you type regex validation in `PhoneNumberFormField`

### PR DESCRIPTION
**Pull request by rithviknishad**
### <samp>🤖 Generated by Copilot at 0f5f660</samp>

The pull request enhances the validation of phone number and email inputs in the form components. It refactors the `EmailValidator` function to use a generic `RegexValidator` function and adds a new `PhoneNumberValidator` function. It also modifies the `PhoneNumberFormField` component to use the new validator and show error messages.

## Proposed Changes

- Fixes #5788

image
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 0f5f660</samp>

*  Refactor `EmailValidator` function to use a generic `RegexValidator` function and add new validators for phone numbers and email addresses ([link](https://github.com/coronasafe/care_fe/pull/5789/files?diff=unified&w=0#diff-c636e9ceaf17e1786a2c45ee0c55b24c47893a291e51cc06fad0de0cf2fd46dfL39-R57))
*  Update `PhoneNumberFormField` component to import and use the new `PhoneNumberValidator` function and the `FieldError` type from `FieldValidators.tsx` ([link](https://github.com/coronasafe/care_fe/pull/5789/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eL4-R7))
*  Add a local state variable `error` to `PhoneNumberFormField` component to store and display the validation error message from `PhoneNumberValidator` ([link](https://github.com/coronasafe/care_fe/pull/5789/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eR25), [link](https://github.com/coronasafe/care_fe/pull/5789/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eL44-R56))
*  Pass the `error` state to the parent `FormField` component as part of the `field` prop to enable the validation logic and error handling ([link](https://github.com/coronasafe/care_fe/pull/5789/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eL44-R56))

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 
image

when, we start typing it, the error is showing, doesn't seem good, any other approach have in mind

**Comment by rithviknishad** [comment]
For validating on submit, we'll have to update everywhere it's used manually as it would become outside the scope of the reusable component.

**Comment by rithviknishad** [comment]
Isn't this better, user will be aware immediatley if it's wrong instead rather than waiting to submit and come back

**Comment by nihal467** [comment]
@rithviknishad 
image

there is a bug in the field, that is why cypress is failing

- when we are inputting 10 digit's the initial +91 is auto-removed and there is a 0 by-default added

**Comment by Ashesh3** [comment]
@rithviknishad The page is crashing when opening advanced filters on User page.

**Comment by rithviknishad** [comment]
I've resolved the crash; not the issue #5846

**Comment by rithviknishad** [comment]
@Ashesh3

**Comment by nihal467** [comment]
@rithviknishad fix the cypress

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
