### PR TITLE
Removed auto scroll to top on Users page

### LINKED ISSUE #4123: Auto-scroll is malfunctioning in User management page
**Describe the bug**

When we click on link facilities in the user management page, the page is getting auto-scroll to the top from the bottom of the page.

**To Reproduce**

https://care.coronasafe.in/users?page=1&limit=15&username=doc#

**Expected behavior**

when we click on the "Click here to show linked facility" button, the page shouldn't be auto-scrolling to the top of the page, it only should show the pop-up

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #4123 
Removed auto scroll when clicking the `Click here to show linked facilities` button
image

### CODE REVIEW

**Review by Ashesh3 — CHANGES_REQUESTED** [review]
The issue is still happening.

UnnaturalRingtailedlemur

**Comment by nihal467** [comment]
@Pranshu1902 issue still persist

**Comment by nihal467** [comment]
@Pranshu1902 what is the status on this PR

**Comment by Pranshu1902** [comment]
Still working on the issue, will update in a few days

**Comment by Pranshu1902** [comment]
@nihal467 bug resolved

**Comment by nihal467** [comment]
LGTM

**Comment by khavinshankar** [comment]
@Ashesh3 can you re-review this one

**Review by Ashesh3 — APPROVED** [review]
Works fine!

**Pull request merged**
