### PR TITLE
Doctor Specialisation

### LINKED ISSUE #4501: Doctors : Specialisation
When registering a doctor user type (https://care.coronasafe.in/users/add) the following additional fields to be added to the form 
- Specialisation- dropdown with search function. The list of specialities is available at https://docs.google.com/spreadsheets/d/1lCBF2hhmlYV3paPP3xIep6tPHmzTefdD67w-eaKql7I/edit?usp=sharing
- Qualification- short text field- mandatory field 
- Years of experience- drop-down (0, 1-2, 3-5, 5-7, 7-10, more than 10) years- mandatory field
- Medical council registration No. (short field for numeric values accepting max 10 digits)- mandatory field

- [x] Make all the input visible in the user list
- [x] Make qualification and specialty appear against the name in the doctor  connect panel (https://care.coronasafe.in/facility/a31e6a24-0146-4043-b295-3a6c2fe7e095/patient/86db5dde-ffdb-4473-9eab-3e6b2088d7d6/consultation/de8455fa-3d11-49e3-9dc2-1aaec616379b)

### LINKED ISSUE #4643: Cross button is misaligned in the user creation page
image

make the button alignment proper in the user creation page

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Resolves #4501
- Fixes #4643 
- Updated User Profile page to include doctor related fields

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by rithviknishad** [comment]
- Waiting for backend: https://github.com/coronasafe/care/pull/1151

**Comment by nihal467** [comment]
@rithviknishad 
image

user id : test-Jan-999 , ( User type: Doctor ) , Password has been send of your slack

when we click, edit profile, after login in as a doctor, the page is crashing

**Comment by nihal467** [comment]
@rithviknishad 
image

even though the update form is getting submitted, the data is not getting updated

**Comment by rithviknishad** [comment]
@nihal467 i've fixed it, could you checck now

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
