### PR TITLE
Resolving issue #177

### PR DESCRIPTION
**Pull request by cyriacbijun**
I have added filtering using a button, to only take `Positive` patients. The cards also change colour based on the health of patient.

### CODE REVIEW

**Comment by SandeepThomas** [comment]
Filter needs to be implemented using API since we are having backend pagination.

**Comment by cyriacbijun** [comment]
@SandeepThomas  I had gone through the API and did not find a query parameter to match `diease_status`. 
image
Please correct me if I'm wrong. I not even sure if this was what you meant.

**Comment by SandeepThomas** [comment]
@bodhish @tomahawk-pilot @anroopak @vigneshhari Could you please look into the above comment?

**Comment by anroopak** [comment]
@cyriacbijun The filter does not exist. But we will be adding that. 
Available options would be - 
    SUSPECTED
    POSITIVE
    NEGATIVE
    RECOVERY
    RECOVERED
    EXPIRED

**Comment by cyriacbijun** [comment]
> 
> 
> @cyriacbijun The filter does not exist. But we will be adding that.
> Available options would be -
> SUSPECTED
> POSITIVE
> NEGATIVE
> RECOVERY
> RECOVERED
> EXPIRED

So, should I close this pull request and open another one after the change?

**Comment by SandeepThomas** [comment]
@cyriacbijun yes, you can do that. It would be better if you could communicate in the slack channel.

**Pull request closed without merging**
