### PR TITLE
Fixed feed full screen issue with iOS devices

### LINKED ISSUE #3765: Camera Feed(IOS): `HLS Player` non-functional fullscreen toggle
**Describe the bug**
The fullscreen toggle for HLS Player in IOS devices is not working.

**To Reproduce**
On IOS device, visit this [link](https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/feed) and toggle fullscreen
**Tip**: Use `Browser Stack` to emulate an IOS device.

- OS: IOS
- Browser Safari

### PR DESCRIPTION
**Pull request by khavinshankar**
## Proposed Changes

- Fixes #3765 
- fixed full-screen issue with iOS devices in Feed

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
full screen button is not working @khavinshankar

**Comment by nihal467** [comment]
@khavinshankar what is the status on the PR

**Comment by khavinshankar** [comment]
@nihal467 can please you retest this, seems to be working

**Comment by nihal467** [comment]
@khavinshankar can you merge the development branch

**Comment by nihal467** [comment]
@khavinshankar 
0E6CCE65-8DEB-46FC-B636-4CC3A46CF495

the full screen button not working in incognito mode or normal mode.

**Comment by nihal467** [comment]
LGTM

**Review by gigincg — APPROVED** [review]

**Pull request merged**
