### PR TITLE
Fixed: Update Facility Malfunction

### LINKED ISSUE #3251: Update Facility Page : Malfunction
image

- [ ] i can update the facility page, without selecting the ward, as it is a mandatory field, we should not be able to do that

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #3251
- [x] Added `reset` methods to reset the form value

### CODE REVIEW

**Comment by aeswibon** [comment]
Whenever the value of either State, District, or LocalBody is changed, the other values are not reset. Eg: If we __change the value of LocalBody__, the __form is submitted__ by taking the __previous value of ward__. That ward may not be present in the new LocalBody. This check is not done. I have added the `resetWard` function which will reset the value of __Ward__ when __LocalBody__ is changed. Similarly, the reset function for District and LocalBody too.

**Comment by nihal467** [comment]
@cp-Coder 
image

when iam trying to update the facility district or anything, it is unable to select any other district from the droplist

**Review by Ashesh3 — APPROVED** [review]
LGTM, would it be better if the state name is consistent with its function?
`localBodies, setLocalBodies` instead of `localBody, setLocalBodies` ?

**Comment by nihal467** [comment]
@cp-Coder see a comment by ashesh, check it and remove the question tag

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
