### PR TITLE
Fix mispositioned active link indicator

### LINKED ISSUE #6879: Sidebar link indicator is misplaced if font size is other than default one.
**Describe the bug**
Kinda similar to this bug https://github.com/coronasafe/care_fe/issues/6805
The link indicator logic assumes that font size will always be 16px which is default for browsers. But this hardcoded height makes it look misplaced when user has changed default font size from browser settings.

**To Reproduce**
- Go to browser settings and change default font size to anything other than 16px.
- Go to care and notice the indicator. It's size doesn't change as per new font size. 
- Click on some links in sidebar you'll notice it's not positioned correctly before active link. 

**Expected behavior**
Indicator size should change according to font size. 
Indicator should be positioned accurately before active link.

**Screenshots**
font size is 24px. "Sample test" is active but indicator goes below "Resource"

image

### PR DESCRIPTION
**Pull request by Omkar76**
## Proposed Changes
- Fixes #6879 
- Use ref and get height of link element instead of hard-coding it. 
- Update `top` and `bottom` style of indicator when navigating. 
- If going up first update `top` and then `bottom` after 50ms to see the transition in height happen.
- While going down first update `bottom` and then `up`.
- indicator height is 40% of element.
 
@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

30px
image

12px
image

[indicator-(4).webm](https://github.com/coronasafe/care_fe/assets/56870381/83c2d985-7d37-4961-9e9c-7cc4dca72c26)

### CODE REVIEW

**Comment by Omkar76** [comment]
Video upload is failing. I'll update description with video recording later. Edit: Done.

**Comment by nihal467** [comment]
@Omkar76 marking it for discussion, the link width is increased, which seems a little bit weird to me, for taking others opinion

**Comment by Omkar76** [comment]
As discussed, changes have been made so as to not affect height of indicator at default fonts. I've added video to show the same. height of indicator is relative to link. It takes 26% of height of link and is vertically centered.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
