### PR TITLE
Removed unwanted blank space in info page

### LINKED ISSUE #2878: Revamp Info Page
https://www.loom.com/share/f0dcb02d49e6489d9ce2eebb854db979

we are having a lot of blank space been wasted in the info page

### PR DESCRIPTION
**Pull request by GokulramGHV**
Fixes #2878

### Before:

image

### After:

image

### CODE REVIEW

**Review by developedBySJ — COMMENTED** [review]
Add the read more button to avoid problems with long text

image

image


@gigincg @nihal467

**Comment by nihal467** [comment]
@GokulramGHV is it good for testing, saw a comment by @developedBySJ

**Comment by GokulramGHV** [comment]
@developedBySJ @nihal467 Is this okay?

image

**Comment by nihal467** [comment]
@GokulramGHV

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
