### PR TITLE
Fixed BP Decimal Precision to 2 decimal places

### LINKED ISSUE #2596: BP Decimal Precision to 2 decimal
Screenshot 2022-05-31 183225

the mean along the heading of BP is having correct value, but the another is having lengthy decimal point

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2596 

### Made the values of BP to the precision of 2 Decimal places

https://user-images.githubusercontent.com/59426397/171412580-324733af-4017-4351-9cc3-a584aed5edbc.mp4

### CODE REVIEW

**Review by developedBySJ — CHANGES_REQUESTED** [review]
The code looks complicated and hard to read.
You can easily round off floats by `Math.round(d * 100) / 100`

**Comment by patelaryan7751** [comment]
@developedBySJ Is it okay now?

**Review by developedBySJ — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
@patelaryan7751 the deploy preview is failed

**Comment by patelaryan7751** [comment]
Hey, @nihal467 the deploy preview is ready now.

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
