### PR TITLE
Solve hidden overflow in duplicate patient record modal

### LINKED ISSUE #2671: Malfunction in patient creation Form
ed

in the patient creation form, in the popup, the patient id is not fully visible, and the separation line of data is having a black dots,

### PR DESCRIPTION
**Pull request by skks1212**
closes #2671

image

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Comment by nihal467** [comment]
@skks1212 @gigincg is it good for testing !

**Comment by shivankacker** [comment]
> @skks1212 @gigincg is it good for testing !

Yep! 👍

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
