### PR TITLE
Add Calories Column

### PR DESCRIPTION
**Pull request by sam9111**
Add Calories Column in IO Balance Editor. I have also added the units in the dropdown since calories would typically be kcals.

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Comment by sam9111** [comment]
Added "convert to" mcg or ng option for infusions sections.

**Comment by nihal467** [comment]
dfksdofko

@gigincg @sam9111 test failed, 
- the column heading of the value is misplaced.
- when we select the value unit convert, we can't see the selected unit.

**Comment by sam9111** [comment]
screenshare

@nihal467 I believe the wording must have been confusing. The value would be recorded in the backend in mg unit only. But the user can enter the value in mcg or ng and use the convert option to convert it into the respective value in mg.

**Comment by nihal467** [comment]
@sam9111 @gigincg can you check this !

**Comment by gigincg** [comment]
@sam9111 Hey, the concentration and the volume need to be 2 different values. The concentration would also have a separate Value, and you should not convert this in the UI. You'll have to modify on save and recalculate when you fetch it back. If that feels tedius, you can save the concentration Units as well

**Comment by sam9111** [comment]
I have decided to work on a new branch for this issue. So closing this PR and working on a new PR.

**Pull request closed without merging**
