### PR TITLE
RadioFormField: changed optionDisplay to optionLabel in RadioFormField

### LINKED ISSUE #8529: Consistency in label prop name for `RadioFormField`
The `RadioFormField` component uses `optionDisplay` prop to render the label. However, all other CareUI components such as `SelectFormField`, `MultiSelectFormField`, `AutocompleteFormField`, 'AutocompleteMultiselectFormField`, etc. uses `optionLabel` as the prop name to for the field label.

Hence for improving consistency, let's rename the `optionDisplay` to `optionLabel` for the `RadioFormField` component.

**Screenshots**

### Usages of `optionLabel` (185 results)

image

### Usages of `optionDisplay` (28 results) that needs to be replaced with `optionLabel`

image

### PR DESCRIPTION
**Pull request by xakep8**
## Proposed Changes

- Fixes #8529
- Changed the optionDisplay to optionLabel in `type` defined for props of RadioFormField.
- Updated all usage of optionDisplay to optionLabel.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad can you approve the netlify deploy

**Review by rithviknishad — CHANGES_REQUESTED** [review]
LGTM, but could you discard the changes made to the `package-lock.json` file?

**Comment by xakep8** [comment]
@rithviknishad I've reverted the changes made to `package-lock.json`.

**Review by rithviknishad — APPROVED** [review]

**Review by shivankacker — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM @rithviknishad tested it via locally

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
