### PR TITLE
Reenabled discharge patient admitted to filter

### LINKED ISSUE #7869: Follow-up : Admitted to filter in Facility Specific discharge patient page
**Is your feature request related to a problem? Please describe.**
Follow-up: https://github.com/coronasafe/care_fe/pull/7853
Currently, we are not able to filter patient list in facility specific discharge patient page based on admitted to 

**Describe the solution you'd like**

We should be able to filter the patient discharge list based on the admitted to (bed type) { This status should be based on the last bed assigned to the patient while discharging }

**Describe alternatives you've considered**

image

### PR DESCRIPTION
**Pull request by shivankacker**
Dependent on https://github.com/coronasafe/care/pull/2204

## Proposed Changes

- Fixes #7869
- Enables admitted to (bed types) filter on the discharge patients page

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 

image

- [ ] when we filter patient with "No bed assigned" , the data is not showing the patient card with no bed history.

image
image

- [ ] when i filter the card with "bed with oxygen support" and "ICU" bed type individually, both are filtering it and showing same data

shivank make sure to run basic QA covering :

- whether no bed patients are filtered properly, if they were discharged without bed history
- if a patient have move to multiple bed during the consultation, the filter should only checking his last bed assigned during discharged
- if a patient have multiple consultation, filter it based on latest consultation

**Comment by nihal467** [comment]
@skks1212 The filtering works, but it fails when the same patient is readmitted. Currently, the bed history of the latest active consultation is considered, which should not be the case. Instead, the filter should check the last bed of the latest discharged consultation of the facility

**Comment by nihal467** [comment]
@skks1212 can you clear the merge conflict

**Comment by bodhish** [comment]
Closing this PR due to lack of recent progress.

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
