### PR TITLE
Add toggle for camera access key visibility

### LINKED ISSUE #4120: View/Eye Button for AssetConfigure/Credentials Field
Add an option to reveal the credentials in the Asset Configure Page, similar to the Password Field in the Login Page

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #4120

image
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@Ashesh3 how about using `TextFormField` instead? It is ideal for use in forms and has an error label and input label embedded in the component too.

Feel free to bring support for bringing the password toggle button if it doesn't support already.

**Comment by Ashesh3** [comment]
> @Ashesh3 how about using `TextFormField` instead? It is ideal for use in forms and has an error label and input label embedded in the component too.
> 
> Feel free to bring support for bringing the password toggle button if it doesn't support already.

Done!

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@rithviknishad can u re-review this

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
