### PR TITLE
Improve UI on External Test page

### LINKED ISSUE #2505: UI issues on Upload External Results page
The elements on the Upload External Results seem misaligned, The text "Sample Format" is difficult to see.

image

The error messages are not user friendly:

image
image

Alignment and padding of "No results" should be improved:
image

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #2505 
Backend PR: https://github.com/coronasafe/care/pull/810

Some UI changes to the External Test page.

Before:

image

After:

image

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 merge the latest deployment and check the conflicts

**Comment by Ashesh3** [comment]
@nihal467 Done!

image

**Comment by nihal467** [comment]
image

@Ashesh3 make it responsive

**Comment by Ashesh3** [comment]
@nihal467 Should be more responsive now:

300px width
image

**Comment by nihal467** [comment]
@Ashesh3 
image

check the responsivity

**Comment by Ashesh3** [comment]
Fixed.

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
