### PR TITLE
Tailwind `SearchInput` with keyboard shortcut to focus

### LINKED ISSUE #3898: Ctrl + K shortcut for focus to search box in main pages where search bar is present.
- [x] Tailwind search bar with shortcut input
- [x] Support it to be focused on shortcut `Ctrl` + `K`
- [x] Hide the shortcut key in mobile

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- [x] Tailwind search bar with shortcut input
- [x] Support it to be focused on shortcut `Ctrl K` (`⌘K` on Apple devices)
- [x] Hide the shortcut key in mobile
- Closes #3898

https://user-images.githubusercontent.com/25143503/199454069-e70c2daa-fb26-4034-9066-6795e3cc9c46.mp4

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 
image

is it intentional

**Comment by rithviknishad** [comment]
@nihal467 yes, the colors is intentional. inspired from
https://tailwindcss.com/
image

**Comment by nihal467** [comment]
LGTM, marking it as team discussion required for final approval

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
