### PR TITLE
fixed width of patient bed select dialog box in patient dashboard

### LINKED ISSUE #5557: Bed select dialog width feels too small
**Describe the bug**
Increase bed select dialog's width.

**To Reproduce**

1. Go to a patients dashboard
2. Attempt to switch beds

**Expected behavior**
The width of the bed select dialog should be larger

**Screenshots**
image

### PR DESCRIPTION
**Pull request by satyam0601**
### WHAT
The width of the bed select dialog should be larger
issue image
## Proposed Changes

- Fixes #5557?
-  removed redundant 'max-w-md' tailwind class from Dialog.Panel component

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]
Nice work. @nihal467 could you make sure all popup dialogs are proper when testing since it solves directly by modifying the main dialog component?

**Comment by nihal467** [comment]
@satyam0601 
image

The switch-bed pop-up appears to be well-designed, but the other pop-ups, such as the one that appears after clicking "Add Patient" in the patient tab, are looking strange. Please fix them as per current staging

CC: @rithviknishad

**Comment by satyam0601** [comment]
working on it @nihal467 @nihal467

**Comment by rithviknishad** [comment]
@satyam0601 I'd suggest you to revert the changes in the generic component and instead use classNames to adjust only for the bed select dialog

**Comment by satyam0601** [comment]
i think the appropriate className prop is being sent to the dialog modal in `PatientInfoCard.tsx`, since i am unable to recreate the issue
```javascript
    <>
      <DialogModal
        title={bedDialogTitle}
        show={open}
        onClose={() => setOpen(false)}
        className="w-full max-w-2xl"
      >
```
image
<br>
also, when i remove the className prop in `PatientInfoCard.tsx` it recreates the issue
```javascript
    <>
      <DialogModal
        title={bedDialogTitle}
        show={open}
        onClose={() => setOpen(false)}
        className=""
      >
```
image
@nihal467 @rithviknishad

**Comment by rithviknishad** [comment]
See how its implemented in popups like discharge popup

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
