### PR TITLE
fix(UserProfile): Unable to update user details

### LINKED ISSUE #4059: Unable to update user details in profile page
**Describe the bug**

when we go to the profile page of a user and try to edit our name, it is not getting changed, even though there is an alert coming up mentioning details updated successfully

**To Reproduce**

Step 1: go to https://care.coronasafe.in/user/profile
step 2: update your name on the profile page
step 3: click the update button and the pop up will come stating that the data has been updated successfully
step 4: refresh the page
step 5: see the error that, the user details are not been updated

**Expected behavior**

a user should be able to update his details on the profile page

**Screenshots**

image

### LINKED ISSUE #4126: The profile page of a user is misaligned
**Describe the bug**

when we click the update profile page, the spacing and the alignment of the page is not proper

**To Reproduce**

https://care.coronasafe.in/user/profile

**Expected behavior**

the edit profile page should be properly aligned 

**Screenshots**

image

### PR DESCRIPTION
**Pull request by cp-Coder**
# Bug Fix

## Proposed Changes

- Updated API endpoint to `/users/{username}` with `PATCH` type
- Replaced MUI with Tailwind components
- Reduced padding and made the page responsive

## Associated Issue

- Fixes #4059
- Fixes #4126

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update product[documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [ ] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder 
image

now, we are able to change the profile name but to see the updated profile in the bottom on the tab, we need to manually refresh the page.

**Comment by khavinshankar** [comment]
@cp-Coder can you also handle issue #4126 in this pr?

**Comment by aeswibon** [comment]
> @cp-Coder can you also handle issue #4126 in this pr?

Sure

**Comment by nihal467** [comment]
@cp-Coder 
image

to see the updated name in the tab, I need to refresh the page manually, the issue still persists, do read out the comments and after verifying the issue is resolved, mark it for "need testing"

**Comment by nihal467** [comment]
@cp-Coder what is the status of the PR

**Comment by aeswibon** [comment]
@nihal467 I am not facing this issue in the deployed preview. Can you check it once again?
__PS__: I have attached the recording.

https://user-images.githubusercontent.com/77210185/206228003-d6f4f2fd-b194-465e-9071-2d9504c5d3e8.mp4

**Comment by nihal467** [comment]
@cp-Coder 

https://app.flonnect.com/view/video/nihalcct/6390cc0ff31aaa756ef7693b

see the error, it is not updating in the sidebar in the bottom until we manually reload the entire page

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@cp-Coder also change the buttons from mui to custom component, I'm merging this pr as it is p1 issue, so make a new pr as a follow up

**Pull request merged**
