### PR TITLE
Made The shifting page board responsive

### LINKED ISSUE #2826: shifting page is unresponsive
4-d

the shifting page is not responsive, and it is tested in the iPad dimension

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2826 

# Bugs Fixed

## Made The shifting page board responsive in iPad
- iPad Air
image
- iPad Mini
image

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
@patelaryan7751 test failed, the issue still the same with galaxy fold

**Comment by patelaryan7751** [comment]
@nihal467 Now it is responsive in Samsung fold I guess
image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
