### PR TITLE
Updated Rhythm View to table for easy access and efficiency

### PR DESCRIPTION
**Pull request by skks1212**
This PR closes [https://github.com/coronasafe/care_fe/issues/2258](https://github.com/coronasafe/care_fe/issues/2258).
A table has been added to keep track of patient rhythm details
The new UI looks like this 
image

### CODE REVIEW

**Comment by gigincg** [comment]
@skks1212 Add a Screenshot to the new UI!

**Comment by shivankacker** [comment]
> @skks1212 Add a Screenshot to the new UI!

Edited!
image

**Comment by sainak** [comment]
@skks1212 can you try making the time and rhythm column a bit narrower because they don't need that much space.

**Comment by shivankacker** [comment]
> @skks1212 can you try making the time and rhythm column a bit narrower because they don't need that much space.

The other columns will automatically give space to the description columns if needed. I have not limited space for sake of responsiveness.

**Comment by nihal467** [comment]
test approved

**Pull request merged**
