### PR TITLE
Remove libphonenumber js

### LINKED ISSUE #6082: remove libphonenumber-js
**Is your feature request related to a problem? Please describe.**
Remove libphonenumber-js package as part of reducing bundle size epic issue

**Describe the solution you'd like**
Replace libphonenumber-js with custom function to format phone number

### PR DESCRIPTION
**Pull request by print-Sathvik**
### WHAT
Replaced libphonenumber-js with custom functions

## Proposed Changes

- Fixes #6082 
- Deleted libphonenumber-js
- Implemented methods to parse phone number, format phone number, check its validity, and fetch country code from phone number

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### HOW
- For getting country name from phone number, the country whose country code is longer is returned in case there are multiple matches. For example when +1242 is typed, the country returned is Bahamas(+1242) instead of US(+1) or Canada(+1)
- When there is a clash in country codes(like many North American countries have +1 as country code), their area code is checked.
- Only Indian phone numbers are formatted as +91 nnnnn nnnnn. To format phone numbers of other countries we will need their area codes and there are many rules to be considered which is not practical without using library
- Landline numbers will be formatted as cc nnnn nnnn or ccc nnn nnnn or cccc nnn nnn where 'c' is a digit of area code. Also the leading zeros for area codes are removed. This was how the function from libphonenumber-js was formatting. 

### <samp>🤖 Generated by Copilot at 1b89556</samp>

*  Remove `libphonenumber-js` dependency and replace it with custom phone number parsing and formatting functions ([link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L75))
*  Add `AREACODES` and `IN_LANDLINE_AREA_CODES` constants to store the area codes for different countries and Indian landline numbers ([link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-37705b30476b14631124ce42dd5c3500d43fbede16f0e91f9ae2905e4adc6376R1005-R1127))
*  Add `parsePhoneNumber`, `formatPhoneNumber`, and `getCountryCode` functions and `CountryData` interface to `src/Utils/utils.ts` to implement the custom phone number logic ([link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-5903b23c9778624d9c178b9779024a4265e5fc365714fed34d49225ee6b8dc73R248-R379))
*  Change the `code` values for some countries in `src/Common/static/countryPhoneAndFlags.json` to remove the `+` and `-` symbols and handle countries with multiple area codes under the same country code ([link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L27-R32), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L59-R63), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L81-R84), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L94-R94), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L106-R106), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L117-R118), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L126-R134), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L155-R158), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L188-R188), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L217-R220), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L231-R231), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L242-R245))
*  Change the `parse` function for the `support_phone` field in the `XLSXAssetImportSchema` to use the custom `PhoneNumberValidator` function and handle the `1800` prefix differently ([link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-37705b30476b14631124ce42dd5c3500d43fbede16f0e91f9ae2905e4adc6376L940-R948))
*  Change the phone number fields validation, parsing, and formatting in various components to use the custom functions from `src/Utils/utils.ts` and handle the `+91` and `1800` prefixes differently ([link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-3ff48bac32004c8412fdd842f678d61ab738bbada999fa8d9fa1da73f760ea11L68-R68), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-d7d19aab87f2678510fa29d56b44e2a94098c956b954df68110c117f7f366073L344-R343), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-2cc6bedfa390407b524789d1828633368f746e65564574ffa86b715c469c8098L150-R152), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c1bd2754f233548fd1a6217ebe45fe603c71864f10c26f6350596f85b39e000cL437-R445), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c1bd2754f233548fd1a6217ebe45fe603c71864f10c26f6350596f85b39e000cL491-R495), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eL76-R59), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eR66-R67), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eL109-R91), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eL125-R107), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eL179-R171), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-6a60fce2df893cf91c0457f6445b903c1d6667b6a86fc21c38a9e8fc385c7575L163-R166), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-09e14a8b77195fb6628b716eb09a71a996a55f559ddc5c3ef19d3c54948a4775L101-R105), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-09e14a8b77195fb6628b716eb09a71a996a55f559ddc5c3ef19d3c54948a4775L599-R618), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-09e14a8b77195fb6628b716eb09a71a996a55f559ddc5c3ef19d3c54948a4775L732-R745), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-09e14a8b77195fb6628b716eb09a71a996a55f559ddc5c3ef19d3c54948a4775L915-R928), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-09e14a8b77195fb6628b716eb09a71a996a55f559ddc5c3ef19d3c54948a4775L961-R974), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-7ec03dd8838e59d1d7ef0aa4f42c6ed82aa5f086d5d280b42617974f674f561fL59-R60), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-7ec03dd8838e59d1d7ef0aa4f42c6ed82aa5f086d5d280b42617974f674f561fL65-R66), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-7ec03dd8838e59d1d7ef0aa4f42c6ed82aa5f086d5d280b42617974f674f561fL165-R169), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-7ec03dd8838e59d1d7ef0aa4f42c6ed82aa5f086d5d280b42617974f674f561fL225-R234), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-60a064d920f5f0359fb42250988ba67773d6bcf0e5e506b011ece11471ef740aL44-R45), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-60a064d920f5f0359fb42250988ba67773d6bcf0e5e506b011ece11471ef740aL134-R142), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-60a064d920f5f0359fb42250988ba67773d6bcf0e5e506b011ece11471ef740aL197-R201), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-9bd3f042da788b477c58be6b5fe84715b43138511ba961eda57b3317333bfe18L210-R212), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-5d9f2efbfb558b3bdc89362fef4a25f68c166440805631dfb6d12b8701f9236fL225-R228), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-61941d2843942da2640b50b54d0f8503484ec0a268e75b7962d90faf364d3827L475-R482), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-61941d2843942da2640b50b54d0f8503484ec0a268e75b7962d90faf364d3827L494-R497), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-61941d2843942da2640b50b54d0f8503484ec0a268e75b7962d90faf364d3827L575-R586), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-f9f925077f8a2a85dc2ce98d7b1d106635fccd175f50e19fd28f403d28029807L17-R18), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-f9f925077f8a2a85dc2ce98d7b1d106635fccd175f50e19fd28f403d28029807L28-R29), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-212e167063b7d0bd79ef5e31edcc0aa76904bfa277b7d6fa0966055cecc5064dL202-R207), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-212e167063b7d0bd79ef5e31edcc0aa76904bfa277b7d6fa0966055cecc5064dL222-R222), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-212e167063b7d0bd79ef5e31edcc0aa76904bfa277b7d6fa0966055cecc5064dL303-R299))
*  Remove unused `libphonenumber-js` imports from various files ([link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-37705b30476b14631124ce42dd5c3500d43fbede16f0e91f9ae2905e4adc6376L4-R6), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c2412847db74965b2f824d87d0a0dc4a291eb876affe61e985e68ceef1947947L5-R18), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-3ff48bac32004c8412fdd842f678d61ab738bbada999fa8d9fa1da73f760ea11L9-R9), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-d7d19aab87f2678510fa29d56b44e2a94098c956b954df68110c117f7f366073L33), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c1bd2754f233548fd1a6217ebe45fe603c71864f10c26f6350596f85b39e000cL29-R34), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-09e14a8b77195fb6628b716eb09a71a996a55f559ddc5c3ef19d3c54948a4775L61), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-61941d2843942da2640b50b54d0f8503484ec0a268e75b7962d90faf364d3827L2), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-f9f925077f8a2a85dc2ce98d7b1d106635fccd175f50e19fd28f403d28029807L6-R6), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-212e167063b7d0bd79ef5e31edcc0aa76904bfa277b7d6fa0966055cecc5064dL11))
*  Add `parsePhoneNumber` and `PhoneNumberValidator` imports to various files to use the custom functions from `src/Utils/utils.ts` and `src/Components/Form/FieldValidators.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-d7d19aab87f2678510fa29d56b44e2a94098c956b954df68110c117f7f366073L39-R38), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-2cc6bedfa390407b524789d1828633368f746e65564574ffa86b715c469c8098L12-R12), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-c1bd2754f233548fd1a6217ebe45fe603c71864f10c26f6350596f85b39e000cL54-R62), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eL42-L56), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-09e14a8b77195fb6628b716eb09a71a996a55f559ddc5c3ef19d3c54948a4775R28), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-09e14a8b77195fb6628b716eb09a71a996a55f559ddc5c3ef19d3c54948a4775L43-R48), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-7ec03dd8838e59d1d7ef0aa4f42c6ed82aa5f086d5d280b42617974f674f561fR31), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-60a064d920f5f0359fb42250988ba67773d6bcf0e5e506b011ece11471ef740aR28), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-61941d2843942da2640b50b54d0f8503484ec0a268e75b7962d90faf364d3827L28-R31), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-61941d2843942da2640b50b54d0f8503484ec0a268e75b7962d90faf364d3827R47), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-212e167063b7d0bd79ef5e31edcc0aa76904bfa277b7d6fa0966055cecc5064dL17-R16), [link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-212e167063b7d0bd79ef5e31edcc0aa76904bfa277b7d6fa0966055cecc5064dR25))
*  Add `useEffect` hook to `src/Components/Form/FormFields/PhoneNumberFormField.tsx` to initialize the `field.value` with `+91` if it is empty ([link](https://github.com/coronasafe/care_fe/pull/6222/files?diff=unified&w=0#diff-a3de35fe1ee44fd0ec04a82bf508c17c010278d094beb28630efc1264830d01eR66-R67))

### CODE REVIEW

**Comment by nihal467** [comment]
@print-Sathvik the cypress is failing back to back, fix it , PR looks good to me

**Comment by print-Sathvik** [comment]
@rithviknishad New changes:
- Phone number in excel file for importing asset does not have country code. So I adjusted that part by adding country code before validating.
- After uploading the excel file location with value "Camera Locations" was being selected but there is no such location, so I changed it to "Camera Loc" as this is used in other tests.

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]
Nice Work! LGTM

**Comment by rithviknishad** [comment]
Just a minor suggestion, you could've moved the phone number related utility methods to a seperate file under say: `src/Utils/PhoneNumberUtils.ts`

Currently, the `utils.ts` file feels too big and we should consider splitting it based on relevance.

**Comment by print-Sathvik** [comment]
> Just a minor suggestion, you could've moved the phone number related utility methods to a seperate file under say: `src/Utils/PhoneNumberUtils.ts`
> 
> Currently, the `utils.ts` file feels too big and we should consider splitting it based on relevance.

I pulled, rebased and separated phone number utils in my local but that requires me to force push to current branch. Doing that will close this PR. So I will create a new PR for seperating phone number utils once this PR is merged.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
