### PR TITLE
Disallow empty notes and comments

### LINKED ISSUE #2507: Empty notes and comments should not be allowed
Comment/Notes field should not be optional. Empty message should not be allowed.

Patient Notes:
image

Resource details page:
image

Appropriate message should be shown if the content is empty.

Intended Behavior should be similar to this:

Shifting details page:
image

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #2507

Patient Notes:
image

Resource details page:
image

### CODE REVIEW

**Comment by patelaryan7751** [comment]
Hey @Ashesh3 I found a bug in the shifting page comment posting algorithm we can easily overide the check **"Comment should contain 1 character"** by giving **space** . You can view it here #2532 for more detail demonstration. 

I think we need to also have a check for spaces it might go like this:

```
// Explanation
const notes= " Hello Doctor  "
console.log(notes,notes.length);
console.log(notes.trim(),notes.trim().length);

/* Output
Hello Doctor   15
Hello Doctor 12
*/

// Implementation
if (noteField.trim().length < 1) {
      Notification.Error({
        msg: "Note Should Contain At Least 1 Character",
      });
      return;
    }
```

**Review by developedBySJ — CHANGES_REQUESTED** [review]
Make changes suggested by @patelaryan7751

**Comment by Ashesh3** [comment]
Using `/\S+/` to check if the string is empty or not. 

image

**Comment by patelaryan7751** [comment]
Fixes #2532

**Comment by nihal467** [comment]
@Ashesh3 @gigincg is it good for testing ?

**Comment by Ashesh3** [comment]
> @Ashesh3 @gigincg is it good for testing ?

Yep, it is!

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Comment by gigincg** [comment]
@Ashesh3 Can you make the Backend issues as well for this?

**Comment by Ashesh3** [comment]
> @Ashesh3 Can you make the Backend issues as well for this?

Sure, On it!

**Comment by Ashesh3** [comment]
> @Ashesh3 Can you make the Backend issues as well for this?

Made it here: https://github.com/coronasafe/care/pull/838

**Pull request merged**
