### PR TITLE
Issue 2962 - scroll to top if in whitelist

### LINKED ISSUE #2962: In Patient Dashboard Page while changing tabs the scroll bar is coming to top of page in mobile devices
# Bugs 

## In Patient Dashboard Page while changing tabs the scroll bar is coming to the top of the page on mobile devices instead the scroll should be near the tabs section.
https://user-images.githubusercontent.com/59426397/176984704-1b52748c-2958-41fe-ab14-1ad649c2fb42.mp4

### PR DESCRIPTION
**Pull request by Ritesh-Aggarwal**
## Proposed Changes

- scroll to top only if link regex in whitelist
- closes #2962 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
@Ritesh-Aggarwal can you double-check it once again, when I go to the pressure sore tab, it scrolls to the top, also when I go to a different tab and go back to updates, it scrolls back to the top, also check other tabs too

**Comment by Ritesh-Aggarwal** [comment]
going to updates tab will always scroll to top that is the expected behavior
I have fixed the pressure sore tab and checked all other tabs 
good to go now
@khavinshankar

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
