### PR TITLE
Fixes facility cover image from not reloading after upload

### LINKED ISSUE #8401: Facility Cover Image is not getting auto-refresh post upload
**Describe the bug**

When you successfully upload a facility cover image, you need to manually refresh the page once to view the newly uploaded cover image

**To Reproduce**

1. Login to the platform and click on view facility button in any card
2. click on the cover image and try to upload a image
3. upon successfully upload a cover image, See error

**Expected behavior**

upon successful cover image upload, the facility detail page state should refresh to show the newly uploaded cover image rather than making user to manually refresh the page to view the new image

**Screenshots**

image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Fixes #8401
- Regression from #7368 
- Adds a note about time taken for cache invalidation when updated

image

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by gigincg** [comment]
@rithviknishad I think this is a better approach, but the browser cache would still cause the old image to persist. Maybe adding the imageKey back might help.

**Comment by rithviknishad** [comment]
@gigincg Added a note to indicate about time taken for browser cache invalidation

image

**Comment by gigincg** [comment]
@rithviknishad The note isn't showing up on Mobile Screens

image

**Comment by rithviknishad** [comment]
Updated and improved the design

image


image

**Pull request merged**
