### PR TITLE
Changes in Patient Registration Form 

### PR DESCRIPTION
**Pull request by sam9111**
Screenshot 2022-04-18 at 8 57 28 PM

- [x]     Remove "Frontline Worker"
- [x]     Remove "Is a medical worker?"
- [x]     Remove "Is a Guests Worker?"
- [x]     Remove "Domestic International Air Travel"
- [ ]     Occupations field is added as a dropdown with a radio buttons for specifying if "head of household"
  Screenshot 2022-04-18 at 8 56 57 PM

### CODE REVIEW

**Comment by nihal467** [comment]
@sam9111 @gigincg test failed, once we save the patient registration form by selecting yes in " head of household ", and when we try to update the existing details after saving it, the selected option is blank.

peofjewop

**Comment by aparnacoronasafe** [comment]
@sam9111 Why are we asking "is the patient head of the household"?

**Comment by nihal467** [comment]
GERG

merging Conflicting files also here @gigincg @sam9111

**Comment by nihal467** [comment]
GERG

there is a merging conflict, too, @gigincg @sam9111

**Pull request merged**
