### PR TITLE
Icon overlapping with text in text-box of Doctor's Notes. #7495

### LINKED ISSUE #7495: Icon overlapping with text in text-box of Doctor's Notes.
**Describe the bug**

**To Reproduce**

1. Go to Doctor's Notes
2. Write on the text box till it completes one row
3. See error

**Expected behavior**
Screenshot 2024-03-29 at 11 39 06 PM

**Screenshots**
Currently,
Screenshot 2024-03-29 at 11 38 35 PM

### PR DESCRIPTION
**Pull request by Sulochan-khadka**
## Proposed Changes

- Fixes #7495 
- Improved alignment

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by rithviknishad** [comment]
Hey @Sulochan-khadka 
Could you resolve the merge conflict?

**Comment by Sulochan-khadka** [comment]
> Hey @Sulochan-khadka Could you resolve the merge conflict?

Yeah sure... I will do...

**Comment by Sulochan-khadka** [comment]
@rithviknishad have solved merge conflicts... Kindly have a look.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@Sulochan-khadka the UI doesn't look good, can you try to implement Ui similar to slack 

image

**Comment by Sulochan-khadka** [comment]
@nihal467 sure... But then I need to make changes to another issue that was solving that of patient's notes. Shall I go ahead and make your suggested changes on both?

**Comment by Sulochan-khadka** [comment]
> @Sulochan-khadka the UI doesn't look good, can you try to implement Ui similar to slack
> 
> image

Should I add a rich text editor ? something like react-quill? Or you just want to correct the alignment . I think adding something like react quill will obviously be a firm step towards improving the doctor's notes functionality for example, adding markdown feature and file upload functionality. Let me know your thoughts on this.

**Comment by nihal467** [comment]
@rithviknishad can you comment on this issue

**Comment by rithviknishad** [comment]
@Sulochan-khadka I'd suggest creating a separate issue for that as that would be a larger change and the related issue simply needs to solve the icon overlapping issue and have a good UI.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
