### PR TITLE
upgraded tailwindcss to v3

### LINKED ISSUE #2375: Upgrade Tailwindcss to latest version
Current tailwind is 2 versions behind. To unlock more features we need to upgrade to v3.0.24

### PR DESCRIPTION
**Pull request by cp-Coder**
## Issue Fixed
#2375

## Updates
- [x] Upgraded to tailwindcss v3
- [x] Upgraded postcss and autoprefixer
- [x] Removed @tailwindcss/ui plugin according to this [post](https://github.com/tailwindlabs/tailwindui-issues/issues/1089#issuecomment-991661639)

### CODE REVIEW

**Comment by sainak** [comment]
@cp-Coder tailwindcss/custom-forms needs to be migrated to tailwindcss/forms https://tailwindcss.com/blog/tailwindcss-v2#utility-friendly-form-styles

**Comment by shivankacker** [comment]
@cp-Coder please try to resolve the issues asap! A lot of UI overhauls need the latest tailwind dist. 😅

**Comment by aeswibon** [comment]
@skks1212  I didn't add package-lock.json so it was showing build issues as there were many packages that I have removed during tailwind update.

**Comment by nihal467** [comment]
@cp-Coder @gigincg can you check the conflicting file

**Comment by nihal467** [comment]
@cp-Coder @gigincg the netlify deploy preview is showing failed, can you check it

**Comment by aeswibon** [comment]
@nihal467 now netlify checks are passing.

**Comment by nihal467** [comment]
@gigincg @cp-Coder test failed



- [ ] username and password box is coloured with a blue line
- [ ] login button is having a black border



- [ ] the notification tab is having by default a black border



- [ ] it is hard to view the facility and the patients button in the facility page.



- [ ] in the facility detail page, all the buttons are having black borders, which is not looking good in the UI
- [ ] the separation by a line for the information on oxygen, bed capacity, doctors list, and corona triage is missing



- [ ] all the heading and the cards are overlapping to each other



- [ ] in the assets, there is no lines present to separate them.
- [ ] the search box and all the buttons are having black border



- [ ] the search by name box size is high and overlapping with the button
- [ ] live and discharge button is not working smoothly, and the colour of the button is blue with live and dischage
- [ ] there is no line separating the patient names
- [ ] the add details of a patient button is having black border
- [ ] download live list and download all patient buttons having a border would look good.



- [ ] all the buttons are having black border
- [ ] all the user cards are assembles in vertical, and there is a lot of white space been wasted on the right side



- [ ] the active, completed, list view and filters buttons are not looking good
- [ ] the datas in the shifting cards look scrambled
- [ ] patient name box is having higher space and black border
- [ ] all details button is having black border



- [ ] the black border is present for the back button and referral letter
- [ ] Details of the patient are looking scrambled, a change of UI will be better



- [ ] doctor video, create investigation and all the buttons are having black border
- [ ] when we are clicking the update, summary, etc... button, they are not showing any indication that it is been selected.
- [ ] in the nursing analysis, all the cards are overlapping.



- [ ] in the IO Balance plot, intake and output are having black border
- [ ] all the graphs are not having any borders



- [ ] all the boxes having the black border
- [ ] the boxes are overlapping
- [ ] the boxes are oversized

**Pull request merged**
