### PR TITLE
Issue: 7132 - Disallow Add Consultation updates for active consultations without bed assigned

### LINKED ISSUE #7132: Able to create daily round update without a bed assigned through patient details page but not through consultation dashboard
**Describe the bug**
When a consultation has no bed assigned, we are restricted from filing a log update if there is no bed assigned if the "Log update" button is clicked from the consultation dashboard.

However, if we go to the patient details page and click "Add consultation updates" we can still access the daily round form and we can file a Daily Round log update successfully. This should not be allowed.

**Expected behavior**
Disallow "Add consultation updates" button for active consultations without a bed assigned.

**Screenshots**
image

image

image

image

### PR DESCRIPTION
**Pull request by mohanrajnambe**
… assigned

## Proposed Changes

- Fixes #7132 
- Change 1 Restrict the "Add Consultation Updates" button functionality when active consultations are without bed assigned in Patient Details screen

image
image

- Change 2
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by mohanrajnambe** [comment]
@rithviknishad Please let me know if anything else needs to be updated on this PR

**Comment by nihal467** [comment]
@mohanrajnambe 
image

the add consultation update button is still not working after assigning a bed

**Steps to replicate the bug** 

- when i click on the add consultation update button for an admission patient with no bed assigned
- the pop-up for assigning bed came in, and I assigned a bed to the patient
- then again try clicking the add consultation update button, it still asks me to assign the bed ( bug)

**Comment by mohanrajnambe** [comment]
@nihal467 
 the add consultation update button is still not working after assigning a bed - bug is fixed and working as expected. Please review and test once again.

**Comment by nihal467** [comment]
LGTM

**Review by Ashesh3 — APPROVED** [review]

**Review by rithviknishad — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
