### PR TITLE
Alignment issue of Patient Page

### LINKED ISSUE #2819: Fix Position & Font for Heading
3-a

When we are taking the Facility, patient, asset, etc... tab, the heading is having different positioning. So making a fixed position for all the tab, will improve the UI experience.

### LINKED ISSUE #3135: Resource & Shifting Page : Revamp List View
image

image

make the header with active, complete patients and filters, etc. with the same alignment to the list view as it is in the board view for both shift and resource page

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #2819
- [x] Fixes #3135 
- [x] Fixed `Alignment` issue for Patient Page

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder test failed, the alignment issue of heading is for all the pages starting from the facilities tab to user management, make the heading stationery, than moving from one position to another on each pages

**Comment by nihal467** [comment]
@cp-Coder check the merge conflict !

**Comment by nihal467** [comment]
15a

@cp-Coder the page is not aligned properly, compare the alignment with the white box at the bottom and fixed the position. Make a uniform position throughout all page

If the white box is short, increase the size of the white box on required pages to match with the heading alignment.

NB: Check for all the tabs

**Comment by nihal467** [comment]
@cp-Coder little bit more aligning to be done all all pages, kindly check it

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — COMMENTED** [review]
@cp-Coder is the changes in other files (other than patients page) intentional?

**Comment by aeswibon** [comment]
> @cp-Coder test failed, the alignment issue of heading is for all the pages starting from the facilities tab to user management, make the heading stationery, than moving from one position to another on each pages

@khavinshankar Yep. In the above comment, nihal told to make all the alignment stationary. That's why I have made those changes

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
