### PR TITLE
Switch to Tailwind elements for bed capacity

### LINKED ISSUE #4202: Upgrade the facility bed capacity into tailwind
image

https://care.coronasafe.in/facility/63086719-10ec-4c6c-9b43-4b0f87ca6cba/bed

- [ ] Replace dropdown to newer tailwind dropdown
- [ ] change the buttons from material UI to newer tailwind.

### PR DESCRIPTION
**Pull request by Ashesh3**
Resolves #4202 

image
image
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Comment by khavinshankar** [comment]
@Ashesh3 can you merge this with the develop branch and after merging if cypress fails, please do resolve that

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@Ashesh3 can you resolve the failing cypress tests

**Comment by Ashesh3** [comment]
@khavinshankar Done! Tests are passing now.

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
