### PR TITLE
Show password requirement error during input

### LINKED ISSUE #3907: User Password condition to be check before form submission
**Describe the bug**

Before, submitting the add user form, we are not able to check whether the password passes all the conditions required to be followed while creating one.

**To Reproduce**

https://care.coronasafe.in/user/add

**Expected behavior**

- [ ] implement a password condition check similar to the one been used in user id 
image

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #3907 

IncredibleMegalosaurus

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@Ashesh3 the PR LGTM, and it serve the purpose.

image

Iam marking it team discussion required since i feel like making it similar to the username validation is good, don't work on this comment until it is approved in today's EOD

**Comment by nihal467** [comment]
@Ashesh3 as we discussed in the EOD, make the requirement of password been shown similar to the username 
image

**Comment by Ashesh3** [comment]
@nihal467 Done.

DarkcyanElkhound

**Comment by nihal467** [comment]
@Ashesh3 
image

even if the password column is empty, it is saying confirmed. can you fix it, like someone type a single character, then only this condition start coming

**Comment by Ashesh3** [comment]
@nihal467 Done.

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — CHANGES_REQUESTED** [review]
@Ashesh3 can you make a separate component or function for the validation rules, something like,

```js
const validationRule = (valid, content) => {
return (
  <div>
      {valid ? (
        <i className="fas fa-circle-xmark text-red-500" />
      ) : (
        <i className="fas fa-circle-check text-green-500" />
      )}{" "}
      <span
        className={clsx(
          valid
            ? "text-red-500"
            : "text-primary-500"
        )}
      >
        {content}
      </span>
    </div>
)
}
```

**Comment by Ashesh3** [comment]
> @Ashesh3 can you make a separate component or function for the validation rules, something like,
> 
> ```js
> const validationRule = (valid, content) => {
> return (
>   <div>
>       {valid ? (
>         <i className="fas fa-circle-xmark text-red-500" />
>       ) : (
>         <i className="fas fa-circle-check text-green-500" />
>       )}{" "}
>       <span
>         className={clsx(
>           valid
>             ? "text-red-500"
>             : "text-primary-500"
>         )}
>       >
>         {content}
>       </span>
>     </div>
> )
> }
> ```

That's a good suggestion, definitely makes the code cleaner. Done!

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
