### PR TITLE
Removed max height and filtered users by doctor type in DoctorVideoSlideover

### LINKED ISSUE #2515: Doctor Video Menu
On the patient dashboard (https://care.coronasafe.in/facility/3fec5944-e6b4-4c56-bd01-95f32813578d/patient/f0a1f32a-22fd-4514-b266-9d8ffc670fb5/consultation/1b0dabc7-e641-417f-83d3-032f6285a99e)

when the user clicked on "Doctor Video" a menu on the right side opens up with all the doctors contacts. 

Even when there are more than 5 doctors registered, only 5 items on top of the list shows up. The rest is available only upton scrolling.

Change this and use the entire length of the screen to show the list of doctors.
Screenshot 2022-05-25 at 7 40 36 PM

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #2515 

- [x] removed max height

UI initially:
image

UI now:
image

### CODE REVIEW

**Comment by khavinshankar** [comment]
- [x] show only doctors instead of all users

image

**Comment by nihal467** [comment]
esofesopf

@khavinshankar @gigincg the alignment is off, can you realign it!

**Comment by khavinshankar** [comment]
fixed the padding issue

image

**Comment by nihal467** [comment]
test approved

**Pull request merged**
