### PR TITLE
Added Cypress test for adding doctor's note.

### LINKED ISSUE #4235: Cypress: Add doctor's note to a patient page

### PR DESCRIPTION
**Pull request by SahilSingh177**
### WHAT

Added test that adds doctor's note to a patient and verifies if the note has been added successfully.

## Proposed Changes

- Fixes #4235 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by SahilSingh177** [comment]
> @SahilSingh177 is attempting to deploy a commit to the **Coronasafe** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=Coronasafe&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%22164fadbde2c0a0bbad6d144f6c101b8b37f40967%22%7D%2C%22id%22%3A%22QmWfLJxsgZfTCbSzDUM1o96qXCgUXx5v3wABC7ULTyTUm3%22%2C%22org%22%3A%22coronasafe%22%2C%22prId%22%3A5620%2C%22repo%22%3A%22care_fe%22%7D).

I encountered the same issue with my previous pull request and it did not occur earlier. What could be causing this?

**Comment by rithviknishad** [comment]
@SahilSingh177 you can ignore that. Outside collaborators needs approval to get preview deploys on vercel. However, we are using vercel deployments in this repo only for CareUI storybook.

**Comment by rithviknishad** [comment]
@SahilSingh177 could you refrain from force pushing?

**Comment by SahilSingh177** [comment]
I'm sorry. I didn't want this PR to have too many unnecessary commits for merging. I won't be force pushing now.

**Pull request closed without merging**
