### PR TITLE
Added appropriate message when no data is found

### LINKED ISSUE #2403: Display appropriate message when no data is found
In the patient details section on the investigation tab, if no investigation data is available it is just blank and no appropriate message is displayed.

Link: https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/dbad1792-62ae-49e8-b1c6-cf91e5d42257/consultation/e689e7de-481f-4df5-a15c-9e4d80c8b3dc/investigations

image

And it is the same for the 'Medicines' and 'Nursing Analysis' tabs.

image
image

### PR DESCRIPTION
**Pull request by GokulramGHV**
Fixes #2403 

When no data is found, an appropriate message stating that no data is available is displayed.

image

image

image

### CODE REVIEW

**Comment by nihal467** [comment]
@GokulramGHV @gigincg 
poewkf

test failed, as there is no message showing in the medicine

**Comment by GokulramGHV** [comment]
@nihal467 It is working for me...
Can you please share the link of the patricular page in which it is not working?

image

**Comment by nihal467** [comment]
@GokulramGHV @gigincg 

https://deploy-preview-2474--care-net.netlify.app/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation/95cef5a8-e8f0-4559-a3b1-71a0cbd33ea6/medicines

check this patient, it is not showing any message

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — CHANGES_REQUESTED** [review]
please work on following changes,
- [ ] when an import is not used remove it instead of commenting it out
- [ ] similarly for the unused variables, functions and interfaces, remove them instead of commenting it out
- [ ] try to fix the eslint errors instead of using eslint disable (only when fixing the error is not possible go with eslint disable)

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
