### PR TITLE
fix: Placeholder and autofill credentials overlap in chrome

### PR DESCRIPTION
**Pull request by Pragati1610**
fixes https://github.com/coronasafe/care_fe/issues/3992

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Review by Ashesh3 — COMMENTED** [review]
It does the job, but I feel it breaks the original design where the placeholder would be inside the input fields when the form is loaded empty.

Original design (on page load):
image

With this PR (on page load):
image

**Comment by nihal467** [comment]
@Pragati1610 marking it for team discussion, for reviewing the PR

**Comment by gigincg** [comment]
https://medium.com/weekly-webtips/detecting-chrome-autofill-on-page-load-78ea178e4a68

@Pragati1610 We need to detect autofill and not focus when there is nothing to autofill

**Review by Ashesh3 — APPROVED** [review]
Works great, tested on Firefox, Edge and Chrome.

**Comment by nihal467** [comment]
@Pragati1610 LGTM, great work, Marking it team discussion for final approval

**Few points to discuss on EOD**

- the font size on autofill is different compared to the actual one

image

when we click somewhere on the page, the font gets back to normal one

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@nihal467 does this require team discussion or can I go ahead and merge this?

**Comment by Ashesh3** [comment]
> @nihal467 does this require team discussion or can I go ahead and merge this?

We discussed it a day back on EOD (after this was marked for discussion), and this was approved. 😄

**Pull request merged**
