### PR TITLE
Use facility.middleware_address for asset.meta.middleware_hostname

### LINKED ISSUE #4356: Purge `asset.meta.middleware_address` in favour of `facility.middleware_address`
As a follow up of https://github.com/coronasafe/care_fe/issues/4122 We need to purge the `asset.meta.middleware_address` and replace all usages of it with `facility.middleware_address`

### PR DESCRIPTION
**Pull request by khavinshankar**
## Proposed Changes

- Fixes #4356
- resolved facilityId type mismatch
- use facility.middleware_address for asset.meta.middleware_hostname

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar 
image

the camera input is coming in and it is working fine , but there is a error message coming in

**Comment by khavinshankar** [comment]
@nihal467 the above-mentioned error is from the backend. In the backend, it is still using `asset.meta.middleware_hostname`

_get_url function in the image_
image

**Comment by khavinshankar** [comment]
@nihal467 I have made a pr https://github.com/coronasafe/care/pull/1127 in the backend related to the above-mentioned issue, once that is merged this pr can be tested.

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
