### PR TITLE
Added drag and drop feature in Shifting BoardView

### LINKED ISSUE #2400: Draggable Components on Shifting Page
## Implementation Details
- This requires you to take care of access control limitations.
- A lot of work is required depending on the stage it is moved
- Create a modal for additional fields to be filled.

Shifting Page:
image

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #2400 

_can drag a shifting card from one board to another, when dropped it will be redirected to shift details update form where status is pre filled according to the board in which card was dropped_

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar @gigincg test failed,
- [ ] the card is really transparent, so it's hard to see.
- [x] when we move to the rightmost corner, the page is not scrolling to the additional sections

**Comment by khavinshankar** [comment]
@nihal467 
about the opacity issue, it seems this is a default behavior and can't be modified easily. 
_please refer this: https://stackoverflow.com/questions/9712535/html5-drag-and-drop-no-transparency_

and about the scrolling, this issue is fixed.

I think we can overlook the ghosting (opacity) issue for now.
@gigincg what's your thoughts?

**Comment by nihal467** [comment]
@gigincg @khavinshankar what are your thoughts! is it good for testing

**Comment by gigincg** [comment]
@nihal467 I think its good to go!

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
Closing this pr because of wrong merge, follow up with #2681

**Pull request closed without merging**
