### PR TITLE
ConsultationDetails.tsx split into seperate components.

### LINKED ISSUE #5830: Code Refactor: `ConsultationDetails.tsx`
`ConsultationDetails.tsx` contains 1000+ lines of hard-to-maintain code for all the tabs.

- [x] Break each tab into a separate component
- [x] Use object to show current tab.

Currently we are doing 
```jsx
{tab === "UPDATES" && <div>....</div>}
{tab === "FEED" && <div>...</div>}
```

Instead, we could do something like:

```jsx
// ConsultationUpdatesTab.tsx

export interface ConsultationTabProps {
  // necessary props received for each tab
}

export default function ConsultationUpdatesTab(props: ConsultationTabProps) {
  return <div>...</div>
}


// ConsultationDetails.tsx

const CONSULTATION_TABS = {
  UPDATES: ConsultationUpdatesTab,
  FEED: ConsultationFeedTab,
  ...
}

...

const SelectedTab = CONSULTATION_TABS[tab];

return <div>
  ...
  <SelectedTab {...necessaryProps} />
  ...
</div>

```

### PR DESCRIPTION
**Pull request by thtauhid**
### <samp>🤖 Generated by Copilot at b736565</samp>

This pull request adds several new components to the `ConsultationDetails` folder that render different tabs for displaying various data and plots related to a consultation. The components use existing components from other folders and pass the appropriate props to them. The components also use the `PageTitle` component to show the name of each tab.

## Proposed Changes

- Fixes #5830

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at b736565</samp>

*  Add new components to render different tabs for a consultation ([link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-0e6e5e77ece2a61a932971c45a635933842da6021cec723d93c80359c1b6e2f0R1-R22), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-10fce89b504200750d182205065db5a6b02d0586310b0fe24e85b928bd22240bR1-R14), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-b888c8d72b875d5cab5f4ef1e7d61a9b54231afbda08994a8a200c655ce6e7a0R1-R22), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-a175e89136f7e2a7a8183740c61bd7f15d7f703d01fa6fc040bc392b78679aedR1-R18), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-f406e158de4a6745d3427529b60d6ddc2c755ea07ac13cfab53c2495610a33ebR1-R42), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-7e2d81fb339fd5a24de7c07f5ec063c2404d191885c1d078a05017c0769cf5c5R1-R19), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-c8b6d7dc199f6fcca6645168c32c0ef091495cd9ff610cdd4a1c122a5d7e531bR1-R24), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-30cb7b62379f77f45cc4f2253c21a474877d01f77ea9b619be67e4abcb30bc64R1-R18), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-ad8aaf6ddb9524594cd153c102668cfdbd1f72cc52037c69133304c88fc6d314R1-R18), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-052499ac7ec090b63e5b40242fdcc625152840ac9eb33d268851d1f863dcccf0R1-R16), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-0e82e22ac493fd7773a4d0037c7ee3a7c15ad8f5aea32e418427cb72722684abR1-R22), [link](https://github.com/coronasafe/care_fe/pull/6232/files?diff=unified&w=0#diff-958b4e69c3a36fbd3fd9ba25532f67909a95e3cec57f86ef5bfac4e7acb95131R1-R22))

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]
Nice Work! LGTM.

**Comment by thtauhid** [comment]
Had conflict of 3 lines. I've updated the lines.

**Comment by thtauhid** [comment]
I should have removed `{consultationData.verified_by}` in commit [afa08f3](https://github.com/coronasafe/care_fe/pull/6232/commits/afa08f3c2bdf0082da889a120e8caea9721f741e). But, removed it in [5456fad](https://github.com/coronasafe/care_fe/pull/6232/commits/5456fad8118cd3b7c5016f167ded8a5fa3d98789)

Conflicts have been resolved. 

Thanks.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
There are a lot of unnecessary changes now in this PR.

You'll have to rebase your original changes correctly.

**Comment by rithviknishad** [comment]
Let's try to get this merged first on Monday once the necessary changes are made.
This will always keep catching conflicts every day.

**Comment by rithviknishad** [comment]
@khavinshankar @nihal467

**Comment by thtauhid** [comment]
Hello,
I've created a new PR #6258 as this PR is a bit messy and I was having some issues rebasing it. 
I hope it doesn't create much of a problem. 

Thank you for understanding.

Should I close this PR?

**Comment by khavinshankar** [comment]
@thtauhid is this a duplicate PR of https://github.com/coronasafe/care_fe/pull/6258, 

I'm closing this PR, If this is relevant, feel free to reopen it.

**Pull request closed without merging**
