### PR TITLE
Fix notification filtering

### LINKED ISSUE #1387: The filtering logic is not working
Filter by event type in notifications is not working. 

https://www.loom.com/share/0ca4e620d7704188ab5e079360111ce2

### PR DESCRIPTION
**Pull request by arpancodes**
fixes #1387 
Now we can filter notification according to the categories
notification_filter

### CODE REVIEW

**Comment by aparnacoronasafe** [comment]
Visit link for Shifting updates are not working

**Comment by arpancodes** [comment]
@aparnacoronasafe I can't check it as I don't have any notification in `devdistrictadmin` for shifting update could you provide me with a test account I can check with?

**Comment by nihal467** [comment]
@arpancodes 
credentials for district admin: 
Username: admin123
Password: Lilo@123

**Comment by arpancodes** [comment]
@nihal467 I can't see any notification 😅 in this account... I needed an account which has shifting updates notifications

**Comment by nihal467** [comment]
@arpancodes 

this is a doctor credential, 
Username: test-doc
Password: Lilo@123

**Comment by bodhish** [comment]
It's working for me. Merging it.

**Pull request merged**
