### PR TITLE
Remove DateLL & Lines,Catheters #1973

### PR DESCRIPTION
**Pull request by developedBySJ**
# Changes
- Remove  Date/Size/LL
- Remove Lines and Catheters

# Preview
image

image

### CODE REVIEW

**Comment by nihal467** [comment]
@developedBySJ 
ejiweiow 

these fields are also not mandatory, can you remove this too !

**Comment by nihal467** [comment]
@developedBySJ 
ejiweiow

- Remove CPK/MB field 
- Make Operation & Special Instructions as non-mandatory

**Comment by nihal467** [comment]
@developedBySJ @gigincg 
egeropg

test failed, the front-end changes are made but it is not accepting the form

**Comment by developedBySJ** [comment]
@nihal467 This is a backend issue. I have updated the front-end but the backend is not updated yet.

**Comment by gigincg** [comment]
@developedBySJ Can you make a PR to remove the enforcement of these fields?

**Comment by nihal467** [comment]
test approved

**Comment by gigincg** [comment]
@developedBySJ Can you revert the removal of Special Instructions and Operation. I think they just needed to be non-mandatory fields.

**Comment by nihal467** [comment]
@gigincg the changes are working

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
