### PR TITLE
Added responsiveness on Assets page

### LINKED ISSUE #3155: Scan Asset Button unresponsive on Assets page
https://care.coronasafe.in/assets
image

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #3155 
http://localhost:4000/assets
image

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

**Comment by Pranshu1902** [comment]
Updated view:
image

**Review by developedBySJ — APPROVED** [review]

**Comment by nihal467** [comment]
@Pranshu1902 
image

mobile view : Ipad air, make it responsive

**Comment by Pranshu1902** [comment]
@nihal467 
Updated view:
image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
