### PR TITLE
Added Facility Image Form (API URL needed)

### PR DESCRIPTION
**Pull request by anuran-roy**
This PR addresses Issues #2131 and #2171.

Except the Backend API, other frontend components are ready to be used. 

## Screenshots:
Before image selection

After image selection

### CODE REVIEW

**Comment by rithviknishad** [comment]
@anuran-roy deploy preview is failing. merge the latest develop branch.

**Comment by rithviknishad** [comment]
@anuran-roy I've cleared cache and triggered deploy. but still it's failing :/ 
I can also see that you do have the latest develop here...

image

**Comment by nihal467** [comment]
@anuran-roy @rithviknishad @gigincg the deploy is still failed

**Comment by rithviknishad** [comment]
@anuran-roy @nihal467 deploy fails even after clear cache and deploy.

**Comment by anuran-roy** [comment]
@nihal467 actually this PR is awaiting the backend changes to be merged by Marmik. It requires an endpoint, which is yet to be added to care backend.

**Comment by rithviknishad** [comment]
@gigincg @anuran-roy Vercel preview deploy works without clearing cache out of the box for this PR. 
However netlify preview build failed 3 times even after clearing cache.

[Build logs](https://app.netlify.com/sites/care-net/deploys/62a4a77f19201b00093b79a1#L13) says: 

```
8:03:16 PM: Different build command detected, going to use the one specified in the Netlify
configuration file: 'CI='' yarn run build' versus 'CI="" yarn run prebuild && CI="" yarn run
build || { cat /tmp/* ; sleep 30 ; false; }' in the Netlify UI
```

**Comment by nihal467** [comment]
@anuran-roy is it good for testing

**Pull request closed without merging**
