### PR TITLE
Add a better search UI for patients index page(#8691)

### PR DESCRIPTION
**Pull request by i0am0arunava**
## Proposed Changes

- Fixes # https://github.com/ohcnetwork/care_fe/issues/8691

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network/).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by Jacobjeevan** [comment]
@i0am0arunava make sure to follow the PR format we have - proposed changes that mentions the issue # and merge checklist :)

**Comment by i0am0arunava** [comment]
> @i0am0arunava make sure to follow the PR format we have - proposed changes that mentions the issue # and merge checklist :)

okay I am doing

**Comment by bodhish** [comment]
This is not what we want, please check the comments in https://github.com/ohcnetwork/care_fe/pull/8725#pullrequestreview-2353086959

**Comment by i0am0arunava** [comment]
> This is not what we want, please check the comments in [#8725 (review)](https://github.com/ohcnetwork/care_fe/pull/8725#pullrequestreview-2353086959)

okay,I am making the changes as required.

**Pull request closed without merging**
