### PR TITLE
Added subtext to show current values in critical-care graphs

### LINKED ISSUE #2149: Critical Care | Show Current Value along with Graph
Even though the Graph Values are Valuable to Doctors, it is quite important for them to quickly get a glance of the current values. Show the Current Values of any Critical Care Graph along with the Title 

> Make sure that the unit is also shown

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #2149 

UI showing current values in the graphs:
image

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar @gigincg 
test failed,
ewkfep


When I take the value of SPO2 on the first log update and save it, The current value shows the inputted value, but when I take the second log update, and I didn't input the SPO2 level, the current value for the SPO2 is showing NA.

**Comment by khavinshankar** [comment]
@nihal467 It is intentional behavior, like it shows the lastest value, if it is empty then it shows NA

@nihal467  @gigincg should it show the latest valid value?

**Comment by nihal467** [comment]
@khavinshankar sorry, it was an expected behavior, test approved

**Comment by gigincg** [comment]
@khavinshankar Can we have this alongside the title? Instead of a separate row?

**Comment by khavinshankar** [comment]
@gigincg initially i tried putting it beside the title but, in mobile view and in small screens, we will be having overlapping issues, 
image

**Comment by gigincg** [comment]
@khavinshankar When you write it on the same line. I think there's no need to specify "current value". If you say "SpO2 99" It's understandable right?

**Comment by khavinshankar** [comment]
moved current value beside the title,

image

**Comment by nihal467** [comment]
test approved

**Pull request merged**
