### PR TITLE
Disabled dates before previous bed's start date while switching patients bed

### LINKED ISSUE #2451: Validation: New Bed Assignment should be newer than oldest start time
In the UI to Switch Beds, only dates that are newer than the start_time of the current bed should be allowed. Other dates should be disabled

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2451 

# Bugs Fixed

### Disabled dates before the previous bed's start date while switching the patient's bed. Furthermore, if the selected date is the same as the previous start date it would check for the time if the time selected is after the previous start date's time or not.

https://user-images.githubusercontent.com/59426397/171999198-8f02b591-6e10-494e-9cde-a94f27417040.mp4

### CODE REVIEW

**Review by developedBySJ — CHANGES_REQUESTED** [review]
Add validation for `<input/>`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

**Comment by nihal467** [comment]
test failed, @patelaryan7751 @gigincg the date is saying invalid

**Comment by nihal467** [comment]
test approved

**Comment by patelaryan7751** [comment]
Hey, @developedBySJ I added the min attribute inside the TextInput.

https://user-images.githubusercontent.com/59426397/172843319-76a5bf9c-d2d9-4365-ab07-dbabbc754f1b.mp4

**Comment by nihal467** [comment]
@patelaryan7751 @gigincg test failed,



I can change the bed, with a future time

**Comment by patelaryan7751** [comment]
Hey, @nihal467 I enquired with @vigneshhari he told me that we can have beds on the same dates but at a future time. The main aim is that we should not allocate beds to one or more patients at the same time.

https://user-images.githubusercontent.com/59426397/173192341-dc94ebce-6797-4065-9518-c2b40969816e.mp4

**Comment by aparnacoronasafe** [comment]
This issue seems resolved in staging

**Pull request closed without merging**
