### PR TITLE
Add state logo on login page and migrates envs to read from `/config.json`

### LINKED ISSUE #4192: Create config.json for Whitelabelling
We need to create a `config.json` file that would contain all environment variables relevant for Whitelabelling CARE.

There should be a useEffect in the App.tsx file, that does `fetch("./config.json") and initializes the global config for CARE.

The App should be "Loading" Until the `config.json` is fetched and the `config` state is initialized.

Here's a list of basic items we can whitelabel:
```
dashboard_url: "https://dashboard.coronasafe.network",
kasp_label: "KASP",
kase_full_string: "Karunya Arogya Sethu Padhathi",
enable_kasp: false,
government_logo: "cdn.coronasafe.network/xxx"
maps_api_key: "xxxxxxxxx",
sentry_api_key: "xxxxxxxxxx"
```

### LINKED ISSUE #4442: Add state logo on login page
https://care.coronasafe.in/

Add a customizable component for the state logo on the top left corner of the page. 

Since CARE is utilized by various health departments and other groups, having their logo on the home page would increase the sense of ownership and help in the smooth deployment.

Eg of a logo:

Kar-Health

### PR DESCRIPTION
**Pull request by rithviknishad**
> #### Realted PRs in `care_deploy_configs`
> - https://github.com/coronasafe/care_deploy_configs/pull/8
> - https://github.com/coronasafe/care_deploy_configs/pull/9
> - https://github.com/coronasafe/care_deploy_configs/pull/10

## Proposed Changes

- [x] Resolves #4442
- [x] Closes #4192 
- [x] Migrates white-labelled envs to read from `/config.json` via `useConfig`
- [x] Since constant `BED_TYPES` are dependent on `KASP_ENABLED` and `KASP_STRING` configs, made the it as a method `getBedTypes(kasp_config)`
- [x] Removes `REACT_APP_DEPLOYED_URL`, alternative used: `window.location.origin`

> 💬 https://github.com/coronasafe/care_deploy_configs/pull/10#issue-1550893315
>
> ### Newly added white labels
> 
>   * `static_dpg_white_logo`: image resource URL of [white logo of digital public goods](https://digitalpublicgoods.net/wp-content/themes/dpga/images/logo-w.svg). 
>   * `static_coronasafe_logo`: image resource URL of coronasafe logo 
>   * `coronasafe_url`: URL to coronasafe.network (https://coronasafe.network?ref=care) 
>   * `dpg_url`: URL to Coronasafe Care DPG Registry (https://digitalpublicgoods.net/registry/coronasafe-care.html)
>   * `sample_format_asset_import`: sample format file for asset import
>   * `sample_format_external_result_import`: sample format file of external result import
> 
> 
> ### Other updates
>   * `state_logo` to use the official white logo of DPG instead of inverting the default logo to white via `state_logo_white` flag.

#### Additionally, the following could be affected:
- All KASP related things (KASP filters, bed types, etc...)
- GMAPS Location Picker
- Pincode Autocomplete
- Presence of care logos

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [ x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by skks1212 — CHANGES_REQUESTED** [review]
I feel that we should have the DPG logo somewhere else, so it shows even in state deploys. Maybe it would look good in any of these places?
image
Also use this white logo, its from their official site.
https://digitalpublicgoods.net/wp-content/themes/dpga/images/logo-w.svg

Rest all LGTM
cc. @gigincg

**Comment by rithviknishad** [comment]
@skks1212 1/4 height for the div looks like this:
image

**Comment by shivankacker** [comment]
@rithviknishad can you add opacity to the current divider?
Should look like this
image
I have added
opacity: 0.5;
border-radius:10px; (wont make any significant difference but why not)

Also I can see it next to the Coronasafe logo too, why are we duplicating it?

**Comment by rithviknishad** [comment]
@skks1212 There are two logos.
1. `state_logo` which for staging uses DPG logo as a placeholder. This one's beside CARE logo.
2. `static_dpg_white_logo` which as you suggested, added the DPG logo regardless of `state_logo` beside coronasafe

**Review by skks1212 — APPROVED** [review]
LGTM!

**Comment by rithviknishad** [comment]
@nihal467 
The first DPG logo is a placeholder for showing state logos in state-specific deployments.
Will be removed once merged.

**Comment by nihal467** [comment]
@rithviknishad PR LGTM , get final UI approval in EOD call

**Comment by nihal467** [comment]
@gigincg as per conversation, with @rithviknishad the UI is already approved, @khavinshankar reverify it, and merge it

**Comment by khavinshankar** [comment]
@rithviknishad I believe that this was already discussed in the EOD (the color invention ...) and was approved, right?

cc: @nihal467

**Review by khavinshankar — APPROVED** [review]

**Comment by rithviknishad** [comment]
yes color inversion was a solution proposed during EOD meet itself.

**Pull request merged**
