### PR TITLE
fix: Tailwind the Add User page + cypress tests for user feature

### LINKED ISSUE #4320: Create a new user

### LINKED ISSUE #4321: update the existing user profile and link facility

### LINKED ISSUE #4322: Tailwind the Add User page
# Bug

## Describe the problem

- The `Add User` page uses MUI components

### To Reproduce

1. Go to https://care.coronasafe.in/users/add

## Expected behavior

- Tailwind the `Add user` page

## Screenshots

image

### PR DESCRIPTION
**Pull request by cp-Coder**
# Feature Request

## Proposed Changes

- Tailwind the `Add User` page
- Fixes cypress test for `users`

## Associated Issue

- Fixes #4322
- Fixes #4320
- Fixes #4321

## Screenshots

image
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update product[documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [ ] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder check the merge conflict

**Comment by aeswibon** [comment]
@nihal467 merge conflict has been resolved

**Comment by nihal467** [comment]
@cp-Coder follow the same field positioning as of existing staging, in your current PR, all the input fields' existing positions are changed.

image

**Comment by nihal467** [comment]
@cp-Coder 
image

unable to create a user id

**Comment by aeswibon** [comment]
For some reason, the cypress tests are not running for this specific PR. Will open a new PR.

**Pull request closed without merging**
