### PR TITLE
Eslint upgrade to v9

### LINKED ISSUE #9050: Upgrade eslint to v9
- Make sure the plugins are compatible with eslint v9
- Go through the breaking changes and make necessary changes to make the current codebase compatible
- Update the eslint config to newest version

### PR DESCRIPTION
**Pull request by amjithtitus09**
## Proposed Changes

- Fixes #9050 
- Eslint upgraded from v8 to v9
- Eslint config changes and plugin upgrades

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Introduced a new context for resetting history state.
	- Added navigation buttons in the ConsultationForm for easier access to sections.
	- Enhanced rendering performance by adding unique keys to various components for improved React reconciliation.

- **Bug Fixes**
	- Updated phone number validation logic in multiple components to ensure correct error handling.

- **Documentation**
	- Added display names to several components for better debugging in React DevTools.

- **Refactor**
	- Improved error handling by renaming caught error variables to indicate they are unused.
	- Refactored validation logic for phone numbers across multiple components for clarity and correctness.

- **Chores**
	- Removed unnecessary ESLint directives and comments to streamline code.

### CODE REVIEW

**Comment by amjithtitus09** [comment]
@sainak This is the new PR with existing commits. Additionally pushed commits to fix the lint errors. However there are cypress test failures now

**Comment by sainak** [comment]
@nihal467 can you check out the cypress tests

**Comment by nihal467** [comment]
image

-  Above is the PR Deploy Preview

image

- Above is the current staging preview

@sainak @amjithtitus09 The button, which previously displayed task-specific text, has now been generalized to a simple "Submit" button in your PR. This change is causing the tests to fail. Please avoid making unnecessary changes like this in your PR and revert the button text back to its original task-specific form.

**Review by nihal467 — CHANGES_REQUESTED** [review]
revert unnecessary changes in the codebase, as mentioned in the latest commit

**Comment by rithviknishad** [comment]
seeing the amount of conflicts, i think it'd be faster to re-do from scratch with new architecture.

image

**Pull request closed without merging**
