### PR TITLE
fix: Duty doctors and Staff for each Location in a Facility

### LINKED ISSUE #5364: Duty doctors and Staff for each Location in a Facility
We need to identify in CARE the duty doctors and staff for each location in a facility.

For the same do the following:

- [x] Add a field to allot duty doctors and staff to a location (in https://care.coronasafe.in/facility/d1649863-471c-4f6c-841a-67885ebdefe6/location/029ee3ff-4c3c-4c25-8dcd-1d78c8d5a328/update)

- Add a section in the form called "Duty Staff" and have 2 fields
1. Doctors on duty- allow selection of multiple doctors from the list of doctors whose "Home Facility" is the relevant facility
2. Nurses on Duty- allow selection of multiple staff from the list of staff linked to the relevant facility.

- [x] Such staff must be visible in the Location list (table view) - under two heads
https://care.coronasafe.in/facility/d1649863-471c-4f6c-841a-67885ebdefe6/location
1. Doctors on duty
2. Nurses on Duty

### PR DESCRIPTION
**Pull request by cp-Coder**
# Bug Fix

### <samp>🤖 Generated by Copilot at ba5bdc4</samp>

The pull request adds the feature to assign users (doctors and staff) to locations in a facility and display them in the location management table. It modifies the `AddLocationForm.tsx`, `LocationManagement.tsx`, and `models.tsx` files in the `src/Components/Facility` folder to handle the user data and the UI components.

## Proposed Changes

- Adds `Duty Staff` section to location form
- Stores `doctors` and `staff` with each location

## Associated Issue

- Fixes #5364

## Screenshot

- **Location View table**
image

- **Location Add form**
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update product [documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [ ] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at ba5bdc4</samp>

*  Add multi-select dropdown fields for selecting users (doctors and staff) for a location in the `AddLocationForm` component ([link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eR9), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eR17-R18), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eR35-R38), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eL43-R64), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eR74-R83), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eL68-R101), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eR123), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eR158-R163), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eR185-R216))
*  Fetch and store the list of users (doctors and staff) associated with a facility using the `getFacilityUsers` action in the `AddLocationForm` component ([link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eR9), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eL43-R64))
*  Extract and store the list of users (doctors and staff) assigned to a location from the API response in the `AddLocationForm` component ([link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eR74-R83))
*  Include the `duty_staff` field in the data object sent to the API when submitting the `AddLocationForm` component ([link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eL68-R101), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-1de7d57cfac6560a32d4838c30766fb977804e85f55ce2d04b3859a40dfe1b9eR123))
*  Render the list of users (doctors and staff) assigned to a location as badges with icons and names in the `LocationRow` component ([link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdR11-R12), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL23-R30), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdL34-R56))
*  Pass the `doctors` and `staff` props to the `LocationRow` component from the `duty_staff_objects` field of the `locationItem` object in the `LocationManagement` component ([link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-042c54113f687e89c2429ff1d97fe7dfcccfa3818279170a82ea1286684a53cdR148-R157))
*  Add the `duty_staff_objects` field to the `LocationModel` interface in the `src/Components/Facility/models.ts` file ([link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfL1-R4), [link](https://github.com/coronasafe/care_fe/pull/5370/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfR188))

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder resolve the merge conflict

**Comment by nihal467** [comment]
@cp-Coder can you clear the merge conflict

**Comment by nihal467** [comment]
@cp-Coder can you clear the merge conflict

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
@gigincg to post a comment on @vigneshhari query in the back-end

**Comment by nihal467** [comment]
@cp-Coder will be creating a new co-related back-end PR for review in two days 

CC : @khavinshankar @gigincg

**Comment by aeswibon** [comment]
Opening a new PR

**Pull request closed without merging**
