### PR TITLE
Old discharged patient now  getting unlinked from the feed and camera

### LINKED ISSUE #5177: Old discharged patient are not getting unlinked from the bed, feed and camera
**Describe the bug**

When we are checking the discharge patients data files who are discharged 8+ months ago and the discharge reason is UNKNOWN,  the patient is still linked with the bed and its camera

**Note:** this bug is only seen for old discharge patients with discharge reasons unknown 

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/76943ccc-48d5-408c-8e0b-cfebcd5452be/patient/b5b54256-61be-472a-9485-43d9ac9ff898/consultation/765932b0-16a4-426e-9892-66b57f7fdc79/updates
2. See the error

**Expected behavior**

All the patients discharged from care should have their bed, vital, and camera unlinked from them.

**Screenshots**

image

### PR DESCRIPTION
**Pull request by patelaryan7751**
## Proposed Changes

- Fixes #5177 
Old discharged patient now  getting unlinked from the feed and camera
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@patelaryan7751 
image

https://deploy-preview-5186--care-net.netlify.app/facility/76943ccc-48d5-408c-8e0b-cfebcd5452be/patient/b5b54256-61be-472a-9485-43d9ac9ff898/consultation/765932b0-16a4-426e-9892-66b57f7fdc79/updates

the patient is still linked to a bed, unlink the bed too, from the discharged patient

**Comment by patelaryan7751** [comment]
hey @nihal467 
image
i have fixed the bug

**Comment by nihal467** [comment]
@patelaryan7751 
image
image

in the patient consultation page, things have been changed but in the patient tab view, the patient is still have the bed assigned

**Comment by patelaryan7751** [comment]
Hey @nihal467 i have fixed the bug 
image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
