### PR TITLE
ICD-11 diagnosis cannot be both prov and final

### LINKED ISSUE #6366: ICD-11 (same diagnosis cant be both prov and final)
**Is your feature request related to a problem? Please describe.**
Currently in CARe, the same diagnosis can be marked as Prov and Final diagnosis. This leads to confusion.

The ideal flow is that when a doctor suspects a diagnosis, he marks it as prov diagnosis. Then as and when enough evidence is collected to conclude that it is in fact the correct diagnosis, the same is moved from prov diagnosis to final diagnosis. Sometimes, a doctor may also mark a diagnosis as final diagnosis at the onset.

**Describe the solution you'd like**

- [ ] When a diagnosis is selected as a final diagnosis, it must automatically get un-selected as a prov. diagnosis. 
- [ ] When a diagnosis is already marked as final diagnosis, Do NOT allow the user to select it as a provisional diagnosis.

### PR DESCRIPTION
**Pull request by GokulramGHV**
### <samp>🤖 Generated by Copilot at be504af</samp>

The pull request enhances the diagnosis selection and validation features in the `ConsultationForm` component. It uses the `DiagnosisSelectFormField` component with some exclusions to avoid duplicate diagnoses, and adapts to the new `ICD11DiagnosisModel` fields.

## Proposed Changes

- Fixes #6366 
- [x] When a diagnosis is selected as a final diagnosis, it must automatically get un-selected as a prov. diagnosis.
- [x] When a diagnosis is already marked as final diagnosis, Do NOT allow the user to select it as a provisional diagnosis.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at be504af</samp>

*  Exclude already selected diagnoses from provisional diagnosis field ([link](https://github.com/coronasafe/care_fe/pull/6447/files?diff=unified&w=0#diff-8b8d34546dbec628ffb3d365ac18b8e247bd0fd5c33a0d22c6d64c8eab0abd97L13-R16), [link](https://github.com/coronasafe/care_fe/pull/6447/files?diff=unified&w=0#diff-8b8d34546dbec628ffb3d365ac18b8e247bd0fd5c33a0d22c6d64c8eab0abd97L35-R40), [link](https://github.com/coronasafe/care_fe/pull/6447/files?diff=unified&w=0#diff-0815d428acd0061366098da333b4ad3a1df84c9f05d55a82b23790c22bdc5f2fR1219))
* Update state reducer to handle changes in diagnosis fields ([link](https://github.com/coronasafe/care_fe/pull/6447/files?diff=unified&w=0#diff-0815d428acd0061366098da333b4ad3a1df84c9f05d55a82b23790c22bdc5f2fL327-R351))
* Add console log for debugging errors in form submission ([link](https://github.com/coronasafe/care_fe/pull/6447/files?diff=unified&w=0#diff-0815d428acd0061366098da333b4ad3a1df84c9f05d55a82b23790c22bdc5f2fL424-R437))

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
@GokulramGHV update the validations in the backend too

**Comment by GokulramGHV** [comment]
@rithviknishad I've updated the validations in the backend. Pls review this https://github.com/coronasafe/care/pull/1673

**Comment by nihal467** [comment]
@GokulramGHV fix the backend failing test  for reviewing the PR

**Comment by nihal467** [comment]
LGTM

**Comment by rithviknishad** [comment]
@GokulramGHV marking it as do not merge as the model changes made in https://github.com/coronasafe/care/pull/1690 will fix it.

**Pull request closed without merging**
