### PR TITLE
Sachdevavaibhav/#4945

### PR DESCRIPTION
**Pull request by sachdevavaibhav**
### WHAT
Working on #4945 

### <samp>🤖 Generated by Copilot at 5739e28</samp>

Improved date input component by closing popover after selection. Updated `setDateValue` function and `DateInputV2.tsx` file.

## Proposed Changes

- Fixes #issue?
- Change 1
- Change 2
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 5739e28</samp>

* Import `MutableRefObject` type from `react` to use as parameter type for `close` function ([link](https://github.com/coronasafe/care_fe/pull/5551/files?diff=unified&w=0#diff-277f47613d077cedcaf477f502fdbe6f452f7da1410e81ac6741b61b255d8f7bL1-R1))
* Modify `setDateValue` function to accept `close` function as second parameter and invoke it after `onChange` callback ([link](https://github.com/coronasafe/care_fe/pull/5551/files?diff=unified&w=0#diff-277f47613d077cedcaf477f502fdbe6f452f7da1410e81ac6741b61b255d8f7bL93-R97), [link](https://github.com/coronasafe/care_fe/pull/5551/files?diff=unified&w=0#diff-277f47613d077cedcaf477f502fdbe6f452f7da1410e81ac6741b61b255d8f7bR106))
* Destructure `close` function from `Popover` component props and pass it to `setDateValue` function ([link](https://github.com/coronasafe/care_fe/pull/5551/files?diff=unified&w=0#diff-277f47613d077cedcaf477f502fdbe6f452f7da1410e81ac6741b61b255d8f7bL197-R202))
* Pass `close` function to `setDateValue` function inside `onClick` handler of `div` element that renders each date in calendar ([link](https://github.com/coronasafe/care_fe/pull/5551/files?diff=unified&w=0#diff-277f47613d077cedcaf477f502fdbe6f452f7da1410e81ac6741b61b255d8f7bL313-R318))
* Close popover component after user selects or clicks on a date from `DateInputV2` component ([link](https://github.com/coronasafe/care_fe/pull/5551/files?diff=unified&w=0#diff-277f47613d077cedcaf477f502fdbe6f452f7da1410e81ac6741b61b255d8f7bL93-R97), [link](https://github.com/coronasafe/care_fe/pull/5551/files?diff=unified&w=0#diff-277f47613d077cedcaf477f502fdbe6f452f7da1410e81ac6741b61b255d8f7bR106), [link](https://github.com/coronasafe/care_fe/pull/5551/files?diff=unified&w=0#diff-277f47613d077cedcaf477f502fdbe6f452f7da1410e81ac6741b61b255d8f7bL313-R318))

### CODE REVIEW

**Comment by sachdevavaibhav** [comment]
@rithviknishad Could you please check if I am moving in the right direction?

Also did I mess up with the branches?

**Comment by rithviknishad** [comment]
Yes you did mess up your branches ig.

You've branched out from your previous PR's branch I assume.

When working on a new PR, you can simply do the following:

```bash
git checkout develop
git pull upstream develop # if you've added upstream remote, you can do this to fetch latest develop so that you always branch from latest develop (or you can simply go to your github repo and fetch latesst changes and do a git pull)
git checkout -b "your-new-branch-name"
```

**Comment by sachdevavaibhav** [comment]
@rithviknishad 
Yes, I didn't checkout to develop. I pulled develop into the previous branch and then created a new branch. Sorry for the mess.

Any suggestions on how I can fix it?

**Comment by rithviknishad** [comment]
You could create a fresh new branch and re-open another PR and close this.

**Comment by sachdevavaibhav** [comment]
@rithviknishad 
I have reverted changes in the previous branch and force pushed it (since I merged develop into it). Closing this PR and creating new one.

**Pull request closed without merging**
