### PR TITLE
Show loading state when switching tabs in Discussion Notes

### LINKED ISSUE #7818: Show loading state when switching tabs in Discussion Notes
**Describe the bug**
Currently when we switch between tabs in discussion notes, it takes time to reflect the notes of that tab. 

Loading animation is not shown when switching to another tab if there are notes in the previous tab.

This could confuse when users don't have reliable internet access.

**To Reproduce**
1. Go to Discussion Notes (popup or dedicated page, both has the issue)
2. Add some notes
3. Switch to another tab

**Expected behavior**
Loading animation should be present when we switch tab.

### PR DESCRIPTION
**Pull request by sunny-thakurwar**
## Proposed Changes

- Fixes #7818 
- Added Loader in Discussion Notes

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by sunny-thakurwar** [comment]
@rithviknishad its is with reference to issue #7818. can you please check once.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Awesome! LGTM. However changes needs to be present in Patient Notes too. This changes only for Consultation Notes.

For reference, this page: https://deploy-preview-7819--care-net.netlify.app/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/notes

**Comment by sunny-thakurwar** [comment]
@rithviknishad Thank you for the feedback. The requested changes have been applied to the patient Notes. can you can review the current implementation.

**Review by rithviknishad — APPROVED** [review]

**Comment by sunny-thakurwar** [comment]
@rithviknishad the branch was outdate need to approve once again

**Comment by sunny-thakurwar** [comment]
@rithviknishad updated the branch with develop. might required approval again

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
