### PR TITLE
Fix row gap and column gap classes

### LINKED ISSUE #2569: The old col-gap and row-gap class are no longer valid in Tailwindcss v3
## Fixes

The current tailwind class for row gap and column gap are invalid in Tailwindcss v3

| Invalid | Fix |
| :---:|:---:|
| `col-gap-1` | `gap-x-1` |
| `row-gap-1` | `gap-y-1` |

### PR DESCRIPTION
**Pull request by rabilrbl**
Fixes #2569 

Change tailwind classes

| Old | New |
| :---:|:---:|
| `col-gap-1` | `gap-x-1` |
| `row-gap-1` | `gap-y-1` |

### CODE REVIEW

**Comment by nihal467** [comment]
@rabilrbl @gigincg deploy preview is failed

**Review by developedBySJ — APPROVED** [review]
LGTM

**Comment by rithviknishad** [comment]
@rabilrbl deploy preview is failing. merge the latest develop branch.

**Comment by nihal467** [comment]
@rabilrbl @rithviknishad @gigincg the deployment preview is failed

**Comment by rabilrbl** [comment]
@nihal467 Deploy preview success

**Review by sainAk — APPROVED** [review]

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
@rabilrbl please do work on the merge conflict

**Review by gigincg — APPROVED** [review]

**Pull request merged**
