### PR TITLE
Pressure Sore Diagrams in Updates Section

### PR DESCRIPTION
**Pull request by peeyush14goyal**
- [x] Click on any part to get its label
- [x] Click on any label to get its part
- [x] Border for highlighting selected label or part
- [x] Choosing data of different dates available

### CODE REVIEW

**Comment by bodhish** [comment]
@peeyush14goyal we are duplicating a lot of code here. Let's update the editor to have a preview mode

**Comment by peeyush14goyal** [comment]
@bodhish Functionality differs in both of them

**Comment by nihal467** [comment]
@bodhish shall i test it ?

**Comment by bodhish** [comment]
@peeyush14goyal I am merging this. Could you create an issue to convert it to rescript. It is relatively simple to maintain complex elements like in a shared component. We should also remove the scroll part. It's hard to use multi click as the focus changes with every single click.

**Pull request merged**
