### PR TITLE
Migrate rescript components to typescript; uninstall ReScript

### LINKED ISSUE #7781: Enhancement to the pain scale / Pressure sore component
**Is your feature request related to a problem? Please describe.**

When we click on the badges related to the pain scale / pressure sore data's , there is no behavior been executed, it is acted as a simple badge.

**Describe the solution you'd like**

When i click on the badge, in the preview mode of pain scale / pressure sore, the user should be auto-scrolled to the part of the preview mode, the pop-up related to the body part should come up

**Describe alternatives you've considered**

image

- [ ] above is the badge, user will be clicking

image

- [ ] post clicking the badge, this should be the view, this pop-up related to the body part

### LINKED ISSUE #7855: Migrate the Critical Care sections list page to Typescript
As a larger effort to bring consistent UI design across round types and make the log updates easy to use, a first step would be to move the critical care sections list page to typescript. Once done, the list of sections should be able to be adjustable based on the round type.

#7839 adds support for editing active prescriptions, diagnosis, investigations, symptoms and vitals. However, these would be better shown as individual sections in the critical care sections like page.

image

### LINKED ISSUE #8208: Remove/hide preview mode for pain scale from log update.
**Is your feature request related to a problem? Please describe.**
In log update form where user adds details regarding pain by marking region, pain scale and provide description, there is option for "preview". 
https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/daily_rounds/9ad27d33-0ced-4c11-9274-90cf8f86b316/update

Screenshot 2024-07-24 at 3 13 17 PM

The preview mode inside a form is redundant

**Describe the solution you'd like**
remove the toggle with preview mode. Always have edit mode in the form

### LINKED ISSUE #8297: Missing unit for I/O balance quantity fields
I/O balance quantity fields does not have unit defined in CARE.

Add `ml` as the unit for I/O balance quantity fields.

@aparnacoronasafe

### LINKED ISSUE #8298: Detailed Log Update round type's View Details page crashes when pain scale data is entered in vitals section
**Describe the bug**
When pain scale data is entered in vitals section of Detailed Log Update, it's view details page crashes [ randomly crashing ]

**To Reproduce**

1. Create a Detailed Log Update for a patient (that is admitted and has a bed assigned to it)
2. Open the Daily Rounds tab and click View Details of the filed round.
3. See error

**Expected behavior**
Page shouldn't crash.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by shivankacker**
## Proposed Changes

- Resolves #7855 
- Resolves #7781 
- Closes #8208
- Fixes #8297
- Fixes #8298
- Pre-requisite of #7351
- Pre-requisite of #8115
- Uninstalled rescript and upgraded eslint related packages to fix issues with linting
- Removed Medicines section from Critical Care details page as adding medicines for critical care round type support was removed previously.
- Ventilator related information was shown in others section instead of Respiratory support section in View Details page, corrected that.
- Improved i18n coverage for Critical Care section

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 @rithviknishad  Test in Progress

image

- [x] the temperature is bydefault filled with 95, keep the field black,
- [x] The switching mechanism for F and C is confusing for normal users, thing of something like a dropdown or something more commonly used, so they don't have any confusion about which is active now.

image

- [x] when you click on any badge, the active ones will have shadow, for example i click on the right shoulder, since the right shoulder button is having shadow and right hand badge is brighter, the users might get confused which one is currently active

image

- [x] pulse is missing in the vital section
- [x] when i filled all data in the vital section and try to submit the form, it is throwing error

**Comment by nihal467** [comment]
image

- [x] in the neurological monitoring section, when use select the patient is on prone position, then the left and right pupil response related everything should be hidden

**Comment by nihal467** [comment]
## Testing Completed @rithviknishad 6:08 Pm

image

- [ ] detailed log update view details page is crashing

image

- [x] post progress note creation, we should be redirected to the critical care form with only neurological monitoring and respiratory support

Vitals Section ( brief log update and detail log update ) 
---

- BP
- PULSE
- TEMPERATURE
- RESPIRATORY RATE
- SPO2
- RHYTHM
- RHYTHM DESCRIPTION
- Pain ( Only in detail log update )

Verify the data reflection in the echart, view details page, and work flow of edit : faulty

**Bug**

image

- [x] the input box is having high width, in normal view, decrease the width of the input box
- [x] in the temperature input box, there is no arrow to click for changing values

image

- [x] when you click on the badge and enter the value then submit the pop-up, it's not auto-closing the pop-up
- [x] as the color of the anatomy changes based on the user input, bring that same behavior for the badges as well

image

- [x] add space between the date and time dropdown and preview anatomy in the vitals section in consultation page

image

- [x] when you randomly click on the anatomy across all parts, at some points, the pop-up is clipping-in in the mobile view

Neurological Monitoring
---

- LEVEL OF CONSCIOUSNESS ( Brief Log Update also have it )
- THE PATIENT IS IN PRONE POSITION ( If ticked, hide all right and left pupil field )
- Left & Right Pupil ( Size , cannot assessed, reaction ) 
- Glasgow Coma scale ( Eye Opening, Verbal Response, Motor Response )
- Limb Response ( Upper and Lower Extremity left and right )


**Bug**

image

- [x] when we select the unresponsive option in the level of consciousness, the preview in the neuro tab is failing

image

- [x] Reduce the space between each heading for example the space between eye opening response and verbal response
- [x] Keep the total number in the bottom, not on the top, as it is generated based on all three input.

image

- [x] when we select connot be assessed , it is mentioned constricted, was this intentionally added, in the current staging version, we don't have it ?

image

- [x] select the cannot be assessed radio button in the left pupil, after checking that box, **click on the text "cannot be assessed"** under the right pupil, the radio in left pupil for cannot be assessed radio button become unchecked.

image

- [x] all the preview of pupil size, extremity , in the data preview in the neuro section, when you compare the right and left side, they are not consistent, for example  in the above screenshot, the total on the left is not properly aligned with the number 7 on the right
> Tracked as separate issue: https://github.com/coronasafe/care_fe/issues/8265

image

- [x] level of consciousness description field is not visible in the frontend, seem like its not been implemented in the frontend, verify and hide the reflection in the frontend in the neuro section

Respiratory Support
---

- Bilateral Air Entry
- EtCO2
- Respiratory Support
- Ventilator Mode
- PEEP
- PIP
- MAP
- bpm
- pressure support
- tidal volume
- fio2
- spo2
- oxygen flow rate
- flow rate

**bug**

image

- [x] the normal, high that range related alert is missing for the tidal volume in the respiratory NIV support


Arterial Blood Gas Analysis
---

- PO2
- PCO2
- pH
- HCO3
- Base Excess
- Lactate
- Sodium
- Potassium

**Bug**

image

- [x] The maximum range of pH is 10 not 14, as per current staging and backend

Blood Sugar
---

- Blood Sugar Level
- Insulin Intake
- Frequency

verify edit and reflection : Looks good for blood sugar

I/O Balance
---

- Infusion
- IV Fluid
- feed
- output

**bug**

image

- [x] unable to select any dropdown for all the section from intake to output, the entire is non-functional

Dialysis
---

- Fluid Balance
- Net Balance

dialysis section looks good

pressure sore
---

**bug**

image

- [x] the pop-up is clipping in, in the mobile view
- [x] when we click the submit button, the pop-up is not auto-closing or saving the data in the page [ no colour change in the anatomy skeleton ]

the entire section is non-functional

nursing care
---

- Personal hygiene
- positioning
- suctioning
- ryles tube care
- IV site care
- nubulisation
- dressing
- DVT pump stocking
- restrain
- chest tube care
- tracheostomy care
- stoma care
- catheter care

**bug**

image

- [x] reduce  the spacing between the nursing care checkbox

**Comment by rithviknishad** [comment]
All of the above mentioned bugs fixed; except 1 remaining that is to implement the critical care detail view page (1). 

cc: @nihal467

**Comment by rithviknishad** [comment]
Bundle size:

**Before:**

image

**After:**

image

**Comment by nihal467** [comment]
Testing Report @rithviknishad 
---

## Vital Section [ Normal Log Update & Critical Care ]

- BP
- PULSE
- TEMPERATURE
- RESPIRATORY RATE
- SPO2
- RHYTHM
- RHYTHM DESCRIPTION
- Pain ( Only in detail log update )

Status of functionality across creation, view details, edit and related charts : Other than the below mentioned bug, everything looks good

**Bug**: 

image

- [x] mean is missing in the BP chart, when we are filling the vital section in the critical care

Neurological Monitoring
---

- LEVEL OF CONSCIOUSNESS ( Brief Log Update also have it )
- THE PATIENT IS IN PRONE POSITION ( If ticked, hide all right and left pupil field )
- Left & Right Pupil ( Size , cannot assessed, reaction )
- Glasgow Coma scale ( Eye Opening, Verbal Response, Motor Response )
- Limb Response ( Upper and Lower Extremity left and right )

Status of functionality across creation, view details, edit and related charts : Looks good

Respiratory Support
---

- Bilateral Air Entry
- EtCO2
- Respiratory Support
- Ventilator Mode
- PEEP
- PIP
- MAP
- bpm
- pressure support
- tidal volume
- fio2
- spo2
- oxygen flow rate
- flow rate

Status of functionality across creation, view details, edit and related charts : looks good

Arterial Blood Gas Analysis
---

- PO2
- PCO2
- pH
- HCO3
- Base Excess
- Lactate
- Sodium
- Potassium

Status of functionality across creation, view details, edit and related charts : looks good

Blood Sugar
---

- Blood Sugar Level
- Insulin Intake
- Frequency

verify edit and reflection : Looks good 

I/O Balance
--

- Infusion
- IV Fluid
- feed
- output

verify edit and reflection : Looks good

Pressure Sore
---

Bug : 

image

https://deploy-preview-8119--care-net.netlify.app/facility/a5b29ba6-cc6c-42d6-adcb-5dfc6035ae5c/patient/417bcdb7-f006-44be-92d9-4bf9ac0080ec/consultation/140bb301-e5a6-4f36-9152-ebea4e548834/daily_rounds/0942acb6-036e-4962-8dc8-f282030543a5/update

- [x] some of the body parts not having colour based on the input

Nursing Care
---

- Personal hygiene
- positioning
- suctioning
- ryles tube care
- IV site care
- nubulisation
- dressing
- DVT pump stocking
- restrain
- chest tube care
- tracheostomy care
- stoma care
- catheter care

verify edit and reflection : Looks good

**Comment by nihal467** [comment]
LGTM @khavinshankar you can review and merge it, the testing it completed

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
