### PR TITLE
Revamp bed management page, improve responsiveness

### LINKED ISSUE #2745: Bed management page is not mobile responsive
image

### PR DESCRIPTION
**Pull request by naman114**
Fixes #2745

- Revamped the design of the Bed Management page
- Replaced the existing table with a list view to improve responsiveness on mobile screens
- Created a separate route to edit a bed's details, replacing the current method of updating the values in the table itself

## Before
image
image

## Now

https://user-images.githubusercontent.com/57593654/175819883-10b222c0-7ce3-49db-a415-bc1f38f10b00.mp4

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

**Comment by aeswibon** [comment]
Fixes #2838

**Comment by nihal467** [comment]
@naman114 



having the badge on the top. waste a lot of space, can we have an alternate location for the badge

**Comment by naman114** [comment]
I've moved the Bed Type tag next to the Bed Name. How does this look? @nihal467 

image

**Comment by nihal467** [comment]
@naman114 the alignment of the both bottom feel like too much low, can you bring it up a bit

**Comment by naman114** [comment]
Fixed the vertical alignment of the buttons @nihal467 

image

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
image

@naman114  the text seems to be overflowing in md screens, truncate might help

please add `need testing` after the fix

**Comment by naman114** [comment]
Fixed the overflowing title text on md screens @khavinshankar

image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
