### PR TITLE
Adds support for viewing discharged patients of a facility

### LINKED ISSUE #4678: Access to discharged patient file
**Is your feature request related to a problem? Please describe.**
When hosp A discharges a patient and the same patient is admitted to hosp B, hosp A then cannot see the details of the patient in their discharged patient list.

It is mandatory for hospitals to store all patient records of even discharged patients for a few years. They may also have periodic audits etc, where the information may have to be retrieved.

**Describe the solution you'd like**

- [ ] On the facility dashboard (https://care.coronasafe.in/facility/0421de45-3541-4652-862d-79cec4acb6af) below "View patients" add an option to "View Discharged Patients"
- [ ] In the patient list, hide the "Discharged" tab for all users other than State Administrators. 

> Note: Requires a new API to get Unique Patients with active=false from Consultation for the Facility. Do not reuse the existing Patient List API

### PR DESCRIPTION
**Pull request by rithviknishad**
## Required Backends
- https://github.com/coronasafe/care/pull/1866

## Proposed Changes
- Fixes #4678

image

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
image

- [ ] a discharge patient file is trying to be accessed by a staff , but he is not able to see the details, because the patient is already admitted in another facility as live patient

is this expected behaviour @rithviknishad

**Comment by rithviknishad** [comment]
@nihal467 unable to reproduce.

I've admitted a previously discharged patient of "Critical Care" patient named "James Gunn" to "James Assets" facility (so he is a live patient).

I'm still able to access the patient from the discharged patients view of "Critical Care"


image

image

**Comment by rithviknishad** [comment]
As per discussions, the following changes will be made to the permissions:

## Patient Registration Permission

**Current**: 
If a patient is readmitted to a different facility, the users of the previous consultation's facility cannot access those patient details.

**New**: 
If the user belongs to one of the facilities where the patient has ever had a consultation, they can read the "Patient Registration" details.


## Consultation History

**Current**: 
If a patient has access to the patient details page, they can "read" older consultations even if those consultations may not be part of the latest facility of the patient. I.e., If a patient is readmitted to a different facility, users of the latest facility can "view" all the consultations regardless of which facility the previous consultations belong to.

**New**:
Possible solutions:
- [ ] Allow users who have access to view the patient details to also be able to view all previous consultations regardless of which facility the previous consultations belonged to.
- [ ] Allow users to view all consultation history (regardless of facility) if the active/latest consultation belongs to the facility that the user belongs to. However, if the user belongs to a facility which is not the latest consultation facility, they won't have permission to view consultations that took part in other facilities of the patient. (This could lead to confusion to the user as they'll loose access to the full consultation history once the patient is readmitted to a different facility).


@aparnacoronasafe to comment on which solution to go with.

**Comment by aparnacoronasafe** [comment]
Discussed this with @rithviknishad over slack.

Notes from discussion:
Screenshot 2024-02-20 at 10 03 20 AM

@nihal467 while testing, test for all these
1) Home and remote user: live patient, see all prev consultation across all hospitals
2) Home user: discharged patient- can see patient details and all consultation from that hospital (NOT other hospitals)
3) Remote user: discharged patient- can only see patient details and no consultations

**Comment by nihal467** [comment]
LGTM

**Review by Ashesh3 — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
