### PR TITLE
Required Oxygen in Resource Form and Approved Quantity in Resource Update

### PR DESCRIPTION
**Pull request by Sandra3657**
Issue #1207

User can add required amounts of oxygen in the form. The quantity can be seen in the resource card and also be updated.

### CODE REVIEW

**Review by gigincg — APPROVED** [review]
The Feature Looks Good @Sandra3657  While you're at it can you add assigned_quantity to the Update Form as well?

**Comment by Sandra3657** [comment]
Yes. I will add it.

**Comment by nihal467** [comment]
test approved

**Comment by Sandra3657** [comment]
Resolves #1267
Resolves #1207

The option to add approved quantity has been added in. The approved quantity can be added in only when the current status is pending. It cannot be modified in any other case.
@gigincg
@aparnacoronasafe

**Pull request merged**
