### PR TITLE
Add New Cypress Tests for Language Selection and GitHub/License Link Verification on the Login Page

### LINKED ISSUE #9017: Add New cypress Test for language selection and link redirection
**Description**

Add a new Cypress test to verify language selection and repository redirection functionality.

**Conditions to follow**

- Add these tests to the redirect.cy.ts file.
- Use the Page Object Model (POM) approach.
- Reuse existing functions and add necessary API verification with cy.intercept.

**Test - 1**

- After the LoginPage loads, click the "Contribute on GitHub" link and verify redirection by checking the URL and the new page content.
- Repeat the same for the "Third Party Software License" link.

**Test - 2**

- After the login page loads, switch between all five languages and verify that the login submit button text updates according to the selected language.
- Log in with any language selected other than English and verify that the sidebar items display in the chosen language

**Screenshot**

Image

### PR DESCRIPTION
**Pull request by rajku-dev**
## Proposed Changes

- Fixes #9017 

- Test for Clicking the `Contribute on GitHub` link redirects to the correct URL (https://github.com/ohcnetwork) and validates the new page content.
- Test for Clicking the `Third Party Software License` link redirects to the /licenses page and checks for the expected content.
- Test for after the Login page loads, switch between all five languages and verify that the login submit 
button text updates according to the selected language.
- Test for Login with `Hindi` language and verify that the sidebar items display in the `Hindi` language

https://github.com/user-attachments/assets/33f15b13-9fad-430e-8afa-48cd8d22ee04

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Tests**
	- Added new test cases for verifying the functionality of GitHub and license links.
	- Implemented methods for checking link presence and language switching functionality.

- **New Features**
	- Enhanced `LanguageSelectorLogin` component with an `id` attribute for easier identification.
	- Introduced unique identifiers for navigation items in the sidebar for better structure.

### CODE REVIEW

**Comment by rajku-dev** [comment]
@Jacobjeevan @nihal467 Please review the new tests created in this PR, and let me know if any changes are required.

**Comment by rajku-dev** [comment]
https://github.com/user-attachments/assets/0a6064d4-a957-4757-955f-2d9eb097e0cc

don't why it failing here? 
@nihal467

**Comment by rithviknishad** [comment]
no longer relevant in new architecture

**Comment by rajku-dev** [comment]
> no longer relevant in new architecture

@rithviknishad we can't login in new architecture?

**Pull request closed without merging**
