### PR TITLE
Fix navigation bar highlighting to select only the active section

### LINKED ISSUE #9244: Handle the Volunteer Contact Number in the patient details page
**Describe the bug**

- [ ] The emergency contact field does not display the volunteer's primary phone number.
- [ ] When selecting the volunteer contact option in the navigation bar, both "Volunteer Contact" and "Insurance Details" appear as selected simultaneously.

**To Reproduce**

1. Go to patient details page
2. Assign a volunteer to the patient
3. See error

**Expected behavior**

- [ ] The emergency contact field should display the volunteer's primary phone number correctly.
- [ ] Selecting "Volunteer Contact" in the navigation bar should ensure only that option is highlighted, without affecting "Insurance Details."
**Screenshots**

Image

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #9244 
- Selecting "Volunteer Contact" in the navigation bar only that option is highlighted, without affecting "Insurance Details."

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved section scrolling behavior in patient details view
  - Fixed emergency contact phone number display

- **Refactor**
  - Enhanced section tracking mechanism to prevent unintended section changes

### CODE REVIEW

**Comment by Rishith25** [comment]
@coderabbitai Full review

**Comment by Jacobjeevan** [comment]
Waiting for backend [changes](https://github.com/ohcnetwork/care/pull/2624).

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image

the phone number is not being fetched to the frontend even with backend

**Comment by Rishith25** [comment]
> image
> 
> the phone number is not being fetched to the frontend even with backend

I raised a PR in backend so it should be merged to get the patient contact number. 
In frontend we have to use phone_number instead of alt_phone_number So frist the backend need to be merged in order to get the phone_number of the volunteer.

now i have changed the alt_phone_number to phone_number in frontend

**Comment by nihal467** [comment]
LGTM

**Comment by Rishith25** [comment]
@Jacobjeevan I will update it by tomorrow.

**Comment by rithviknishad** [comment]
no longer relevant in new architecture

**Pull request closed without merging**
