### PR TITLE
tidy-up asset ui

### LINKED ISSUE #2064: Asset UI is Bulky
erkfrop

- there are lots of project in this page and it seem bulky
- having the badges in between the data are not looking good, relocate it

### PR DESCRIPTION
**Pull request by arpancodes**
fixes #2064 

Changed list to grid layout

Before:
image

After:
image

### CODE REVIEW

**Comment by nihal467** [comment]
@arpancodes @bodhish @gigincg 
Presentation1

can you align the QR and the button also, because I feel like that they are a little bit more upward when compare with left side

**Comment by arpancodes** [comment]
@nihal467  this should fix this
image

**Comment by gigincg** [comment]
> @nihal467 this should fix this image

Hey @arpancodes . I think I tiny bit of padding would look good. Instead of the QR touching the border

**Comment by arpancodes** [comment]
@nihal467 it's not a border 😅 it was just a drawing tool I used to take screenshot 
it looks like this
image

**Comment by nihal467** [comment]
@arpancodes @gigincg @bodhish 

smdl;sd

**My Suggestion** 

can we change the right side like this, I simply edited using the paint
- bring the QR little bit down and it is not left-aligned when compared to the alignment the buttons below
- increase the space between the QR and buttons

**Comment by nihal467** [comment]
@arpancodes @gigincg 

eowfkope

can you bring the QR little bit down, inside the aligned box

**Comment by nihal467** [comment]
test approved

**Review by gigincg — APPROVED** [review]

**Pull request merged**
