### PR TITLE
Scribe Enhancements support PR

### PR DESCRIPTION
**Pull request by shivankacker**
Supporting PR for https://github.com/ohcnetwork/care_scribe_fe/pull/4

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Added the option to "Transcribe Again" in the user interface, enhancing transcription capabilities.
  
- **Style**
	- Updated audio control styles for a more refined appearance.
	- Introduced new styling for horizontal rules to align with overall UI design.

### CODE REVIEW

**Comment by nihal467** [comment]
image

- [ ] when we edit the transcribe and reprocess it, the new data is not being fetching by replacing the old one

**Comment by shivankacker** [comment]
@nihal467 cannot replicate


https://github.com/user-attachments/assets/b14abf94-3728-474e-ad35-701a9c412746

Might be a one time issue with gpt

**Comment by nihal467** [comment]
image

randomly the autofill is failing can you investigate it, but the feature you added working good
@shivankacker

**Comment by shivankacker** [comment]
@nihal467 we can take it as a separate issue, but i am sure it is due to whisper failing 🤔

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
