### PR TITLE
fix: add action and recommend discharge data on patient consultation page

### LINKED ISSUE #5271: Recommend Discharge data is not shown in patient consultation page
**Describe the bug**

a patient is recommended discharge when we are filling a patient log update, the saved data is not shown anywhere on the patient consultation page.

Note: When we click "View details" button in the existing log update card, we can see the data 

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/aec039c8-d3e2-4691-a1b6-78b80d8530ed/patient/c278ebfa-5f30-4f9b-8f23-3acfd158f46c/consultation/53b241cb-e589-4d76-9fe5-796505cc4cf3
2. Create a log update with recommend discharge selected
3. come to patient consultation page
5. See error

**Expected behavior**

**Screenshots**

image
image
image

### LINKED ISSUE #5272: Action data is not showing in the patient consultation page
**Describe the bug**

When we select an action while creating a log update/ in consultation form, it is only shown in the patient list and not shown anywhere on the patient dashboard

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/aec039c8-d3e2-4691-a1b6-78b80d8530ed/patient/c278ebfa-5f30-4f9b-8f23-3acfd158f46c/consultation/53b241cb-e589-4d76-9fe5-796505cc4cf3
2. Create a log update with an action
3. come to patient dashboard

**Expected behavior**
The action tagged for the patient must be visible on the patient basic info card itself. 

Design how the action must look. It must be prominently visible on the basic info card on the patient dashboard. Once designed, discuss in EOD before finalising the design.

**Screenshots**

image
image

### PR DESCRIPTION
**Pull request by cp-Coder**
# Bug Fix

### <samp>🤖 Generated by Copilot at ebd64a0</samp>

This pull request implements the telemedicine action feature for patients, which allows doctors to recommend discharging a patient from the facility. It removes the recommend discharge option from the daily rounds form, adds the action property to the patient model, and displays the action in the patient info card. It also improves the UI of the patient info card.

## Proposed Changes

- Added `action` and `recommend discharge` tag

## Associated Issue

- Fixes #5271
- Fixes #5272

## Screenshot

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update product [documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care)
- [ ] Ensure that UI text is kept in I18n files
- [ ] Prep the screenshot or demo video for the changelog entry, and attach it to issue
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at ebd64a0</samp>

*  Remove the recommend discharge option from the daily rounds form for a patient ([link](https://github.com/coronasafe/care_fe/pull/5347/files?diff=unified&w=0#diff-2b725d1dcc3aabbc0438aff687d8c29b79847cde3ea5e171e86ca113a4e6a612L23), [link](https://github.com/coronasafe/care_fe/pull/5347/files?diff=unified&w=0#diff-2b725d1dcc3aabbc0438aff687d8c29b79847cde3ea5e171e86ca113a4e6a612L54), [link](https://github.com/coronasafe/care_fe/pull/5347/files?diff=unified&w=0#diff-2b725d1dcc3aabbc0438aff687d8c29b79847cde3ea5e171e86ca113a4e6a612L277), [link](https://github.com/coronasafe/care_fe/pull/5347/files?diff=unified&w=0#diff-2b725d1dcc3aabbc0438aff687d8c29b79847cde3ea5e171e86ca113a4e6a612L409-L415), [link](https://github.com/coronasafe/care_fe/pull/5347/files?diff=unified&w=0#diff-2b725d1dcc3aabbc0438aff687d8c29b79847cde3ea5e171e86ca113a4e6a612L680-L687))
*  Add the action property to the patient object to store the id of the action taken by a telemedicine doctor for a patient ([link](https://github.com/coronasafe/care_fe/pull/5347/files?diff=unified&w=0#diff-d9b29c5d9c92cf894c097a6c8d38ca2ff4c598fdbc68e91a33324654e54eed81R29))
*  Display the action taken by a telemedicine doctor for a patient, if any, in a badge in the `PatientInfoCard` component, using the `TELEMEDICINE_ACTIONS` constant ([link](https://github.com/coronasafe/care_fe/pull/5347/files?diff=unified&w=0#diff-474c76838170cd340f215b026249385e32a2d8263bd30a568c2b02b38d272948R13), [link](https://github.com/coronasafe/care_fe/pull/5347/files?diff=unified&w=0#diff-474c76838170cd340f215b026249385e32a2d8263bd30a568c2b02b38d272948L162-R188))
*  Add a new option to the `TELEMEDICINE_ACTIONS` constant with an id of 90 and a text and desc of "DISCHARGE_RECOMMENDED" ([link](https://github.com/coronasafe/care_fe/pull/5347/files?diff=unified&w=0#diff-37705b30476b14631124ce42dd5c3500d43fbede16f0e91f9ae2905e4adc6376R484))

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder clear the merge conflict

**Comment by nihal467** [comment]
@cp-Coder can you clear the merge conflict in front-end and back-end

**Comment by nihal467** [comment]
@cp-Coder 
image
image

- [x] once you create a log-update with a action "specialist required" and try to create a second log-update for the same patient, the whole code crashes

**Comment by nihal467** [comment]
Functionality LGTM @rithviknishad @khavinshankar can you review it

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
