### PR TITLE
Fix issues with 3965 4004 3920

### LINKED ISSUE #4003: Facility search not working properly
**Describe the bug**
When searching for a particular facility, it shows the total no. of facilities to be a number that is greater than zero, but it says no facilities found.
The above issue only occurs when the facility list in not in the first page of the pagination.

**To Reproduce**

1. Go to [ttps://care.coronasafe.in/facility](ttps://care.coronasafe.in/facility)
2. Scroll down to the pagination
3. Change the page to any other page other than page 1.
4. Now search for a particular facility

**Expected behavior**
"No facilities found" should not be displayed when the total facilities is greater than zero when searching for a particular facility.

**Screenshots**
image

### LINKED ISSUE #4015: Fix issues in #4009
The following issues would be present when (#3965 #4004 #3920) are merged (draft #4009 for testing).

- #3965 
- #4004
- #3920

**Describe the bug**
- [ ] Removing the search filter tag works, but the search filter comes back after a delay.
- [ ] #3965 introduces query params-based pagination, however, #4004 still relies on the old method to solve the issue.

**To Reproduce**

(already described in the bug)

**Expected behavior**
- [ ] Removing the search filter tag, should remove it and not come back after a delay.
- [ ] Use pagination query param to reset the search filter

**Screenshots**

image

image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Closes #4015 
- Fixes #4003 
- Fixes issue that causes search to come back when filter is removed from tag.
- Resets to page 1 when filters are updated for
  - [x] Assets
  - [x] Facilities
  - [x] Patients
  - [x] Users
  - [x] Samples
  - [x] Resources (List view)
  - [x] Shifting (List view)
  - [x] External results (list view)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 
image

the problem which got solved on facility page is showing up on the asset page, shall we take that as a separate issue, or is it correlated

**Comment by nihal467** [comment]
@rithviknishad 
image

the same is happening in user management page

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@rithviknishad @nihal467 

There seem to be some side effects:
**Steps:**
_in facilities page_
1. Search something in the facility search
2. Remove the search term
3. Now try to change page
4. *Problem: * the page seems to reset to 1

also test the same in others too


@nihal467 _lets hold this on for next production release_

**Comment by rithviknishad** [comment]
Closing as base PR #4004 is closed, base PR #3920 is merged and a follow-up PR was made to fix the side-effect caused by the new Search Input in #4037.
The only issue left to solve is resetting to page 1 when filters are updated and will be continued in a new branch / PR since this PR contains many hacks to solve multiple issues present before and has diverged from the intended fix.

**Pull request closed without merging**
