### PR TITLE
UI changes to shifting form

### LINKED ISSUE #5300: Changes to shifting form
The shifting form (https://care.coronasafe.in/facility/d02ef2cb-b5b2-4baf-bc9a-fac348893b00/patient/fddf2473-bc46-403d-b450-b569ce29d997/shift/new) needs to be amended as below: 

- [x] "Contact person at the facility" to be edited to "Contact person at the current facility "
- [x] "What facility would you like to assign the patient to" field must also allow free text to type in names of hospitals outside the CARE Network.
- [x] Hide preferred vehicle
- [x] Hide preferred facility Type
- [x] Hide severity of breathlessness
- [x] Add patient category- to be autofilled with the last updated patient category in consultation form/log update. user must have option to revise it. (non-mandatory). field to come below "is this an upshift"
- [x] Add short text field for name of ambulance driver (non-mandatory). field to be placed after the reason for the shift
- [x] Phone ni. of Ambulance No.(non-mandatory)
- [x] Add short text field for Ambulance No. 

**Shifting approving facility**
- [x] The approval of the shifting approving facility must be given by default. This must be a "peacetime" configuration for any particular instance. During times of public health emergency, when the deployment goes into "wartime" operations, the manual approval by "Shifting approval authority" must be brought back. 
- [x] Wherever approval is made default, hide the field to select "Shifting approval authority" from the shifting request form.
- [x] When `patient expired` is selected as status and the changes are saved, Redirect the user to Discharge from CARE pop-up window, with the reason for discharge "death" must come auto-populated and must not be editable.

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #5300
Backend PR: https://github.com/coronasafe/care/pull/1246 , https://github.com/coronasafe/care/pull/1265

- [x] "Contact person at the facility" to be edited to "Contact person at the current facility "
- [x] "What facility would you like to assign the patient to" field must also allow free text to type in names of hospitals outside the CARE Network.
- [x] Hide preferred vehicle
- [x] Hide preferred facility Type
- [x] Hide severity of breathlessness
- [x] Add patient category- to be autofilled with the last updated patient category in consultation form/log update. user must have option to revise it. (non-mandatory). field to come below "is this an upshift"
- [x] Add short text field for name of ambulance driver (non-mandatory). field to be placed after the reason for the shift
- [x] Phone no. of Ambulance No.(non-mandatory)
- [x] Add short text field for Ambulance No. 
- [x] Wherever approval is made default, hide the field to select "Shifting approval authority" from the shifting request form.

image

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

**Comment by Ashesh3** [comment]
> @Ashesh3 why are the lines commented out, assuming that they can be uncommented at wartime, if that is the case can you use `wartime_shifting` env from useConfig

Hey, those features were to be removed from shifting, hence i commented them once to test the UI. I will remove the comments and make a push. There's no mention of those commented features to be needed at warmode so they can be removed. 

Edit: Used the `wartime_shifting` config to show/hide fields accordingly.

**Comment by Ashesh3** [comment]
Waiting on https://github.com/coronasafe/care/pull/1265

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
