### PR TITLE
Changed leaflet location picker to gmap

### LINKED ISSUE #2526: Migrate to Google Maps Location Picker
Migrate the leaflet based location picker (In Facility Create/Update Page) to Google Maps.

Refer: https://developers.google.com/maps/documentation/javascript/react-map

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #2526

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar the map is not working

**Comment by nihal467** [comment]
@khavinshankar what is the PR status

**Comment by khavinshankar** [comment]
@nihal467 this won't work in the netlify deploy because the gmap api key permissions are not given for netlify sites, either we can merge this into staging (it should work in staging) and test it or we can ask mathew to add permissions to the api key to allow netlify

**Comment by nihal467** [comment]
@gigincg what is your opinion

**Comment by gigincg** [comment]
@nihal467 @khavinshankar Updated the restrictions to allow deploy-previews under care-egov-staging.

Tested to be working in https://deploy-preview-2921--care-egov-staging.netlify.app/

**Comment by nihal467** [comment]
@khavinshankar 
image

can we have a location search box in it, as we have in our current staging,  in case, the GPS doesn't work out, we would be requiring a search area to type in the location.

**Comment by nihal467** [comment]
@khavinshankar what is the status !

**Comment by khavinshankar** [comment]
@mathew-alex can you please enable permission for places library in gmaps api for this key
image

**Comment by mathew-alex** [comment]
:wave: Hi, @khavinshankar,
Conflicts have been detected against the base branch. Please rebase your branch against the base branch.

***

This message is automatically generated by [prince-chrismc/label-merge-conflicts-action](https://github.com/prince-chrismc/label-merge-conflicts-action) so don't hesitate to report issues/improvements there.

**Comment by mathew-alex** [comment]
> @mathew-alex can you please enable permission for places library in gmaps api for this key image

the permission is enabled now.

**Comment by khavinshankar** [comment]
Changes made:
- added searchbox
image

**Comment by nihal467** [comment]
@khavinshankar 
image

- [ ] i can't get it, it is showing Oops
- [ ] it is always asking allow or not in the platform, which is not good, since most of our users are not tech savy

**Comment by khavinshankar** [comment]
@mathew-alex can you check the permissions for gmap API
image

**Comment by mathew-alex** [comment]
> @mathew-alex can you check the permissions for gmap API image

added permissions

**Comment by nihal467** [comment]
@khavinshankar 

https://deploy-preview-2921--care-egov-staging.netlify.app/ it is working on this staging, test approved

**Pull request merged**
