### PR TITLE
Make Administer Medicine responsive view

### LINKED ISSUE #6459: Administer Medicine Slider and Modal not responsive
**Describe the bug**
Text is going outside Modal in mobile view and input box size is very small in desktop view for slider.

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/80e47d10-9ed8-4193-ade6-d69aa45999e9/consultation/b81e5e1f-fd11-4b38-aa51-14bea5583c76/medicines
2. Click on `Administer`
3. Open in mobile view
5. Now click on `Administer Medicines`
6. See error

**Screenshots**
image
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
### <samp>🤖 Generated by Copilot at 907d053</samp>

This pull request improves the responsiveness and layout of various components related to medicine and prescription details. It adjusts the grid columns, whitespace, and wrapping of text elements in `PrescriptionDetailCard.tsx`, `RecordMeta.tsx`, and `AdministerMedicine.tsx`.

## Proposed Changes

- Fixes #6459 
http://127.0.0.1:4000/facility/657c32be-d584-476c-9ce2-0412f0e7692e/patient/80e47d10-9ed8-4193-ade6-d69aa45999e9/consultation/b81e5e1f-fd11-4b38-aa51-14bea5583c76/medicines
Removed `nowrap` for modal text and changed the col-span to fit both mobile and desktop view

image

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 907d053</samp>

*  Prevent user name from wrapping in record meta by adding `whitespace-nowrap` class to span element ([link](https://github.com/coronasafe/care_fe/pull/6460/files?diff=unified&w=0#diff-f0d2ab732677f4577c5beaba451e232beca423da2365428db6644c199008447cL51-R51))
*  Make label text responsive in administer medicine form by adding `md:` prefix to `whitespace-nowrap` class in `CheckBoxFormField` component ([link](https://github.com/coronasafe/care_fe/pull/6460/files?diff=unified&w=0#diff-0cff6f571c166a4b174e2180d36c81d41819d2d57cb32bef474c1718d0c70519L90-R90))
*  Make prescription details more compact and consistent in `PrescriptionDetailCard` component by modifying grid layout classes in `Detail` components ([link](https://github.com/coronasafe/care_fe/pull/6460/files?diff=unified&w=0#diff-5c00daca7231dea096a64831937270460d419a332ecf820075ad74c4c69e61d5L87-R88), [link](https://github.com/coronasafe/care_fe/pull/6460/files?diff=unified&w=0#diff-5c00daca7231dea096a64831937270460d419a332ecf820075ad74c4c69e61d5L102-R102), [link](https://github.com/coronasafe/care_fe/pull/6460/files?diff=unified&w=0#diff-5c00daca7231dea096a64831937270460d419a332ecf820075ad74c4c69e61d5L114-R114), [link](https://github.com/coronasafe/care_fe/pull/6460/files?diff=unified&w=0#diff-5c00daca7231dea096a64831937270460d419a332ecf820075ad74c4c69e61d5L122-R125), [link](https://github.com/coronasafe/care_fe/pull/6460/files?diff=unified&w=0#diff-5c00daca7231dea096a64831937270460d419a332ecf820075ad74c4c69e61d5L129-R132), [link](https://github.com/coronasafe/care_fe/pull/6460/files?diff=unified&w=0#diff-5c00daca7231dea096a64831937270460d419a332ecf820075ad74c4c69e61d5L136-R139), [link](https://github.com/coronasafe/care_fe/pull/6460/files?diff=unified&w=0#diff-5c00daca7231dea096a64831937270460d419a332ecf820075ad74c4c69e61d5L143-R146))

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@Pranshu1902 
image

in normal view, the administration not specified is over flowing

**Comment by Pranshu1902** [comment]
@nihal467 check now

**Comment by nihal467** [comment]
@Pranshu1902 
image

https://deploy-preview-6460--care-net.netlify.app/facility/dc863dcf-5649-4c4a-9f06-4de4f7202277/patient/5dc47e6b-eae3-48d0-85a7-aee4bd9ce4a7/consultation/8a64fd02-6801-4411-8fc0-10fd279206c6/medicines

its still the same

**Comment by Pranshu1902** [comment]
@nihal467 Updated view
The values are large so its best to make it full width 
image

**Comment by rithviknishad** [comment]
@Pranshu1902 @nihal467 These changes are likely to be already fixed in #6396

Could you test the following deploy preview? Changes in #6396 are huge and some files have been deleted/moved too. Conflicts might be chaos / practically a rework. https://deploy-preview-6396--care-net.netlify.app/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/medicines

**Comment by rithviknishad** [comment]
This design has lots of screenspace wasted IMO

> @nihal467 Updated view The values are large so its best to make it full width image

**Comment by Pranshu1902** [comment]
Closing the PR as fixed in #6396

**Pull request closed without merging**
