### PR TITLE
Hide Linked Facility button added on Users page

### LINKED ISSUE #4323: Hide Linked Facilities option on Users page
**Describe the bug**
The Users page should have the option to hide user-linked facilities as well.

**To Reproduce**
https://care.coronasafe.in/users

**Expected behavior**

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #4323 
Added button to hide linked facilities
image

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
@Pranshu1902 the functionality works well, but can you polish the UI!
my suggestion would be, to have an eye icon that can be toggled, and also have a max width for the facilities and make it scrollable
feel free to bring this up in an EOD call

cc: @nihal467

**Comment by Pranshu1902** [comment]
@nihal467 @khavinshankar 
Updated view:
image

image

**Comment by khavinshankar** [comment]
@nihal467 can you retest this pr

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@Pranshu1902 clear the failing cypress tests

**Comment by Pranshu1902** [comment]
@khavinshankar cypress error resolved!

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
