### PR TITLE
Made the teleicuvitalcard responsive

### LINKED ISSUE #3634: Minor UI break in the Live Vitals of Patient Consultation page
**Describe the bug**

Few datas are not showing fully in the live Vital responsive view

**To Reproduce**

https://care.coronasafe.in/facility/ba2f8df6-20e6-4351-b2a3-065d7886e11a/patient/c2e3ce12-44bb-4db1-bcc8-dcbea9843edc/consultation/215fa91e-80e7-4fd9-bf53-4e841bd5a024/updates

**Expected behavior**

make it responsive

**Screenshots**

image

### PR DESCRIPTION
**Pull request by patelaryan7751**
## Proposed Changes
Fixes #3634 
- Made the details visible 
image

- Made the tooltip visible
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
@patelaryan7751 LGTM. How about making the "Toggle stats for nerd" text a little smaller, like `text-xs`?

image

**Review by Ashesh3 — APPROVED** [review]
LGTM, Although, I recall @vigneshhari suggested removing the stats for nerd button altogether.

**Comment by patelaryan7751** [comment]
Yeah @Ashesh3 let's bring this up in the next EOD .

**Comment by nihal467** [comment]
@patelaryan7751 once it is completed, mark it for need testing,

**Comment by patelaryan7751** [comment]
Hey @nihal467 , @gigincg has given to have the stats for nerds buttons so its good for testing.

**Comment by nihal467** [comment]
@patelaryan7751 can you merge the latest development

**Comment by patelaryan7751** [comment]
yeah @nihal467 it's done

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
