### PR TITLE
Update dependency

### LINKED ISSUE #1233: Update dependency
Update all the packages that used to the latest version. 
You can ignore tailwind on this as we have another issue for the same.

### PR DESCRIPTION
**Pull request by abhinandanarya06**
Co-authored-by : @ProCode2 
## Proposed Changes
1. Remove `node-sass` and `sass-loader` from dependency
2. Update dependencies packages 

## Packages skipped for upgradation
1. `raviger`
2. `webpack`, `webpack-cli`, `webpack-dev-middleware`, `webpack-dev-server`, `webpack-hot-middleware`, `webpack-manifest-plugin`, `workbox-webpack-plugin`, `source-map-loader`, `ts-loader`, `html-webpack-plugin`(prod dependency)
3. `@tailwindcss/ui`, `postcss-safe-parser`, `optimize-css-assets-webpack-plugin`, `postcss-cli` 

## Merge Checklist
- [x] No errors after updating

closes #1233

### CODE REVIEW

**Comment by bodhish** [comment]
@abhinandanarya06 can you check if the styles in `App.scss` are currently loaded?
I assumed that we could convert those to `.css`

**Comment by ghost** [comment]
> @abhinandanarya06 can you check if the styles in `App.scss` are currently loaded?
> I assumed that we could convert those to `.css`

Scss file was working as logo was rotating on loading. Don't know why because I removed the` sass-loader`. May be because of cached build like thing

Anyway App.scss converted to css

**Comment by bodhish** [comment]
@abhinandanarya06 can you resolve the merge conflicts

**Comment by ghost** [comment]
> @abhinandanarya06 can you resolve the merge conflicts

Done

btw when there is actual errors, these all tests passes and when there is no error, then tests failed. Don't know why 😅

**Comment by ghost** [comment]
Finally all tests passed😌

**Pull request merged**
