### PR TITLE
fix: close profile dropdown on first click when navigating

### LINKED ISSUE #8816: Modify Active Profile Dropdown Behavior to Redirect to Other Pages
Follow-up : https://github.com/ohcnetwork/care_fe/pull/8789#issuecomment-2416409351

Bug Description

When the profile dropdown is open, clicking on other navigation buttons doesn't redirect to the intended page immediately. For example, if the profile dropdown is active and the user clicks on the "Assets" tab in the sidebar navigation, the first click closes the dropdown, but the user has to click again to navigate to the Assets page.

Steps to Reproduce:

1. Click on the profile name to open the dropdown menu.
2. Try clicking on the "Assets" tab in the sidebar.
3. Notice that the first click only closes the dropdown without navigating to the Assets page.

Expected Behavior 

- [ ] The profile dropdown should automatically close when the user clicks on any other button, and the intended action (e.g., navigation to a different page) should happen immediately on the first click.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by JavidSumra**
## Proposed Changes

- Fixes #8816  : Ensures the profile dropdown menu closes on the first click when the user clicks on another navigation item.
- Added `modal={false}` to the `DropdownMenu` in `SidebarUserCard` component to prevent the dropdown from requiring a second click for navigation actions.
- Improved user experience by allowing immediate navigation to other pages when the profile dropdown is open.

@ohcnetwork/care-fe-code-reviewers

Demo Video: [View here](https://drive.google.com/file/d/1-6LPwFdaHH_fCXrI9DvMXBqmXXzbB3V1/view?usp=sharing)

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews.
- [ ] Completion of QA.

### CODE REVIEW

**Comment by JavidSumra** [comment]
@nihal467 sir can you please review this PR

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Comment by JavidSumra** [comment]
Hey @rithviknishad can you please assign 2 story point's for this issue?

**Comment by rithviknishad** [comment]
1 is the maximum what's reasonable for something that takes less than half a day of effort. Have a look at story points assigned to already assigned ones to get a an estimate based on relative effort.

https://github.com/orgs/ohcnetwork/projects/4/views/19

cc @bodhish

**Pull request merged**
