### PR TITLE
fix: Resolve creation of patient name despite having numeric values

### LINKED ISSUE #9143: Patient created despite having numeric values in name
**Describe the bug**
Patient can be created despite having wrong name (numeric values in the name e.g. 1234hh)

**To Reproduce**

1. Go to [https://care.ohc.network/patients](url)
2. Click on 'Add Patient'
3. Fill the details (Put numbers in name).
4. Create Patient.

**Expected behavior**
There should not be any numeric values in the name. If it is, then the patient should not be created.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome

### PR DESCRIPTION
**Pull request by Tanuj1718**
## Proposed Changes

- Fixes #9143
- Added check for validating a patient name

https://github.com/user-attachments/assets/59b5ac7b-3ad8-477a-9a85-f5113b205f1a

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced form validation for patient registration, including a new validation check for the patient's name.
	- Added a new field for the patient's name in the registration form.

- **Bug Fixes**
	- Improved error messaging for invalid name entries.

- **Improvements**
	- Ensured consistent formatting of names before submission, enhancing data integrity.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Review by shivankacker — APPROVED** [review]

**Comment by shivankacker** [comment]
@Tanuj1718 have we also accounted for characters like underscores, dots and commas ?

**Comment by Tanuj1718** [comment]
> @Tanuj1718 have we also accounted for characters like underscores, dots and commas ?

Yes we have checked. We only allow alphabetic characters and spaces in Name.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by rithviknishad** [comment]
@Tanuj1718 #9177 would be reverting this PR due to reason mentioned in https://github.com/ohcnetwork/care_fe/issues/9143#issuecomment-2491409154

**Comment by Tanuj1718** [comment]
> @Tanuj1718 #9177 would be reverting this PR due to reason mentioned in [#9143 (comment)](https://github.com/ohcnetwork/care_fe/issues/9143#issuecomment-2491409154)

Okay @rithviknishad , it's always interesting to know about the new things.

**Pull request merged**
