### PR TITLE
Revamped the scroll bar UI

### LINKED ISSUE #2863: Revamp the scroller
the scroller is having a white background, and it doesn't look good. Revamp the whole scroller to a better UI

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2863 

# Bugs Fixed 

## Revamped the scroll bar UI of Side BAR
https://user-images.githubusercontent.com/59426397/175858060-f41fcb85-2c1e-4871-8a10-c5f16ae42bf7.mp4

### CODE REVIEW

**Review by cp-Coder — COMMENTED** [review]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@patelaryan7751 test failed, it is same

**Comment by patelaryan7751** [comment]
@nihal467 can you close that download bar and see? If I go to dev tools and decrease the height it's working fine

image

 but if I see by decreasing chrome window size or with a download bar like this it's showing like this .
Screenshot from 2022-06-27 23-44-25

Let me check on this issue deeply how to solve this problem

**Comment by patelaryan7751** [comment]
Hey, @nihal467 I have fixed the scroll bar bug

https://user-images.githubusercontent.com/59426397/177466141-eac3e3c8-88d7-4be2-bae5-802cc955fcf1.mp4

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
