### PR TITLE
Corrected Spelling mistake of daily rounds fields: ventilator_fi02 to ventilator_fio2 in Frontend #8241

### LINKED ISSUE #8241: Correct spelling mistake of daily round field: `ventilator_fi02` to `ventilator_fio2`
Daily rounds model's field name: `ventilator_fi02` needs to be corrected to `ventilator_fio2`

### Action Items

- [x] Correct the field name in the backend (https://github.com/coronasafe/care).
- [x] Correct the field name in the type definition and usages in the frontend.

### PR DESCRIPTION
**Pull request by SagarSharma2809**
### Required Backends

- https://github.com/coronasafe/care/pull/2356

## Proposed Changes

- Fixes #8241
- Correct Spelling Mistake of daily rounds fields: ventilator_fi02 to ventilator_fio2 in:
- type definitions
- usages in frontend

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@SagarSharma2809 can you make the requested changes in the related backend PR https://github.com/coronasafe/care/pull/2345 ,

**Comment by SagarSharma2809** [comment]
Yes @nihal467

**Comment by nihal467** [comment]
@rithviknishad assigning you the PR, to create relevant backend changes, post fixing it, mark it as need testing

**Comment by nihal467** [comment]
@SagarSharma2809 @rithviknishad nice work.

image

- [ ] the fio2 in detailed log update (Create, Edit and view) is working properly

**Comment by nihal467** [comment]
LGTM @khavinshankar you can review the PR

**Review by rithviknishad — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
