### PR TITLE
Error color change in patient creation form

### LINKED ISSUE #4867: Change error statement colour from black to red in patient creation form
**Describe the bug**

in the patient creation form, the error statement for mandatory fields are shown in black color making it hard to understand the statement

**To Reproduce**

https://care.coronasafe.in/facility/4adaaff2-c6b2-4530-a518-3fbe44752421/patient

**Expected behavior**

 the error statement should be shown in red

**Screenshots**

image

### PR DESCRIPTION
**Pull request by siva-balan**
## Proposed Changes

- Fixes #4882 
- Fixes #4867 
- Made use of TextFormField and SelectFormField to implement consistency and to change error statement color from black to red.
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by siva-balan** [comment]
@rithviknishad Please take a look at this pr. And thanks for the help.

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@siva-balan everything LGTM, except that pincode field isn't working.

**Comment by siva-balan** [comment]
> @siva-balan everything LGTM, except that pincode field isn't working.

Done now, Had to change it into handleformfieldchange.

**Review by rithviknishad — APPROVED** [review]

**Review by Pranshu1902 — APPROVED** [review]

**Comment by nihal467** [comment]
@siva-balan 

image

- [ ] 682001 - pincode belongs to a place in ernakulam, as per my input into the pincode , the state and district field should be auto filled. It is not working in your PR.

image

- [ ] blood type is mandatory field, it is missing " * " for the same.

**Comment by siva-balan** [comment]
> 

The changes are done @nihal467 , pls check it once

**Comment by siva-balan** [comment]
@rithviknishad can u change the label to need testing

**Comment by nihal467** [comment]
LGTM, have a small issue with the blood group droplist expanding the page,

**Comment by nihal467** [comment]
@siva-balan @rithviknishad the PR LGTM , @khavinshankar you can review it and merge it

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
