### PR TITLE
Show error message when camera is offline

### LINKED ISSUE #4559: Better Error Messages for Camera Feed
Example edges 

- When no Camera Record Available

### PR DESCRIPTION
**Pull request by khavinshankar**
## Proposed Changes

- Fixes #4559 
- Show an error message when the camera is offline

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar 
even though a patient is having a camera configured properly, it is not showing the feed

https://deploy-preview-4575--care-net.netlify.app/facility/32676d52-5454-4f14-bbb0-179a1981e536/patient/3a24919b-a553-41ca-bb1c-9296f3dd6bd0/consultation/2d091fe9-8a5c-481d-8ea4-11b5888cdd40/feed

**Comment by nihal467** [comment]
@khavinshankar can you check this again

**Comment by nihal467** [comment]
@khavinshankar 
image

https://deploy-preview-4575--care-net.netlify.app/facility/1fabc5fb-d96d-455a-ab61-53e6e0483cbc/patient/dda0caa4-a52c-49cd-9dd3-7fe8093aaa76/consultation/3e0a9c49-5148-4669-8d46-e3117d0987cf/feed

when the configuration is wrong, and it doesn't have feed coming into the patient consultation page, the screen goes black, not show any status

**Comment by khavinshankar** [comment]
image

@nihal467 can you retest this with a hard refresh or in incognito, it's working on my end.

**Comment by nihal467** [comment]
@khavinshankar check the link i shared, I am having the trouble

image

https://deploy-preview-4895--care-net.netlify.app/facility/98375114-038b-4c95-a580-86d9ad09d06a/patient/8693d9ed-ffad-4e80-a599-5f4a608de7dd/consultation/de9e470e-d035-40b3-a9fc-46ab183be288/feed

**Comment by nihal467** [comment]
@khavinshankar 
image

can you check the PR, I am not getting offline error

**Comment by khavinshankar** [comment]
@nihal467 About the Offline status, we won't be able to see that status because the feed will always try to reconnect, this is an intentional behavior.

**Comment by nihal467** [comment]
already solved in PR https://github.com/coronasafe/care_fe/pull/6408

**Pull request closed without merging**
