### PR TITLE
Added padding in the user tab for "No users found"

### LINKED ISSUE #7894: Add padding in the user tab for "No user found"
**Describe the bug**

When there is no user found in the user tab, text is shown without a padding

**To Reproduce**

1. Go to user tab
2. filter the data with no match
3. See error

**Expected behavior**

Add white padding and show the "No user found" text similar to the no sample file card similar to below screenshot

image

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Aryanshu919**
## Proposed Changes

- Fixes #7894 
Screenshot 2024-05-26 at 2 57 25 PM

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@Aryanshu919 as per the issue , it should be similar to the no sample history shown in the platform 
image

make the necessary changes

**Comment by nihal467** [comment]
LGTM

**Comment by khavinshankar** [comment]
@Aryanshu919 fix the linting errors

**Comment by nihal467** [comment]
@khavinshankar the lint is fixed

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
