### PR TITLE
search by typing in symptoms

### LINKED ISSUE #7543: search by typing in symptoms list
at present the symptom list in the consultation is only drop down, could we add search by typing as well?
Screenshot 2024-04-05 at 7 29 34 AM

### PR DESCRIPTION
**Pull request by hrit2773**
## Proposed Changes

- Fixes #7543

### CODE REVIEW

**Comment by nihal467** [comment]
@hrit2773 fix the cypress issue

**Comment by hrit2773** [comment]
1) Patient Consultation in multiple combination
       OP Patient with admission consultation:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `[role='option']`, but never found it.
      at Context.eval (webpack://care_fe/./cypress/support/commands.ts:131:0)

  2) Patient Consultation in multiple combination
       OP Patient with Declare Death:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `[role='option']`, but never found it.
      at Context.eval (webpack://care_fe/./cypress/support/commands.ts:131:0)

  3) Patient Consultation in multiple combination
       Internal Transfer within facility Patient with Domicilary Care:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `[role='option']`, but never found it.
      at Context.eval (webpack://care_fe/./cypress/support/commands.ts:131:0)

  4) Patient Consultation in multiple combination
       Referred From another Facility Patient with OP consultation:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `[role='option']`, but never found it.
      at eval (webpack://care_fe/./cypress/support/commands.ts:122:0)
  at Array.forEach (<anonymous>)
      at Context.eval (webpack://care_fe/./cypress/support/commands.ts:121:0)

  5) Patient Consultation in multiple combination
       OP Patient with Refer to another hospital consultation:
     AssertionError: Timed out retrying after 10000ms: Expected to find element: `[role='option']`, but never found it.
      at eval (webpack://care_fe/./cypress/support/commands.ts:122:0)
  at Array.forEach (<anonymous>)
      at Context.eval (webpack://care_fe/./cypress/support/commands.ts:121:0)                    

@nihal467  what is this [role='option'] how to track them

**Comment by hrit2773** [comment]
@nihal i just made changes to autoCompleteMultiSelect component. I think this issue has nothing to do with the patient op declare death or domiciliary care. And i didnt make any changes to the field attributes or selectors, maybe cypress is unable to get the selectors of the components...just tell me if im missing something. Can you tell me more about these cypress tests configurations because the consultation form is working completely fine

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image
@hrit2773 
- [ ] Go to the patient_consultation.cy.ts file and modify the patientconsultationpage.selectsymptoms().
- [ ] Since we don't have search and multi-select reusable selector components, create a component in the command.ts file for Cypress, and use it to select symptoms in the function.

**Comment by hrit2773** [comment]
@nihal467 all the cypress test passed

**Comment by nihal467** [comment]
@hrit2773 
image

- [ ] when a user click the option "asymptomatic", it should auto-close the component, your PR is not preserving the existing behavior in our current staging

**Comment by hrit2773** [comment]
@nihal467 I see...will fix it

**Comment by hrit2773** [comment]
@nihal467 why are the commas getting excluded during the commit the lint test is failing is it due the changes in prettier? because even if iam adding the commas its considering it as empty commit. @rithviknishad

**Comment by rithviknishad** [comment]
Try reinstalling the packages locally. There was a recent version change.

**Comment by hrit2773** [comment]
@rithviknishad @nihal467 now i added auto close for single select also so it is preserving the previous behaviour of closing the component as soon as user clicks on Asymptomatic.

**Review by nihal467 — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
