### PR TITLE
Added patient category descriptions for ICU bed patients

### LINKED ISSUE #7962: Patient categorisation- add definitions
**Is your feature request related to a problem? Please describe.**
CARE provides options for users to categorise patients as "Comfort care/ Mild/Moderate/Critical". However, there is no definition for this categorisation and users may use it subjectively. 

Providing more definitions would help bring about more standardisation in the way this categorisation is utilised.

**Describe the solution you'd like**

- [ ] Only for patients admitted, the dropdown for patient category in consultation form, edit consultation form and log update form must also have the definitions for these categories in fine text.

Mild (Urgent: not life-threatening)
Moderate (Emergency: could be life-threatening)
Critical (Immediate: life-threatening)

Make this fine text visible in the dropdown itself

- [ ] We are discontinuing "Comfort care" as a category and introducing "Actively Dying" as the 4th category. In the dropdowns, hide "comfort care" and add the new category "Actively dying". All previous records with comfort care classification will stay as is. In future medical records, the only option for category must be Mild, Moderate, Critical and Actively dying.

### PR DESCRIPTION
**Pull request by shivankacker**
Dependent on https://github.com/coronasafe/care/pull/2298

## Proposed Changes

- Fixes #7962

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 can you modify the PR based on the issue

**Comment by nihal467** [comment]
@skks1212 

image


- [ ] In the log update patient category, the definition is always present , but as per issue, its should only be shown when patient is in icu bed

image

- [ ] in the create consultation page, when i select icu bed, the patient category definition is not present

**Comment by nihal467** [comment]
@skks1212 keeping this PR on hold, as there is a discussion going on in the related issue

**Comment by nihal467** [comment]
@skks1212 
image

the issue is modified few days back, make the necessary changes to cypress and PR, and follow up on the ongoing discussion in the issue

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — CHANGES_REQUESTED** [review]
LGTM, except missing i18n

**Pull request merged**
