### PR TITLE
fix: Add user media ready and camera permission denied notifications

### LINKED ISSUE #8687: Implement Camera Permission Handling and User Media Notifications indication
**Describe the bug**
- blank container appears, if we deny the camera permission's in browser.
   - After clicking on `Open camera` button:
camera_Open

   - After clicking on Switch button, camera screen stucks:
camera_switch
- Users are not informed when camera permissions are granted or denied, leading to confusion and a poor user experience.
- when user drag's a to website , There is no indication that file is dragged or not.

**To Reproduce**

1. Go to Facilities.
2. Click on any item.
3. Click on cover photo.
__**Note**: Edit cover photo modal opens__
4. Click on `Open camera`, now block the permission of camera, See the `Blank container`.
5. Now go to mobile screen , Click on `Open camera`, Now grant the permission of camera , and then `Switch`, See the Video stuck.
6. Drag and hold the file upon `Drag & drop container`, See **No indication of file being dragged**
7. No Indication of granted or blocked camera permission's, leading to confusion and a poor user experience.

**Expected behavior**
- If there is no stream to display on web cam then it should return to previous state with warning toast.
- When the camera permission is granted, a success toast should be displayed.
- When the camera permission is denied, an warning toast should be displayed.
- The SVG background should change to green when an image is being dragged over the drag-and-drop container.

**Video of solution**

https://github.com/user-attachments/assets/520c6d9e-aa31-4173-8215-ffcaba865ee6

**Desktop (please complete the following information):**

- OS: Windows
- Browser Brave
- Version 1.70.119

### PR DESCRIPTION
**Pull request by shauryag2002**
## Proposed Changes

- Fixes #8687 
- Added camera permission handling in `CoverImageEditModal`.
- Display success and error toasts for camera permission granted and denied states.
- Updated SVG to change background color when dragging an image over the drag-and-drop container.
- Improved user feedback with appropriate notifications for different states.
## Video of changes:

https://github.com/user-attachments/assets/ba6042ec-232d-4f58-9b8c-3dce60ffcf2b

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@shauryag2002 
image

- [ ] Remove the notification, when the camera feed is on. Notification is only required when the permission is denied

**Comment by shauryag2002** [comment]
@nihal467, Removed the notification, when the camera feed is on.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]
@shauryag2002 LGTM nice work, just a heads up on future PRs, no need to add translations for each language (English is enough), rest will be handled using crowdin.

**Pull request merged**
