### PR TITLE
Replaced existing medication with history of present illness 

### LINKED ISSUE #2784: History of Present illness comes on Existing Medication field
The values given in "History of Present Illness" field  on Consultation page shows in "Existing Medication" field under Medicines In Patient Dashboard.

issue github new 3

issue github new 2

### PR DESCRIPTION
**Pull request by skks1212**
History of present illness will be added in a later pr after it gets added to backend.
closes #2784

### CODE REVIEW

**Review by GokulramGHV — APPROVED** [review]

**Comment by nihal467** [comment]
@skks1212 once the work is completed, change the label to need testing

**Comment by shivankacker** [comment]
Please review this but do only merge it when [https://github.com/coronasafe/care/pull/890](https://github.com/coronasafe/care/pull/890) is merged

**Comment by shivankacker** [comment]
@nihal467 please merge as soon as you can as backend PR has been merged.

**Comment by nihal467** [comment]
@skks1212 can you merge the latest version to it, for testing

**Comment by shivankacker** [comment]
> @skks1212 can you merge the latest version to it, for testing

Done @nihal467

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
