### PR TITLE
Increase the Add button height in skills slideover.

### PR DESCRIPTION
**Pull request by shyamprakash123**
## Proposed Changes

- Fixes https://github.com/coronasafe/care_fe/issues/7142

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Comment by Ashesh3** [comment]
After discussing with Nihal, following changes are to be done on the button:
```
element.style {
    height: 45px !important;
    width: 74px !important;
    font-size: 16px;
}
```
The above is to be applied on the button using Tailwind classes.

To be done for:
- Linked Facilities
- Linked Skills

image

**Comment by nihal467** [comment]
@shyamprakash123

**Comment by shyamprakash123** [comment]
@nihal467 I've updated the code according to the requested changes.

cc: @rithviknishad @Ashesh3

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
