### PR TITLE
Revamped shifting UI

### PR DESCRIPTION
**Pull request by anuran-roy**
#2856

### CODE REVIEW

**Comment by nihal467** [comment]
@anuran-roy  this one still look bulky, can we do something about it

**Comment by anuran-roy** [comment]
@nihal467  I think the other lines (Address, Comments) can break into the next lines.

**Comment by nihal467** [comment]
@anuran-roy can you work on the shift UI, by referring to resource UI by positioning audit log, origin details, etc...

https://care.coronasafe.in/resource/7a98eb68-4418-4012-a376-cb93d35f022d

**Comment by anuran-roy** [comment]
image

@nihal467 will this work?

**Comment by nihal467** [comment]
@anuran-roy it looks good

**Pull request closed without merging**
