### PR TITLE
Improves Input Field UI for phone number input

### LINKED ISSUE #7248: Improve Input Field UI for Phone Number
**Describe the bug**
The current phone number input field UI presents challenges, primarily due to the inclusion of flags preceding to country codes without a search functionality. This design choice makes it difficult for users to locate their country efficiently. Additionally, the overall UI lacks visual appeal and can be enhanced for a more user-friendly experience.

**To Reproduce**

1. Go to any page consisting of phone number input field
2. Click on the phone number input field.
3. Observe the country selection dropdown menu.
4. Attempt to find a specific country without a search functionality.
5. Evaluate the overall appearance and user experience of the UI.

**Expected behavior**
The phone number input field UI should be improved to address the following:

1. Integrate a search functionality within the country selection dropdown to facilitate easy and quick identification of the user's country.
2. Enhance the overall visual design for a more appealing and modern look.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by UdaySagar-Git**
## Proposed Changes

- Fixes #7248 
- Improved UI to match existing UI 
-  Added search functionality 

Before : 
image

After :
image

[Screencast from 22-02-24 10:08:43 PM IST.webm](https://github.com/coronasafe/care_fe/assets/111575806/c295e7a9-12ec-4485-9aef-7bbef21bd364)

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
Hey! Nice work! Looks great!

Just a minor suggestion, could you decrease the width of the country select dropdown button?

image

**Review by Ashesh3 — APPROVED** [review]

**Comment by Ashesh3** [comment]
This looks really neat!

**Comment by UdaySagar-Git** [comment]
@rithviknishad @Ashesh3 
image

Thanks for the suggestion 

should I decrease more or this looks fine?

**Comment by Ashesh3** [comment]
> @rithviknishad @Ashesh3 image
> 
> Thanks for the suggestion
> 
> should I decrease more or this looks fine?

Looks like the perfect width to me.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
