### PR TITLE
Add Camera Feed to Tabs in Patient Consultation Page

### LINKED ISSUE #2449: Camera Feed as Tab in Consultation Page
The Camera Feed is currently a dedicated page. It should instead be loaded in the Consultation Page as a Tab

### PR DESCRIPTION
**Pull request by rabilrbl**
Closes #2449 

### Changes
- Replace the Old implementation of Feed (`LiveFeed.tsx`) with the new Feed (`Feed.tsx`) on the consultation details page.
- Remove CameraFeed from AppRouter
- Remove unused variables as shown in ESLint errors in the pre-commit hook
- Removed unnecessary styling found in `Feed.tsx`

image

### CODE REVIEW

**Comment by rabilrbl** [comment]
Stuck on an issue with vertical overflow from the camera feed component hence marked as draft till it's fixed. 
The camera movement buttons are causing the issue.

@developedBySJ @gigincg 

https://user-images.githubusercontent.com/63334479/169994498-c68e3c21-ee28-4cbe-a403-1a72e8562799.mp4

**Comment by gigincg** [comment]
@developedBySJ Can you help solve the overflow issue here?

**Comment by developedBySJ** [comment]
@gigincg Sure

**Comment by rabilrbl** [comment]
@developedBySJ

Issue is seen when deeply scroll into the page

image

**Comment by rabilrbl** [comment]
The overflow problem is fixed from #2758. This PR is good to merge

**Comment by developedBySJ** [comment]
@rabilrbl Fix conflicts

**Comment by nihal467** [comment]
@khavinshankar @gigincg @rabilrbl what is the difference with that existing staging !

**Comment by rabilrbl** [comment]
@nihal467  **Camera feed has been moved**. Now available under tabs in patient details
| Before | After |
| - | - |
|image|image|

**Comment by nihal467** [comment]
@rabilrbl does the camera feed button is not redirecting anywhere after this!

**Comment by aparnacoronasafe** [comment]
@nihal467 I have tested this in preview. It looks good to me. Check for the patient "Annie Philip" Lets try and merge it this week itself

**Comment by aparnacoronasafe** [comment]
@gigincg @khavinshankar Please review this. Lets close this this week

**Comment by nihal467** [comment]
image

@rabilrbl 

- [ ] make the page responsive
- [ ] make the button from doctor's note to the top, have same length as of the log update buttons

**Comment by nihal467** [comment]
@rabilrbl what is the status !

**Comment by rabilrbl** [comment]
@nihal467 All issues are fixed after merging `develop` branch! 
LMK for any further changes

image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
