### PR TITLE
Restyled discharge patient popup

### LINKED ISSUE #2992: Revamp : Discharge Pop-up
the pop-up looks so simple, can we have a revamped design

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #2992 
image

### CODE REVIEW

**Review by cp-Coder — COMMENTED** [review]
LGTM

**Comment by nihal467** [comment]
@Pranshu1902 the combination of red and green doesn't look good, can you change it to something suitable to the UI

**Review by developedBySJ — COMMENTED** [review]
Use this for reference
modals

@nihal467 @gigincg

**Comment by Pranshu1902** [comment]
@nihal467  Updated UI:
image

**Comment by nihal467** [comment]
@Pranshu1902 give a border for the cancel button too,

**Comment by Pranshu1902** [comment]
Updated view:
image

**Comment by nihal467** [comment]
@Pranshu1902 reduce the grey intensity, its shadow effect, of the button

**Comment by Pranshu1902** [comment]
@nihal467 is this ok?
image

**Comment by nihal467** [comment]
test approved

**Comment by Pranshu1902** [comment]
Updated view:
image

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
