### PR TITLE
Replace metatag with CARE logo

### PR DESCRIPTION
**Pull request by sam9111**
Screenshot 2022-03-23 at 6 25 21 PM

Tested with metatags.io

Have replaced the cover image environment variables in the .env file with https://cdn.coronasafe.network/care-manifest/images/icons/icon-192x192.png

### CODE REVIEW

**Comment by nihal467** [comment]
@sam9111 @gigincg the picture clarity looks so low, is there a possibility to get a more quality pic, in its recommend size 1200 x 628

**Comment by gigincg** [comment]
@sam9111 I think the Care Logo would work better than the Break the Chain logo. @bodhish comments?

**Comment by nihal467** [comment]
@sam9111 @gigincg 

ieofjweif

its blank

**Comment by sam9111** [comment]
Screenshot 2022-03-31 at 3 04 57 PM

**Comment by sam9111** [comment]
https://cdn.coronasafe.network/care_logo.png

**Comment by nihal467** [comment]
test approved

**Pull request merged**
