### PR TITLE
Add Frontend validation in the add multiple bed function

### LINKED ISSUE #6624: Add Frontend validation in the add multiple bed function
**Describe the bug**

We can only create 100 multiple beds at a location per request, there is no validation for the front-end but back-end has it and rejects any creation request for 100+ bed

**To Reproduce**

1. Go to facility location management and try creating multiple 100+ beds
2. See error

**Expected behavior**

- [ ] add a frontend validation for multiple bed creation form

**Screenshots**

image

### PR DESCRIPTION
**Pull request by sriharsh05**
### <samp>🤖 Generated by Copilot at dd101fe</samp>

Added validation error message for `numberOfBeds` field in `AddBedForm` component. This improves the user experience and data quality when creating or updating beds in a facility.

## Proposed Changes
Add Frontend validation in the add multiple bed function. If there are more than 100 beds given into the input, ""Number of beds cannot be greater than 100" is given as error.

- Fixes #6624 ?
- Add Frontend validation for number of beds in AddBedForm.tsx

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at dd101fe</samp>

* Add a validation error message to the number of beds field ([link](https://github.com/coronasafe/care_fe/pull/6643/files?diff=unified&w=0#diff-c3725e9874032f1cdb18f7c6b15f978b17a7306d49ce27104377ac1ccaaa4b8cR232-R236))

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Also disable the submit button if invalid

**Comment by sriharsh05** [comment]
> Also disable the submit button if invalid

If i disable the submit button, I don't think there is a requirement for backend validation for number of beds . Shall i remove that too?

**Comment by rithviknishad** [comment]
True, but backend validations are a must anyhow. Say we create a seperate tool that populates beds (which is outside care_fe), so backend must still validate properly.

But if you know for sure something is wrong from client side, and it's a minor validation, it's good to block it from front-end itself.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
