### PR TITLE
Add vaccination information

### PR DESCRIPTION
**Pull request by shaileshaanand**
All linting issues have been reverted

Co-authored-by: Divya <divyagarg2601@gmail.com>
Co-authored-by: Amit <amitkr0819@gmail.com>
Co-authored-by: Khavin <khavinshankar@gmail.com>

### CODE REVIEW

**Comment by shaileshaanand** [comment]
@vigneshhari @bodhish @amruthavijay88 I have fixed the linting issues, please verify and merge this one instead of #997 .

**Comment by divyagar** [comment]
The validation is pending. Will complete it asap.

**Comment by divyagar** [comment]
@bodhish @tomahawk-pilot The changes are done. Please review.

**Comment by khavinshankar** [comment]
This fixes #945 Vaccination: Info on Dose and type

**Comment by divyagar** [comment]
@bodhish @tomahawk-pilot Is there anything that needs to be done here?

**Pull request merged**
