### PR TITLE
fixed spacing issues in Consultation Details

### LINKED ISSUE #2044: Alignment Issue : Consultation Page
set 1

https://care.coronasafe.in/facility/7a560e62-6aae-4293-8f1a-0ba840e3449f/patient/192fdee9-397f-49bd-833a-10f700416da8/consultation/d794ba54-da42-4238-8ba9-0b628ca60069

- 2 years ago and the date is overlapping
- spacing under the log update button

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #2044 

After fix:
image

### CODE REVIEW

**Comment by nihal467** [comment]
test failed @khavinshankar @gigincg 

151167410-2178dfbb-c0c4-4c20-9282-f1bb4d35c5d7 (1)

- the alignment of the adjacent two boxes are gone

My suggestion 

- can you lift the last modified date and the user name upwards, so we manage the white space out there and the both boxes adjacent to each other are aligned

**Comment by khavinshankar** [comment]
@nihal467 is this ok
image

**Comment by nihal467** [comment]
@khavinshankar don't change the location of created, because now it seem so bulky there

**Comment by khavinshankar** [comment]
@nihal467 having `Created` on one side and `Last Updated` on another side might seem inconsistent, what are your thoughts?

**Comment by gigincg** [comment]
> test failed @khavinshankar @gigincg 
> 
> 
> 
> 151167410-2178dfbb-c0c4-4c20-9282-f1bb4d35c5d7 (1)
> 
> 
> 
> - the alignment of the adjacent two boxes are gone
> 
> 
> 
> My suggestion 
> 
> 
> 
> - can you lift the last modified date and the user name upwards, so we manage the white space out there and the both boxes adjacent to each other are aligned

Isn't it better this way? I might even say remove the white box around the buttons. Opinion? @khavinshankar

**Comment by khavinshankar** [comment]
reverted back to the previous style and removed the white box around the buttons

UI:
image

**Pull request closed without merging**
