### PR TITLE
Fix no notification on hard refresh

### LINKED ISSUE #3449: notice board is not showing any notification send to the facility
**Describe the bug**

- [x] when we are sending a notification to the facility using a district admin access and view the notification received to the facility as a staff user, unable to see the notification received in the notice board
- [x] when we hard refresh ( Ctrl + F5 ) the notice board page, it says no notice available 

**To Reproduce**

1. Go to the facility page using a district admin access
2. Click on any facility, and send a notification to the facility 
3. re-login using a staff id linked to that facility
4. go to the notice board
5. see the error that nothing is been reflected there

**Expected behavior**

the notice sent to the facility using a district admin should appear on the notice board of the staff linked to the facility

**Screenshots**

image

- above image shows that the notification is sent to the facility

image

- above image shows that the notification is not reflected in the staff login notice board

image

- above image shows that after the hard refresh ( Ctrl +F5 ), the notice board become blank

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #3449 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar 
image

bug still remains, when we are hitting ctrl+F5 and ctrl+R , after opening the notice tab, the bug still persist

**Comment by nihal467** [comment]
@khavinshankar 
image

the issue still remains there

**Comment by nihal467** [comment]
@khavinshankar 
image

go to notice board tab, and hit ctlr+r or ctrl+f5, then you will see no notice found

**Comment by nihal467** [comment]
@khavinshankar what is the update on this PR

**Comment by nihal467** [comment]
@khavinshankar what is the status on this PR

**Comment by khavinshankar** [comment]
will create a new pr

**Pull request closed without merging**
