### PR TITLE
Suggestion: Rename WhatsApp number to Alternative number

### PR DESCRIPTION
**Pull request by Ashesh3**
The secondary phone number for a user is referenced as "Alternative number" throughout the code and also in the users filter.

image

```
<PhoneNumberField
    name="altPhoneNumber"
...
    value={states.form.altPhoneNumber}
    onChange={(value: string) =>
        handleAlternativeNumChange(value, "altPhoneNumber")
    }
    errors={states.errors.altPhoneNumber}
 />
```

In order to make it more user friendly and consistent, WhatsApp number should be labelled as "Alternative number" instead.
image

### CODE REVIEW

**Comment by developedBySJ** [comment]
@Ashesh3 can you mention the issue?
Alternative numbers and WhatsApp numbers are two different things.

**Comment by Ashesh3** [comment]
> @Ashesh3 can you mention the issue? Alternative numbers and WhatsApp numbers are two different things.

They appear to be the same thing. 

We can set WhatsApp number on the profile page, but in the users page, the filter lists it as "Alternative number" and filtering works displaying it as alt number

image
image

But the profile page shows it as "WhatsApp" number.
image


The frontend is inconsistent with how the data is stored and represented in the backend. Everywhere, the "second number" is referenced by "Alternative number" and not "WhatsApp number".

https://github.com/coronasafe/care/blob/master/care/users/models.py#L216

```
class User(AbstractUser):
    ...
    alt_phone_number = models.CharField
```

The filter displays it as "Alternative number" too
image

Updating the said "WhatsApp number" actually sends it as the alternative number:
image

https://github.com/coronasafe/care_fe/blob/develop/src/Components/Users/UserProfile.tsx#L491

```
<PhoneNumberField
    --> name="altPhoneNumber"
        label="Whatsapp Number"
    --> value={states.form.altPhoneNumber}
        onChange={ (value: string) =>
    -->     handleWhatsappNumChange(value, "altPhoneNumber")
        }
    errors={states.errors.altPhoneNumber}
/>
```

The `UserModel` only lists the second number as `alt_phone_number`, I do not see a distinction between "WhatsApp" and "Alternative" number here, the second number is always mentioned as the Alternative. 

https://github.com/coronasafe/care_fe/blob/develop/src/Components/Users/models.tsx#L12

```
export interface UserModel {
  ...
  phone_number?: string;
  alt_phone_number?: string;
  ...
```

So, it appears that "WhatsApp number" is actually just the "Alternative number" but mislabeled.

**Comment by nihal467** [comment]
@Ashesh3 once work is completed, change the badge

**Comment by Ashesh3** [comment]
@coronasafe/care-fe-code-reviewers Need your opinion here.

**Comment by Ashesh3** [comment]
Todo: After discussing this with @gigincg , The change would be to rename "Alternative number" on the filter page to "WhatsApp number"

**Comment by Ashesh3** [comment]
Renamed Alt phone to WhatsApp phone on the filters page, to maintain consistency.

image

**Comment by nihal467** [comment]
@Ashesh3 
image

the badge still says, it is alternative number , where everywhere else it is WhatsApp no

**Comment by Ashesh3** [comment]
@nihal467 Fixed!

image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Review by cp-Coder — APPROVED** [review]

**Pull request merged**
