### PR TITLE
Fix unresponsiveness of consultation page

### LINKED ISSUE #3142: consultation page is unresponsive
image

### PR DESCRIPTION
**Pull request by naman114**
Fixes #3142 

image

image

### CODE REVIEW

**Review by developedBySJ — CHANGES_REQUESTED** [review]
@naman114 Make full-width buttons

image

**Comment by nihal467** [comment]
@naman114 once the work completed, update it to need testing

**Comment by naman114** [comment]
@developedBySJ @nihal467 Made the buttons full width

image

**Review by developedBySJ — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
