### PR TITLE
Fixed UI issue in dropdown

### LINKED ISSUE #3121: UI issue in SelectField
image

remove the top curves in the dropdown, across the platform

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #3121
- [x] Added `MenuItem` as dropdown options

### CODE REVIEW

**Comment by aeswibon** [comment]
@nihal467 Is this UI okay??

https://user-images.githubusercontent.com/77210185/178935451-fa3f84d2-a4e3-4af2-9748-1b12162b440e.mp4

**Comment by developedBySJ** [comment]
@cp-Coder Instead of using material UI components, Style components using tailwind or make custom components.

@gigincg

**Comment by nihal467** [comment]
@cp-Coder 
image

this UI doesn't look good, can we have a better alternative

**Comment by aeswibon** [comment]
Will open a new PR to fix this issue

**Pull request closed without merging**
