### PR TITLE
Adds user type: Nurse and Nurse (readonly)

### LINKED ISSUE #6240: New user type "Nurse"
**Is your feature request related to a problem? Please describe.**
Currently, all nurses using CARE are registered under the User type "Staff"
In future we expect administrative staff to be registered in CARE as "Staff" usertype

**Describe the solution you'd like**

- [x] Make a new User Type for "Nurse" with exact same access and role as "staff" user type
- [x] Migrate all existing "Staff" users in CARE to "Nurse" usertype.

For any doubts or clarifications, reach @gigincg

### PR DESCRIPTION
**Pull request by rithviknishad**
### <samp>🤖 Generated by Copilot at ba07f48</samp>

Added Nurse role and updated user-related components and README. This pull request introduces a new user role `Nurse` and a read-only variant `NurseReadOnly` to the application. It also updates the user-related components and functions in `src/Common/constants.tsx` and `src/Components/Users/UserAdd.tsx` to use the new roles. Additionally, it changes the staffdev user role and the staff option in the video consultation component to Nurse in `README.md` and `src/Components/Facility/DoctorVideoSlideover.tsx` respectively.

## Required Backends
- https://github.com/coronasafe/care/pull/1819

## Proposed Changes

- Fixes #6240

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at ba07f48</samp>

*  Add Nurse and NurseReadOnly user roles to the application ([link](https://github.com/coronasafe/care_fe/pull/6464/files?diff=unified&w=0#diff-37705b30476b14631124ce42dd5c3500d43fbede16f0e91f9ae2905e4adc6376R31-R32), [link](https://github.com/coronasafe/care_fe/pull/6464/files?diff=unified&w=0#diff-37705b30476b14631124ce42dd5c3500d43fbede16f0e91f9ae2905e4adc6376R52-R53))
*  Change the staffdev user role from Staff to Nurse in the staging API credentials ([link](https://github.com/coronasafe/care_fe/pull/6464/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L59-R59))
*  Enable doctors to assign video consultations to nurses instead of staff ([link](https://github.com/coronasafe/care_fe/pull/6464/files?diff=unified&w=0#diff-f15a132265ab339453f06bc7dc6b773802090dfba335c46051a309b512de2060L61-R62))
*  Refactor the UserAdd component to use a constant array for the user types that are related to a facility ([link](https://github.com/coronasafe/care_fe/pull/6464/files?diff=unified&w=0#diff-61941d2843942da2640b50b54d0f8503484ec0a268e75b7962d90faf364d3827R108-R114), [link](https://github.com/coronasafe/care_fe/pull/6464/files?diff=unified&w=0#diff-61941d2843942da2640b50b54d0f8503484ec0a268e75b7962d90faf364d3827L249-R261), [link](https://github.com/coronasafe/care_fe/pull/6464/files?diff=unified&w=0#diff-61941d2843942da2640b50b54d0f8503484ec0a268e75b7962d90faf364d3827L343-R349), [link](https://github.com/coronasafe/care_fe/pull/6464/files?diff=unified&w=0#diff-61941d2843942da2640b50b54d0f8503484ec0a268e75b7962d90faf364d3827L401-R405))
*  Remove the unused ROLE_STATUS_MAP object from the `src/Common/constants.tsx` file ([link](https://github.com/coronasafe/care_fe/pull/6464/files?diff=unified&w=0#diff-37705b30476b14631124ce42dd5c3500d43fbede16f0e91f9ae2905e4adc6376L413-L430))

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
@aeswibon clear the merge conflict

**Comment by nihal467** [comment]
@aeswibon clear the merge conflict

**Comment by nihal467** [comment]
@aeswibon 

image

- [ ] iam able to create a sample request using a staff id, can you reconfirm all the access control

**Comment by aeswibon** [comment]
> @aeswibon
> 
> image
> * [ ]  iam able to create a sample request using a staff id, can you reconfirm all the access control

Okay I will check

**Comment by nihal467** [comment]
LGTM , checked through tunnel provided by aakash

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
