### PR TITLE
Adds Asset Class field and hints for Asset Type in AssetCreate

### LINKED ISSUE #2431: Create a new Field in CreateAsset Form to update the asset_class for the asset

### LINKED ISSUE #2432: Create a Hint next the Asset Type field (Internal/External) that specifies the difference

### PR DESCRIPTION
**Pull request by rithviknishad**
Asset Class field added to Create Asset page.
Waiting for coronasafe/care#792 to be solved.

Closes #2431 
Closes #2432

### CODE REVIEW

**Comment by rithviknishad** [comment]
Closes #2431 #2432

**Comment by rithviknishad** [comment]
https://user-images.githubusercontent.com/25143503/170995258-2de66c3f-caba-4119-9585-3b9a425a25a0.mp4

Edit: ignore the something went wrong. It has been fixed by the backend and works without issues.

**Comment by nihal467** [comment]
wkeopf

test failed @rithviknishad @nihal467 the droplist is look like a description, can you change it to better UI

**Comment by rithviknishad** [comment]
@nihal467 unable to reproduce. this is what i see, even from preview deploy. will look into it.

image

**Comment by rithviknishad** [comment]
https://user-images.githubusercontent.com/25143503/172046804-90c6228a-8f37-4f16-b859-972c61e68407.mp4

**Comment by rithviknishad** [comment]
@nihal467 fixed it...

**Comment by nihal467** [comment]
test failed, @rithviknishad @gigincg the UI still doesn't look good, i have done hard refresh also, still no change

**Pull request closed without merging**
