### PR TITLE
Made sidebar scrollable in small screens and landscape mode

### PR DESCRIPTION
**Pull request by khavinshankar**
## Proposed Changes

- made sidebar scrollable in small screens and landscape mode

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

cc: @nihal467

### CODE REVIEW

**Comment by nihal467** [comment]
@gigincg 
image

not able to see the profile name, marking it to team discussion required, for reviewing in call

**Comment by nihal467** [comment]
@khavinshankar @gigincg as per Eod, @skks1212 will be working on a solution

**Comment by nihal467** [comment]
@gigincg can you check the merge conflict

**Comment by khavinshankar** [comment]
@nihal467 resolved the merge conflict, can you test it out again..

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
