### PR TITLE
Refactor discharge_reason data type to Integer

### PR DESCRIPTION
**Pull request by Ashesh3**
Backend PR: https://github.com/coronasafe/care/pull/1773

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 5693149</samp>

The pull request refactors and updates the code related to discharge reasons in various components and interfaces. It uses a constant `DISCHARGE_REASONS` for the discharge reasons and changes the type of the `discharge_reason` property to a number or null to align with the backend API. This improves the code consistency, clarity, and maintainability.

## Proposed Changes

- Fixes https://github.com/coronasafe/care/issues/1739

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 5693149</samp>

*  Change the type of `discharge_reason` from string to number or null in various interfaces, components, and states to match the backend API and avoid type errors ([link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-0815d428acd0061366098da333b4ad3a1df84c9f05d55a82b23790c22bdc5f2fL123-R124), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-0815d428acd0061366098da333b4ad3a1df84c9f05d55a82b23790c22bdc5f2fL173-R174), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-0815d428acd0061366098da333b4ad3a1df84c9f05d55a82b23790c22bdc5f2fL399-R400), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L29-R29), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L43-R43), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L57-R57), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfL103-R103))
*  Replace hard-coded strings with the `DISCHARGE_REASONS` constant from `src/Common/constants.tsx` in various components to improve readability and maintainability and avoid errors due to typos or changes in the discharge reasons ([link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-a1ae41968a05e24ed2d94c91009fbb88f1319a60a3b965773b3395130d27658bL199-R200), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-a1ae41968a05e24ed2d94c91009fbb88f1319a60a3b965773b3395130d27658bL217-R220), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-a1ae41968a05e24ed2d94c91009fbb88f1319a60a3b965773b3395130d27658bL227-R232), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-a1ae41968a05e24ed2d94c91009fbb88f1319a60a3b965773b3395130d27658bL262-R269), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-a1ae41968a05e24ed2d94c91009fbb88f1319a60a3b965773b3395130d27658bL289-R297), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-0815d428acd0061366098da333b4ad3a1df84c9f05d55a82b23790c22bdc5f2fL651-R653), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L126-R128), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L215-R217), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L233-R243), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-53fbb567d16de67259204bd83187f4916032665a0198c0f09fe3dd67a7541e6fL760-R765), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-474c76838170cd340f215b026249385e32a2d8263bd30a568c2b02b38d272948L325-R326), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-474c76838170cd340f215b026249385e32a2d8263bd30a568c2b02b38d272948L357-R359), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-5d9f2efbfb558b3bdc89362fef4a25f68c166440805631dfb6d12b8701f9236fL285-R288))
*  Change the label, value, name, and error of the `TextFormField` and `TextAreaFormField` components in the `DischargeModal` component based on the `discharge_reason` value using numbers and an object literal to access the corresponding text ([link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L233-R243), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L252-R264), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L264-R272), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L283-R292), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L289-R299), [link](https://github.com/coronasafe/care_fe/pull/6807/files?diff=unified&w=0#diff-ad38d96db62f6d8302226491a72c518ad76ebac1f3f2efbf1b4ca9754d01e764L301-R312))

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 clear the merge conflict and follow up on the backend PR

**Comment by nihal467** [comment]
**test to complete**

- [ ] all four type discharge is possible in patient consultation / shifting form / patient transfer
- [ ] discharge reason is properly chosen in patient consultation page
- [ ] discharge reason is properly chosen in discharge summary

**Comment by nihal467** [comment]
@Ashesh3 
image

- [ ] patient discharge reason with recovered, referred, LAMA is not possible

**Comment by Ashesh3** [comment]
Note: Discharge reason filter on Patient List page is non functional - Pending merge of https://github.com/coronasafe/care/pull/1818

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
