### PR TITLE
Introduced Reusable JSON Parser and Validator with Schema, File Preview, and Selected Import Support for XLSX/CSV Files

### LINKED ISSUE #7333: Improve import UI for External Results Import
**Describe the bug**
The current UI for the External Results import is inconsistent and differs from the UI on other pages. Specifically, when attempting to import, it navigates to new page instead of the present page

**To Reproduce**
1. Go to External Results tab 
2. Click on import 

**Expected behavior**
current ui :
image
expected ui :
image

### LINKED ISSUE #7607: Auto-close import asset pop-up
**Describe the bug**

When we complete the asset import, the pop-up is not auto closing

**To Reproduce**

1. Go to asset tab, click on the import asset icon
2. Upload a excel file
3. once the upload is complete

**Expected behavior**

Upon completing the upload, the import assets pop-up should auto-close

**Screenshots**

image

### PR DESCRIPTION
**Pull request by UdaySagar-Git**
## Proposed Changes

- Fixes #7333 
- Implemented a reusable JSON parser and validator with a specific schema for any JSON data
- Converted a separate page for external result upload to a modal
- Enhanced drag and drop functionality
- Added file preview functionality for XLSX/CSV files
- Replaced two packages with a single package

## Features included in file viewer 
- Displays errors on hover
- Provides pagination with selectable number of rows per page
- Allows users to select specific rows for import
- Blocks selection if the row has any errors

[Screencast from 09-03-24 03:53:46 PM IST.webm](https://github.com/coronasafe/care_fe/assets/111575806/1d83fe06-ebf0-4e43-bcc3-9710d422bb00)
*screen recording feels laggy, but it was smooth in local development.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by UdaySagar-Git** [comment]
@rithviknishad @Ashesh3 can you please review this pr

**Comment by UdaySagar-Git** [comment]
@gigincg fixed cypress tests , can you please mark this as needs review /needs testing

**Review by Ashesh3 — APPROVED** [review]
Awesome!

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@UdaySagar-Git 
image

- [ ] once the upload is successful, we should auto-close the pop-up

image

- [ ] if there is error in the data, 
- mention the error to the user, it can be a pop-up on hovering over the error icon
- or it can be written on the top or bottom in the preview component

- [ ] hide the pagination component if it's a single page

**Comment by UdaySagar-Git** [comment]
@nihal467 regarding error on hover, I have did that for individual cell . What should I display on hover on icon ?!
Like the join of cell names by " , " would work ? 
( you can observe the error in the above preview by scrolling to right ! Can you please confirm  whether it's working or not ?)

**Comment by UdaySagar-Git** [comment]
- [x]  once the upload is successful, we should auto-close the pop-up
- [x]  if there is error in the data show it on hover 
- [x]  hide the pagination component if it's a single page

**Comment by UdaySagar-Git** [comment]
@nihal467 Let me know if this works or need any improvements 

image
image
image

**Comment by UdaySagar-Git** [comment]
@nihal467 cypress failures are not due to this pr
they are occurring in  user_creation.cy.ts

**Comment by nihal467** [comment]
image

@UdaySagar-Git the build is failing due to type error , fix it

**Comment by UdaySagar-Git** [comment]
@nihal467 fixed

**Comment by UdaySagar-Git** [comment]
@rithviknishad can you please mark this as needs testing

**Comment by nihal467** [comment]
@UdaySagar-Git fix the merge conflict

**Comment by rithviknishad** [comment]
@UdaySagar-Git lint checks failing. upgrade the packages locally and fix the lints

**Comment by UdaySagar-Git** [comment]
@rithviknishad done!

**Review by rithviknishad — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
