### PR TITLE
added skeleton loader for consent records

### LINKED ISSUE #7897: No Records Found behavior is not working properly in consent form
**Describe the bug**

- [ ] When we upload a new file to the consent form, the "no record found" is displayed along with the file. (refer no: SS 1)
- [ ] When it is a new patient with no consent record (Archive or upload), the "no record found" text is no displayed at all (refer no: SS 2)

**Screenshots**

image
image

### LINKED ISSUE #7900: Add Loader to the Consent form page
**Is your feature request related to a problem? Please describe.**

When there is file present in the patient consent form, and it's in a loading state, currently we are not showing anything

**Describe the solution you'd like**

When the existing files are loading, add a loader in the patient consent form

**Screenshot**

image

### PR DESCRIPTION
**Pull request by shivankacker**
## Proposed Changes

- Fixes #7900 
- Fixes #7897
- Adds a skeleton loader at consent records page

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 
image

its still buddy, with files, it shows no file

**Review by nihal467 — CHANGES_REQUESTED** [review]
its still buggy

**Comment by nihal467** [comment]
- [ ] reset the component once the upload is completed.
- [ ] the upload button is flickering when we click upload button

image

- [ ] bug remains

**Comment by nihal467** [comment]
@skks1212 
image
image

- [ ] the file is not getting auto-archive
- [ ] when we click the archive button of the file, which should have auto-archived, we can see the archive reason frontend validation is thrown and the reason is auto-filled

**Review by nihal467 — CHANGES_REQUESTED** [review]
its still buggy, check the above comment

**Comment by nihal467** [comment]
image

@skks1212 can you make it responsive

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Review by nihal467 — APPROVED** [review]

**Pull request merged**
