### PR TITLE
Fixes issues in Facility Card's layout and minor UI tweaks

### LINKED ISSUE #3954: Facility card layout having space below action buttons bar
**Describe the bug**
An issue with the facility card responsive layout.

**To Reproduce**

1. Go to the facilities page

image

**Expected behavior**
It should look like this
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #4012: alignment of buttons on Facility list
On the facility list, when there are two facilities listed in the same row, and one facility card has more labels, the content in the adjacent facility card is not aligned properly.
Screenshot 2022-11-09 at 4 11 06 PM

The buttons for notify, facility and patients must be pinned to the bottom of the card

### LINKED ISSUE #4013: Facility cover photo in mobile view is not clipped if height is too high
**Describe the bug**
Height of facility cover image is not limited in mobile view.

**To Reproduce**

1. Go to facilities page in mobile view and scroll to a facility having a long height image.

**Expected behavior**
- [ ] The image's width should be card's width but height should restricted. Something like: `w-full object-cover max-h-[120px]`

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: ubuntu 22.10
- Browser Firefox Developer Edition
- Version 100+

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

image
- Fixes #4013 
- Fixes #3954 
- Duplicate issue: Fixes #4012
- Replaced old buttons with new tailwind buttons

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
The only changes made were: 
1. class h-fit was conflicting with h-full, but in the end h-fit got priority, so removed it
image

2. Refactored out the whole card to a named component: `FacilityCard`.

**Comment by nihal467** [comment]
@rithviknishad 
image

the facility buttons are missing, in responsive view

**Comment by nihal467** [comment]
LGTM, marking it as "Team Discussion required" for final approval of the UI

**Comment by nihal467** [comment]
@rithviknishad once its done,let me know

**Comment by nihal467** [comment]
@rithviknishad the deployment is failed

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
