### PR TITLE
FIXED: The assets configuration page lacks mobile responsiveness

### LINKED ISSUE #9465: The assets configuration page lacks mobile responsiveness
**Describe the bug**
The bug is that the assets configuration page is not mobile-responsive, causing layout issues on smaller screens.

**To Reproduce**

1. Go to 'Assents button on sidebar'
2. Click on 'Configure button'
3. See error

**Expected behavior**
I expected the assets configuration page to adapt seamlessly to smaller screen sizes, ensuring all elements are displayed correctly and remain fully functional on mobile devices.

**Screenshots**
Image

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [130.0.6723.117]

**Additional context**

### PR DESCRIPTION
**Pull request by modamaan**
## Proposed Changes

- Fixes #9465 
- Change 1
Screenshot 2024-12-17 184211

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Enhanced layout and styling for the HL7 Monitor component.
	- Conditional rendering of the Ventilator Patient Vitals Monitor based on asset type.
	- Improved responsiveness and layout for the HL7 Patient Vitals Monitor component.

- **Bug Fixes**
	- Improved error handling for invalid IP addresses with updated messaging.

- **Chores**
	- Updated import paths for the Card and Button components.
	- Replaced the Submit component with the Button component.
	- Adjusted styling for Card components with additional padding and margin.
	- Enhanced spacing and layout for non-waveform data in the Vitals Monitor component.

### CODE REVIEW

**Comment by Jacobjeevan** [comment]
Check the failing cypress test; should be related to the button changes.

**Comment by modamaan** [comment]
@Jacobjeevan please check the updation

**Review by rithviknishad — APPROVED** [review]

**Review by rithviknishad — CHANGES_REQUESTED** [review]
use screen's width as in other pages

image

**Comment by modamaan** [comment]
@rithviknishad @Jacobjeevan @bodhish  how to resolve these cypress errors  

Screenshot 2024-12-18 203149

**Comment by modamaan** [comment]
@rithviknishad can you please check the updation

**Comment by Jacobjeevan** [comment]
image


Update the screens as well.

**Review by Jacobjeevan — CHANGES_REQUESTED** [review]
image


Update the screens as well.

**Comment by modamaan** [comment]
@Jacobjeevan  HL7 monitor
Screenshot 2024-12-19 231415

ventilator monitor
Screenshot 2024-12-19 231330

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
image

@modamaan the screen is not responsive in mobile screen

**Comment by modamaan** [comment]
@nihal467  i didnt get the real time data for testing

**Comment by Jacobjeevan** [comment]
> @nihal467 i didnt get the real time data for testing

@modamaan  You can check Gigin in the staging site (`devdistrictadmin` login if you can't access it, same password).

Here's direct link to two assets:

https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/assets/73885d66-4891-4d4f-ba65-78c75baf7e8d/configure

https://care.ohc.network/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/assets/491bfe55-fe71-47fe-bb2e-a06e20071431/configure

**Comment by modamaan** [comment]
@Jacobjeevan  I logged into the `devdistrictadmin` and clicked the provided direct link, but it shows 
Screenshot 2024-12-31 003844

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan I logged into the `devdistrictadmin` and clicked the provided direct link, but it shows Screenshot 2024-12-31 003844

Sorry, I meant dev-districtadmin. But anyways, don't worry about it. Issue is no longer relevant as we are removing/reworking assets 👍

**Pull request closed without merging**
