### PR TITLE
Facilityui

### PR DESCRIPTION
**Pull request by divyagar**
#999

### CODE REVIEW

**Comment by bodhish** [comment]
@divyagar lets talk about this today

**Comment by dauntlessnomad** [comment]
@divyagar @bodhish whats the verdict on this one ?

**Comment by divyagar** [comment]
@tomahawk-pilot I am making the changes that were requested by @bodhish .

**Comment by divyagar** [comment]
@bodhish Do I have to remove `poppins` and `roboto` font families also from `tailwind.config.js` ?

**Comment by bodhish** [comment]
I still see font awesome deps in the changes. Please clean it up

**Comment by bodhish** [comment]
@divyagar what happens to the old files?

**Comment by divyagar** [comment]
@bodhish I was thinking of keeping `FacilityList` file in case anything fails, we can switch back, just like `PatientFilter` and `PatientFilterV2` files. But if you want I can remove FacilityList and make changes accordingly.

**Comment by bodhish** [comment]
It should not fail 😅.

We should remove unused files from the Repo.

**Comment by divyagar** [comment]
Done @bodhish

**Review by bodhish — APPROVED** [review]
LGTM

**Pull request merged**
