### PR TITLE
Improve bed UI

### LINKED ISSUE #2682: Align bed assignment modal and improve general UI
image

### PR DESCRIPTION
**Pull request by skks1212**
Before
image

After
image

Mobile :
image

closes #2682

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 check the deployment failure

**Comment by shivankacker** [comment]
@nihal467 https://deploy-preview-2699--care-net.netlify.app

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
@skks1212 please do work on the merge conflicts

**Comment by shivankacker** [comment]
@khavinshankar merged

**Review by cp-Coder — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
