### PR TITLE
Fix: Volunteer access to link facility

### LINKED ISSUE #9420: Disable Volunteers’ access to Unlink Assigned Facility
**Describe the bug**
Currently, volunteers have the ability to unlink their assigned facility. This action should be restricted.

**To Reproduce**
- Login to CARE with Volunteer access. 
- Go to Users > Linked Facilities 
- Click on unlink button

**Expected behaviour**
Disable the “unlink facility” option for volunteers.

### PR DESCRIPTION
**Pull request by AdityaJ2305**
## Proposed Changes

- Fixes #9420 

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **New Features**
	- Conditional logic added to disable certain UI elements for users with the "Volunteer" type.
	- Enhanced access control within the user interface to improve user experience.

### CODE REVIEW

**Comment by AdityaJ2305** [comment]
I don’t think the Cypress tests failed due to the changes in this PR. Could someone confirm?

**Review by Jacobjeevan — APPROVED** [review]

**Comment by Jacobjeevan** [comment]
> I don’t think the Cypress tests failed due to the changes in this PR. Could someone confirm?

yep

**Comment by nihal467** [comment]
image

- An admin is currently unable to unlink a facility for a volunteer user. The expected behavior is that an admin should have the ability to both link and unlink facilities for volunteer users. However, volunteer users should be restricted from unlinking their assigned facilities themselves.

**Comment by AdityaJ2305** [comment]
> image
> 
> * An admin is currently unable to unlink a facility for a volunteer user. The expected behavior is that an admin should have the ability to both link and unlink facilities for volunteer users. However, volunteer users should be restricted from unlinking their assigned facilities themselves.

@nihal467, Fixed it, but restricted volunteer users from unlinking for himself and other user types. Let me know if any changes are needed.

**Review by Jacobjeevan — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
