### PR TITLE
Add Title Element

### LINKED ISSUE #2177: Relavant Titles
Currently we are not using the Document title in Care. We need to implement some effects that update the title when you load a page. I think an approach like this would work well.

```
useEffect(()=>{
const title = document.title
document.title = "Patient Consultation"
return (() => {
    document.title = title
})
},[])
```

Let's make this a habit for any page that we work on.

 @bodhish opinions?

### PR DESCRIPTION
**Pull request by shrihari689**
## Changes 💪

Instead of adding Page Title (#2177) to all the pages, added it to the Breadcrumbs Element. This is to avoid any breaking if we update in all pages. 

## Screenshot

image

(Titles on the browser will be changed when change the pages)

Resolves #2177 🔨

### CODE REVIEW

**Comment by nihal467** [comment]
@shrihari689 @gigincg test failed

ewkpofewop

it is the patient details form not the sample test history

**Comment by shrihari689** [comment]
@nihal467 Fixed the title 🚀

**Comment by gigincg** [comment]
@nihal467 Can you test again?

**Comment by nihal467** [comment]
test approved

**Pull request merged**
