### PR TITLE
Made User card same in filter users in the facility page

### LINKED ISSUE #4658: User card is different when we filter users in the facility page
**Describe the bug**
User card is different when we filter users in the facility page
**To Reproduce**

1. Go to https://care.coronasafe.in/facility/2bfdbbe6-0516-4269-9d17-860efd705ffb/users

**Expected behavior**
User card is different when we filter users in the facility page it needs to be same

**Screenshots**
## Real user card
image

## Filtered user card
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by patelaryan7751**
## Proposed Changes

- Fixes #4658 ?
Made User card same in filter users in the facility page
image
Made a seperate component named UserCard and reused it in facility users
@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@patelaryan7751 check the merge conflict

**Comment by nihal467** [comment]
@patelaryan7751 https://github.com/coronasafe/care_fe/issues/4566 can you check this issue, we are completely changing the user page for a specific facility

**Comment by nihal467** [comment]
@patelaryan7751 clear the merge conflict @khavinshankar review it

**Comment by nihal467** [comment]
@patelaryan7751 clear the merge conflict

**Comment by patelaryan7751** [comment]
closing this working on a new PR

**Pull request closed without merging**
