### PR TITLE
Uninstall and replaces all Material UI icons with Care Icons

### LINKED ISSUE #5049: Get rid of material-ui/icons
There are only around 15 usages of material-ui/icons across the entire codebase. 

Let's refactor that to use CareIcons

### PR DESCRIPTION
**Pull request by ayushjnv1**
## Proposed Changes

- Fixes #5049 
- Uninstalls `@material-ui/icons`

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by ayushjnv1** [comment]
#5049

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Comment by khavinshankar** [comment]
@ayushjnv1 can you please resolve the merge conflicts

**Comment by rithviknishad** [comment]
@khavinshankar

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
