### PR TITLE
Hide "Asset Type"

### PR DESCRIPTION
**Pull request by shyamprakash123**
### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at be3b8e2</samp>

This pull request removes the asset type feature from the frontend components that deal with assets. The asset type is no longer a relevant attribute for filtering, creating, or managing assets, since the backend API only supports internal assets. The affected components are `AssetFilter`, `AssetCreate`, and `AssetManage`.

## Proposed Changes

- Fixes https://github.com/coronasafe/care_fe/issues/6789

- [x]  Removed "Asset Type" select input from asset create/edit form.

 

- [x] Upon creating an asset, it is always created with asset type as "Internal" (default)

 

- [x] Removed Asset Type label from the asset details page.

 

- [x] Removed Asset Type filter from Advanced Filters also.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at be3b8e2</samp>

*  Remove the asset type filter option from the `AssetFilter` component and the filter logic ([link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96L24-L26), [link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96L59), [link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96L72), [link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-eb665fb95a27de8a5d89f3f2525843abb2e62ce596832617cd03fa5e49bdeb96L137-L148))
*  Remove the asset type input option from the `AssetCreate` component and the asset creation logic ([link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-d7d19aab87f2678510fa29d56b44e2a94098c956b954df68110c117f7f366073L110-R113), [link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-d7d19aab87f2678510fa29d56b44e2a94098c956b954df68110c117f7f366073L202), [link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-d7d19aab87f2678510fa29d56b44e2a94098c956b954df68110c117f7f366073L244-L249), [link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-d7d19aab87f2678510fa29d56b44e2a94098c956b954df68110c117f7f366073L307), [link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-d7d19aab87f2678510fa29d56b44e2a94098c956b954df68110c117f7f366073L332-R322), [link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-d7d19aab87f2678510fa29d56b44e2a94098c956b954df68110c117f7f366073L570-R560))
*  Remove the asset type display from the `AssetManage` component ([link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-d3677127a55934962254fa660ba9b01a59fdb23bee06c9160832527f36c8bf20L368-L372))
*  Hardcode the asset type value to `AssetType.INTERNAL` for creating or editing the assets in the `AssetCreate` component ([link](https://github.com/coronasafe/care_fe/pull/6835/files?diff=unified&w=0#diff-d7d19aab87f2678510fa29d56b44e2a94098c956b954df68110c117f7f366073L332-R322))

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@shyamprakash123 
image

- [ ] modify the cypress test in asset file, when you are hiding the asset type, make necessary change in the file as well

**Comment by shyamprakash123** [comment]
@nihal467 

**Cypress Tests are now fixed.**

Screenshot 2023-12-14 210939
Screenshot 2023-12-14 211001
Screenshot 2023-12-14 211014

**Comment by nihal467** [comment]
@shyamprakash123 fix the failing cypress test, you should be fixing cypress with running care in the local frontend and backend by loading dummy data

**Comment by shyamprakash123** [comment]
@nihal467 I reverted the cypress test variables, can you re-test this?

**Review by rithviknishad — APPROVED** [review]

**Comment by rithviknishad** [comment]
The cypress test still seems to be failing, could you look into it?

**Comment by nihal467** [comment]
@shyamprakash123 fix the cypress issue

**Pull request closed without merging**
