### PR TITLE
Improve resolution images uploaded via camera

### LINKED ISSUE #7154: Improve the camera uploaded patient files quality
**Describe the bug**

When we upload a file using the camera feature to a patient file, the quality drops significantly

**To Reproduce**

1. Go to patient consultation page
2. Click on file upload and select camera
3. upload a captured file and check the image quality

**Expected behavior**

file upload using the camera feature to patient file should retain a good amount of quality

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Omkar76**
## Proposed Changes

- Fixes #7154 
- `forceScreenshotSourceSize` to keep original resolution from source video stream
-  `screenshotQuality` set to 1. (default is 0.92)
-  change mediaconstraint to high resolution. 
- Removed `height` and `width` from <Webcam> as they had no effect. The component height is already limited by  the containing modal.

Reference https://stackoverflow.com/questions/27420581/get-maximum-video-resolution-with-getusermedia
https://www.npmjs.com/package/react-webcam

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [X] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [X] Request for Peer Reviews
- [ ] Completion of QA

# Screenshots

Images uploaded to this patient http://localhost:4000/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/291bf9c3-b016-43a6-84f3-7ea6d860814c/files/

Before
211 x 376
image

After 
480 x 853
image

### CODE REVIEW

**Review by Ashesh3 — APPROVED** [review]

**Review by rithviknishad — COMMENTED** [review]
@Omkar76 the back camera is not working on my phone for this deploy preview specifically. Works in staging.

cc: @Ashesh3

**Comment by Ashesh3** [comment]
> @Omkar76 the back camera is not working on my phone for this deploy preview specifically. Works in staging.
> 
> cc: @Ashesh3

Seems like the component was malfunctioning due to CSP fixes not being merged in the brach. I've updated the branch with develop. 

Could you check once again?

**Comment by rithviknishad** [comment]
@Ashesh3 I'm still getting a white image preview for the back camera. The front camera works.

(Verified in incognito mode too)

**Comment by Ashesh3** [comment]
Oh weird 🤔 . @Omkar76 could you take a look into this issue?

**Comment by Omkar76** [comment]
looking :eyes:

**Comment by Omkar76** [comment]
@rithviknishad it's working fine for me :thinking:. which browser are you using? 
I tested on Brave browser on my android.

**Comment by sainak** [comment]
@rithviknishad its working fine for me as well, try remote debugging to see whats the error.

**Review by rithviknishad — APPROVED** [review]

**Comment by Ashesh3** [comment]
Reverted the change applying to facility cover image as per discussion with Nihal - as it increased image load times without adding any extra usability.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
