### PR TITLE
Removed App.css and index.scss, moved css imports to index.css

### LINKED ISSUE #2602: Tailwind: Get rid of the App.css File
Remove the App.css file in favour of the index.css file. 

Use `@import` for better structuring CSS rules. Refer https://tailwindcss.com/docs/using-with-preprocessors

### LINKED ISSUE #2603: Explore using @import statements for all css imports
Some packages such as pnotify require CSS imports. These are currently being imported within React. Check if they can be imported using `@import` in the `index.css` file

### PR DESCRIPTION
**Pull request by skks1212**
all imports are working properly in `index.css`,
all styles are now in a single file.
I could see that `index.scss` was not being used in the entire project so I went ahead and deleted that too.

closes #2603 
closes #2602

### CODE REVIEW

**Review by developedBySJ — APPROVED** [review]
LGTM

**Review by ishanExtreme — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
powefkowe

@skks1212 @gigincg 
the consultation heading tab is misaligned, but it is okay in the current staging, so when this PR is merged, will it affect the UI

**Comment by shivankacker** [comment]
@nihal467 should work now, merged develop

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
