### PR TITLE
fix: white space on smaller device

### LINKED ISSUE #2577: Additional white space on smaller devices on asset page
URL - https://care.coronasafe.in/assets

image

### PR DESCRIPTION
**Pull request by kunatastic**
fixes #2577 

Consistent white space even on smaller devices

image

### CODE REVIEW

**Comment by nihal467** [comment]
@kunatastic @gigincg the deployment preview is failed

**Review by developedBySJ — APPROVED** [review]

**Comment by rithviknishad** [comment]
@kunatastic deploy preview is failing. merge the latest develop branch.

**Comment by nihal467** [comment]
@kunatastic @gigincg test failed, make the page responsive, asset advance filter button and all are not responsive

**Review by cp-Coder — APPROVED** [review]

**Comment by kunatastic** [comment]
Updated UI: 
image

Previously:
image

**Comment by nihal467** [comment]
test approved

**Pull request merged**
