### PR TITLE
Login

### PR DESCRIPTION
**Pull request by gauravsoti1**
Added material ui custom theme for the project,
Styled login page. 
Add basic table structure for state dashboard.

### CODE REVIEW

**Comment by gauravsoti1** [comment]
Resolved the merge conflicts @tomahawk-pilot

**Review by dauntlessnomad — CHANGES_REQUESTED** [review]
Please make the header and footer into a seperate classes inside common

**Comment by dauntlessnomad** [comment]
hey @gauravsoti1  , we are writing code in typescript so the extention is .tsx   
Please do a pull from develop branch .

**Comment by gauravsoti1** [comment]
@tomahawk-pilot Merged with develop, Removed my redundant header.

**Pull request closed without merging**
