### PR TITLE
fixed: csv files are not in proper format

### PR DESCRIPTION
**Pull request by cp-Coder**
## Proposed Changes

- Downgrade `react-csv` to `v2.1.9`

## Associated Issue

- Fixes https://github.com/coronasafe/care_fe/issues/3852

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug/test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to the issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@cp-Coder 
image
issue still persist

**Comment by gigincg** [comment]
@cp-Coder Can your get this resolved?

**Comment by nihal467** [comment]
@cp-Coder what is the status of the PR

**Comment by aeswibon** [comment]
Demo

https://user-images.githubusercontent.com/77210185/207871630-2f1f1006-30b8-4821-a6ee-c380efbd7df4.mp4

**Comment by nihal467** [comment]
LGTM, @khavinshankar check it carefully

**Comment by khavinshankar** [comment]
checked it in ubuntu -> chrome -> LibreOffice calc, works fine
LGTM

cc: @nihal467

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
