### PR TITLE
Flow rate appears only when high flow nasal cannula chosen

### PR DESCRIPTION
**Pull request by sam9111**
chrome-capture (2)

### CODE REVIEW

**Comment by nihal467** [comment]
test failed, the values showing in the update log history, in the graph under the ventilator tab is different after inputting in the data. So make it uniform everywhere,

**Comment by nihal467** [comment]
@sam9111

**Comment by sam9111** [comment]
> test failed, the values showing in the update log history, in the graph under the ventilator tab is different after inputting in the data. So make it uniform everywhere,

I just checked. It seems to be the same in the graphs as well. Could you upload a video of the problem? @nihal467

**Comment by nihal467** [comment]
1 a

i input data in the flow rate, and the graph is showing input in the oxygen flow rate


2a

when I input data in oxygen flow rate, the data is showing in oxygen rate graph

**Comment by nihal467** [comment]
https://user-images.githubusercontent.com/57055998/130952015-96f15019-3e51-4534-ae41-f5c792be5cc2.mp4

when i update the log , and change the radio button selection from oxygen rate to flow rate and input data. The data's in oxygen rate and flow rate both are been shown in the log update.

**Comment by nihal467** [comment]
@sam9111 there are two errors and I have mentioned both as two separate comments. do check it

**Comment by nihal467** [comment]
test approved

**Review by gigincg — APPROVED** [review]

**Pull request merged**
