### PR TITLE
Updated ABHA popup UI

### LINKED ISSUE #7729: Redesign ABHA related POP-up
**Issue Description**

The ABHA ID and No. are not properly represented in the Abha-related pop-up found on the patient consultation page
below is the existing design

image

below is the expected design

image

### PR DESCRIPTION
**Pull request by shivankacker**
## Proposed Changes

- Fixes #7729
Screenshot 2024-06-05 at 9 21 51 AM

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 
image

increase the QR code size and keep both sides consistent, ( Between the two drawn lines)

**Comment by nihal467** [comment]
@skks1212 make the changes as per the discussion

**Comment by nihal467** [comment]
@skks1212 
image

as per the discussion, it should be using three rows as existing, don't use 4 rows

**Comment by nihal467** [comment]
@skks1212 any update on this PR

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
