### PR TITLE
[FIXED] Enhancement of pain scale value and badge position

### LINKED ISSUE #7791: Enhancement of pain scale value and badge position
**Describe the bug**
Pain scale value and badge is right shifted which could be enhanced for better user experience

**To Reproduce**

1. Go to patient consultation page
2. Create critical care type log update
3. Choose vitals
4. Scroll down to pain scale
5. See error

**Expected behavior**
Pain scale value and badge should be in center in all kind of devices (phone/desktop)

**Screenshots**
In mobile view:
IMG_20240510_174431

In desktop view:
IMG-20240510-WA0000

### PR DESCRIPTION
**Pull request by r-nikhilkumar**
- Fixes #7791
- Changes
for mobile:
image

for desktop:
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
String interpolating classes does not guarantee it would work. Refer: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

See how tailwind detects used classes: https://tailwindcss.com/docs/content-configuration#class-detection-in-depth

Use classNames utility instead

**Comment by r-nikhilkumar** [comment]
@rithviknishad done, now you can finalize it...!

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@r-nikhilkumar 
image

reduce the input box size and keep the things center aligned

**Comment by r-nikhilkumar** [comment]
@rithviknishad @nihal467 done, you can check and test

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
