### PR TITLE
Made add beds page uniform

### LINKED ISSUE #3111: Add uniformity on Add Beds page
https://care.coronasafe.in/facility/f8f05c04-5c97-415c-814d-419ecf692d0e/location/0f28afd4-2e64-40b0-aff4-aac2c99b88b9/beds/add

image

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #3111 
http://localhost:4000/facility/f8f05c04-5c97-415c-814d-419ecf692d0e/location/0f28afd4-2e64-40b0-aff4-aac2c99b88b9/beds/add

image

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

**Review by kunatastic — APPROVED** [review]

**Comment by aeswibon** [comment]
@Pranshu1902 Merge the latest develop branch to fix netlify deploy issue

**Comment by developedBySJ** [comment]
@Pranshu1902 It will be better if you group `name` and `bed type`

image

@nihal467

**Comment by Pranshu1902** [comment]
Updated view:
image

**Comment by naman114** [comment]
@Pranshu1902 This issue has been resolved and merged in PR #2903 

The updated view looks like this 

https://care.coronasafe.in/facility/551f9e09-04a3-4f52-ade2-1db45588741d/location/4b9231cf-805d-4fc3-ab23-77e4d8bfba03/beds/add

image

**Pull request closed without merging**
