### PR TITLE
HCX Plug FE

### PR DESCRIPTION
**Pull request by khavinshankar**
> [!Note]
> Policies are kept in the main repo to support policies being added even when plug is not enabled.

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
image

the Entire UI of pre-auth is broken, can you check it once

**Comment by khavinshankar** [comment]
@nihal467 fixed the styling issues, it was caused because tailwind classes in plugs were not recognized (i.e., any new tailwind class used in the plug will not work)

image

**Comment by nihal467** [comment]
LGtM

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
