### PR TITLE
Fix (Advanced Filters): made all filter sidebars collapse on clearing filters

### LINKED ISSUE #4191: Clearing Advanced Filters For Facilities Collapses the Sidebar
**Describe the bug**
In the `Advanced Filters` for Facilities, the `Clear Filter` button collapses the Sidebar in addition to clearing the filters

**To Reproduce**

1. Go to http://care.coronasafe.in/facility
2. Click on 'Advanced Filters'
3. Click on 'Clear Filter'

**Expected behavior**
The `Clear Filter` button should just clear the filters and not collapse the sidebar

https://user-images.githubusercontent.com/57593654/208047371-b2faeaa1-8171-4f14-ba32-b62a3f1f52e4.mp4

### PR DESCRIPTION
**Pull request by naman114**
## Proposed Changes

- Fixes #4191

https://user-images.githubusercontent.com/57593654/209093771-13302842-ec1e-4b73-ad14-860e0bfd7d83.mp4

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@naman114 once the merge conflict is cleared, mark it for testing

**Comment by naman114** [comment]
@nihal467 the merge conflict has been resolved

**Comment by nihal467** [comment]
@naman114 iam marking it as team discussion required, as after clear filter, the sidebar is not collapsing, and the behaviour doesn't feel good in my view, will be discussion in the call

**Comment by naman114** [comment]
I have made all the `Advanced Filters` sidebars collapse on clearing the filters. The video showing the same is updated in the PR description

@nihal467

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
