### PR TITLE
Don't allow future dates for facility triage

### LINKED ISSUE #4093: Future dates shouldn't be allowed in facility triage date
**Describe the bug**
The user is able to add a future date in the triage for the facility

**To Reproduce**

1. Go to ['link'](https://care.coronasafe.in/facility/072e9364-a108-42e2-a0a5-3e70f9d90e3c/triage)
2. Add a date of the future and enter the remaining details
3. Click "Save Triage"

**Expected behavior**
Only dates of today and before should be allowed

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #4093 
http://localhost:4000/facility/072e9364-a108-42e2-a0a5-3e70f9d90e3c/triage
The form raises an error when submitting the form with an invalid date
image

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — CHANGES_REQUESTED** [review]
@Pranshu1902 
- can you change all the mui components in this form to our custom components
- and also add constraints in the DateInput component to disable future dates (something like maxDate)

**Comment by Pranshu1902** [comment]
@khavinshankar Done!
Disabled future dates
image

Removed MUI buttons
image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — CHANGES_REQUESTED** [review]
@Pranshu1902 also change the date picker too, not only the buttons, we already have custom date pickers

**Comment by nihal467** [comment]
@Pranshu1902 @khavinshankar  is it good for testing

**Comment by Pranshu1902** [comment]
Updated view:
image

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
- [ ] Add max and min props in DateInputV2 to set limits or constraints for date selection

**Pull request merged**
