### PR TITLE
Added Breadcrumbs

### LINKED ISSUE #1911: Breadcrumbs to supplement Soft Back Buttons
Create optional Breadcrumbs along with the PageTitle to supplement the soft back buttons.

The breadcrumbs would be used for hardcoded navigation, and the soft back button would simply be used to go back for people using PWA Versions.

### PR DESCRIPTION
**Pull request by khavinshankar**
Fixes #1911

### CODE REVIEW

**Comment by khavinshankar** [comment]
Added BreadCrumbs
fixes #1911 

UI look like,
image

**Comment by nihal467** [comment]
@khavinshankar @gigincg 
spdofksdo

1. in the first page like facilities, patient, asset, showing the breadcrumbs links won't feel necessary
2. make the links as facilities, from facility and check all the heading and texts of the links 

oidjsv

3. the link start from the facility name only, because home button will anyway take us back to the facilities home page.
4.  increase the colour of the " / ", as it is hard to see it.
5.  in the name of the facilities, external results etc... we can see '.....', try to have the full text displayed, check it

**Comment by khavinshankar** [comment]
To do:
 1. - [x] remove breadcrumbs in initial pages (like `/facility`, `/patients`)
 2. - [x] rename crumbs accordingly (capitalize, remove symbols)
 3. - [ ] remove facility crumb (both facility and home redirects to the same page)
 4. - [x] increase the dividers "/" color
 5. - [x] display full text in crumbs

**Comment by khavinshankar** [comment]
@nihal all requested changes made except for the 3rd one, if we do that it might feel inconsistent at places like 
`🏠 / Facility Name`, it would be good if we had `🏠 / Facilities / Facility Name`, so I left it out.

**Comment by nihal467** [comment]
@khavinshankar @gigincg 
qwidwqodi

can you make this alignment proper

**Comment by nihal467** [comment]
efjwfe

@khavinshankar can you check the alignment of this too

**Comment by khavinshankar** [comment]
- [x] fix the alignment issue with the page title and download button in Sample Management
- [ ] fix the alignment issue in the Patient's Home with assigned Doctor and assigned Volunteer

**Comment by khavinshankar** [comment]
@nihal467 I don't think there is an alignment issue in the Patient's Home with the assigned Doctor and assigned Volunteer
image

_Note: the breadcrumbs are meant to have that left margin too_

**Comment by nihal467** [comment]
@khavinshankar can you make all the  starting letters of all heading like from patient to Patient (Make the first letter capital)

**Comment by khavinshankar** [comment]
- [x] capitalized the first letters of the static crumbs

image

**Comment by nihal467** [comment]
test approved

**Pull request merged**
