### PR TITLE
Fix patient download button

### LINKED ISSUE #3240: Download Live List button enabled without 7 day range
The "DOWNLOAD LIVE LIST" and "DOWNLOAD ALL PATIENTS" buttons need a 7 day period to be selected before functioning. 

"DOWNLOAD ALL PATIENTS" is disabled automatically when a 7 day range is not selected. But the same is not done with Live list button. This causes an error during the download which is not displayed to the user.

Fix: The List list button should be disabled just like with All patients button when a 7 day period is not selected.

image

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #3240 

image

After selecting a 7 day filter:

image

### CODE REVIEW

**Review by cp-Coder — APPROVED** [review]

**Comment by nihal467** [comment]
@Ashesh3 
image

the file is not getting downloaded, test failed

**Comment by Ashesh3** [comment]
@nihal467 It seems there is a backend issue currently causing the download to fail. The downloads are failing on the staging too, even without this PR. Waiting for the backend issue to be fixed.

**Comment by Ashesh3** [comment]
This seems to be fixed from the backend, can test again now.

**Comment by nihal467** [comment]
@Ashesh3, when we use the download live list button and download all patient button, both the excel sheet, generated is the same.

**Comment by Ashesh3** [comment]
@nihal467 It seems like a backend issue having trouble filtering patients. Would it be okay if I create a separate backend  issue to resolve that? This PR just changes UI styling of download button, nothing else. We should be able to test and merge this PR (without worrying about the excel files) and resolve the issue you mentioned separately.

**Comment by nihal467** [comment]
@Ashesh3 create a separate issue and resolve it there

**Comment by Ashesh3** [comment]
> @Ashesh3 create a separate issue and resolve it there

@nihal467 Done here https://github.com/coronasafe/care_fe/pull/3417

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
