### PR TITLE
Remove `_` from headings - fix #1644

### LINKED ISSUE #1644: Remove '_' from heading : Consultation
error

Remove the '_' in the two heading

### PR DESCRIPTION
**Pull request by abhinandanarya06**
image

closes #1644

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Comment by bodhish** [comment]
@nihal467 the buttons are not working.

**Comment by nihal467** [comment]
@abhinandanarya06 test failed, the buttons are not working

**Comment by ghost** [comment]
> @abhinandanarya06 test failed, the buttons are not working

now it should work fine.

**Comment by samholics** [comment]
tested ,verified

" _ " now cleared and also the buttons are working

**Pull request merged**
