### PR TITLE
Fix: Allergies Count in Patient details page

### LINKED ISSUE #9328: Fix allergies count in Patient details page
*Describe the bug*
Currently allergies count in patient card is showing incorrect count.

*To Reproduce*

1. Go to 'any patient details page'
2. Observe allergies count in patient card

*Expected behavior*
It should show count of allergies instead of length

*Screenshots*
Image

*Desktop (please complete the following information):*

*Smartphone (please complete the following information):*

*Additional context*
Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by Rishith25**
## Proposed Changes

- Fixes #9328 
- Fixed Allergies Count

Image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved accuracy of allergy count display by filtering out empty entries.
  
- **Refactor**
	- Enhanced the method of counting allergies in the `PatientHome` component for better data representation.

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
Allergies is a charfield. Not sure if it's right to show the count in the first place. 

For discussion:


- We could either show "Has Allergies" if field has value and show the allergies value directly either as tooltip or in the sections below as a detail.

**Comment by Rishith25** [comment]
Hi, @bodhish and @vinutv , could you please confirm whether to use a count for allergies or "has allergies"? Should the details be displayed in a tooltip on hover, as suggested by @rithviknishad ?

**Comment by bodhish** [comment]
I would be happy to show the count with a darker styling in circle!

**Comment by rithviknishad** [comment]
@bodhish so it is okay to get count by splitting by `,` and getting the length? 

What if the user types: "Allergy 1 and Allergy 2" :)

**Comment by bodhish** [comment]
We will have structured allergy in the coming weeks, so I don't think we should work on this.

**Pull request closed without merging**
