### PR TITLE
Replace font-awesome icons by CareIcon component

### LINKED ISSUE #7080: Migration of font-awesome icons to `CareIcon`
Currently, we are using both Font-awesome and CareIcons for icons in care. We need to phase out existing usages of font awesome icons.

Existing usages (143 usages) of font-awesome icons can be found by searching for `fa-solid|fas fa-` with regex search enabled.
image

cc: @sainak

### PR DESCRIPTION
**Pull request by Omkar76**
## Proposed Changes

- Fixes #7080 
- If direct alternative is not available in CareIcon used other icons based on context

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — COMMENTED** [review]
LGTM, but do uninstall fontawesome related packages and remove related configurations

**Comment by Omkar76** [comment]
@rithviknishad found some more icons by searching `fa-`.  these were not matched by that regex earlier. I've replaced those in this commit. Also `npm uninstall`ed fontawesome and removed from `index.css`

**Comment by rithviknishad** [comment]
> @rithviknishad found some more icons by searching `fa-`. these were not matched by that regex earlier. I've replaced those in this commit. Also `npm uninstall`ed fontawesome and removed from `index.css`

Awesome 🚀

**Review by rithviknishad — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Comment by nihal467** [comment]
@Omkar76 can you clear the merge conflict

**Review by rithviknishad — COMMENTED** [review]
@Omkar76 we generally apply `text-2xl` to all CareIcon's classname. But in the migrated one's that classname is not present

**Comment by nihal467** [comment]
image

- [ ] the cross button is smaller compared to the existing staging, keep it as consist on size and boldness

image

- [ ] the asset import all the icons are really small, do check its size

@Omkar76 seems like all the icon sizes are small comparatively, so go through all file change and make sure the icons are in proper size before you mark it again for review and testing

CC: @rithviknishad @Ashesh3

**Comment by Omkar76** [comment]
@nihal467, fixed the sizing issue and resolved conflicts. 
BTW The test case failure is unrelated to my change. Same test is failing on master.

**Comment by nihal467** [comment]
@Omkar76 can you clear the merge conflict

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
