### PR TITLE
Improve File Preview

### LINKED ISSUE #7240: Enhance File Preview Experience for Non-Embeddable Documents and PDF Consistency
Our application's file preview feature faces challenges with non-embeddable document formats like `.xlsx` and `.docx`, leading to blank white pages, and provides an inconsistent preview experience for PDF files, which open in separate tabs instead of an expected overlay. To enhance user experience and address these issues, we propose automatically opening links for these non-previewable documents in new tabs. This solution aims to provide a consistent and straightforward way for users to access document contents directly, eliminating confusion and improving overall accessibility and usability of our application.

### PR DESCRIPTION
**Pull request by Ashesh3**
This pull request adds a new component called PDFViewer, which allows for rendering and viewing PDF files in the application. The component uses the react-pdf library to handle PDF rendering and provides options for loading and navigating through pages.

image
image
image

Fixes #7240

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by UdaySagar-Git** [comment]
Hey @Ashesh3 ,

Does a file preview for CSV and XLSX files already exist? Or is that open for work? I'm currently working on a similar issue, and I would like to implement a file preview for CSV and XLSX files. I just wanted to confirm before starting the work.

**Comment by Ashesh3** [comment]
> Hey @Ashesh3 ,
> 
> Does a file preview for CSV and XLSX files already exist? Or is that open for work? I'm currently working on a similar issue, and I would like to implement a file preview for CSV and XLSX files. I just wanted to confirm before starting the work.

Currently we do not have file preview for CSV and XLSX, you can work on it if you want but remember that we cannot send our document to a third party service to get the render, i.e Google Doc Embed, Office365 embeds won't work for our case, if you can render csv and xlsx files without iframe'ing these third party sites, then sure, take it up!

**Comment by UdaySagar-Git** [comment]
> > Hey @Ashesh3 ,
> > Does a file preview for CSV and XLSX files already exist? Or is that open for work? I'm currently working on a similar issue, and I would like to implement a file preview for CSV and XLSX files. I just wanted to confirm before starting the work.
> 
> Currently we do not have file preview for CSV and XLSX, you can work on it if you want but remember that we cannot send our document to a third party service to get the render, i.e Google Doc Embed, Office365 embeds won't work for our case, if you can render csv and xlsx files without iframe'ing these third party sites, then sure, take it up!

I will use the existing packages, read-excel-file and react-csv-reader, for implementation. Is that okay?

**Comment by Ashesh3** [comment]
> > > Hey @Ashesh3 ,
> > > Does a file preview for CSV and XLSX files already exist? Or is that open for work? I'm currently working on a similar issue, and I would like to implement a file preview for CSV and XLSX files. I just wanted to confirm before starting the work.
> > 
> > 
> > Currently we do not have file preview for CSV and XLSX, you can work on it if you want but remember that we cannot send our document to a third party service to get the render, i.e Google Doc Embed, Office365 embeds won't work for our case, if you can render csv and xlsx files without iframe'ing these third party sites, then sure, take it up!
> 
> I will use the existing packages, read-excel-file and react-csv-reader, for implementation. Is that okay?

Yep, that'll be great!

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
