### PR TITLE
Fix facility create page responsiveness and adds `RadioFormField` component

### LINKED ISSUE #4692: Create facility page is not consistent in responsive view
**Describe the bug**

in the responsive view, the create facility page, buttons and text fields are not consistent

**To Reproduce**

https://care.coronasafe.in/facility/create

**Expected behavior**

all the text fields and buttons in the create facility page should be consistent 

**Screenshots**

image

### LINKED ISSUE #4739: Disallow negative values for oxygen capacity and burn rates fields in facility create
**Describe the bug**
We are able to input negative numbers in oxygen capacity and burn rate fields

**To Reproduce**

1. Goto facility create
2. Enter negative numbers in oxygen capacity and burn rate fields

**Expected behavior**
Disallow below 0

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Fixes #4692
- Fixes #4739
- Replace Material Icon with CareIcon for Location Picker
- Adds FormField component: `RadioFormField` 
- Deletes old RadioInputV2 implementation as no longer used
- Adds units to numeric inputs
- Replace V2 components with FormField components

image

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 
image

- [ ] when we are inputting data to the oxygen input field, the 0 is not getting auto removed

image

- [ ] this blank space in mobile doesn't give a good look in my opinion, can you take this up in EOD discussion

**Comment by nihal467** [comment]
LGTM

**Comment by nihal467** [comment]
@rithviknishad @khavinshankar check the cypress issue

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@rithviknishad can you fix these merge conflicts

**Pull request merged**
