### PR TITLE
Refactor cypress action; separate setup and run

### PR DESCRIPTION
**Pull request by khavinshankar**
Refactor cypress action; separate setup and run

### CODE REVIEW

**Review by bodhish — APPROVED** [review]
LGTM

**Comment by bodhish** [comment]
@khavinshankar any idea why the tests are timing out?

**Review by rithviknishad — CHANGES_REQUESTED** [review]
Care backend is not running in the second job

**Comment by bodhish** [comment]
@nihal467 please take this up, this should potentially reduce the time for specs.

**Comment by nihal467** [comment]
@khavinshankar https://github.com/ohcnetwork/care_fe/pull/8738#issuecomment-2399483449 , I have tried a lot of approaches to resolve the issue, seem like there are limitation for GitHub action job processing, feel free to try other alternatives otherwise close the PR

**Comment by nihal467** [comment]
Closing in favour of experimenting with different approach: https://github.com/ohcnetwork/care_fe/pull/8989

**Pull request closed without merging**
