### PR TITLE
Fix (NotificationsList): made the Notifications sidebar responsive

### LINKED ISSUE #4387: Notifications sidebar is not responsive
**Describe the bug**
The Notifications sidebar panel is not responsive

**Screenshots**
image

### PR DESCRIPTION
**Pull request by naman114**
## Proposed Changes

- Fixes #4387
- Made the notification bar open from the right edge of the screen
- Earlier, the `NotificationsList` component was part of the `Sidebar` component. This caused the notification bar to open as part of the Sidebar (smaller width) in mobile view. In this PR, the `NotificationsList` component is moved higher up to the `AppRouter` component along with its state (handling its opening/closing). The state and setState for the the same have been passed down to the `Sidebar` and  `NotificationsList`  components

https://user-images.githubusercontent.com/57593654/210279661-3b675882-37af-4c79-8c9b-3545c12d3e84.mp4

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
The notification bar should be opening from the right edge of the screen.

**Comment by naman114** [comment]
Made the sidebar open from the right edge of the screen. Updated the video in the PR description showing the same

@rithviknishad

**Comment by nihal467** [comment]
LGTM

**Review by rithviknishad — COMMENTED** [review]
I'm not too fond of the notification logic being handled inside the sidebar.
What do you think @khavinshankar?

**Comment by naman114** [comment]
How would you handle it? @rithviknishad

**Comment by rithviknishad** [comment]
@naman114 I would ideally prefer using redux here. This way there's no need to keep on passing the props, and the sidebar handles the logic of the sidebar only.

**Comment by rithviknishad** [comment]
A component: `NotificationItem` (the sidebar list item) could mimick the sidebar item, but could fetch the notification count from redux maybe?

The open/close state may also be handled with redux.

**Comment by naman114** [comment]
@rithviknishad  Here, we just have the `AppRouter` component as the parent with the `Sidebar` and `NotificationList` as the children components.  Since the component hierarchy doesn't extend beyond parent-child, won't Redux be overkill?

Also, even if Redux is used, the Sidebar will have to update the opening/closing state of the Notifications Modal so it's still not really like - the sidebar handling the logic of sidebar only

**Comment by rithviknishad** [comment]
@naman114 Yes I agree using redux is overkill 😅 

Can you checkout this deploy preview? https://deploy-preview-3996--care-net.netlify.app

I and shivank had solved this issue in an earlier PR.

@khavinshankar can you put this on hold, I'll get the slideover implementation refactored out from that PR in a separate PR by today

PR: https://github.com/coronasafe/care_fe/pull/3996

**Comment by rithviknishad** [comment]
@naman114 @khavinshankar fixed in #4487 by using the new `SlideOver` component instead.

**Comment by naman114** [comment]
Should I close this PR? @rithviknishad @khavinshankar

**Pull request closed without merging**
