### PR TITLE
add non-binary gender type to constants

### PR DESCRIPTION
**Pull request by Ritesh-Aggarwal**
This PR fixes an uncaught error which was causing isLoading state to never set to false which caused profile page to get stuck on loading screen ( #2723 ).

### CODE REVIEW

**Review by skks1212 — APPROVED** [review]

**Review by cp-Coder — APPROVED** [review]

**Review by Ashesh3 — APPROVED** [review]

**Comment by nihal467** [comment]
@Ritesh-Aggarwal 


unable to create a non-binary gender user

**Review by cp-Coder — APPROVED** [review]

**Comment by nihal467** [comment]
@Ritesh-Aggarwal test failed



the non-binary is missing from user creation form

**Comment by Ritesh-Aggarwal** [comment]
* https://care.coronasafe.in/user/add
There was a discrepancy in GENDER_CHOICES in frontend and backend. 
Now the frontend has been updated to same choices as it is saved in backend. That is "Other" has been changed to "Non-Binary".

**Comment by nihal467** [comment]
test approved

**Review by rithviknishad — APPROVED** [review]

**Pull request merged**
