### PR TITLE
Auto scroll to error on Asset Creation

### LINKED ISSUE #4044: Auto-scroll to error in asset page on submission
**Describe the bug**

When we submit the asset creation form and if any mandatory field is missed, we need to manually scroll through the form to check, which field is missing

**To Reproduce**

https://care.coronasafe.in/facility/9a96c9d3-1ae6-4a69-ad1e-162d0e318d31/assets/new

**Expected behavior**

When we click the create asset button, if any mandatory field missing, auto-scroll to the missing field

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #4044

WildSpringtail

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 

image

not working is breaking in your PR

**Comment by Ashesh3** [comment]
> @Ashesh3
> 
> image
> 
> not working is breaking in your PR

It seems to work fine for me. Could you let me know the steps to reproduce the error? And can you also confirm that this issue is not there on staging?

image

**Comment by nihal467** [comment]
@Ashesh3 
Untitled

in your PR, the not working button is written in two rows, but in current staging ,the not working button is written in single row.

**Comment by Ashesh3** [comment]
> @Ashesh3 Untitled
> 
> in your PR, the not working button is written in two rows, but in current staging ,the not working button is written in single row.

Fixed.

image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
