### PR TITLE
convert to treatment summary link

### PR DESCRIPTION
**Pull request by sam9111**
Treatment Summary page is now at route  "/facility/:facilityId/patient/:patientId/consultation/:consultationId/treatment-summary"

### CODE REVIEW

**Comment by nihal467** [comment]
test approved

**Comment by gigincg** [comment]
@sam9111 Can you also wire the Treatment Summary link in /teleicu/facility/facilityId/patient/patientId Page

**Comment by sam9111** [comment]
screenshare

**Comment by nihal467** [comment]
okergre

@sam9111 @gigincg it is not reflecting the date of positive in the treatment summary

**Comment by sam9111** [comment]
> okergre
> 
> @sam9111 @gigincg it is not reflecting the date of positive in the treatment summary

which patient is this for?

**Comment by nihal467** [comment]
test approved

**Pull request merged**
