### PR TITLE
Fix same-day discharge date selection in DateInputV2 component

### LINKED ISSUE #9011: Date and Time component restricts selecting same-day discharge date for patients due to non-proper future date validation.
**Describe the bug**

- [ ] When discharging a patient on the same day as their admission, the discharge date selector does not allow selecting the admission date in the patient discharge pop-up.

**To Reproduce**

1. Go to the patient tab
2. Select any active patient to open their dashboard.
3. Click on Manage Patient and choose Edit Consultation.
4. Set the patient admission date to today’s date.
5. Submit the form to return to the patient dashboard.
6. Click on Manage Patient again and select Discharge from Care.
7. See error

**Expected behavior**

- [ ] The date and time component should allow selecting any date and time from the admission date up to the current date and time, supporting same-day discharges.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by JavidSumra**
## Proposed Changes

- Fixes #9011
- Modified `DateInputV2.tsx` component to allow selection of same-day discharge date.
- `isDateWithinConstraints` function checks if the selected date is the same as the admission date and falls within the allowed constraints.
- Improved date validation logic to support discharges on the same day as admission.

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test the new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews.
- [ ] Completion of QA.

## Summary by CodeRabbit

- **New Features**
	- Enhanced date selection logic to allow selecting a date that matches both minimum and maximum constraints when they are the same.

### CODE REVIEW

**Comment by nihal467** [comment]
LGTM @rithviknishad can you review the code

**Review by rithviknishad — APPROVED** [review]
LGTM; @shivankacker could you review this

**Review by shivankacker — APPROVED** [review]

**Comment by JavidSumra** [comment]
Hey @nihal467 can you please assign 2 story points for this.

**Comment by JavidSumra** [comment]
Hey @nihal467 can you please assign 2 story points for this?
cc @rithviknishad

**Pull request merged**
