### PR TITLE
Add all WHO approved vaccines

### LINKED ISSUE #1574: Add Vaccine Name List in Patient Details
Screenshot 2021-07-19 024703

Add the name of vaccine approved by WHO in the droplist

### PR DESCRIPTION
**Pull request by shaileshaanand**
This PR adds the following vaccines to Patient Creation Page:

 - Sputnik V
 - Moderna
 - Pfizer
 - Janssen (Johnson & Johnson)
 - Sinovac
 
Screenshot_20210729_200123

Note: Needs https://github.com/coronasafe/care/pull/602 to be merged in the backend to work.

Closes #1574

### CODE REVIEW

**Comment by nihal467** [comment]
@bodhish @shaileshaanand shall we keep an option called other, in case any other vaccine is used by the patient, for example, Sinopharm(used in Malaysia),

**Comment by shaileshaanand** [comment]
> @bodhish @shaileshaanand shall we keep an option called other, in case any other vaccine is used by the patient, for example, Sinopharm(used in Malaysia),

@vigneshhari

**Comment by shaileshaanand** [comment]
https://github.com/coronasafe/care/pull/602 has been merged we can now test this branch

**Comment by nihal467** [comment]
test approved

**Pull request merged**
