### PR TITLE
Rearrange tabs in patient dashboard

### LINKED ISSUE #7288: re-arrange tabs in patient dashboard
**Is your feature request related to a problem? Please describe.**
The patient dashboard (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e)  has multiple tabs into which clinical data is arranged. These tabs can be named and arranged better.

**Describe the solution you'd like**

- [ ] Rename "Summary" to "Vitals"
- [ ] Rename "Update" to "Overview"
- [ ] Rename "Neurological monitoring" to "Neuro"
- [ ] Rename "Respiratory Support" to "Ventilation"
- [ ] Rearrange it as
1. Overview
2. Feed
3. Vitals
4. ABG
5. Medicines
6. files
7. Investigations
8. Neuro
9. Ventilation
10. Nutrition
11. Pressure sore
12. Nursing
13. Dialysis

**Describe alternatives you've considered**

**Additional context**

**Used** 
Update
summary
feed
medicine
file
Investigation
Nursing care
Resp Support

### PR DESCRIPTION
**Pull request by AnkurPrabhu**
## Proposed Changes

- Fixes #7288 
- Renamed tabs as mentioned in the issue 
-  Re-arranged tabs in patient dashboard as mentioned in the issue  
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by Ashesh3 — APPROVED** [review]

**Comment by AnkurPrabhu** [comment]
@rithviknishad are these test fails due to my change ?

**Comment by rithviknishad** [comment]
Nope @AnkurPrabhu 

cc: @nihal467

**Review by rithviknishad — COMMENTED** [review]
Correct me if I'm wrong, are the `id` attribute used anywhere?

**Comment by AnkurPrabhu** [comment]
> Correct me if I'm wrong, are the `id` attribute used anywhere?

Nope was not able to find

**Comment by rithviknishad** [comment]
> > Correct me if I'm wrong, are the `id` attribute used anywhere?
> 
> Nope was not able to find

Let's drop the id too then 😄

**Comment by AnkurPrabhu** [comment]
in ConsultationDetails/index.tsx:423 CONSULTATION_TABS is being mapped there we might need ids ?

**Comment by rithviknishad** [comment]
Why is `id` required there? What purpose/requirement does it satisfy?

**Comment by AnkurPrabhu** [comment]
> Why is `id` required there? What purpose/requirement does it satisfy?

as in  as far as i know its good to have ids while mapping it in the front end also CONSULTATION_TABS is of type Array<OptionsType>  so id is a compulsory field so what do you think should we remove it ? thoughts @rithviknishad ?

**Comment by rithviknishad** [comment]
> as in as far as i know its good to have ids while mapping it in the front end also CONSULTATION_TABS is of type Array so id is a compulsory field so what do you think should we remove it ? thoughts @rithviknishad ?

It doesn't serve any purpose. It's purely a front-end and thing and has nothing to do with backend. Let's drop ID, it's also not being referenced anywhere else. Also you can drop the type `Array<OptionsType>` for CONSULTATION_TABS and simply do `as const` which should take care of the type safety.

**Comment by AnkurPrabhu** [comment]
> > as in as far as i know its good to have ids while mapping it in the front end also CONSULTATION_TABS is of type Array so id is a compulsory field so what do you think should we remove it ? thoughts @rithviknishad ?
> 
> It doesn't serve any purpose. It's purely a front-end and thing and has nothing to do with backend. Let's drop ID, it's also not being referenced anywhere else. Also you can drop the type `Array<OptionsType>` for CONSULTATION_TABS and simply do `as const` which should take care of the type safety.

changes are done ptal

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
