### PR TITLE
Added Add Bed Capacity and Exit button

### LINKED ISSUE #3053: Add a save and exit button on Add Bed Capacity page
https://care.coronasafe.in/facility/05fcf441-48b2-4d90-9389-f9ab9af107d5/bed

image

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #3053 
https://care.coronasafe.in/facility/05fcf441-48b2-4d90-9389-f9ab9af107d5/bed

image

### CODE REVIEW

**Review by GokulramGHV — COMMENTED** [review]
@Pranshu1902 The field validation errors are not shown when the 'Save bed capacity' button is clicked. 

Screencast-from-08-07-22-03_10_04-PM-IST

**Comment by Pranshu1902** [comment]
> @Pranshu1902 The field validation errors are not shown when the 'Save bed capacity' button is clicked.
> 
> Screencast-from-08-07-22-03_10_04-PM-IST [ ](https://user-images.githubusercontent.com/40627011/177964919-69315c78-c03d-4db1-9536-68aac73697c3.gif) Screencast-from-08-07-22-03_10_04-PM-IST [ ](https://user-images.githubusercontent.com/40627011/177964919-69315c78-c03d-4db1-9536-68aac73697c3.gif)

resolved

**Review by GokulramGHV — APPROVED** [review]

**Review by skks1212 — APPROVED** [review]

**Review by cp-Coder — APPROVED** [review]

**Comment by nihal467** [comment]
test approved

**Comment by khavinshankar** [comment]
@Pranshu1902 please do remove the button in the update form
image

**Comment by Pranshu1902** [comment]
> @Pranshu1902 please do remove the button in the update form image

done

**Comment by nihal467** [comment]
@Pranshu1902 make the page responsive

**Comment by Pranshu1902** [comment]
@nihal467 
Mobile view:
image

**Comment by nihal467** [comment]
image

@Pranshu1902 make the button full, in responsivity, so that they are aligned to the fields such as currently occupied

**Comment by Pranshu1902** [comment]
@nihal467 
Updated view:
image

**Comment by nihal467** [comment]
test approved

**Pull request merged**
