### PR TITLE
Fix pagination

### LINKED ISSUE #2661: Assets: pagination buttons are disfunctional on intital page load
The issue is common in all pages with same component
image

### LINKED ISSUE #2700: Asset View: Next page arrow
**Describe the bug**
The arrow to navigate to next page (>) or last page (>>>) at the bottom of the view asset page always takes user to 1st page of asset list.

New issue experienced after latest release

**To Reproduce**

1. Go to Facility
2. Click on View Asset
3. Scroll down to end of the page where you have the page numbers and arrows to take you to previous/next page
4. when you click the arrows, the user is taken to the first page of asset list
Screenshot 2022-06-13 at 4 26 59 PM

### PR DESCRIPTION
**Pull request by skks1212**
A previous PR resulted in broken pagination, fixed.
closes #2700 
closes #2661

### CODE REVIEW

**Review by arpancodes — CHANGES_REQUESTED** [review]
These changes won't work for lines 130 and 136. These lines may not be relevant either as right now we are showing next/prev buttons in smaller screens, in that case, we might need to clean up.

Do look into it.

**Comment by rithviknishad** [comment]
@skks1212 can u merge the latest develop again? the one you've is one commit behind the required one and that has a typo in the build command.
image

**Comment by shivankacker** [comment]
@rithviknishad 👍

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
