### PR TITLE
Sidebar: reverts current tab detection logic to the logic before redesign

### LINKED ISSUE #3938: Two tab are been shown selected in sidebar
**Describe the bug**

When we select the patient button from the facility page, it is been redirected to the patient tab, during this, the sidebar is showing two tabs are been selected

**To Reproduce**

1. Go to Facility tab https://care.coronasafe.in/facility
2. Click on patient button in the facility card
4. See error in the side bar

**Expected behavior**

it should only be showing the patient tab as selected

**Screenshots**

image

### PR DESCRIPTION
**Pull request by rithviknishad**
## Proposed Changes

- Resolves #3938 
- detects tab selected with path starts with instead of includes.

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad 
image

https://deploy-preview-3941--care-net.netlify.app/facility/a658232e-254e-4fc1-88ac-3cde14f5da49/patients

the patient tab should be selected than the facility tab

**Comment by rithviknishad** [comment]
@nihal467 i've fixed it :)

Reverted to the original logic which was present before the redesigned sidebar. Example preview deploy that has old sidebar: https://deploy-preview-3933--care-net.netlify.app

image

However, with the old original logic there seems to be a situation where in patient's page it is selected as Facility.
image

**Comment by nihal467** [comment]
@rithviknishad is there a way to solve it !

**Comment by rithviknishad** [comment]
@nihal467 as of now, no, lets discuss in EOD. the current logic is the same logic which was there before the redesign

**Comment by nihal467** [comment]
@rithviknishad iam mark it as team discussion required, as we are going to discuss it in EOD

**Comment by nihal467** [comment]
LGTM, conditionally approving it

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
