### PR TITLE
Redundant API calls in Vitals tab

### LINKED ISSUE #8861: Redudant API Requests being made in the Vitals Tab
The /analyse API is being called multiple times in the Vitals tab of the Patient Dashboard. This needs to be optimised to only 1 Call. 

This is likely an issue with improper dependencies in useEffect hooks.

Image

### PR DESCRIPTION
**Pull request by Jacobjeevan**
## Proposed Changes

- Fixes #8861
- Fetch pain data along with rest of the graph data and pass it as a prop to PainDiagrams

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by gigincg** [comment]
@Jacobjeevan It's been partially fixed, but when you open the tab and refresh the page, there's still a redundant request going through.

image


https://deploy-preview-8864--care-ohc.netlify.app/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/summary

**Comment by Jacobjeevan** [comment]
> @Jacobjeevan It's been partially fixed, but when you open the tab and refresh the page, there's still a redundant request going through.
> 
> image
> 
> https://deploy-preview-8864--care-ohc.netlify.app/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/summary

It was a top-level re-render (caused by patientData), added it to the other checks we have. This should take care of extra calls in other tabs as well 👍

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Comment by gigincg** [comment]
@Jacobjeevan Can you clear the conflicts

**Pull request merged**
