### PR TITLE
Added filter for working/non-working assets

### PR DESCRIPTION
**Pull request by siddnikh**
Solves https://github.com/coronasafe/care_fe/issues/2055

### CODE REVIEW

**Review by Marmik2003 — COMMENTED** [review]
aren't we using yarn?

**Comment by nihal467** [comment]
@siddnikh @gigincg test failed, after applying the filter as working, not working asset also coming in the asset

**Comment by siddnikh** [comment]
@nihal467 the backend pull request needs to be merged, first. Here's the PR: https://github.com/coronasafe/care/pull/821

**Comment by siddnikh** [comment]
@nihal467 backend's been done, this is ready for review!

**Comment by nihal467** [comment]
@siddnikh 


check the error and the merge conflict

**Comment by nihal467** [comment]
@siddnikh what is the PR status

**Pull request closed without merging**
