### PR TITLE
Fixed issue  Pain Scale (0-10) #7378

### LINKED ISSUE #7378: Pain Scale (0-10)
**Is your feature request related to a problem? Please describe.**
https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/cb44a173-6fe2-452f-b2d1-6c6e2695411e/daily_rounds/8e4d0791-30d4-4e5d-8ca4-f6e27abb6418/update

Currently the pain scale in CARE is from 0-5.

Change it to 0-10 to allow user to input a more nuanced measure of pain experienced by the patient.

### PR DESCRIPTION
**Pull request by leftover19**
## Proposed Changes

- Fixes #7378
- Change 1 CriticalCare__PainInputModal.res file

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA
[solution.mp4](https://github.com/coronasafe/care_fe/assets/113136731/17b067b3-d45b-4f6f-a25e-4d469c594e4f)

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
https://github.com/coronasafe/care_fe?tab=readme-ov-file#contributing-to-care

**Comment by leftover19** [comment]
> https://github.com/coronasafe/care_fe?tab=readme-ov-file#contributing-to-care

Test failing for this. 
image

**Comment by rithviknishad** [comment]
Are you sure you've connected your local FE to your local backend?

**Comment by shivankacker** [comment]
Closing in favor of https://github.com/coronasafe/care_fe/pull/7380

**Pull request closed without merging**
