### PR TITLE
Modified infusions and feed sections

### PR DESCRIPTION
**Pull request by sam9111**
Screenshot 2022-04-18 at 6 30 26 PM

Added provision for adding concentration and its unit under Infusions and calories under Feed.

Getting validation error as below

Screenshot 2022-04-18 at 6 33 32 PM

### CODE REVIEW

**Comment by sam9111** [comment]
I have disabled eslint for rescript files for now to make the commit

**Comment by sam9111** [comment]
https://github.com/coronasafe/care/blob/master/care/facility/models/json_schema/daily_round.py this is where I have added the fields to the schema

**Comment by gigincg** [comment]
@aparnacoronasafe Can you check with Dr. Athul and comment if this is how this should work ideally?

**Comment by nihal467** [comment]
@aparnacoronasafe @gigincg @sam9111 what is the update on this PR

**Comment by athulmanuel** [comment]
Hi guys. Didn't get the gist of the query. Is it regarding the dilution rate? 

Regarding giving a medicine diluted in a solvent. Usual injection medicines comes as vial (small glass bottle) or ampule ( small glass pellet). It will be of higher concentrations. At time we give it direct and others instances as diluted. 
The calculation is 
In a vial or a ampule contains __ ml of X Medicne which has the strength of __ mg 
Eg: 1 ampule of Morphine has 1 ml which has a strength of 10 mg 

This __ ml of X Medicne is diluted in __ ml of solvent ( NS/ RL/ Sterile water/ etc.). This will be give as __ ml bolus(single dose) or as infusion @__ ml/hr

**Pull request closed without merging**
