### PR TITLE
Milestone 1.1: Add test to edit and delete and an already created asset.

### LINKED ISSUE #5835: Add cypress test for assets.cy.ts
## Tasks

- [x] Test creating a new asset.
- [x] Update the newly created asset.
- [ ] Configure the newly created asset.
- [ ] Import a new asset.
- [x] Delete an already created asset.

### PR DESCRIPTION
**Pull request by ShivamJhaa**
### <samp>🤖 Generated by Copilot at a33b443</samp>

Added `cypress` tests and UI functionality for editing and deleting an asset. Refactored the login logic to use a page object class. Added `data-testid` attributes to some elements for testing purposes.

## Proposed Changes

- Fixes #5835 part of #5491
- Change 1
- Change 2
- More?

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [x] Completion of QA

### <samp>🤖 Generated by Copilot at a33b443</samp>

*  Add `LoginPage` class to `cypress/pageobject/Login/LoginPage.ts` to provide methods for logging in as different users using `cy.loginByApi` command ([link](https://github.com/coronasafe/care_fe/pull/5841/files?diff=unified&w=0#diff-7c047c6367929f4372b8ef6264c7f7a4ea61848f7ee210d625a0b108dffa3f12R1-R12))
*  Refactor `before` hook in `cypress/e2e/assets_spec/assets_manage.cy.ts` to use `loginPage.loginAsDistrictAdmin` method instead of directly calling `cy.loginByApi` with district admin credentials ([link](https://github.com/coronasafe/care_fe/pull/5841/files?diff=unified&w=0#diff-db4292fd03626d0a4e5a0e899dbceffb54fab4da3fd02e455598e6627248e746L4-R13))
*  Add `openCreatedAsset`, `editAssetDetails`, `clickUpdateAsset`, and `deleteAsset` methods to `AssetPage` class in `cypress/pageobject/Asset/AssetCreation.ts` to provide functionality for editing and deleting an asset from the UI ([link](https://github.com/coronasafe/care_fe/pull/5841/files?diff=unified&w=0#diff-af0a7140a23fb3b1c3379fe2880ce31bab589501929f22c83d2b253753971707R83-R122))
*  Add two new test cases to `cypress/e2e/assets_spec/assets_manage.cy.ts` to verify the functionality of editing and deleting an asset from the UI using the new methods from `AssetPage` class ([link](https://github.com/coronasafe/care_fe/pull/5841/files?diff=unified&w=0#diff-db4292fd03626d0a4e5a0e899dbceffb54fab4da3fd02e455598e6627248e746L52-R80))
*  Add `Notification.Success` method to `AssetManage` component in `src/Components/Assets/AssetManage.tsx` to display a success message when an asset is deleted ([link](https://github.com/coronasafe/care_fe/pull/5841/files?diff=unified&w=0#diff-d3677127a55934962254fa660ba9b01a59fdb23bee06c9160832527f36c8bf20R218-R220))
*  Add `data-testid` attributes to `Button` components with `Edit` and `Delete` texts in `AssetManage` component in `src/Components/Assets/AssetManage.tsx` to provide unique identifiers for the edit and delete buttons that can be used by `cy.get` command in the `cypress` tests ([link](https://github.com/coronasafe/care_fe/pull/5841/files?diff=unified&w=0#diff-d3677127a55934962254fa660ba9b01a59fdb23bee06c9160832527f36c8bf20R331), [link](https://github.com/coronasafe/care_fe/pull/5841/files?diff=unified&w=0#diff-d3677127a55934962254fa660ba9b01a59fdb23bee06c9160832527f36c8bf20R356))
*  Add `data-testid` attribute to `div` element that wraps `AssetCard` component in `AssetsList` component in `src/Components/Assets/AssetsList.tsx` to provide a unique identifier for the list of created assets that can be used by `cy.get` command in the `cypress` tests ([link](https://github.com/coronasafe/care_fe/pull/5841/files?diff=unified&w=0#diff-d61b507f07891c695d44e81effbf8f1da3a8667b0379dcfbd98c5761aa124f49R247))

### CODE REVIEW

**Comment by ShivamJhaa** [comment]
@nihal467 Please review the PR, thanks!

**Comment by nihal467** [comment]
@ShivamJhaa 

- As per our call, we discussed to verify mandatory field error message, so initially click on the submit button and verify all mandatory field are having error message reflected to the existing field
- you only created single asset using create asset button, missed out the functionality check of create and add more button, include that in the test and add multiple asset through it
-  verify the asset is created successfully in the asset tab, by searching with it name ( Only check during single asset creation time )

**Comment by ShivamJhaa** [comment]
> @ShivamJhaa
> 
> * As per our call, we discussed to verify mandatory field error message, so initially click on the submit button and verify all mandatory field are having error message reflected to the existing field
> * you only created single asset using create asset button, missed out the functionality check of create and add more button, include that in the test and add multiple asset through it
> * verify the asset is created successfully in the asset tab, by searching with it name ( Only check during single asset creation time )

* Added error message verification test
* Added test for the functionality of create and add more and also added check to verify whether the asset is present or not

Please take a look

**Comment by nihal467** [comment]
@ShivamJhaa the PR looks good to me, what is the status on the remaining import and configuration of assets related to the issue you linked?

@khavinshankar merge this PR and the issue is only partially completed so don't close it

**Review by nihal467 — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
