### PR TITLE
Made filter buttons in the facility page consistent with the others

### PR DESCRIPTION
**Pull request by siva-balan**
## Proposed Changes
Before
image

After
image

- Made filter buttons in the facility page consistent with the other pages like patients and assets.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@siva-balan 
Untitled

- [ ] the heading like Filter By and State are missing in the PR.
- [ ] when we use the clear filter button for removing applied filters in the facility page, it is been getting redirected to patient page.

Once you clear the following bugs, changed the label to " need testing " .

**Comment by siva-balan** [comment]
Changes are done @nihal467

**Comment by rithviknishad** [comment]
@siva-balan https://github.com/coronasafe/care_fe#%EF%B8%8F-make-use-labels-to-update-the-prissue-status

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by gigincg** [comment]
@siva-balan Thank you for the contribution! Welcome to the community!

**Comment by siva-balan** [comment]
Thank you @gigincg

**Pull request merged**
