### PR TITLE
Add Last vaccinated date to Patient form

### LINKED ISSUE #1297: Date of vaccination
Add a field to the patient basic information form, to capture the date of the last dose of vaccination.

This date may be very useful to study infections post vaccination.

There must also be a filter in the advanced filter in patient list to filter by date of vaccination. Once the field on vaccination is added, Please raise this as another feature request.

### PR DESCRIPTION
**Pull request by shaileshaanand**
closes #1297

This PR Adds a last vaccination date field to the Patient Registration / Edit form.

Screenshot_20210606_112943
 
Screenshot_20210610_113938

### CODE REVIEW

**Comment by shaileshaanand** [comment]
@bodhish I have fixed the issue and created a new PR
@amruthavijay88 Please test #1348

**Comment by nihal467** [comment]
@shaileshaanand test failed, When we create or update a patient and add the "last date of vaccination", an alert says that it has been saved.But when you check the patient's details later, this information cannot be seen

**Comment by shaileshaanand** [comment]
> @shaileshaanand test failed, When we create or update a patient and add the "last date of vaccination", an alert says that it has been saved.But when you check the patient's details later, this information cannot be seen

Is the backend merged for this ? https://github.com/coronasafe/care/pull/589

**Comment by aparnacoronasafe** [comment]
Tested. The information captured is not visible on the patient dashboard.

Screenshot 2021-06-09 at 12 38 12 PM

**Comment by amruthavijay88** [comment]
Tested.
@shaileshaanand - where is the vaccination date?

image

**Comment by shaileshaanand** [comment]
> Tested.
> @shaileshaanand - where is the vaccination date?
> 
> image

I can see the field, could you tell me the Patient name for which it isn't visible?

**Comment by shaileshaanand** [comment]
> Tested. The information captured is not visible on the patient dashboard.
> 

Added now.
Screenshot_20210610_113938

**Comment by nihal467** [comment]
test approved

**Review by bodhish — APPROVED** [review]

**Pull request merged**
