### PR TITLE
Redesigned count block

### LINKED ISSUE #4785: Total Patient card is not consistent
**Describe the bug**

When we are swapping between tabs such as asset, facilities, etc..., the card showing the total count in the top left side, is consistent for all the pages except the patient page

**To Reproduce**

1. go to: https://care.coronasafe.in/facility
2. select each tab randomly
3. see the error in consistency in the patient tab

**Expected behavior**

Redesign the patient tab as per the Figma design

**Screenshots**

image

### PR DESCRIPTION
**Pull request by skks1212**
## Proposed Changes

- Fixes #4785 
- Added an icon
- Updated overall design
- Made the design consistent

After:
image

Before:
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@skks1212 
image


image

all the components are having rectangle curved padding, which gives a uniform feel, having data, is shown without padding on a whole page, which feels like losing consistency. Marking it for discussion

**Comment by nihal467** [comment]
@skks1212 add the padding to the whole page

**Comment by nihal467** [comment]
@skks1212 

image

- [ ] remove excess white padding in the patient tab
- [ ] merge the latest development branch

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
