### PR TITLE
Enhanced UI of patients page

### LINKED ISSUE #2805: Ui enhancement of Patients Page
# Bugs 

## Content overlapping on patient card in mobile devices
image

## Improving bed icon in patient card and making it responsive in mobile devices
image

### LINKED ISSUE #2824: Patient page is unresponsive
4-a

the patient page is not responsive, and it is tested in the iPad dimension

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #2805 
Fixes #2824 

# Bugs Fixed 

## Enhanced Bed UI for Individual patients
image
## Made the page responsive on mobile devices
https://user-images.githubusercontent.com/59426397/175344681-5eaa6bb6-d7dd-46c2-a72e-127937d5e4f7.mp4

### CODE REVIEW

**Comment by patelaryan7751** [comment]
Deploy Preview Ready https://deploy-preview-2812--care-net.netlify.app/

**Comment by nihal467** [comment]
test approved

**Comment by patelaryan7751** [comment]
Fixes #2824 
# Bugs Fixed

## Made responsive for i-pad air
image

## Made responsive for i-pad mini
image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Review by khavinshankar — APPROVED** [review]

**Comment by patelaryan7751** [comment]
Hey, @khavinshankar I have resolved the merge conflicts.

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
