### PR TITLE
improve: Patient page buttons responsiveness

### LINKED ISSUE #3358: Patient page buttons are not properly responsive
image

note : Make it center aligned

### PR DESCRIPTION
**Pull request by kunatastic**
closes #3358

https://user-images.githubusercontent.com/61267953/183580403-7fe20fb1-54fc-4a4b-9346-44889e009dac.mp4

### CODE REVIEW

**Review by skks1212 — CHANGES_REQUESTED** [review]
There is still a lot of whitespace at 0:20 in the video. Can we keep the desktop view of that area for a longer time?

**Review by Ashesh3 — APPROVED** [review]

**Comment by nihal467** [comment]
@kunatastic is it good for testing, see a comment by @skks1212 here !

**Comment by nihal467** [comment]
@kunatastic any update

**Comment by nihal467** [comment]
@khavinshankar can you merge the latest development

**Comment by khavinshankar** [comment]
outdated, not relevant

**Pull request closed without merging**
