### PR TITLE
Added prettier and cleaned up the project.

### PR DESCRIPTION
**Pull request by smartclash**
This PR adds prettier and forces everyone to run prettier.

- Runs prettier during file save
fix_on_save

- Runs prettier during `git commit`
cleaned_git_commit_hook

### CODE REVIEW

**Comment by bodhish** [comment]
@smartclash can we refactor

**Comment by smartclash** [comment]
@bodhish refactor what? 😅

**Comment by bodhish** [comment]
Merge conflicts

**Comment by smartclash** [comment]
Ah sure. Will do it first thing tomorrow morning 😉 @bodhish

**Comment by smartclash** [comment]
I've fixed all the merge conflict and it's good to go @bodhish

**Pull request merged**
