### PR TITLE
add support for webrtc stream

### PR DESCRIPTION
**Pull request by sainak**
### <samp>🤖 Generated by Copilot at 0afb117</samp>

This pull request adds WebRTC support for media streaming in the `Feed` and `LiveFeed` components, and refactors the existing hooks for media players. It introduces a new hook `useWebRTCPlayer` and a new configuration option `use_webrtc`. It also updates the `useMSEMediaPlayer` and `useHLSPlayer` hooks to have consistent interfaces and functionality.

## Proposed Changes

- adds support for webrtc stream

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at 0afb117</samp>

*  Add `webrtc-adapter` package as a dependency to enable consistent WebRTC API ([link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L100-R101))
*  Add `use_webrtc` configuration option to enable or disable WebRTC streaming ([link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-67644ab310d9ac1e98b6694f279c0dcd973ae26b1fd9ef1658281a2b91194adeR26), [link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-85ddd82d8d8242a8120ad7bf95ed40ce93b4290afb8e17e7c2370bfb2086dd71R72-R75))
*  Add `useWebRTCPlayer` hook to stream media using WebRTC protocol ([link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-d23a167a03ac485e5c6da9b10357fde7a207bca13fa9035ee32ace12a509a158R1-R296))
*  Modify `useMSEplayer` hook to simplify interface and handle stop request ([link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-9c97aeeffdf95a04b24615b5a0842918a82f50040f9e09ca7ec69ceac2ea759bL2-R5), [link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-9c97aeeffdf95a04b24615b5a0842918a82f50040f9e09ca7ec69ceac2ea759bL33-R34), [link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-9c97aeeffdf95a04b24615b5a0842918a82f50040f9e09ca7ec69ceac2ea759bL51-L69), [link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-9c97aeeffdf95a04b24615b5a0842918a82f50040f9e09ca7ec69ceac2ea759bR228-R235), [link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-9c97aeeffdf95a04b24615b5a0842918a82f50040f9e09ca7ec69ceac2ea759bL253-R242))
*  Modify `useHLSPlayer` hook to return an empty `stopStream` function ([link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-b653b060e81c4fbd50cfffcdbf00effecc2019e4e37ddd8b3361121afe30ff38L15-R15))
*  Switch between WebRTC and MSE/HLS players based on `use_webrtc` option and device type in `Feed.tsx` and `LiveFeed.tsx` components ([link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-5720f1345a51b321a7409e05b9acc257c75783e165427270755ecc0626e59cb2R35-R36), [link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-5720f1345a51b321a7409e05b9acc257c75783e165427270755ecc0626e59cb2R65), [link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-5720f1345a51b321a7409e05b9acc257c75783e165427270755ecc0626e59cb2L178-R188), [link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-6352cfe4ad14fd5cf49cc8bca3a81880e50c91515c2c11bdff1b379a587c4983R26-R27), [link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-6352cfe4ad14fd5cf49cc8bca3a81880e50c91515c2c11bdff1b379a587c4983L63-R79), [link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-6352cfe4ad14fd5cf49cc8bca3a81880e50c91515c2c11bdff1b379a587c4983L220-R229))
*  Remove unnecessary `startStream` dependency from `useEffect` hook in `LiveFeed.tsx` component ([link](https://github.com/coronasafe/care_fe/pull/6457/files?diff=unified&w=0#diff-6352cfe4ad14fd5cf49cc8bca3a81880e50c91515c2c11bdff1b379a587c4983L220-R229))

### CODE REVIEW

**Comment by sainak** [comment]
https://deploy-preview-6457--care-egov-staging.netlify.app/facility/9bc6e011-3ab6-4aec-ba89-f4cda407fa13/assets/7fd1ec81-f537-421f-8ec0-1bee1c675748/configure

accessible on Palakkad district

**Comment by nihal467** [comment]
@sainak most of the cypress are failing, can you check it

**Comment by nihal467** [comment]
comment from @sainak : this pr is blocked, we need to asses the benefits of webrtc over existing services

**Comment by bodhish** [comment]
Closing this PR due to lack of recent progress.

@sainak ping me if you are planing to work on this.

**Pull request closed without merging**
