### PR TITLE
add scroll buttons instead of scrollbar

### PR DESCRIPTION
**Pull request by Ritesh-Aggarwal**
revamp patient consultation page
#2874

### CODE REVIEW

**Comment by Ritesh-Aggarwal** [comment]
Added scroll buttons instead of scrollbar. Buttons are hidden on mobile devices since they have touch and scroll feature
image

**Comment by samholics** [comment]
@Ritesh-Aggarwal 
tested,failed
Scroll buttons are working fine when logged in via Admin user.
But not working when logged in as Staff user. only Right side button present but its not consistent. It makes unable to scroll back to first section (updates,summary)

**Comment by nihal467** [comment]
@Ritesh-Aggarwal 

the scroll button is covering the heading and it doesn't look good with UI too, is there a better way to avoid the scroller

**Comment by nihal467** [comment]
@Ritesh-Aggarwal what is the status

**Comment by Ritesh-Aggarwal** [comment]
I didn't work on this PR. Didn't get any other ideas to better the ui

**Comment by arpancodes** [comment]
I am working on it separately. Closing this.
cc @gigincg

**Pull request closed without merging**
