### PR TITLE
 Show only those facilties that aren't linked to user

### LINKED ISSUE #6190: Don't show already Linked Facilities on Link New Facility on User page
**Describe the bug**
When a user tries to link a facility to the user, the already linked facilities are also shown.

**To Reproduce**

1. Go to https://care.coronasafe.in/users
2. Click on `Linked Facility`
3. In the form, add a facility that is already linked and click `Add`

**Expected behavior**
Only those facilities that are not linked to the user should be displayed.

**Screenshots**
image
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Pranshu1902**
### <samp>🤖 Generated by Copilot at daa88cd</samp>

Added user-based facility filtering to `FacilitySelect` component. This enables managing user permissions for different facilities in the `ManageUsers` page.

- Fixes #6190 
http://localhost:4000/users
Only shows those facilities in the drop-down that are not linked to the user.
image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at daa88cd</samp>

*  Add `username` property to `FacilitySelectProps` interface to pass the username of the selected user to the `FacilitySelect` component ([link](https://github.com/coronasafe/care_fe/pull/6253/files?diff=unified&w=0#diff-f2f4af4b241c14bc928b5b78882a6a010ae731f7828bdb30472eac45db7014feR9))
*  Destructure `username` prop from `FacilitySelectProps` object and pass it to the `useEffect` hook as a dependency in `FacilitySelect.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6253/files?diff=unified&w=0#diff-f2f4af4b241c14bc928b5b78882a6a010ae731f7828bdb30472eac45db7014feR26))
*  Include `username` value in the query parameters of the `listFacility` API call to fetch the facilities assigned to the selected user in `FacilitySelect.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6253/files?diff=unified&w=0#diff-f2f4af4b241c14bc928b5b78882a6a010ae731f7828bdb30472eac45db7014feR50))
*  Pass `username` prop to the `FacilitySelect` component from the `UserFacilities` component to render the facility selection for each user in the manage users page in `ManageUsers.tsx` ([link](https://github.com/coronasafe/care_fe/pull/6253/files?diff=unified&w=0#diff-a6a7ab3af39c9e2846bc2d69312a095aa77957d33c31ea4c0a70c034dfdfa121R698))

### CODE REVIEW

**Comment by Pranshu1902** [comment]
Waiting for [backend](https://github.com/coronasafe/care/pull/1588)

**Comment by nihal467** [comment]
@Pranshu1902 fix your backend test and mark it for testing

**Comment by nihal467** [comment]
image

LGTM the functionality , @Pranshu1902 fix the failing cypress as well

**Comment by Pranshu1902** [comment]
@nihal467 done!

**Review by nihal467 — APPROVED** [review]

**Comment by nihal467** [comment]
@khavinshankar upon back-end merges, the cypress will pass through,

**Comment by Pranshu1902** [comment]
The back-end PR is merged, this PR can be merged now
@nihal467 @khavinshankar

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
