### PR TITLE
removed extra space

### LINKED ISSUE #2904: Remove spacing in UI on Sample Test page for count of Samples
https://care.coronasafe.in/sample
image

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #2904 
Updated view:
image

### CODE REVIEW

**Review by cp-Coder — CHANGES_REQUESTED** [review]
@Pranshu1902 there is some error when tested on iPad Air. The `Total Samples Taken` column is not properly viewable.
image

**Comment by Pranshu1902** [comment]
@cp-Coder bug resolved!

**Comment by samholics** [comment]
tested,verified

**Comment by khavinshankar** [comment]
@Pranshu1902 please do work on the merge conflict

**Comment by Pranshu1902** [comment]
> @Pranshu1902 please do work on the merge conflict

done

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
image
image

@Pranshu1902 the UI seems to be off

**Comment by Pranshu1902** [comment]
@khavinshankar
Updated view:
image

Mobile View:
image

**Comment by khavinshankar** [comment]
@Pranshu1902 
image

still getting the same

after fixing the UI, please add `need testing` tag

**Comment by Pranshu1902** [comment]
@khavinshankar please clear cache and check again, I too had to clear cache to see the updated version

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
