### PR TITLE
Hide Spokes on Facility Create Page

### LINKED ISSUE #8624: Facility Spoke linking option is not visible in create facility form
**Describe the bug**

- [ ] In the create facility form, only the spoke facility field heading is visible.
- [ ] We are only able to link a spoke to a facility from the update facility form

**To Reproduce**

1. Go to https://care.ohc.network/facility/create
2. See error

**Expected behavior**

- [ ] we should be able to link a spoke to a new facility from the create facility page itself

**Screenshots**

image

### PR DESCRIPTION
**Pull request by Jacobjeevan**
## Proposed Changes

- Partially #8624 

Following the conversation on slack, hiding spokes heading on facility creation page.

Before

image

After

image

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [x] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [x] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by khavinshankar** [comment]
@Jacobjeevan can you please fix the failing cypress tests

**Comment by Jacobjeevan** [comment]
@khavinshankar Reran the failing one and it's passing 👍 

Note: Noticed the same test failing in https://github.com/ohcnetwork/care_fe/actions/runs/11208536036/job/31152363494, but worked later.

**Review by bodhish — APPROVED** [review]
LGTM

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
