### PR TITLE
advanced filter modal is now responsive in small devices

### LINKED ISSUE #3383: Advanced filter modal not responsive in small mobile devices
**Describe the bug**
The advanced filter modal is not responsive in small devices

**To Reproduce**

1. Go to the Patients Tab [here](https://care.coronasafe.in/patients) in Samsung Fold Device
2. Click on Advanced Filters
43 See error

**Expected behavior**
The **Apply button** gets hidden we need to scroll horizontally to see it. It should not happen. Instead, the **Apply button** should go down the next line.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by patelaryan7751**
Fixes #3383 

## Proposed Changes

- The advanced filter modal in the patient dashboard is responsive now.

image

@coronasafe/reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by arpancodes — CHANGES_REQUESTED** [review]
Let's do the same in the facility advanced filter.

image

**Comment by nihal467** [comment]
@patelaryan7751 once the work is done, change the label to need testing

**Comment by patelaryan7751** [comment]
@arpancodes It's done
image

**Comment by nihal467** [comment]
test approved

**Review by gigincg — APPROVED** [review]

**Comment by gigincg** [comment]
@patelaryan7751 Consider making i18n Changes for Generic Texts

**Pull request merged**
