### PR TITLE
fixed QR code

### LINKED ISSUE #2241: link the generated QR and assigned QR on assets page
Currently there are two seperate QR codes on an asset 
1. the uuid qr code that is generated automatically
2. the numeric qr_code_id that has been added to the backend https://github.com/coronasafe/care/pull/720
this need to be fixed

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #2241
- [x] Fixed asset Url (QR scanner will redirect to asset page on scanning `QR code with asset id or qr_code_id` )
- [x] Tested on QR code with value `ffe4159f-ce44-4881-8fba-6a7d560280b5`(asset UUID) or `https://<hostname>?assetId="1234577777"`(url with qr_code_id)

### CODE REVIEW

**Comment by gigincg** [comment]
@cp-Coder Asset Transfers where being managed by the external-id QR Codes. You need to preserve that function as well in this

**Comment by nihal467** [comment]
@gigincg @cp-Coder is it good for testing ?

**Comment by nihal467** [comment]
@cp-Coder @gigincg the deployment preview is failed

**Comment by nihal467** [comment]
@cp-Coder @gigincg check the deployment failed issue

**Comment by nihal467** [comment]
@gigincg

**Comment by aeswibon** [comment]
@gigincg I have made the necessary changes

**Comment by aeswibon** [comment]
Will open a new PR with existing as well as new changes

**Pull request closed without merging**
