### PR TITLE
change all useDispatch to useQuery and request hooks in Consultations (src/Components/Facility/Consultations/**) 

### LINKED ISSUE #6372: 🛠️ Replace `useDispatch` w. `useQuery`/`request`: Consultations (`src/Components/Facility/Consultations/**`)

### PR DESCRIPTION
**Pull request by AshrafMd-1**
### <samp>🤖 Generated by Copilot at aaab0f5</samp>

The pull request refactors the code for the facility consultations component and its subcomponents, using a custom `request` function and a `routes` object for making API calls, and simplifying the use of React hooks and state management. It also adds type annotations for some API routes and removes unused code and imports. This improves the code readability, consistency, and type safety.

## Proposed Changes

- Fixes #6372 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### <samp>🤖 Generated by Copilot at aaab0f5</samp>

*  Refactored the code to use a custom `request` function and the `routes` object instead of the `dispatch` and `fireRequest` functions, and to replace the `useCallback` and `useAbortableEffect` hooks with `useEffect` hooks. This involved changing the imports, the function definitions, the API calls, and the error handling in several files. ([link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-590d7e80413fac07ff0183a58a0685249a25c1eb9f5f5484e8c4a199066ec861L1-R43), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-befff88edc6070c18bee26653a810b4168ae6d9ffde08c2334d6f005fd9053dbL4-R7), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-befff88edc6070c18bee26653a810b4168ae6d9ffde08c2334d6f005fd9053dbL19), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-befff88edc6070c18bee26653a810b4168ae6d9ffde08c2334d6f005fd9053dbL55-R75), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-befff88edc6070c18bee26653a810b4168ae6d9ffde08c2334d6f005fd9053dbL91-R91), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-65429b4a69e72bfde74a8cb5766d1c36270bed52bbacc759c59f9f4a18fb82b6L2-R2), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-65429b4a69e72bfde74a8cb5766d1c36270bed52bbacc759c59f9f4a18fb82b6R9-R10), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-65429b4a69e72bfde74a8cb5766d1c36270bed52bbacc759c59f9f4a18fb82b6L22), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-65429b4a69e72bfde74a8cb5766d1c36270bed52bbacc759c59f9f4a18fb82b6L32-R51), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-4dc0d319103bdf6392aff3ef83718e5e4c01dee7cf32d2e0694f4d0815c34bf4L1-R3), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-4dc0d319103bdf6392aff3ef83718e5e4c01dee7cf32d2e0694f4d0815c34bf4L12-R33), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-5720f1345a51b321a7409e05b9acc257c75783e165427270755ecc0626e59cb2L64-R71), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-5720f1345a51b321a7409e05b9acc257c75783e165427270755ecc0626e59cb2L98-R151), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-5720f1345a51b321a7409e05b9acc257c75783e165427270755ecc0626e59cb2L213-R223), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-5720f1345a51b321a7409e05b9acc257c75783e165427270755ecc0626e59cb2L249-R260), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-6352cfe4ad14fd5cf49cc8bca3a81880e50c91515c2c11bdff1b379a587c4983L4-R5), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-6352cfe4ad14fd5cf49cc8bca3a81880e50c91515c2c11bdff1b379a587c4983L104-R120), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-6352cfe4ad14fd5cf49cc8bca3a81880e50c91515c2c11bdff1b379a587c4983L125-R126), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-6352cfe4ad14fd5cf49cc8bca3a81880e50c91515c2c11bdff1b379a587c4983L136-R151), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-6352cfe4ad14fd5cf49cc8bca3a81880e50c91515c2c11bdff1b379a587c4983L242-R257), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-3f2dc697ea8b52c1b3b887c76623edb0a4e6ace175573dfbd3a7476ffee979a9L1-R5), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-3f2dc697ea8b52c1b3b887c76623edb0a4e6ace175573dfbd3a7476ffee979a9L93-R94), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-3f2dc697ea8b52c1b3b887c76623edb0a4e6ace175573dfbd3a7476ffee979a9L125-R167), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-f07cbda0a403fac8e17a78aaaaaec8cddfee4fefd96aa47a3f1f1f30e5961033L1-R8), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-f07cbda0a403fac8e17a78aaaaaec8cddfee4fefd96aa47a3f1f1f30e5961033L14-R39), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-94226db5d565b8cd3950ba04e488e214a1cf73f75f6fba79b4cfd48a8666f6d4L1-R4), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-94226db5d565b8cd3950ba04e488e214a1cf73f75f6fba79b4cfd48a8666f6d4L14), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-94226db5d565b8cd3950ba04e488e214a1cf73f75f6fba79b4cfd48a8666f6d4L22-R49), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-81677ef4d8448029b758144449c97c1e7c03363f429774be39ac10a375f27f35L1-R5), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-81677ef4d8448029b758144449c97c1e7c03363f429774be39ac10a375f27f35L10), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-81677ef4d8448029b758144449c97c1e7c03363f429774be39ac10a375f27f35L18-R53), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-81677ef4d8448029b758144449c97c1e7c03363f429774be39ac10a375f27f35L53-L59), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-aefc8ee97b74b9da5c9495d03fa60c919c5b3d9112dcb9a910ca0f996a4e3caaL1-R13), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-aefc8ee97b74b9da5c9495d03fa60c919c5b3d9112dcb9a910ca0f996a4e3caaL22-R62), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-aefc8ee97b74b9da5c9495d03fa60c919c5b3d9112dcb9a910ca0f996a4e3caaL58-L64), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-1d99c4da1921b29609caddb59e69d2497f93251e82e48be8ac45973ca9ffcc7aL1-R3), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-1d99c4da1921b29609caddb59e69d2497f93251e82e48be8ac45973ca9ffcc7aL24-R60), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-6bf9540897ec41d399c4c7682fd9bb572b0441f094c0cc8c9ee1d0aad86f0cabL1-R3), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-6bf9540897ec41d399c4c7682fd9bb572b0441f094c0cc8c9ee1d0aad86f0cabL33-R72), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-a0c88ccc2116ceb542bc9be228c54ed98b0bc89e2d9daf66c941f1a0305e626eL292-R292), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-a0c88ccc2116ceb542bc9be228c54ed98b0bc89e2d9daf66c941f1a0305e626eL528-L530))
* Added the types for the different fields and responses of the daily rounds API endpoints to the `models.tsx` and `api.tsx` files, and used them in the `routes` object and the `request` function. This improved the type safety and readability of the code. ([link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfL1-R1), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfR13), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfL18-R24), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfR31), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfR151), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-e2841f01e53119db63c01994d866100758f06ecc85d11914eecc7cdfe8a2f4dfR226-R490), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cL3-R18), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cR190-R191), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cR243-R244), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cL242-R267), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cL285-R313), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cR361-R362), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cR390-R392), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-21639e8b3b95469edd34a3d2641a85e6eb02393c442301e11d91665f10f1cf7cR401-R402))
* Changed the order of some imports to follow alphabetical order, and moved some variables to different lines to follow the code style. This improved the consistency and readability of the code. ([link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-befff88edc6070c18bee26653a810b4168ae6d9ffde08c2334d6f005fd9053dbL26-R24), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-5720f1345a51b321a7409e05b9acc257c75783e165427270755ecc0626e59cb2L14-R26), [link](https://github.com/coronasafe/care_fe/pull/6416/files?diff=unified&w=0#diff-5720f1345a51b321a7409e05b9acc257c75783e165427270755ecc0626e59cb2L40-R43))

### CODE REVIEW

**Comment by nihal467** [comment]
@rithviknishad can you review it !

**Review by rithviknishad — CHANGES_REQUESTED** [review]
1. For all GET requests dispatched during component initial render/mount should be using useQuery!

2. If that request is a paginated response API, consider using the PaginatedList component instead as it'll handle most of the cases for you with minimal code. See example: https://github.com/coronasafe/care_fe/blob/develop/src/Components/Facility/LocationManagement.tsx

**Comment by AshrafMd-1** [comment]
@rithviknishad , I have changed the code as per the requested changes. Can you review this PR once?

**Comment by AshrafMd-1** [comment]
Somehow this pull request literally also added cypress and other files so I will close this and add a new pr request

**Pull request closed without merging**
