### PR TITLE
feat: Add query params while using pagination

### PR DESCRIPTION
**Pull request by cp-Coder**
# Bug Fix

## Proposed Changes

- Adds query params like `page=?&limit=?` to Facilities, Sample Tests, Shifting, and Users page

## Associated Issue

- Fixes https://github.com/coronasafe/care_fe/issues/3955

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
LGTM

**Comment by khavinshankar** [comment]
@cp-Coder 
In assets, changing the page and filtering doesn't reset it to page 1. Test other pages too.

**Comment by rithviknishad** [comment]
@khavinshankar it's fixed in #4017 for all pages
image

**Comment by khavinshankar** [comment]
Putting this pr on hold till #4017 is tested

**Comment by rithviknishad** [comment]
Merged via https://github.com/coronasafe/care_fe/pull/4041.

cc: @cp-Coder @khavinshankar

**Pull request closed without merging**
