### PR TITLE
Added total bed count display on Facility Home page

### LINKED ISSUE #4389: Display total bed count on facility page
Should we also display the total number of beds occupied by the number of beds in the facility
image

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #4389 
Added a display of total beds occupied / total beds
http://localhost:4000/facility/ad8367ed-e0d9-4ff3-971d-5f5519b1a773
image

### CODE REVIEW

**Comment by Pranshu1902** [comment]
The cypress tests are failing for users page, this PR has nothing to do with that

**Comment by rithviknishad** [comment]
@Pranshu1902 this feels like there's too much text present and congested now near the title.

How about the way @khavinshankar has suggested in the issue itself? That would look great!

Something like this?

image

cc: @khavinshankar @nihal467

**Comment by nihal467** [comment]
@Pranshu1902 let's discuss the UI in the EOD call, marking it for team discussion required

**Comment by nihal467** [comment]
@Pranshu1902 
image

to show the total bed count,change the page similar to the dashboard,

**Comment by Pranshu1902** [comment]
@nihal467 
Sample view:
image

**Comment by nihal467** [comment]
@Pranshu1902 add the edit and delete icon similar to the existing icon to the staging and take it up in the EOD call for final approval

**Comment by Pranshu1902** [comment]
@nihal467 Updated view:
image

**Comment by nihal467** [comment]
@Pranshu1902 
image

the UI still feels bigger, marking it as team discussion required for further discussion

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
