### PR TITLE
Tooltip and full asset name

### LINKED ISSUE #7787: Lengthy asset name is not properly handled in asset list page
**Describe the bug**

When we have bigger asset names, they are hidden few characters, even if we have enough white space

**To Reproduce**

1. Go to asset tab
2. create asset with wider lengthy names
3. See error

**Expected behavior**

- [ ] if space is available, based on the screen size, show the full asset names
- [ ] in the cases, due to limited space, if we are hiding part of the asset name with "...", add a tooltip to the asset name, if user hover over it, they can view the full name of the asset in the tooltip

**Screenshots**

image

### PR DESCRIPTION
**Pull request by 609harsh**
## Proposed Changes

- Fixes #7787
- Asset name is available based on space available
- Tooltip is added so that full name is visible

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@609harsh 

image

- [ ] Don't show this tooltip for all asset names. Show it only for assets with lengthy names, similar to the screenshot attached in the issue. When the user hovers over those cards, display the tooltip.
- [ ] fix the cypress failure

**Comment by 609harsh** [comment]
> @609harsh
> 
> image
> 
> * [ ]  Don't show this tooltip for all asset names. Show it only for assets with lengthy names, similar to the screenshot attached in the issue. When the user hovers over those cards, display the tooltip.
> * [ ]  fix the cypress failure

Hi @rithviknishad how can 1st one be done? please suggest

**Comment by rithviknishad** [comment]
As a simple fix, we can show tooltip only if name length is beyond certain length. Although it may not guarantee in all screen sizes and zoom levels.

Not sure if there are better alternative ways to achieve that fix via CSS. @skks1212 Any ideas?

**Comment by shivankacker** [comment]
If we follow conventions, I believe we should use a simple `title` prop rather than a tooltip for all names regardless of length.
We can also keep a toggle on the name. If you click/hover on it, rather than a tooltip, the full name is toggled. Just suggesting. 
Keeping the popup dependant on length doesn't seem like a good idea to me
cc. @rithviknishad

**Comment by 609harsh** [comment]
@nihal467 what should be done next? Since displaying dynamic tooltip can only be possible by length of text but it will not insure all screen sizes give similar results. i guess we can go ahead with displaying tooltip to all names or remove it for all as most of the time valid asset name will be smaller.

**Comment by khavinshankar** [comment]
@609harsh

can you try out what @skks1212 suggested

>We can also keep a toggle on the name. If you click/hover on it, rather than a tooltip, the full name is toggled. Just suggesting.

and also fix the cypress issue

**Comment by nihal467** [comment]
@609harsh any status update on the PR

**Comment by bodhish** [comment]
Closing this PR due to lack of recent progress.

**Pull request closed without merging**
