### PR TITLE
Made General Instructions field in Consultation Form non mandatory

### LINKED ISSUE #8365: General instructions (advice): consultation
**Is your feature request related to a problem? Please describe.**
In consultation form (https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1/update) the field for General Instructions (advise) was made mandatory field as that was the field where doctor would detail out the care plan. But now we have specific fields to detail out the care plan. 

Therefore the text field may be made non-mandatory to easy data entry 

**Describe the solution you'd like**
Make General Instructions (advise) field non-mandatory

### PR DESCRIPTION
**Pull request by JOSHIK27**
## Proposed Changes

- Fixes #8365 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@JOSHIK27 could you discard changes from your other PR being present here?

Treating physician required condition is not relevant to the linked issue of this PR right.

Other than that, LGTM

**Comment by JOSHIK27** [comment]
> @JOSHIK27 could you discard changes from your other PR being present here?
> 
> Treating physician required condition is not relevant to the linked issue of this PR right.
> 
> Other than that, LGTM

Makes sense. 

[Edited]
Updated the code. Hope it is as expected @rithviknishad

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@JOSHIK27 
image

- [ ] When we are trying to create a new consultation, keeping the general instructions, its throwing a 500 error

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
