### PR TITLE
Fix representation of facility name

### LINKED ISSUE #2268: Facility name : Representation Error : UI
pwekfeo

the facility name is represented simply in the UI, with no specific symbols or anything

### PR DESCRIPTION
**Pull request by Ashesh3**
Fixes #2268 

- Added "Facility" prefix to facility representation
- Font size increased by 114% (`sm`  to `3xl`)

Preview:
image

### CODE REVIEW

**Review by developedBySJ — APPROVED** [review]

**Comment by nihal467** [comment]
opewfkoew

@Ashesh3 @gigincg rather than writing the facility, can we use any symbols for a facility like hospital symbols, now it's not looking good

**Comment by Ashesh3** [comment]
@nihal467 Is this better?

image

**Comment by nihal467** [comment]
wpojefeopf

@Ashesh3 @gigincg  i can't see any update in the PR,

**Comment by Ashesh3** [comment]
> wpojefeopf
> 
> @Ashesh3 @gigincg i can't see any update in the PR,

That's correct, Just wanted to get a visual feedback first if that looks good or not. if yes, I'd add the updated commit to this PR! Did that just now!

**Comment by nihal467** [comment]
oekpwfwo

@Ashesh3 @gigincg the facility name and the patient name alignment is off, make the alignment proper

**Comment by Ashesh3** [comment]
@nihal467 Fixed the alignment to match the padding of the patient name on the left side.

- With inner padding on div `md:pl-2` (Updated in this PR)
image

- Without inner padding (Not in this PR)
image

Let me know which one works the best.

**Comment by nihal467** [comment]
apokfopfaw

@Ashesh3 @gigincg test failed

- the left side alignment is off
- the facility name font size is big, can you reduce it a bit, or try some other font, the existing font doesn't feel matches the UI

**Comment by Ashesh3** [comment]
@nihal467 Fixed the left alignment, reduced the facility name font size, made it semi bold to match it more with the surrounding elements.

image

**Comment by nihal467** [comment]
psajfojasf

@Ashesh3 the alignment of created, diagnosis, and verified by is off, when we compared to the top

**Comment by Ashesh3** [comment]
> psajfojasf
> 
> @Ashesh3 the alignment of created, diagnosis, and verified by is off, when we compared to the top

Fixed the alignment of the said elements.

image

**Comment by nihal467** [comment]
wekofewop

@Ashesh3 now, everything is aligned, but make it aligned to the line present under the blood group

pwkefoepk

**Comment by Ashesh3** [comment]
All the elements are now aligned to the line below the blood group.

image

**Comment by nihal467** [comment]
@Ashesh3 @gigincg  check the conflicting files !

**Comment by nihal467** [comment]
wepokfewokpf

@Ashesh3 @gigincg reduce the spacing between the borderline and the content

**Comment by Ashesh3** [comment]
Reduced the spacing

image

**Comment by nihal467** [comment]
test approved

**Pull request merged**
