### PR TITLE
Fixed: Switching Bed Malfunction

### LINKED ISSUE #3216: Switching Bed : Malfunction
image

if we are trying to shift a patient to an existing bed being use, there is no pop up showing that the bed is in use

### LINKED ISSUE #3252: Inventory Mangement : Malfunction
image

I am able to submit the above detail and no data reflection or anything takes place nor getting a error notification

### LINKED ISSUE #3260: Malfunction : Login Page
image

when an invalid user data is inputted, no error pop-ups are stating that no active found or anything related like that

### PR DESCRIPTION
**Pull request by cp-Coder**
# Updates

- [x] Fixes #3216
- [x] Fixes #3252 
- [x] Fixes #3260 
- [x] Added default value to `suppressNotif` prop to enable notification for any error code
- [x] Modified `getUserDetails` action to disble notification for it

### CODE REVIEW

**Review by kunatastic — APPROVED** [review]

**Comment by nihal467** [comment]
@cp-Coder 
image
image

without submitting the pop-up, I am unable to know which bed is in use, can we badge for it , saying things in-use or allocated etc... in the list

**Comment by aeswibon** [comment]
@nihal467 I have added a field in bed model in coronasafe/care#936 PR. I will add this feature in #3151

**Comment by aeswibon** [comment]
@nihal467 Can you test this PR urgently? This PR only fixes the `Notification` error. The changes that you requested will be added in PR #3151

**Comment by nihal467** [comment]
test approved

**Comment by aeswibon** [comment]
@khavinshankar Can you urgently merge this PR? This PR fixes notification error. A lot of issue are being opened regarding this error

**Review by gigincg — APPROVED** [review]
suppress ?? true is not a good practice. Do make an issue and get this sorted @cp-Coder

**Pull request merged**
