### PR TITLE
Sort imports

### PR DESCRIPTION
**Pull request by sainak**
## Proposed Changes

- reorganized files
- sorted imports using prettier-plugin-sort-imports
- depends on https://github.com/ohcnetwork/care_livekit_fe/pull/3

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by sainak** [comment]
@coderabbitai ignore

**Comment by sainak** [comment]
latest deploy: https://app.netlify.com/sites/care-ohc/deploys/672b6670ed04884183bb7054

**Review by rithviknishad — CHANGES_REQUESTED** [review]
config changes lgtm

**Review by rithviknishad — APPROVED** [review]

**Comment by rithviknishad** [comment]
*accidentally clicked request changes button

**Pull request merged**
