### PR TITLE
Add edit option for doctor notes

### PR DESCRIPTION
**Pull request by Ashesh3**
This pull request adds an edit option for doctor notes in the patient consultation notes list. It also includes necessary changes to the API endpoints and models.

Waiting for https://github.com/coronasafe/care/pull/1221

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 fix the backend test

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
- [ ] the edit button is not clickable , only the icon is clickable

**Comment by Ashesh3** [comment]
> * [ ]  the edit button is not clickable , only the icon is clickable

Fixed, made the edit experience more intuitive.

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by aparnacoronasafe** [comment]
@Ashesh3 There is a risk in allowing notes to be edited anytime. Doctor's notes serve as a log of interactions and recommendations between clinicians on a case. 

What do you think of limiting such edit option for 30Min? for the doctor to correct any errors in the messages.

**Pull request merged**
