### PR TITLE
Show camera feed only for admin and doctor

### LINKED ISSUE #6430: Show camera feed ONLY to "Doctor", "District Admin" and "State Admin"
**Is your feature request related to a problem? Please describe.**
Currently live camera feed is visible to all user types. However, we need to be more conservative with allowing access to camera feed to protect privacy of the patients.

**Describe the solution you'd like**
For all usertypes other than "Doctor", "State Admin" and "District Admin"

- [ ] Disable the tab "Feed" on the Patient dashboard (https://deploy-preview-6396--care-net.netlify.app/facility/015ad911-39b7-4104-b304-bf8178c33830/patient/85497ba2-3319-4acc-829a-d116e8b3136a/consultation/e356715b-5fd3-4cfc-ab45-d64509cb7cb2)

- [ ] Disable "Configure" button on Assets with asset class "ONVIF Camera" (https://deploy-preview-6396--care-net.netlify.app/facility/1210229b-711a-46e6-ab0a-207c4808e32e/assets/01feff7a-1306-4550-a80f-22bc26cbfb28)

### PR DESCRIPTION
**Pull request by Ashesh3**
### <samp>🤖 Generated by Copilot at e13495c</samp>

The pull request adds more checks and conditions for rendering the configure button and the feed tab for ONVIF assets. These changes are meant to improve the security and usability of the asset management and consultation features.

## Proposed Changes

- Fixes #6430 

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

### <samp>🤖 Generated by Copilot at e13495c</samp>

*  Restrict access to asset configuration page for ONVIF assets ([link](https://github.com/coronasafe/care_fe/pull/6453/files?diff=unified&w=0#diff-d3677127a55934962254fa660ba9b01a59fdb23bee06c9160832527f36c8bf20L456-R472))
* Hide feed tab for discharged or non-admitted consultations ([link](https://github.com/coronasafe/care_fe/pull/6453/files?diff=unified&w=0#diff-8a3d15fd6d3361688d96f67af80b867cc60bfbd6bc7642555fd6b5fd04d63901L503-R509))

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 
image

the vital configure button is missing for district admin users

**Comment by Ashesh3** [comment]
> @Ashesh3 image
> 
> the vital configure button is missing for district admin users

Fixed.

### DistrictAdmin / Doctor
image
image


### Volunteer
image
image

**Comment by nihal467** [comment]
@Ashesh3 
image

- [ ] For non-asset class assets, this PR is showing the configuration button, which shouldn't be shown

**Comment by Ashesh3** [comment]
> @Ashesh3 image
> 
> * [ ]  For non-asset class assets, this PR is showing the configuration button, which shouldn't be shown

fixed now

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
