### PR TITLE
Fixed UI issues on Edit Bed and Edit Doctor Capacity page

### LINKED ISSUE #3664: Minor UI fix
- Make better use of the space on Edit bed capacity form
https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/bed/1
image

- Remove the unnecessary gaps between elements on the Edit Doctor capacity page
https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/doctor/1
image

### PR DESCRIPTION
**Pull request by Pranshu1902**
Fixes #3664 

- Reduced length of unnecessary elements on Edit Bed Capacity form
http://localhost:4000/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/bed/1
image

- Removed unnecessary gaps between elements on the Edit Doctor Capacity form
http://localhost:4000/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/doctor/1
image

### CODE REVIEW

**Review by Ashesh3 — APPROVED** [review]

**Comment by nihal467** [comment]
@Pranshu1902 
image

the buttons in the bed capacity are not of equal width

**Comment by Pranshu1902** [comment]
@nihal467 
Updated view:
image

**Comment by nihal467** [comment]
@Pranshu1902 
image
the button sizes are not uniform

**Comment by Pranshu1902** [comment]
@nihal467 
Updated view:
image

**Comment by nihal467** [comment]
test approved

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
