### PR TITLE
Revamped resource and shifting boards to the KanbanBoard component and removed react-dnd

### LINKED ISSUE #8584: Replace React-DND
Preferably with @hello-pangea/dnd

### LINKED ISSUE #8636: Fix shifting and resource board scroll and drag
- Unable to scroll while dragging
- Board X scroll gets hidden
- Board titles are not sticky

### PR DESCRIPTION
**Pull request by shivankacker**
## Proposed Changes

- Fixes #8636 
- Fixes #8584 
- Removes React-DND library in favour of @hello-pangea/dnd (maintained fork of react-beautiful-dnd)
- Revamps the shifting and resource board
- Adds a new KanbanBoard component that is easy to configure

Screenshot 2024-10-07 at 12 19 55 PM
Screenshot 2024-10-07 at 12 19 43 PM

@ohcnetwork/care-fe-code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by bodhish** [comment]
@shivankacker we have plans to add more boards like these 
image
Make sure the KanbanBoard component is clean.

**Comment by shivankacker** [comment]
@bodhish yup the KanbanBoard component is made to be reused in the future. It is easy to configure and supports infinite scroll.

**Comment by nihal467** [comment]
@shivankacker can you clear the merge conflict

**Comment by nihal467** [comment]
@shivankacker 

image

- [x] the exported shifting CSV file names are not correct
- [x] can you clear the merge conflict

rest of the functionality looks good

**Comment by shivankacker** [comment]
@nihal467 fixed

**Comment by nihal467** [comment]
LGTM @shivankacker @khavinshankar can you clear the merge conflict

**Review by khavinshankar — APPROVED** [review]

**Pull request merged**
