### PR TITLE
Fixed Query Params bug

### LINKED ISSUE #4542: Pagination and list view is broken across the platform
**Describe the bug**

- [ ] when we are changing pages from one page to another one, even though the page is getting reloaded, the page is not getting changed and the same data is being reflected
- [ ] one card is missing on the patient and asset page.

**To Reproduce**

1. Go to https://care.coronasafe.in/assets
2. Click on the pagination of the page
3. See the error

**Expected behavior**

- [ ] when we are using the pagination, it should be functioning properly
- [ ] all the cards should be visible on a page

**Screenshots**

image

### PR DESCRIPTION
**Pull request by skks1212**
## Proposed Changes

- Fixes #4542 ?
- Fixes params not being urlized in `fireRequest` function.
- Pagination should work properly now.

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by shivankacker** [comment]
@nihal467 can you check again? Bug has vanished 👀

**Review by rithviknishad — CHANGES_REQUESTED** [review]
This wouldn't work @skks1212 since special characters need to be encoded.

Try searching patient by phone number +91 99999999999 in staging and deploy preview.

We have 70+ results in staging, but 0 results in deploy preview.

**Comment by shivankacker** [comment]
@rithviknishad Missed out on encoding, thanks for pointing it out! Should work now.

**Review by rithviknishad — APPROVED** [review]

**Comment by nihal467** [comment]
@skks1212 https://deploy-preview-4547--care-net.netlify.app/facility?page=2, still unable to access this link

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@nihal467 fixed the country code error, can you check it out

cc: @skks1212

**Comment by shivankacker** [comment]
> @nihal467 fixed the country code error, can you check it out
> 
> cc: @skks1212 

@khavinshankar works perfectly!

**Comment by nihal467** [comment]
LGTM

**Pull request merged**
