### PR TITLE
Fix inconsistent type of visited countries attribute

### LINKED ISSUE #2440: ICMR Sample export fails for new patients
Viewing the ICMR sample report for newly created patients error out.

https://care.coronasafe.in/patient/148e7f44-da24-491b-af7e-86d78648efb1/test_sample/43f119c7-0e30-43ac-937f-5b26d8b5ebdc/icmr_sample

image

## Backend Error:

```
File "/root/care/care/facility/models/patient_icmr.py", line 219, in symptomatic_international_traveller
    len(self.patient.countries_travelled) != 0
TypeError: object of type 'NoneType' has no len()
[19/May/2022 16:42:18] "GET /api/v1/patient/148e7f44-da24-491b-af7e-86d78648efb1/test_sample/43f119c7-0e30-43ac-937f-5b26d8b5ebdc/icmr_sample/ HTTP/1.1" 500 26894
```

It seems like `patient.countries_travelled` and `patient_travel_history` are zombie attributes, I am not able to find any way to add or update those fields about the Patient. Since those fields are never initialized, the ICMR report fails.

### PR DESCRIPTION
**Pull request by Ashesh3**
Closes #2440 
Accompanying backend change: [care/pull/789](https://github.com/coronasafe/care/pull/789)

The old way of storing countries was as a single string where each country was separated by a comma. This was later changed to instead store each country in an array and return it as-is from the backend. This change aligns the frontend with the current implementation of storing countries at the backend. 

This change is accompanied with a backend change to remove any inconsistencies there where the `JSONField` is sometimes cross referenced as a `CharField`.

### CODE REVIEW

**Comment by nihal467** [comment]
@Ashesh3 what is the current status of the PR

**Comment by Ashesh3** [comment]
> @Ashesh3 what is the current status of the PR

The backend change was approved but hasn't been merged yet. Waiting for it to be merged before we can proceed with testing this PR.

**Comment by nihal467** [comment]
@Ashesh3 merge the latest development branch and check merge conflict, then mark it for testing

**Comment by nihal467** [comment]
@Ashesh3 
image

https://deploy-preview-2536--care-net.netlify.app/patient/148e7f44-da24-491b-af7e-86d78648efb1/test_sample/43f119c7-0e30-43ac-937f-5b26d8b5ebdc/icmr_sample

iam still receiving the something wrong error

**Comment by Ashesh3** [comment]
Waiting for: https://github.com/coronasafe/care/pull/1175

**Comment by nihal467** [comment]
LGTM

**Review by khavinshankar — APPROVED** [review]

**Comment by khavinshankar** [comment]
@Ashesh3 initially we were using string and later we changed it to an array, so is that factored in?

**Comment by Ashesh3** [comment]
> @Ashesh3 initially we were using string and later we changed it to an array, so is that factored in?

Yes, that is factored in at both backend and frontend. It's strictly to array only now. (Backend PR merged already)

**Pull request merged**
