### PR TITLE
Enhance Patient Search UI with Smart Component..

### LINKED ISSUE #8691: Add a better search UI for patients index page
In the current patient page, we have 4 independet search on patient, at any point in time you can only search by one practically.
Here is an how the current UI looks.  
image

Let upgrade it with a smart search compoent where the user can select what to search for. 
image

It should also support keyboard short cuts. 
image

The valid options would be Name | Phone Number | OP/IP number | Emergency Contact Number.

Also reduce the height of the count box to match the component.

### PR DESCRIPTION
**Pull request by Jash2606**
## Proposed Changes

- Fixes [#8691](https://github.com/ohcnetwork/care_fe/issues/8691)
 Video:
 

https://github.com/user-attachments/assets/7aa32b82-9b4f-46ec-8ce9-8911b819b349

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.ohc.network).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by khavinshankar** [comment]
@Jash2606 can you please fix the failing cypress tests

**Comment by Jash2606** [comment]
> @Jash2606 can you please fix the failing cypress tests

Hey @khavinshankar, could you help me figure out the error? I'm new to Cypress testing and open-source contributions, so any guidance would be appreciated. Thanks!

**Review by bodhish — CHANGES_REQUESTED** [review]
@Jash2606 when we add designs in an issue, we expect it to be in sync. 
The current implementation is a super hacky version of the design. 

If I was building it:
- It would have been a component 
- the component accepts a config (its not going to be just these inputs it can be anything right)
- it will use a single state to store the user input and selected type
- the design will be 100% match 
- `/` will let users switch the selected input type.

**Comment by bodhish** [comment]
@Jash2606 closing this PR as it is inactive.

**Pull request closed without merging**
