### PR TITLE
Scroll to madatory empty fields

### PR DESCRIPTION
**Pull request by kushalbhana**
## Proposed Changes

- Fixes ##8222
- Whenever the patient category is left empty the validation with generating error scroll the page to the specific field

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [ ] Add specs that demonstrate bug / test a new feature.
- [ ] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [ ] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Review by rithviknishad — CHANGES_REQUESTED** [review]
@kushalbhana 

1. There is already a utility fn. called `scrollTo` defined. You can simply pass an `id` value and scroll to the element by invoking the fn.

2. When there are errors in blood pressure field, it does not auto-scroll to that field.

**Comment by kushalbhana** [comment]
Made the changes, please review it.

**Comment by rithviknishad** [comment]
@kushalbhana The previous review was not fully solved. Please take a look at the 2nd point.

**Review by rithviknishad — APPROVED** [review]

**Comment by kushalbhana** [comment]
#8246 Fixed- Handled error in  blood pressure field @rithviknishad

**Comment by rithviknishad** [comment]
@kushalbhana Was this closed by accident?

**Comment by kushalbhana** [comment]
Yes!! let me make the pr again

**Pull request closed without merging**
