### PR TITLE
Added drag and drop in BoradView for Shifting and Resources

### LINKED ISSUE #2400: Draggable Components on Shifting Page
## Implementation Details
- This requires you to take care of access control limitations.
- A lot of work is required depending on the stage it is moved
- Create a modal for additional fields to be filled.

Shifting Page:
image

### LINKED ISSUE #2401: Draggable Components on Resource Page
## Implementation Details
- Take care of access control limitations
- Different types of users are allowed to do only a specific set of movements

Resource Page
image

### PR DESCRIPTION
**Pull request by khavinshankar**
- [x] add drag and drop for shifting (Fixes #2400)
- [x] add drag and drop for resources (Fixes #2401)

### CODE REVIEW

**Comment by nihal467** [comment]
@khavinshankar 


when we take the card to the right-most corner, it is not automatically scrolling to the right side of the shifting

**Comment by nihal467** [comment]
@khavinshankar what is the status

**Comment by nihal467** [comment]
@khavinshankar can you merge the latest development branch

**Comment by khavinshankar** [comment]
@nihal467 merged

**Comment by nihal467** [comment]
test approved

**Pull request merged**
