### PR TITLE
Facility image issue is Fixed

### PR DESCRIPTION
**Pull request by NikhilGolla72**
Users can now upload facility cover image in the facility registration form itself by enabling the checkbox option provided in the 3rd step of facility registration/

@ohcnetwork/care-fe-code-reviewers

Screenshot 2024-10-09 014534

## Summary by CodeRabbit

- **New Features**
  - Introduced a cover image upload feature for facility creation.
  - Added a modal for users to edit and upload cover images.
  - Enhanced internationalization support with localized placeholder texts.

- **Bug Fixes**
  - Improved phone number validation for clearer error handling.

- **Improvements**
  - Streamlined default value settings for form fields.
  - Updated rendering logic to accommodate the new cover image upload step.

### CODE REVIEW

**Comment by nihal467** [comment]
@NikhilGolla72 Adding it to staff capacity is not bringing any value to the users, so closing this PR, as this is an irrelevant change, feel free to work on any open issues in the care_fe

**Comment by nihal467** [comment]
@NikhilGolla72 Sorry for the inconvenience, bro, but make sure you link an issue(https://github.com/ohcnetwork/care_fe/issues/7297) to your PR so that, during the review, we can see which issue you're trying to address. The PR heading is not clearly communicating what the PR is about. Could you make the following changes: :

1. Mention the issue in the PR and give it a proper heading based on the PR.
2. From the issue and the slack thread, I'm getting the understanding that you need to make it an optional fourth step after the staff capacity. However, what you’ve done is added a checkbox in the staff capacity step, which isn’t ideal because the cover image is not part of staff capacity. So, keeping it as a fourth step would be better.

**Comment by NikhilGolla72** [comment]
@nihal467 sorry for the misunderstanding I caused,I am new to the open source contribution and I didn't know the fomat to submit a PR.I will follow the format from now on for sure and also I will make it as a 4th step 

and also I want to ask about the cypress attempt 2 which is caused by not identifying the " div#map-close " under 10000ms .Can I change it 20000ms to that it may be solve this cypress test issue?

**Comment by nihal467** [comment]
@NikhilGolla72 can you share the screenshot of the cypress dashboard  , to know what is exactly

**Comment by NikhilGolla72** [comment]
@nihal467 
Screenshot 2024-10-10 152035
Screenshot 2024-10-10 152047

**Comment by nihal467** [comment]
@NikhilGolla72 run the cypress locally and try to debug it, use the command "npx cypress open" and check whether its passing in your local to not

**Comment by NikhilGolla72** [comment]
@nihal467 
Screenshot 2024-10-10 202500
Screenshot 2024-10-10 202537
Screenshot 2024-10-10 232624
The same error for every file in the specs 
Screenshot 2024-10-10 233005

**Comment by rithviknishad** [comment]
Looks like your local cypress is unable to connect to your local backend. Are you sure ur local backend is accessible in that URL?

**Comment by NikhilGolla72** [comment]
@rithviknishad i think this is what causing the problem 
Screenshot 2024-10-11 142407
Screenshot 2024-10-11 142417

i tried fixing it many times but still i am getting the same error, i tried to reinstall @types/cypress and verified type definition files but i dont understand what is causing the problem 
Screenshot 2024-10-11 142918

**Comment by rithviknishad** [comment]
create a separate issue, this issue seems to be present in develop branch too.

**Comment by NikhilGolla72** [comment]
@rithviknishad  i just want to confirm, is this issue present in the develop branch itself?and i can't clear it by fixing my tsconfig file in local?

**Comment by nihal467** [comment]
@NikhilGolla72 can you log in manually, and verify that you are connected to your local backend? Are you able to see the dummy data ?

**Comment by NikhilGolla72** [comment]
@nihal467 i am working on the care_fe repo which doesnt has any Makefile so i couldnt run the makeup command to load the dummy data but i am able to run the backend using docker desktop.Could you please tell me what is causing the error in tscong file and also in cypress attempt 2
Screenshot 2024-10-11 224750
Screenshot 2024-10-11 232955
Screenshot 2024-10-12 115103
Screenshot 2024-10-11 224423

**Comment by nihal467** [comment]
Nikhil from the screenshot, you are not doing the backend configuration properly

Note: CARE is not a monorepo; you can access the frontend at https://github.com/ohcnetwork/care_fe and the backend at https://github.com/ohcnetwork/care.

steps to run the docker : 

1. Clone the backend repo: https://github.com/ohcnetwork/care (backend)
2. now since you are using the docker app, open the vs code and verify you are in the correct branch
3. run `docker compose -f docker-compose.yaml -f docker-compose.local.yaml up -d` in your vs code panel
4. now open the docker app and check all the containers are running
5. now open the celery container and view the log, verify all the migration is completed
6. open the localhost:9000 and you will be able to view a similar page as below: 
image

7. once the entire backend is up, run the command in vs code for loading the dummy data `docker exec care-backend-1 python manage.py load_dummy_data` 

Once all the steps are followed properly, your backend is fully up.

Connect the frontend to the backend:

- in the frontend , open the .env file and replace the REACT_CARE_API_URL=https://careapi.ohc.network to REACT_CARE_API_URL=http://localhost:9000

**Comment by NikhilGolla72** [comment]
@nihal467 Hi nihal, i am working on setup up the backend in the local, but can i know how the issue with Github actions cypress test is related  to my backend setup?The change in my PR is only modifiying the Facilitycreate.tsx file and it's working fine.
Screenshot 2024-10-15 134230
Screenshot 2024-10-15 134907

**Comment by nihal467** [comment]
@NikhilGolla72 

- [ ] Setting up the local backend is necessary to run Cypress locally, replicate the failure mentioned in the GitHub action, and fix it.
- [ ]  You have modified the facility creation workflow by adding a 4th step into it, which means there are already existing tests in that workflow that are breaking due to your PR modifications. Therefore, you also need to update the existing Cypress tests in your PR.

**Comment by bodhish** [comment]
@NikhilGolla72 would you be working on this PR?

**Comment by NikhilGolla72** [comment]
@bodhish yes I am working on it.I had to change my code again because I was working on the non updated repo.sorry for the delay.

**Comment by bodhish** [comment]
@NikhilGolla72 let get this merged this week?

**Comment by NikhilGolla72** [comment]
@bodhish i will try to fix this by this weekend

**Comment by bodhish** [comment]
@NikhilGolla72 closing this PR as we have no progress. Feel free to open it agian when its ready to be merged

**Pull request closed without merging**
