### PR TITLE
Added functionality to change consultation file name in files tab

### LINKED ISSUE #2288: Delete option for Consultation Files
Add an option to soft delete files on the Consultation Files page

Screenshot 2022-04-29 at 3 28 03 PM

### LINKED ISSUE #3367: File Upload: file rename permission to owner
The File Upload is available on Patient consultation, (https://care.coronasafe.in/facility/c92cc4df-0fea-4d37-9c24-1c9f07bfac23/patient/1b63b5b5-e1ba-4e87-878e-9c178996255a/consultation/4516faa0-77cd-4b5e-9c52-1df41fbf9090/files)

Give the user that uploaded the file to rename the file. Nobody else must have the option to rename it

### PR DESCRIPTION
**Pull request by patelaryan7751**
## Proposed Changes
Fixes #3367
- Added functionality to change file name this operation is available to user who created the file.

Video
https://www.loom.com/share/239b82a74c9b47ebb2d07e4ced007a23

EDIT:

NEW UI 

image

@coronasafe/care-fe-code-reviewers @coronasafe/code-reviewers

## Merge Checklist

- [x] Add specs that demonstrate bug / test a new feature.
- [x] Update [product documentation](https://docs.coronasafe.network/coronasafe-care-documentation/architecture/architecture-and-layering-of-care).
- [ ] Ensure that UI text is kept in I18n files.
- [x] Prep screenshot or demo video for changelog entry, and attach it to issue.
- [ ] Request for Peer Reviews
- [ ] Completion of QA

### CODE REVIEW

**Comment by nihal467** [comment]
@patelaryan7751 
image

- [ ] make the button of the same length in responsive view

image

- [ ] once I select the button and click cancel, it always seems like selected

**Comment by patelaryan7751** [comment]
@nihal467  i have fixed all bugs updated UI to as disscused in EOD

new UI : 
image


Samsung Fold :
image

**Comment by patelaryan7751** [comment]
new Ui 
image
more icons to be added for all types of file when this PR https://github.com/coronasafe/care/pull/1019 is meged

**Comment by Ashesh3** [comment]
This PR appears to be related to this issue: https://github.com/coronasafe/care_fe/issues/3366 

@aparnacoronasafe suggested an archive option rather than a delete button

**Comment by mathew-alex** [comment]
:wave: Hi, @patelaryan7751,
Conflicts have been detected against the base branch. Please rebase your branch against the base branch.

***

This message is automatically generated by [prince-chrismc/label-merge-conflicts-action](https://github.com/prince-chrismc/label-merge-conflicts-action) so don't hesitate to report issues/improvements there.

**Comment by patelaryan7751** [comment]
a new PR has been created to work on this https://github.com/coronasafe/care_fe/pull/3716

**Pull request closed without merging**
